### ISSUE TITLE
Fairing documentation does not exist despite a suggestion that there are docs

### ISSUE THREAD

**Issue by hamelsmu** [kubeflow/website#1000]
The kubeflow website has a link on the sidebar discussing documentation for fairing, however, documentation does not exist.

The [readme for the fairing repo](https://github.com/kubeflow/fairing#documentation) mentions there are docs but that points to the same website without documentation.  

My suggestion is to clarify that documentation is WIP, and official docs for the api does not exist yet so that users don't get confused (like I did).  LMK and I'll make a PR fixing this .  🙇  Thank you!

**Comment by sarahmaddox** [comment]
Hallo @hamelsmu 

The docs for Fairing are here:
https://www.kubeflow.org/docs/fairing/

The README for the Fairing repo points to this page, which is within the above section:
https://www.kubeflow.org/docs/fairing/fairing-overview/

Is it a particular feature of Fairing that's missing from the docs? If that's right, then yes please, a PR is most welcome. :)

**Comment by hamelsmu** [comment]
I’m going to close this issue as I am going to contribute to the docs where I think some things are missing - got connected in the slack channel
