### ISSUE TITLE
Test and fix the end-to-end Kubeflow on GCP Tutorial 

### ISSUE THREAD

**Issue by temporafugiunt** [kubeflow/website#1012]
https://www.kubeflow.org/docs/gke/gcp-e2e/

The **End-to-end Kubeflow on GCP** tutorial is having issues and is probably using outdated python tutorial code no longer compatible with the default version of TensorFlow in the Jupyter notebook environment setup by default. The issue related to section **(Optional) Test the code in a Jupyter notebook**

Here are the steps I took to before having the issue:

1) I created a new GCP based kubeflow cluster by running through the **Kubeflow on GCP** documentation and was able to get a cluster with IAP running.
2) I created a new Jupyter notebook to attempt running the section example, I used
**gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0** as the notebook docker image.
3) Created a Python2 notebook in the Jupyter notebook environment.
4) I cloned the code from https://github.com/kubeflow/examples.git
5) As the section suggested I cut and pasted the code from **mnist/model.py** into a cell and ran it and had my first exception:
![Exception1](https://user-images.githubusercontent.com/5757895/62327639-ca055b00-b476-11e9-99cb-df2bc5922415.PNG)
6) I fixed this temporarily by adding another allowed command line argument: 
![Exception1Fix](https://user-images.githubusercontent.com/5757895/62327702-e608fc80-b476-11e9-82a5-1cd3c3d4687a.PNG)
But then ran into the model type conflict seen by the second exception:
![Exception2](https://user-images.githubusercontent.com/5757895/62327804-1fda0300-b477-11e9-9587-e38654977575.PNG)

The tutorial code expects only tf_model_type == "LINEAR": but is being passed a type of "CNN". 
Unfortunately I am really new to Data Science and don't have much experience with TensorFlow as I come from a Web Application Developer / DevOps Engineer background so I really can't debug any further.

**Comment by temporafugiunt** [comment]
I did also add a `print(args)` statement, which is what you see first in the second run detail.

**Comment by temporafugiunt** [comment]
Text based output of the run if that is helpful:

`Namespace(f='/home/jovyan/.local/share/jupyter/runtime/kernel-3cf0407c-c1c2-4149-a60e-291f1335e518.json', tf_batch_size=100, tf_data_dir='/tmp/data/', tf_export_dir='mnist/', tf_learning_rate=0.01, tf_model_dir=None, tf_model_type='CNN', tf_train_steps=200)
INFO:tensorflow:TF_CONFIG {}
INFO:tensorflow:cluster=None job_name=None task_index=None
INFO:tensorflow:Will export model
Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
No such model type: CNN

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1`

**Comment by temporafugiunt** [comment]
And contents of %tb:

```
SystemExitTraceback (most recent call last)
<ipython-input-16-840d9f7d1603> in <module>()
    224 
    225 if __name__ == '__main__':
--> 226   tf.app.run()

/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow/python/platform/app.pyc in run(main, argv)
    123   # Call the main function, passing through any arguments
    124   # to the final program.
--> 125   _sys.exit(main(argv))
    126 

<ipython-input-16-840d9f7d1603> in main(_)
    205   else:
    206     print("No such model type: %s" % args.tf_model_type)
--> 207     sys.exit(1)
    208 
    209   train_spec = tf.estimator.TrainSpec(

SystemExit: 1
```

**Comment by sarahmaddox** [comment]
I'm closing this as a duplicate of issue https://github.com/kubeflow/website/issues/844

/close

**Comment by sarahmaddox** [comment]
Thanks @DanSanche for fixing the problem that cause the `model.py` code to error out when copied and pasted into a notebook! See PR https://github.com/kubeflow/examples/pull/625
