### ISSUE TITLE
Document GCP role required of user for deploying Kubeflow

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#1013]
We should clearly document as pre-requisite the GCP project role a user must have in order to be able to successfully deploy Kubeflow in their GCP project. 

It will also be useful to document why this role is required.

**Comment by sarahmaddox** [comment]
+1

We currently do say that people need the **owner** role, on the following pages:
* https://www.kubeflow.org/docs/gke/deploy/deploy-ui/
* https://www.kubeflow.org/docs/gke/pipelines-tutorial/

We should put the information into the GCP setup guide as well:
* https://www.kubeflow.org/docs/gke/deploy/project-setup/

**Comment by sarahmaddox** [comment]
@scottilee Is this an issue that you can take on?

**Comment by sarahmaddox** [comment]
Oh wait, sorry, I see that @abhi-g  has taken it on.
