### ISSUE TITLE
video tutorial does not show commands applied

### ISSUE THREAD

**Issue by ricoms** [kubeflow/website#1017]
video shared here: https://www.kubeflow.org/docs/started/getting-started-gke/

A suggestion would be to write down the commands applied below the video.

**Comment by sarahmaddox** [comment]
/assign @texasmichelle 

@texasmichelle This is an interesting point, which will apply to all videos. The videos need to provide enough tech info for people to be able to follow up on them. Even just a doc link would be good enough, I think.

**Comment by texasmichelle** [comment]
The sentence directly in front of the video includes a link to all the commands used ("All code used in this video can be found in the [examples repository](https://github.com/kubeflow/examples/tree/master/videos/from_zero_to_kubeflow)"). If this is what you're looking for, is there clearer language we could use to make that more obvious or prominent?

**Comment by ricoms** [comment]
@texasmichelle , you are correct. Sorry, I opened directly the kubeflow examples repository when you mentioned them at the video, and later I thought that link ("examples repository") would direct me here to main https://github.com/kubeflow/examples

Thanks a lot for all your great work, I'm learning a lot.
