### ISSUE TITLE
Ambassador service is not being created - Azure deployment

### ISSUE THREAD

**Issue by yuval-yaari** [kubeflow/website#1019]
Either the documentation is out of date, or there is an issue with the installation.
I'm trying to follow the Azure installation instructions, and it states to expose a service called `ambassador`.
Such service is not created in the kubeflow namespace.

**Comment by sarahmaddox** [comment]
This is the likely doc:
https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/

We've updated the portforwarding instructions for other deployments:
https://www.kubeflow.org/docs/other-guides/accessing-uis/#using-kubectl-and-port-forwarding
`kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80`

/assign @gopitk

**Comment by jlewi** [comment]
Ambassador is no longer used. We now use ISTIO.
Closing this as obsolete.
