### ISSUE TITLE
minikube instructions for 0.6 shouldn't use kfctl.sh

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1023]
The minikube instructions need to be updated
https://www.kubeflow.org/docs/started/getting-started-minikube/

We should no longer tell users to use kfctl.sh; that script will no longer work since its using ksonnet.

Instead the instructions should be

1. Setup minikube
1. Follow the instructions for installing Kubeflow on an existing cluster

For the latter we can probably just link to the appropriate section
https://www.kubeflow.org/docs/started/getting-started-k8s/

Note the latter section is being revised in #977

**Comment by jlewi** [comment]
The instructions were partially updated in #1051 
https://www.kubeflow.org/docs/reference/virtual-dev/getting-started-minikube/

The instructions now point users at installing on existing kubernetes clusters but the link is broken

The port-forwarding command also looks incorrect.

Users need to port-forward to the ISTIO gateway not to the Ambassador service.

@abhi-g Are you working on updating the minikube instructions?

/cc @carmine

**Comment by abhi-g** [comment]
I am also working on getting the minikube setup script working. Currently
it's running installing Kubeflow with existing k8s configs. I specifically
tried k8s with istio config. That hasn't worked so far. I am trying to
create a trimmed down config for minikube.

**Comment by sarahmaddox** [comment]
PR https://github.com/kubeflow/website/pull/1067 fixed the port forwarding instructions. 

@abhi-g How's it going with the script?

**Comment by jlewi** [comment]
The instructions 
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/

No longer reference kfctl.sh. The instructions have been updated to tell people to use kfctl.

So this has been fixed.
