### ISSUE TITLE
Add documentation for the Fairing KubeflowAzureBackend sample

### ISSUE THREAD

**Issue by vjrantal** [kubeflow/website#1033]
The PR at https://github.com/kubeflow/fairing/pull/322 will bring support to using `fairing.backends.KubeflowAzureBackend` from sample notebooks such as the ones here https://github.com/kubeflow/fairing/tree/fd87ddcd668de0929c67490280fda3c897957496/examples/prediction.

This issue is to track creating documentation about the Azure-specific steps required to run such notebooks, such as how to set the right secrets in the Kubernetes cluster.

**Comment by sarahmaddox** [comment]
Thanks @vjrantal! I'll assign this doc issue to you. Let me know if that's not OK!

/assign @vjrantal
