### ISSUE TITLE
Is multi-user isolation currently only available in Notebooks?

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1037]
Is multi-user isolation currently only available in Notebooks?

If yes, we should make that clear in the following doc:
https://www.kubeflow.org/docs/other-guides/multi-user-overview/

**Comment by sarahmaddox** [comment]
@abhi-g Do you know the answer to this question? I've heard discussions that imply that multi-user isolation is only implemented for notebooks in v0.6.

**Comment by abhi-g** [comment]
The notebooks service is the first application to be fully integrated with multi-user isolation. Resources created by the notebooks (eg. Training jobs and deployments) will also inherit the same visibility.


Metadata and Pipelines or any other applications currently don't have full fledged integration with isolation, though they will have access to the user identity through the headers of the incoming requests. It's upto the individual applications to leverage the available identity and create isolation stories that make sense for them. 

Should we add a current state and restrictions section documenting this? The current doc does mention that Jupyter Notebooks service is the first fully integrated application in the Example of Usage section, but it's a good idea to explicitly list the current level of support or not for different applications.

**Comment by sarahmaddox** [comment]
Yes, it's a good idea to add an explicit statement of the current state. This will reduce confusion. Also the fact that each application/commponent should implement the feature is useful info.

**Comment by abhi-g** [comment]
Can you please suggest a title for this section?

**Comment by sarahmaddox** [comment]
How about this title: **Current integration and limitations**

Also, I think we should move this sentence from paragraph 1 into the new section: 
"Note that the isolation support in Kubeflow doesn’t provide any hard security guarantees against malicious attempts by users to infiltrate other user’s profiles."

**Comment by sarahmaddox** [comment]
@abhi-g I'll assign this issue to you, but feel free to unassign it if you don't have bandwidth to do the update.

/assign @abhi-g
