### ISSUE TITLE
port-forwarding does work for IAP clusters AFAICT

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1042]
https://www.kubeflow.org/docs/other-guides/accessing-uis/
I believe this line is incorrect:

> This will only work if you haven’t enabled basic auth or Cloud IAP. If authentication is enabled requests will be rejected because you are not connecting over HTTPS and attaching proper credentials.

It's true for basic auth, but I'm reaching the dashboard okay with forwarding on an IAP cluster— I don't think there is any kind of port-forwarding issue with IAP?  Do you know why that qualifier was added originally?

**Comment by sarahmaddox** [comment]
/assign

I'm updating the screenshot and UI text references on this page. I'll take this one on too.
