### ISSUE TITLE
Is it possible to get rid of ads in site search?

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1048]
e.g. a search for 'metadata' returns with the following. I think it doesn't help with site clarity. Don't know how search is set up, so possibly we're stuck with it.
![image](https://user-images.githubusercontent.com/115093/62667195-6f1ea880-b93b-11e9-82ef-576cab0e529b.png)

**Comment by sarahmaddox** [comment]
The search uses Google Custom Search Engine:
https://cse.google.com/cse/

I've investigated removing the ads, but I don't think it's possible unless we change to a different search mechanism.

We use the Docsy theme on top of Hugo static site generator. Hugo mentions a few search options:
https://gohugo.io/tools/search/

If we do decide to implement a different search, we should consider contributing the solution to the Docsy theme.
