### ISSUE TITLE
Deploy using CLI - insufficient GCP project quota

### ISSUE THREAD

**Issue by doschkinow** [kubeflow/website#1065]
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

Following this guide I get following error:

ERRO[0034] Updating kfapp error: &{Code:RESOURCE_ERROR Location:/deployments/kfapp/resources/kfapp Message:{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCo
de":"403","ResourceErrorMessage":{"code":403,"message":"Insufficient project quota to satisfy request: resource \"CPUS_ALL_REGIONS\": request requires '16.0' and is short '4.0'. project has a quota
 of '12.0' with '12.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project=integrated-will-227617.","status":"PERMISSION_DENIED","statusMessage
":"Forbidden","requestPath":"https://container.googleapis.com/v1beta1/projects/integrated-will-227617/locations/us-east1-d/clusters","httpMethod":"POST"}} ForceSendFields:[] NullFields:[]}  filenam
e="gcp/gcp.go:348"

I am using a free google cloud account and would not like to pay to increase my quota for a kubeflow test. I tried to edit the gcp_config/cluster-kubeflow.yaml (generated by kfctl) and reduced the cpu demand by setting

max-cpu: 8
cpu-max-nodes: 4

but this did not help, kfctl seems still to request 16 cpu

Please advise how to proceed. Is it possible to tweak the config, so the ressources for a google cloud test account are sufficient to test kubeflow?

Thanks and best regards!

**Comment by JunPyoL22** [comment]
For deploying kubeflow on GCP, I changed on both "cpu-pool-machine-type" and " gpu-pool-machine-type"  from **n1-standard-8** to **n1-standard-4** in cluster-kuberflow.yaml which is in my project folder because of initial quota limit assigned my free GCP account. 

I think this would be helpful.

**Comment by doschkinow** [comment]
Thanks fo the hint.
I tried **n1-standard-4** and **n1-standard-2** but both failed with a error message, saying that the required node image is not available:

ERRO[0035] Updating kfapp error: &{Code:RESOURCE_ERROR Location:/deployments/kfapp/resources/kfapp Message:{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The required node image is not available.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1beta1/projects/integrated-will-227617/locations/us-east1-d/clusters","httpMethod":"POST"}} ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:348"

**Comment by JunPyoL22** [comment]
Both types should be same.  "n1-standard-"
Sorry for mistyping  on the above comment 
But, you need to check your quota on static ip addresses global. This should be 2 if you want deploy kubeflow with 2 nodes.

**Comment by JunPyoL22** [comment]
@doschkinow 
I think I wrote wrong answer.
Machine types doesn't matter. I might think the error message relate to inconsistency on cpu pool machine-type and  its properties you requested. 
Did you just change both machine types from default config in your cluster-kuberflow.yaml?

**Comment by doschkinow** [comment]
Yes, I changed only the machine types that end with -8(two occurrences). Once with -4 and once with -2, but neither worked. Right now I do not have access to my env, but on Monday I will.
Many thanks!

**Comment by sarahmaddox** [comment]
@doschkinow Do the comments and the new feature request answer your questions, or is there something we need to add to the docs? If there's no doc work to be done, we can close this issue and move comments over to the feature request in the kubeflow/kubeflow repo.

**Comment by doschkinow** [comment]
Yes, but this means that with a free GCP trial you can not test kubeflow on GCP. Please note this in the docs on getting statrted with kubeflow on GCP, so free trial GCP users do not lose time.
Thanks.

**Comment by sarahmaddox** [comment]
@doschkinow Thanks for raising this issue and following through with it! You're right - the docs need updating.

This section mentions quotas already - we need to update it, to reflect the fact that with a free trial can't try Kubeflow using the default GCP installation:
https://www.kubeflow.org/docs/gke/deploy/project-setup/
The doc should refer to this feature request for tracking a fix: https://github.com/kubeflow/kubeflow/issues/3936

**Comment by philipebuka** [comment]
so what do  i do, I'm having this same issue and I am using the free tier
