### ISSUE TITLE
Move docs for On Premise Authorization to Website from manifests/docs

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/website#1066]
/area docs
/priority p2

Example Authorization scrips and RBAC rules are now maintained in manifests/docs and they need to be moved to website before 0.7 release.

**Related Issues:**

kubeflow/manifests#195

**Comment by sarahmaddox** [comment]
@krishnadurai Please could you link to the specific docs that need moving to the website? I've found the following:

* [Kubeflow Authentication and Authorization Prototype](https://github.com/kubeflow/manifests/blob/master/dex-auth/README.md)
* [Using Examples to enable RBAC](https://github.com/kubeflow/manifests/blob/master/docs/dex-auth/examples/README.md)
* [Kustomize Best Practices](https://github.com/kubeflow/manifests/blob/master/docs/KustomizeBestPractices.md)

One thing to bear in mind: The docs for Kubeflow maintainers should remain in the GitHub repo, whereas docs for Kubeflow users should be on the website.

**Comment by sarahmaddox** [comment]
In the [page about deploying Kubeflow on a K8s cluster](https://www.kubeflow.org/docs/started/k8s/overview/], we currently offer two options:
* [Kubeflow Deployment with kfctl_k8s_istio](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)
* [Multi-user, auth-enabled Kubeflow with kfctl_existing_arrikto](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/)

Are we now adding a third option for on-prem authorization with RBAC?

**Comment by krishnadurai** [comment]
@sarahmaddox 
These docs will be removed or modified for 0.7 and be replaced with a website doc.

* [Kubeflow Authentication and Authorization Prototype](https://github.com/kubeflow/manifests/blob/master/dex-auth/README.md)
* [Using Examples to enable RBAC](https://github.com/kubeflow/manifests/blob/master/docs/dex-auth/examples/README.md)

I'll raise a PR for it.

**Comment by krishnadurai** [comment]
> Are we now adding a third option for on-prem authorization with RBAC?

The Kubernetes RBAC configuration enabling will be a separate document as any on-prem installation with Dex should be able to use this configuration. This can be a separate section on recommending using Dex to authenticate and authorize Kubernetes requests based on the above two documents.

**Comment by sarahmaddox** [comment]
Excellent, thanks @krishnadurai 
/assign @krishnadurai

**Comment by sarahmaddox** [comment]
@krishnadurai What's the status of this issue?

**Comment by krishnadurai** [comment]
@sarahmaddox I had been waiting for the fix kubeflow/kubeflow#4517 to go in. Since now its in, I need to make some minor modifications to our manifests to support OIDC plugin for kubernetes.

I'll be able to move and publish these documents thereafter. Expect this to be done within 1.0.

**Comment by sarahmaddox** [comment]
Thanks @krishnadurai
