### ISSUE TITLE
Troubleshooting notebook credentials and poddefaults; notebook startup

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1068]
We need better documentation around how to troubleshoot the use of PodDefaults to inject credentials and other information into jupyter pods.

This comment is a good place to start
https://github.com/kubeflow/kubeflow/issues/3571#issuecomment-520660278

**Comment by jlewi** [comment]
We also need troubleshooting information about notebooks not starting because the required service accounts aren't found in the requested namespace.

See kubeflow/kubeflow#3902

**Comment by sarahmaddox** [comment]
Here's the place to add the info:
https://www.kubeflow.org/docs/notebooks/troubleshoot/

**Comment by sarahmaddox** [comment]
@jlewi Do we still need the troubleshooting info around the injection of credentials? I see that https://github.com/kubeflow/kubeflow/pull/3926 is merged, which (I think) fixes the specific problem that gave rise to this request. 

Regarding the service accounts, the docs have some info around creating a service account named `default-editor` here:
https://www.kubeflow.org/docs/notebooks/troubleshoot/#note-for-gcp-users
Do we need more than that?

**Comment by jlewi** [comment]
@sarahmaddox yes I think we should still have troubleshooting docs around credentials. 

Even though kubeflow/kubeflow#3926 is fixed when people create new namespaces they may run into this issue.

**Comment by mnmami** [comment]
I'd still want troubleshooting guidelines related to other DefaultPod usages, for example env var injection, which we find hard time debug and understand why it is not working during notebook creation.
