### ISSUE TITLE
Deploy using CLI - errors with kfapp storage / metadata

### ISSUE THREAD

**Issue by doschkinow** [kubeflow/website#1069]
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

If I set e.g. ZONE=europe-west3-a and do:

kfctl apply all -V

I get following error:
INFO[0005] Updating kfapp-storage status: RUNNING (op = operation-1565689589282-58ffc83cc3779-1b411f0c-fb977655)  filename="gcp/gcp.go:352"
ERRO[0009] Updating kfapp-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'zone' on resource 'kfapp-storage-metadata-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:348"
ERRO[0009] Updating kfapp-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'type' on resource 'kfapp-storage-metadata-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:348"
ERRO[0009] Updating kfapp-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'zone' on resource 'kfapp-storage-artifact-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:348"
ERRO[0009] Updating kfapp-storage error: &{Code:NO_METHOD_TO_UPDATE_FIELD Location: Message:No method found to update field 'type' on resource 'kfapp-storage-artifact-store' of type 'compute.v1.disk'. The resource may need to be recreated with the new field. ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:348"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating kfapp-storage error(400): BAD REQUEST

If I leave env var ZONE empty, this step is done, but then I am hitting:
https://github.com/kubeflow/website/issues/1065

Any hints or suggestions?
Thanks!

**Comment by sarahmaddox** [comment]
/assign @zhenghuiwang 

@zhenghuiwang Please would you take a look at this error. It seems to be related to the metadata feature.

**Comment by zhenghuiwang** [comment]
The problem seems to be related to Kubeflow storage in general. Not specific to metadata.

@doschkinow Did you deploy Kubeflow to a zone where there is already a deployment?

The error seems to indicate there is already an instance template for `compute.v1.disk` in the zone. The deployment of Kubeflow uses a different template to update it but failed to do so, because "it is not possible to update an existing instance template or change an instance template after it has been created" https://cloud.google.com/compute/docs/instance-templates/

**Comment by doschkinow** [comment]
after deleting the deployments I had, this error disappears but then I am hitting again https://github.com/kubeflow/website/issues/1065

It is a pitty that the default k8s cluster config, needed for kubeflow needs more ressources then allowed for a free GCP trial account. Please either adapt accordingly the default k8s cluster config or document how to adapt it to work for a free GCP trial account.

Thanks.
