### ISSUE TITLE
Usecases would help

### ISSUE THREAD

**Issue by whillas** [kubeflow/website#1081]
Some use-cases for each of the options would help someone to figure out which of the three setup options is relevant

**Comment by sarahmaddox** [comment]
Thanks for raising this issue @whillas! Could you give us more context about the area of the setup docs that you were visiting when you realized the docs could do with use cases. I think maybe it was the getting-started section (https://www.kubeflow.org/docs/started/getting-started/) but I'd like to confirm that.

**Comment by sarahmaddox** [comment]
I'm tackling this as part of issue https://github.com/kubeflow/website/issues/1421

I'll close this issue now and use # 1421 to track the work.

/close
