### ISSUE TITLE
Link doesn't work in - Minikube for Kubeflow installation

### ISSUE THREAD

**Issue by liorshk** [kubeflow/website#1089]
> Now that you have a Kubernetes cluster running - the Minikube cluster - follow the [existing Kubernetes cluster ](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/(/docs/started/k8s/overview/)) instructions for installing Kubeflow.

The above link doesn't work on [this page](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/)

Link should be changed to https://www.kubeflow.org/docs/started/k8s/overview/

**Comment by janeman98** [comment]
@lionshk 
I try today and the link works properly for me. Can you please retry?

**Comment by liorshk** [comment]
Yeah, it works now
