### ISSUE TITLE
Remove mention of TFJob dashboard from the docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1091]
We've stopped supporting the tfjob dashboard, so it is entirely possible that it is broken in Kubeflow v0.6+.

Remove mention of the TFJob dashboard from the docs:
* https://www.kubeflow.org/docs/components/training/tftraining/#accessing-the-tfjob-dashboard
* https://www.kubeflow.org/docs/other-guides/accessing-uis/#next-steps

**Comment by backyes** [comment]
@sarahmaddox 

Why we choose to stop  supporting the tfjob dashboard？ Thanks.

**Comment by sarahmaddox** [comment]
Hallo @backyes There's some information in the [kubeflow-discuss](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubeflow-discuss/1leTpMhSiD4/Qq87AihpAgAJ) group. Here's an extract from the conversation:

>Since TFJob dashboard doesn't provide much value to the users(and UI functionality is much limited), we decided not to support it for now. Also, dashboard doesn't support any other operator.  We have to also remove the TFJob link from the central dashboard.

> Related: https://github.com/kubeflow/tf-operator/issues/1024 
              https://github.com/kubeflow/tf-operator/issues/1019
