### ISSUE TITLE
1.0 Docs for centraldashboard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1107]
We currently don't have application docs for the central dashboard.
https://www.kubeflow.org/docs/components/

We should have docs for each application that goes 1.0. So we will need some documentation for centraldashboard. This can probably be pretty simple since the central dashboard is pretty self explanatory.

We do have this documentation about accessing UIs
https://www.kubeflow.org/docs/other-guides/accessing-uis/

But its kind of buried.

We might want to move or include some of that content in the central dashboard docs.

**Comment by jlewi** [comment]
@avdaredevil could you please provide an update? What docs if any are missing for the central dashboard?

**Comment by jlewi** [comment]
Some notes from meeting with @avdaredevil 

* 1 paragraph about centraldashboard
* Some description about managing namespaces and adding contributors

**Comment by sarahmaddox** [comment]
Thanks @jlewi! For the bit about namespaces and contributors, we can have a high-level overview and link to this doc for details:
http://kubeflow.org/docs/other-guides/multi-user-overview/
