### ISSUE TITLE
Profile & Kfam: Application docs

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/website#1124]
Profile & Kfam: 
Update docs for kubeflow multi-tenancy v1.0.
* explain expected user experience and what's happening on the backend.
* clarity supported scenario and prerequisite.
* how to integrate and extend

**Comment by sarahmaddox** [comment]
Thanks @kunmingg - Please would you expand the title and description of this issue to give more context about what *Profile & Kfam* are.

**Comment by sarahmaddox** [comment]
/assign @kunmingg 

@kunmingg What's the status of this issue?

**Comment by jlewi** [comment]
Bump to P0 because we need this for 1.0.

@kunmingg could you provide an update on what docs are still missing? It looks like we have docs here
https://www.kubeflow.org/docs/other-guides/multi-user-overview/
