### ISSUE TITLE
Update the docs structure to support internationalization of the docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1127]
Update the docs structure to support internationalization of the docs.

See the Kubeflow i18n requirements doc: http://bit.ly/kubeflow-i18n

**Comment by sarahmaddox** [comment]
At the Write the Docs conference, I attended a talk on open source localization. The speaker gave some good insights and tips, which I've summarized in this blog post:
https://ffeathers.wordpress.com/2019/09/18/wtd-prague-localisation-of-open-source-docs/

This will be useful material when we start thinking in more detail about localizing the Kubeflow docs.

**Comment by sarahmaddox** [comment]
The product requirements doc is ready for review: http://bit.ly/kubeflow-i18n

I've scheduled it for discussion in the Kubeflow community meeting on March 24, PT.

**Comment by jihoon-seo** [comment]
Hello all, I am interested in i18n and L10n of Kubeflow website.

In http://bit.ly/kubeflow-i18n ,

[Implement a fallback to English]

> Can we implement a fallback to English when there’s no translation of a page ?
> 
> See the [Kubernetes docs in French](https://kubernetes.io/fr/docs/concepts/). Notice that the left-hand navigation offers some docs in English, with the word (EN) in brackets. Is this manual or automated?

In K8s website, it is automated, and it was achieved by adding some codes to Docsy theme.
Please see: https://github.com/kubernetes/website/pull/28521

---

[Organize the website OWNERS into teams]

> - Add an OWNERS file for the English docs. Each language will have its own OWNERS file, and there’ll also be a top-level OWNERS file.
> - I think we need to set up two teams per language: one team for approvers and one for reviewers. As an example, see the [Kubernetes website OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES), [OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS), [en/OWNERS](https://github.com/kubernetes/website/blob/master/content/en/OWNERS), and [sig-docs/teams.yaml](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml). 
> - **To investigate**: Figure out how the teams.yaml and OWNERS files work. Or maybe we can just stick with individual GitHub IDs in the OWNERS file for each language.

Please see: 
- https://kubernetes.io/docs/contribute/participate/#sig-docs-teams-and-automation
- https://www.kubernetes.dev/docs/guide/owners/
- ( https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/ )
