### ISSUE TITLE
Find Kubeflow community manager for other-language versions of the docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1128]
The Kubeflow docs are currently available only in English. We should ask the Kubeflow community if anyone is interested in managing versions of the docs in other languages. 

The non-English version may consist of a subset of the docs, such as conceptual info or getting-started guide only.

See details in the requirements doc: http://bit.ly/kubeflow-i18n

**Comment by sarahmaddox** [comment]
At the Write the Docs conference, I attended a talk on open source localization. The speaker gave some good insights and tips, which I've summarized in this blog post:
https://ffeathers.wordpress.com/2019/09/18/wtd-prague-localisation-of-open-source-docs/

This will be useful material when we start thinking in more detail about localizing the Kubeflow docs.

**Comment by chpmoreno** [comment]
I am interested in working on Spanish documentation for Kubeflow. I have never contributed to this kind of projects but I would be happy to start with. Let me know how I can contribute and if you have some guidelines about the documentation.

**Comment by sarahmaddox** [comment]
Thanks @chpmoreno that's good to know. We haven't yet started designing the website to handle multiple languages. We'll let you know when we do. Our current priority is the launch of Kubeflow v1.0, scheduled for early 2020. We'll start looking at designing for translated docs some time after that.

**Comment by chpmoreno** [comment]
Perfect. Let me know when I can help.

**Comment by sarahmaddox** [comment]
The product requirements doc is ready for review: http://bit.ly/kubeflow-i18n

I've scheduled it for discussion in the Kubeflow community meeting on March 24, PT.

**Comment by pingsutw** [comment]
I am interested in working on Chinese documentation for Kubeflow.

**Comment by gaocegege** [comment]
@pingsutw Thanks for your interest!

@jlewi

Hi, do we have the owner for the website? Who can help us promote this?

**Comment by jlewi** [comment]
@gaocegege What do you mean by OWNER? There are people listed in the OWNERs file but right now we don't have anyone spending 50-100% of their time working on the docs.
