### ISSUE TITLE
Update the upgrade guide for Kubeflow v1.0 - remove alpha notice

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1130]
Ensure the upgrade guide is complete and clear, including the versioning implications for Kubeflow v1.0. See related issue https://github.com/kubeflow/website/issues/1129.
Define the boundaries for upgrades - what is supported, the constraints, and where users can go for help.

_Note:_ This is a requirement for **Kubeflow v1.0**.

Source: _Kubeflow v1.0 Docs and Processes Design_ ([bit.ly/2OX11vw](https://bit.ly/2OX11vw))

**Comment by richardsliu** [comment]
@sarahmaddox This should be done now: https://www.kubeflow.org/docs/upgrading/upgrade/

**Comment by sarahmaddox** [comment]
/assign

Thanks @richardsliu. All that remains is to remove the **alpha** notice when we launch Kubeflow v1.0. I'll do that when the time comes. We'll leave this issue open until then.

**Comment by sarahmaddox** [comment]
We've decided that we need to keep the upgrade labeled as **alpha** for now. I'll close this issue now.

/close
