### ISSUE TITLE
Upgrade the Kubeflow website to latest version of Netlify to get support for Hugo extended

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1139]
Upgrade the Kubeflow website to latest version of Netlify to get support for Hugo extended.

From https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/:

> Starting today, all new sites on Netlify use the “Xenial” build image by default. This means your new sites are on a modern operating system version with long term support. It also means you can **start using Hugo extended** and taking advantage of features like Hugo pipes!
Meanwhile, existing sites will continue running on the same “Trusty” image they always have. But what if you want to upgrade, too? We’ve got a button for that.

See https://github.com/netlify/build-image/issues/182 (closed as fixed).

**Comment by kbhawkey** [comment]
Good. This should make things easier. Let me know if you need a hand.

**Comment by sarahmaddox** [comment]
I've set the website server to use the new Netlify “Xenial” build image. The Netlify build works for the deployment preview of my PR: https://github.com/kubeflow/website/pull/1190 (small fix just to test the build). When that PR is approved, that will trigger the production build of the website using the new image.

If there are any problems with the build, we can set the website back to the old Netlify build image - see docs linked from this issue.

Next step is to upgrade Hugo, and test out a styling change.

**Comment by kbhawkey** [comment]
👍
