### ISSUE TITLE
Please update NVIDIA TensorRT Inference Server document for kustomize

### ISSUE THREAD

**Issue by asispatra** [kubeflow/website#1142]
Please update [NVIDIA TensorRT Inference Server](https://www.kubeflow.org/docs/components/serving/trtinferenceserver/) document for kustomize. Still the document uses ksonnet.

Thanks.

**Comment by sarahmaddox** [comment]
This is a duplicate of https://github.com/kubeflow/website/issues/959

/close

**Comment by asispatra** [comment]
@sarahmaddox, Is anyone really working on #959 to update the document? 

Thanks.
