### ISSUE TITLE
Website should default to latest release instead of Master

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/website#1159]
At the moment, the website defaults to the documentation for the latest commit (Master).
This makes for a frustrating user experience, as many users are bumping into various different issues that come up in kubeflow master, which moves very fast.
We should point the users to a released version by default, because it's tested and verified to work.

/cc @sarahmaddox @jlewi

**Comment by SachinVarghese** [comment]
I totally agree with @yanniszark that the kubeflow master moves pretty fast and we lack proper documentation for both users and contributors for development versions. As mentioned, the kubeflow website should have a dev documentation section that points to the master branch and should default to the latest release tag for other users. This would definitely help in keeping track of latest updates and setup scripts needed for quick development and easy contributions.

**Comment by Naveenkhasyap** [comment]
> 
> 
> At the moment, the website defaults to the documentation for the latest commit (Master).
> This makes for a frustrating user experience, as many users are bumping into various different issues that come up in kubeflow master, which moves very fast.
> We should point the users to a released version by default, because it's tested and verified to work.
> 
> /cc @sarahmaddox @jlewi

I have asked about the same in slack but none responded , Yes this must be addressed first.
