### ISSUE TITLE
Microk8s for Kubeflow

### ISSUE THREAD

**Issue by ycheng** [kubeflow/website#1163]
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/

the way to install kubeflow on microk8s has change so it work with kubeflow 0.6.

Check web page: https://ubuntu.com/kubeflow/install

**Comment by sarahmaddox** [comment]
Let's track the work on the first-raised issue:
https://github.com/kubeflow/website/issues/1113

/close
