### ISSUE TITLE
Install Kubeflow Fairing

### ISSUE THREAD

**Issue by jdumm** [kubeflow/website#1165]
https://www.kubeflow.org/docs/fairing/install-fairing/

I'm following the steps under the heading "Set up Kubeflow Fairing in a hosted Jupyter notebook".  Running `docker ps` gives me the error "docker: command not found".  The instructions imply that for the case of a GCP hosted notebook from one of the default images, docker should be already be available.  I don't have sudo access and can't follow the instructions to install docker separately.

Some more specifics:  We're using Kubeflow 0.6.2 installed in GCP.  We can create a notebook server and use one of the default Jupyter docker images, such as "gcr.io/kubeflow-images-public/tensorflow-2.0.0a-notebook-cpu:v0.5.0"  (If the tag at the end: v0.5.0 is the Kubeflow version, maybe this list needs to be updated for v0.6.x?)  The next instructions are to verify that python is a 3.6.x version and that docker is installed, but docker is not available.  I wasn't able to install docker either because of sudo issues.

**Comment by jdumm** [comment]
An update with some more details:  When we install docker, we can run `docker ps` to see that the daemon isn't running:
```Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?```

When we try running `dockerd`, we get an error about iptables (same error as when we try to run `sudo dockerd`:
```
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.1: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```

**Comment by karthikv2k** [comment]
@b0noI

can you please look into this issue?

**Comment by nepalineupane** [comment]
@jdumm, can you update, how you fixed this issue. I have encountered the same problem.

**Comment by jdumm** [comment]
@nepalineupane, I think the specific error about "docker: command not found" can be ignored.  I was able to move past it and still generate Docker files from the notebook.  It hasn't been easy though, and I would hesitate to recommend Kubeflow at this point.
