### ISSUE TITLE
Out of date docs: Using Your Own Domain

### ISSUE THREAD

**Issue by apshoemaker** [kubeflow/website#1166]
https://www.kubeflow.org/docs/gke/custom-domain/

This page is very out of date.  I have not spent enough constructive time to figure this out on my own, but this does not seem consistent with the current project setup in 0.6 or 0.7.

**Comment by apshoemaker** [comment]
It appears from some output in coordinator.go that the customization is done in app.yaml prior to `kfctl generate`.  Does that sound right?

**Comment by fediazgon** [comment]
I'm taking this one!

/assign @fediazgon
