### ISSUE TITLE
[GCP] 0.7 docs for workload identity management

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1175]
In 0.7 we will be switching to workload identity with GCP.

We will need docs on how this works.

**Comment by sarahmaddox** [comment]
@lluunn Are you happy to create the doc for workload identity management (I see you commented on https://github.com/kubeflow/kubeflow/issues/3638#issuecomment-525520248)? If you like, you can either point me at a draft in a Google Doc, or send a PR.

**Comment by sarahmaddox** [comment]
v0.7 demo script: http://bit.ly/demo-v0-7
