### ISSUE TITLE
Troubleshooting guide for GKE has a typo in IAP

### ISSUE THREAD

**Issue by agolomoodysaada** [kubeflow/website#1181]
In the Troubleshooting GKE page section called `Changing the OAuth client used by IAP `

```sh
kubectl -n kubeflow create secret generic kubeflow-oauth \
       --from-literal=CLIENT_ID=${CLIENT_ID} \
       --from-literal=CLIENT_SECRET=${CLIENT_SECRET}
```

should be

```
kubectl -n kubeflow create secret generic kubeflow-oauth \
       --from-literal=client_id=${CLIENT_ID} \
       --from-literal=client_secret=${CLIENT_SECRET}
```

Describing the ingress shows this error

```
  Warning  Translate  5m6s (x16 over 7m53s)  loadbalancer-controller  error while evaluating the ingress spec: BackendConfig istio
-system/iap-backendconfig is not valid: secret kubeflow-oauth missing client_id data
```

It would also be useful to have a note to restart the `cloud-endpoints-controller` pod to force the controller to check new credentials.

Finally, a very frustrating issue is giving users IAP access using service accounts. They need to have the `IAP-secured Web App User` assigned via IAM

**Comment by sarahmaddox** [comment]
This is the page: https://www.kubeflow.org/docs/gke/troubleshooting-gke/#changing-the-oauth-client-used-by-iap
