### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by butuzov** [kubeflow/website#1184]
Using my (dummy and non perfect) tool https://github.com/butuzov/deadlinks I was able to find some dead links on the website. I can split them into 4 categories.

1)  internal and external links - that wasn't fixed in time or just added (PR ready).
2) dead component - `/docs/components/ksonnet/`
3) multiple occurrences at `kubeflow/pipelines` repository.
4) other.

I have prepared a PR for 1st item, and guess can check 3rd. Not sure what to do with `ksonnet` links, documentation require rewriting.

**Comment by butuzov** [comment]
Cool, I will back, after sort out where all pipelines are.

**Comment by sarahmaddox** [comment]
Thanks @butuzov!
