### ISSUE TITLE
Need list of P1 Issues for 0.2.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#12]
We need a list of P1 issues that need to be completed for our 0.2 release.

What state are we aiming our website to be in by 0.2?

/cc @ewilderj 
/cc @willingc 
/cc @texasmichelle

**Comment by ankushagarwal** [comment]
Things which I think are important:

* Remove all "lorem ipsum" boilerplate
* Have a minimum viable set of docs in https://www.kubeflow.org/docs/
* Make it easy to contribute docs by having a doc to contribute to docs

**Comment by ankushagarwal** [comment]
Also looks like individual doc pages are in html instead of markdown : https://raw.githubusercontent.com/kubeflow/website/master/content/docs/quick-start.md

We should ideally have markdown docs.

**Comment by jlewi** [comment]
@abhi-g Can we close this issue given the above list?

**Comment by abhi-g** [comment]
Yes. We’ll keep updating the list. But we have a starter set of items on
the list.
