### ISSUE TITLE
Ensure updating of documentation when updating code

### ISSUE THREAD

**Issue by butuzov** [kubeflow/website#1200]
As followback of the #1184, i spend some time trying to cleanup and provide actual links to moved components in `kubeflow/piplines` (see PR #1199).

its partially ready, but what I understand that there absolutely should be rule, once you change some component (pipelines or any other kf component), you should change documentation as well.  I am not sure who makes rules, but its **must have** (at least for pipelines contributors).

**Comment by sarahmaddox** [comment]
Thanks @butuzov and +1 to your comment that updating the docs should be part of the task of updating the code for a feature.

In the [design doc for Kubeflow v1.0 docs and processes](https://bit.ly/2OX11vw) I suggested that we should adhere to the pattern where *doc is part of the [definition of done](https://www.scruminc.com/definition-of-done/)*: The development team must create or update the documentation before they can declare a feature ready for release or a bug fixed.

Perhaps this is something that you'd like to bring up in a community meeting, or perhaps at the upcoming Kubeflow Contributor Summit?
