### ISSUE TITLE
Install Kubeflow on EKS got wrong

### ISSUE THREAD

**Issue by ElijahMingLiu** [kubeflow/website#1201]
Can not install on EKS.
I followed the instruction on https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
But, when I run `kfctl generate all -V`, I got an error:
couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for aws:  (kubeflow.error): Code 400 with message: Could not generate cluster configs under aws_config Error: Could not copy /home/ec2-user/eksworkshop-eksctl/.cache/kubeflow/kubeflow-0.4-branch/deployment/aws/infra_configs/cluster_config.yaml to /home/ec2-user/eksworkshop-eksctl/aws_config/cluster_config.yaml Error cannot create directory: open /home/ec2-user/eksworkshop-eksctl/.cache/kubeflow/kubeflow-0.4-branch/deployment/aws/infra_configs/cluster_config.yaml: no such file or directory

What's wrong?

**Comment by sarahmaddox** [comment]
Thanks for reporting this error!
@Jeffwan Is this something you can resolve?
/assign @Jeffwan

**Comment by Jeffwan** [comment]
Let's track the code changes here.

https://github.com/kubeflow/kubeflow/issues/4199

**Comment by sarahmaddox** [comment]
@Jeffwan Can we close this issue?

**Comment by Jeffwan** [comment]
@sarahmaddox Code has been merged already and we can close this issue. 

/close
