### ISSUE TITLE
Add reference docs for Metadata SDK

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1206]
Add reference docs for the [Metadata SDK](https://github.com/kubeflow/metadata/tree/master/sdk/python#python-client). (We have reference docs for the [Metadata REST API](https://www.kubeflow.org/docs/reference/metadata/v1alpha1/kubeflow-metadata-api-spec/) but not for the Python SDK.)

**Comment by zhenghuiwang** [comment]
I'm updating the SDK right now: https://github.com/kubeflow/metadata/pull/156. More improvements to the SDK are coming.

I will update the doc once these changes are done. (probably in a week or two)

**Comment by sarahmaddox** [comment]
Thanks @zhenghuiwang! Let me know when the SDK reference docs are available on readthedocs.io. The next step is to add some links from the kubeflow website:
* In the [reference](https://www.kubeflow.org/docs/reference/) section, we should create a new page for Metadata, and that new page should link to the existing API reference and to the new SDK ref.
* We should add a link on the [Metadata component page](https://www.kubeflow.org/docs/components/misc/metadata/).

**Comment by sarahmaddox** [comment]
/assign

The Metadata SDK ref docs are now available:
https://kubeflow-metadata.readthedocs.io/en/latest/

I'll link to them from the Kubeflow site.
