### ISSUE TITLE
Explain Metadata implemention and usage in Pipelines vs Kubeflow core

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1207]
Update the [Metadata overview](https://www.kubeflow.org/docs/components/misc/metadata/): There are discussions about merging the metadata UI (see section in the metadata overview) into the Pipelines UI - we need to design docs for UI metadata support. Contact: ajaygopinathan, prodonjs

**Comment by sarahmaddox** [comment]
From further discussions: Users will need metadata functionality for experimentation as well as for pipelines. It's possible that metadata will be implemented as an independent service that can be included in both pipelines and Kubeflow core. The UX team is working on a design for how the metadata service/UI will be exposed to users.

**Comment by sarahmaddox** [comment]
@animeshsingh  Does this issue capture the required updates that you mentioned in today's Kubeflow community call?

@joeliedtke Is there someone from the Pipelines team who can comment from a Pipelines point of view?

@zhenghuiwang has done some excellent work on this doc to date. Zhenghui can you comment on the status of the doc (could it do with further updating) and also on the relationship to Pipelines Metadata? Is this something you may want to tackle during the February doc sprint?

**Comment by zhenghuiwang** [comment]
I went through the metadata doc section with KF1.0 and updated it in https://github.com/kubeflow/website/pull/1641. The major change is to update the backend instruction to use gRPC service.

I think this covers how current Kubeflow metadata SDK, UI and backend work. I would leave it to @joeliedtke or @neuromage for Pipeline's view.

**Comment by sarahmaddox** [comment]
> I went through the metadata doc section with KF1.0 and updated it in #1641. The major change is to update the backend instruction to use gRPC service.
> 
> I think this covers how current Kubeflow metadata SDK, UI and backend work. I would leave it to @joeliedtke or @neuromage for Pipeline's view.

Thanks @zhenghuiwang your Metadata update is great. I've created issue https://github.com/kubeflow/website/issues/1651 to cover the Metadata update for KF1.0. I think your PR can close that issue. Let's restyle this current issue to request a doc explaining the Metadata implemention and usage in Pipelines vs Kubeflow core.

/assign @neuromage 
/unassign @zhenghuiwang 
/cc @joeliedtke

**Comment by animeshsingh** [comment]
/reopen 
related discussion in https://github.com/kubeflow/metadata/issues/225
