### ISSUE TITLE
Install Kubeflow

### ISSUE THREAD

**Issue by rgupta1234** [kubeflow/website#1216]
https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

Getting:

INFO[0000] Processing application: istio-ingress         filename="kustomize/kustomize.go:606"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application istio-ingress
Usage:

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/1201
/assign @Jeffwan

**Comment by sarahmaddox** [comment]
@Jeffwan Can we close this issue?

**Comment by Jeffwan** [comment]
@sarahmaddox We have groups of people testing instruction in the workshop and it's working fine. We can close this issue.
