### ISSUE TITLE
Markdown flavor/customization for the website 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#122]
The markdown used by our website is not the same as GitHub.

I've also noticed weird issues with the way lists and indented lists are handled.
See for example:
https://github.com/kubeflow/website/pull/113#pullrequestreview-142500969

It looks like hugo uses BlackFriday to render markdown and this is customizable.  So maybe
we can customize it to create better markdown formats?

I think there might be an option about treating line breaks in markdown as breaks in html.
See here:
https://github.com/gohugoio/hugo/issues/158#issuecomment-31071583

Its also possible to use GitHub flavored markdown with BlackFriday but I think that's less customizable so that may not be a good option.
https://github.com/gohugoio/hugo/issues/158#issuecomment-234942900

**Comment by jlewi** [comment]
See this comment
https://github.com/kubeflow/website/pull/130#discussion_r208656648

Looks like the indentation issues might be a CSS issue.

**Comment by sarahmaddox** [comment]
We have issue [#163](https://github.com/kubeflow/website/issues/163) to address the problem with bullet styling (partly addressed but needs more tweaking).

My 2c is that it'd be confusing to try overriding the Markdown flavour that we use, and may lead to inconsistent results. I'll close this issue, but please do re-open it if you think we need to do more work on it.

/close
