### ISSUE TITLE
update 'End-to-end Kubeflow on GCP' tutorial as necessary

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1221]
https://www.kubeflow.org/docs/gke/gcp-e2e/
Looks like we'll probably need to update this -- as per Dan, it only works on KF 0.5, but 0.5 deployment is now unsupported via the C2D app.  Creating placeholder to investigate.
(The docs do say to use 0.6 -- it's not clear to me whether the example breaks with 0.6.2...?)

**Comment by amygdala** [comment]
kind/bug

**Comment by amygdala** [comment]
Just some notes on things that need to be addressed:

- existing web ui service spec uses ClusterIP and won't provide external IP
  - related: could it make sense to add routing so that they can go through IAP endpoint?
- this line showing edits in web ui deployment.yaml: `- image: gcr.io/<your-project>/<your-deployment-name>` should be `- image: gcr.io/<your-project>/<your-deployment-name>-web-ui`
- let's consider creating a timestamp-based subdir under the bucket for the training results so that they can run the example multiple times
- the Dockerfile for the web ui image needs to pin to some earlier version of TF -- currently it is breaking with the unpinned build.

(cc @sarahmaddox @DanSanche )

**Comment by amygdala** [comment]
Even using the prebuilt web ui image I get the following error -- do you see this, Dan?
![image](https://user-images.githubusercontent.com/115093/66611477-91b78280-eb73-11e9-8854-8d376b8282a2.png)

**Comment by DanSanche** [comment]
hmm no I didnt see that when I ran through the codelab! It seems like theres an issue with the service. I can run through the doc again if that would help

**Comment by amygdala** [comment]
I wonder if it could be IAP-related (which the tutorial indicates to use but the codelab does not). I tried with a fresh (IAP-enabled) cluster and the prebuilt webui image and got the same result again.  Hmm. I'll try with a basic auth endpoint next.

**Comment by amygdala** [comment]
I think I figured it out -- the tutorial sets the tf-serving service name via
`kustomize edit add configmap mnist-map-serving   --from-literal=name=mnist-gcs-dist`  — which sets the service name to `mnist-gcs-dist`, but the flask app assumes the service name will be `mnist-service`— which is what the codelab uses.  
So I don't see how the tutorial variant actually worked previously. 😬

**Comment by amygdala** [comment]
put in this PR to pin the TF version used for the web UI image: https://github.com/kubeflow/examples/pull/658  (Tests are breaking for reasons unrelated to my change).

**Comment by sarahmaddox** [comment]
/assign @amygdala 
Thanks Amy!

**Comment by sarahmaddox** [comment]
This is fixed by PR https://github.com/kubeflow/website/pull/1240

/close
