### ISSUE TITLE
Reference to `ks` in AWS documentation

### ISSUE THREAD

**Issue by wdhorton** [kubeflow/website#1223]
The "Storage Options" section of the AWS deploy documentation (https://www.kubeflow.org/docs/aws/storage/) still refers to `ks` commands, even though Kubeflow has moved away from `ksonnet`. I think this should be updated with the appropriate commands to run with the current tools.

**Comment by wdhorton** [comment]
I also see there's a reference to `kfctl.sh` on this page: https://master.kubeflow.org/docs/aws/customizing-aws/.

**Comment by Jeffwan** [comment]
@wdhorton I will have a clean up and file PR by this week.

**Comment by sarahmaddox** [comment]
ksonnet (ks) is also referenced on this page:
https://www.kubeflow.org/docs/aws/troubleshooting-aws/

**Comment by sarahmaddox** [comment]
@Jeffwan Will you be tackling this issue during the doc sprint?

**Comment by Jeffwan** [comment]
@sarahmaddox Yeah, I will file a PR to address it.

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/1847
