### ISSUE TITLE
Update all CONFIG paths for kfctl command to the v0.7 paths

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1224]
Update `CONFIG` paths for kfctl command in the following files:
* https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-uri-gcp-basic-auth.html
* https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-uri-gcp-iap.html
* https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-uri-k8s-istio.html
* https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-uri-existing-arrikto.html

The paths in the above files are used on various pages in the docs. For example, the GCP paths are used on this page:
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

**Comment by nrchakradhar** [comment]
The links were referring to kubeflow/kubeflow git. They would need to refer to manifests from 0.7 onwards.
https://github.com/kubeflow/manifests/tree/v0.7.0-rc.0/kfdef

**Comment by sarahmaddox** [comment]
This is now done.
