### ISSUE TITLE
Deploying Kubeflow to an existing GKE Cluster fails

### ISSUE THREAD

**Issue by BBK-PiJ-2015-41** [kubeflow/website#1238]
Good Morning,
Does the command **kfctl apply k8s -V** work with an existing GKE Cluster created using other means (terraform, for example)?

I've so far failed to get the deployment succeed even after creating all gcp resources handled by the deployment manager before hand and have also created the k8s secrets for the three services accounts created by the deployment manager including the OAuth client id and secrets in all namespaces - all normally handled by kfctl if **kfctl apply all -V** is executed.

**Comment by sarahmaddox** [comment]
@jlewi Can you suggest someone to help @BBK-PiJ-2015-41 with this question?

**Comment by jlewi** [comment]
Please follow these instructions to deploy on an existing cluster
https://www.kubeflow.org/docs/started/k8s/

You need to specify a config file that provides the appropriate configuration that you want to deploy.

**Comment by BBK-PiJ-2015-41** [comment]
Thank you
