### ISSUE TITLE
Add links to source file for easy edit links

### ISSUE THREAD

**Issue by activatedgeek** [kubeflow/website#124]
The current structure of the docs is amenable to adding a Github link to the source file. This will be a welcome change to allow easy click and change via the Github PR.

This kind of approach is pretty common across many popular docs and I think should make it easier for all of us to quickly make edits to existing code.

/area docs
/assign @abhi-g

**Comment by sarahmaddox** [comment]
+1 - it'd be great to add an "Edit on GitHub" link to every doc page.

I'm currently investigating the Docsy theme, which incorporates such a link. See issue #291

**Comment by sarahmaddox** [comment]
The Docsy theme is now live on the site, and this issue is fixed.
/close
