### ISSUE TITLE
what's prescribed for gke kubeflow doesn't work. There is an open bug filed from July 15th. 

### ISSUE THREAD

**Issue by yarcyarc** [kubeflow/website#1243]
The recipe and/or url on https://www.kubeflow.org/docs/started/cloud/getting-started-gke/ leading to https://deploy.kubeflow.cloud doesn't work. 

There is a bug filed https://github.com/kubeflow/kubeflow/issues/3659.

**Comment by jlewi** [comment]
Duplicate of kubeflow/kubeflow#3659
