### ISSUE TITLE
Pipelines Quickstart - Note on GKE cluster functionality

### ISSUE THREAD

**Issue by jtanios** [kubeflow/website#1247]
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/

>Due to kubeflow/pipelines#1700 and kubeflow/pipelines#337, some non-critical pieces of functionality are currently available only on GKE clusters.

It looks like both issues mentioned above were fixed and their respective PR's merged recently.

**Comment by sarahmaddox** [comment]
Thanks @themummy that's good to know. The issues are still open, though the PRs are merged. Let's wait until the issues are marked as fixed, in case additional work is required. I'll come back and check in a week's time.

**Comment by sarahmaddox** [comment]
I've added a comment to both the referenced issues, asking if they can now be closed.

**Comment by sarahmaddox** [comment]
Still chasing this down. One of the issues is now closed, but I'm awaiting a response on the container registry issue.

**Comment by sarahmaddox** [comment]
It looks like the fix for https://github.com/kubeflow/pipelines/issues/1700 is still not complete. We should change the note to mention just one issue, not both.

/good-first-issue

**Comment by sarahmaddox** [comment]
I'll take this one.
