### ISSUE TITLE
Set up a GCP Project - Missing required APIs

### ISSUE THREAD

**Issue by themummy** [kubeflow/website#1248]
https://www.kubeflow.org/docs/gke/deploy/project-setup/

>Go to the following pages on the GCP Console and ensure that the specified APIs are enabled on your GCP account:
>
>* Compute Engine API
>* Kubernetes Engine API
>* Identity and Access Management (IAM) API
>* Deployment Manager API

The following APIs are also required:
* Cloud Filestore API
* Cloud Machine Learning Engine

**Comment by sarahmaddox** [comment]
Thanks for reporting this, @themummy. 
@abhi-g Have we added a dependency on the Filestore and CMLE APIs? AFAIK, Filestore is an optional addition. Not sure about CMLE.

**Comment by abhi-g** [comment]
I believe we do enable the CMLE and Filestore APIs are part of the installation process. 
cc @kunmingg 

When deploying with kfctl or through the WebApp deployer on GCP, the deployer application will automatically enable all required APIs. We can probably document as the list of APIs that are enabled. Kunming, please correct me if I am wrong about kfctl enabling the APIs.

**Comment by kunmingg** [comment]
The apis enabled during kubeflow setup: https://github.com/kubeflow/kubeflow/blob/1d811f737d7555782dbeab09eb88795a84aeded9/bootstrap/pkg/kfapp/gcp/gcp.go#L2186
