### ISSUE TITLE
Pipelines API Reference

### ISSUE THREAD

**Issue by TiraO** [kubeflow/website#1257]
https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/

It would be useful to link to https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto

where it says 'see filter.proto' in the pipelines documentation.
e.g. (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto))

**Comment by sarahmaddox** [comment]
Good point. @OfficePop This may be worth investigating as part of your work on the API reference docs.

**Comment by OfficePop** [comment]
Thanks @sarahmaddox, I will look into it!
