### ISSUE TITLE
Remove the gitops guide as it does not work for Kubeflow v0.7 onwards

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1259]
https://www.kubeflow.org/docs/use-cases/gitops-for-kubeflow/

The guide needs updating for Kubeflow v0.6 and v0.7 - it should use kustomize instead of ksonnet, and should use the new kfctl binary rather than `kftcl.sh`.

**Comment by sarahmaddox** [comment]
@dthomson25 Is this something you can take a look at?

**Comment by sarahmaddox** [comment]
Hallo @dthomson25 just wondering if you have bandwidth to update the Kubeflow gitops guide to use the latest kfctl and config?
https://www.kubeflow.org/docs/use-cases/gitops-for-kubeflow/

**Comment by jlewi** [comment]
I would suggest just deleting this page. Our gitops story is incomplete so my suggestion would be to just delete this page until we have a more complete story for gitops and as part of that add documentation.

**Comment by sarahmaddox** [comment]
+1 to deleting this page. That is, remove the file entirely. I've searched the docs for references to this page. There's just one reference - we should remove the following line:
https://github.com/kubeflow/website/blob/master/content/_redirects#L101
