### ISSUE TITLE
Update monitor IAP section for 0.7

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1261]
https://www.kubeflow.org/docs/gke/deploy/monitor-iap-setup/

This page needs to be updated for 0.7 in particular

* Instructions for cetificate need to be updated to use GKE managed certificate
* We should provide a step for checking the JWT policy

**Comment by sarahmaddox** [comment]
@lluunn Is this something you can tackle?

**Comment by jlewi** [comment]
@lluunn Do you have an ETA for a PR?

**Comment by sarahmaddox** [comment]
Thanks @lluunn!

/close
