### ISSUE TITLE
Links for 0.7 manifest kfctl files are broken

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#1267]
In kfctl version cherry-pick PR https://github.com/kubeflow/manifests/pull/565, 

For example, file was renamed from 
`https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.yaml`
to 
`https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_aws.0.7.0.yaml`

Seems we did this in v0.6.2 as well. Want to double make sure if this is right pattern, we may expect 0.7.1 coming as well. If so, we may need to rename file one more time.

**Comment by sarahmaddox** [comment]
@Jeffwan That's correct. The manifest file names are changing incrementally for the various cloud/on-prem configs. And yes, they're version-specific, so we'll need to update them again for v0.7.1.

Would you like to send a PR to update them for AWS, now that we have the final URL for v0.7.0? These are the two doc files that need updating:
* https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-uri-aws-standard.html
* https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-uri-aws-cognito.html

**Comment by Jeffwan** [comment]
I will take the one for aws.
