### ISSUE TITLE
Document the Configurations and Extra Resources fields in the Notebooks setup screen

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1268]
Document the **Configurations** and **Extra Resources** fields in the Notebooks setup screen. (We currently mention **Extra Resources** when discussing GPUs, but we should document other available options too.)

Doc to update:
https://www.kubeflow.org/docs/notebooks/setup/#create-a-jupyter-notebook-server-and-add-a-notebook

Screenshot:
![image](https://user-images.githubusercontent.com/6138251/67442074-385c4400-f5b4-11e9-9594-0015dde35dd0.png)

**Comment by sarahmaddox** [comment]
Guide to updating the docs:
https://github.com/kubeflow/website/blob/master/README.md

**Comment by shanidchamal** [comment]
CPU, RAM and GPU are the main resources for cluster. for gpu, nvidia is common and amd also i think. the plugin set for extending Kubernetes are listed [here](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/). based on that, if somebody uses those plugins, then they may add those resources as extra. Also, [enabling gpu and tpu](https://www.kubeflow.org/docs/pipelines/sdk/gcp/enable-gpu-and-tpu/) suggests ways for adding gpu and nodeSelector for selecting a distinct type of gpu for particular notebook. nodeSelector is important for on-prem users as well but this feature not implemented yet. same the case for adding tpu in gke. For configurations.. are they low-level things users should be aware of ?

**Comment by sarahmaddox** [comment]
@lluunn Maybe you can help? We need to tell users (a) which options are supported, and (b) the format supported by the UI fields. If you have any useful info/links that you can add to this issue, then I can get started with a PR.

/assign

**Comment by lluunn** [comment]
cc @kimwnasptd

**Comment by lluunn** [comment]
For extra resource, the [value](https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py#L402) should be a json string value for container.resouces.limit: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container

For example: `{"memory": "128Mi", "cpu": "500m"}`

**Comment by lluunn** [comment]
Configuration is a list of labels: https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py#L365

It can be used to set [PodDefault](https://www.kubeflow.org/docs/gke/authentication/#poddefault-object). For example, to use the poddefault with:
```
matchLabels:
    addgcpsecret: "true"
```
Add configurations: `addgcpsecret`

**Comment by lluunn** [comment]
@kimwnasptd please correct me if there is anything wrong.
@sarahmaddox please let me know if you need more info

**Comment by sarahmaddox** [comment]
Thanks @lluunn! I'll work on a PR for this doc update.
