### ISSUE TITLE
Multi-user, auth-enabled Kubeflow with kfctl_existing_arrikto;  unknown shorthand flag -f

### ISSUE THREAD

**Issue by BeneaAlinAndrei** [kubeflow/website#1279]
While trying to install Kubeflow following the steps in the tutorial bellow, i encountered the following problem:

I run: `kfctl apply -V -f ${CONFIG_FILE}`

And i received the error: `Error: unknown shorthand flag: 'f' in -f`

The flag  `- f`   does not exist in the documentation of kfctl command.  

https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/

**Comment by sarahmaddox** [comment]
@BeneaAlinAndrei This could be a problem with the Kubeflow version - which version of kfctl have you downloaded? The docs refer to Kubeflow v0.7.0. The `-f` flag is new in kfctl.

If you're looking for the Kubeflow v0.6 docs, you can find them here:
https://v0-6.kubeflow.org/
(You can also access the docs for other versions from the release number dropdown on the docs website.)

**Comment by yanniszark** [comment]
This seems like a wrong kfctl version.
@BeneaAlinAndrei can you give us the output of `kfctl version`?
You should download this version: https://github.com/kubeflow/kubeflow/releases/tag/v0.7.0-rc.6
or a newer one if available.

**Comment by BeneaAlinAndrei** [comment]
Yup, the version was outdated, thanks a lot!
