### ISSUE TITLE
Katib docs need to explain how to do a hyperparameter search

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#128]
The docs for Katib on the website need to explain how to do a hyperparameter search.

For example, in 0.2, metrics for the search are collected from stdout/stderr see 
https://github.com/kubeflow/katib/issues/116#issuecomment-410014730

How hyperparameter tuning works will change in 0.3 because we will likely have a CRD
kubeflow/katib#141

So we may want to wait for that PR before adding updated docs.

**Comment by jlewi** [comment]
@YujiOshima @gaocegege @sarahmaddox Is anyone interested in picking this up in time for 0.4?

**Comment by sarahmaddox** [comment]
@YujiOshima @gaocegege @jlewi sorry, I'm a little flat out at the moment. Happy to review the doc, if someone can put together the first draft?

**Comment by jlewi** [comment]
@YujiOshima @gaocegege any interest in trying to get this done for 0.4?

**Comment by jlewi** [comment]
@YujiOshima @gaocegege @johnugeorge Can anyone take a stab at updating the Katib docs?

**Comment by johnugeorge** [comment]
I will add them

**Comment by andreyvelich** [comment]
Will take it. 
/assign
