### ISSUE TITLE
Add user doc to setup Dex based Kubernetes API Authentication

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/website#1280]
Current setups with Dex Auth enabled at Istio Gateway should be supported with docs for Authentication at Kubernetes API level too. Add a doc to setup and troubleshoot a setup with Dex auth enabled at Kubernetes API.

/assign @krishnadurai

**Comment by sarahmaddox** [comment]
@krishnadurai Is this the doc that you're referring to?
https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/

**Comment by krishnadurai** [comment]
@sarahmaddox I'm looking to document how to setup Dex Authentication with Kubernetes API server - which authenticates kubectl commands. The doc you are referring to sets it up for Istio ingress gateway - for the Kubeflow Web UI.

**Comment by sarahmaddox** [comment]
@krishnadurai What's the status of this issue?

**Comment by krishnadurai** [comment]
Refer comment: https://github.com/kubeflow/website/issues/1066#issuecomment-570390498

@sarahmaddox I had been waiting for the fix kubeflow/kubeflow#4517 to go in. Since now its in, I need to make some minor modifications to our manifests to support OIDC plugin for kubernetes.

I'll be able to move and publish these documents thereafter. Expect this to be done within 1.0.

**Comment by sarahmaddox** [comment]
Thanks @krishnadurai
