### ISSUE TITLE
Document the compatible/incompatible/tested versions of various dependencies

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1281]
Create a page with a compatibility matrix showing compatible/incompatible/tested versions of various dependencies, including:
* K8s, 
* ISTIO, 
* knative, 
* KFServing, 
* and maybe others....

Distinguish between:

* What we test/support
* What we know doesn't work
* What we haven't tested (maybe this can be specified implicitly by not listing it).

For example, for K8s:
* We know that Kubeflow doesn't work with Kubernetes 1.16.
* We haven't tested Kubeflow on Kubernetes 1.15 so we don't really know.
* We test Kubeflow on GKE with 1.14.

Note that we also include the K8s versions on this page:
https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements

We should use shortcodes to contain the various version numbers, to free us up to use it in many places if necessary. (A shortcode also makes searching easy.) The shortcode should be similar to the one we use for K8s min version: https://github.com/kubeflow/website/blob/master/layouts/shortcodes/kubernetes-min-version.html

Location for doc - a page in this section:
https://www.kubeflow.org/docs/other-guides/

**Comment by sarahmaddox** [comment]
Related issue: https://github.com/kubeflow/website/issues/1129

**Comment by sarahmaddox** [comment]
@mameshini @jlewi I think we have two different types of version matrix under discussion:

* In this issue (https://github.com/kubeflow/website/issues/1281), we're looking at **dependencies** such as K8s, Istio, and so on. Users need to know which version of each dependency they should use with each version of Kubeflow.
* In issue https://github.com/kubeflow/website/issues/1129, we're looking at **Kubeflow applications**. These are apps that are part of the Kubeflow project (KFServing, TFServing, Pipelines, and so on). Users need to know which version of each app is included by default when they deploy Kubeflow. Users also need to know whether the app is considered *production-ready with Kubeflow v1.0*.

Does the above make sense?

I'm working on https://github.com/kubeflow/website/issues/1129 as part of the docs for the v1.0 launch.

But I think we need the matrix discussed in this issue (https://github.com/kubeflow/website/issues/1281) earlier than that. @mameshini based on the recent Slack discussion, can I assign this issue to you, to work on with Arun Gupta?

**Comment by mameshini** [comment]
@sarah yes please assign the matrix discussed in this issue (#1281) to me and Arun - we will update https://kubernetes.io/docs/home/supported-doc-versions/ as well as other relevant pages.
We will need to delay the matrix about dependencies (Istio, dex, etc) until we get this information, may be via Kubeflow discussion list.  For example, I am currently using Kubeflow with Istio 1.3.3, but it's not a standard version of Istio shipped with Kubeflow.  I am not sure what is the best way to get  information about supported/unsupported versions.

**Comment by sarahmaddox** [comment]
/assign @mameshini 

To gather the information, I'd suggest creating a Google doc with a partially complete matrix, then circulate it via kubeflow-discuss. You could also mention it in a community meeting. When you have (most of) the info in the matrix, you can move it to a PR.
