### ISSUE TITLE
[GCP] Document IAM and multi-user

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1283]
To share a cluster on GCP people need to be granted appropriate IAM roles.

We should document this.

To access the UI viap IAP they need http accessor role

```
gcloud projects add-iam-policy-binding ${PROJECT} --member=user:${EMAIL} --role=roles/iap.httpsResourceAccessor
```

To be able to do `gcloud get credentials` and see logs in stackdriver they will need viewer access on the project

```
gcloud projects add-iam-policy-binding ${PROJECT} --member=user:${EMAIL} --role=roles/viewer
```

**Comment by jlewi** [comment]
@sarahmaddox yup I think that's a good place for the docs at least for now.
https://www.kubeflow.org/docs/other-guides/multi-user-overview/#pre-requisite-grant-user-minimal-kubernetes-cluster-view-access

**Comment by sarahmaddox** [comment]
@jlewi I think PR https://github.com/kubeflow/website/pull/1318 addressed this issue. Can we close this issue now or is there still work to do?

**Comment by jlewi** [comment]
PR #1318 updated the instructions about workload identity; this covers how people run workloads that authenticate to GCP.
https://www.kubeflow.org/docs/gke/authentication/

The instructions mentioned in the initial comment cover sharing access to the cluster. We have some instructions here
https://www.kubeflow.org/docs/other-guides/multi-user-overview/#pre-requisite-grant-user-minimal-kubernetes-cluster-view-access

but are missing the gcloud commands in the initial comment.

So I think before we close this issue we just need to add the gcloud commands to

https://www.kubeflow.org/docs/other-guides/multi-user-overview/#pre-requisite-grant-user-minimal-kubernetes-cluster-view-access

**Comment by sarahmaddox** [comment]
/assign

Started work on this.
