### ISSUE TITLE
c2d info now needs to include additional instrs on enabling APIs

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1288]
Placeholder issue so I don't forget. Turns out that we now need to have people enable two apis in their GCP project prior to running the c2d app, otherwise deployment will fail:
https://console.cloud.google.com/apis/api/iam.googleapis.com/overview
https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview

This might be a recent change in how GCP projects are set up.

**Comment by sarahmaddox** [comment]
Thanks @amygdala Do people need to enable these APIs only if using C2D? Also, currently C2D doesn't yet support v0.7. Do you know if the requirement for these APIs will apply when C2D supports v0.7 too?

**Comment by sarahmaddox** [comment]
Related (but different APIs): https://github.com/kubeflow/website/issues/1248

**Comment by sarahmaddox** [comment]
Ah, here's where Kubeflow requests the APIs:
https://github.com/kubeflow/kubeflow/blob/1d811f737d7555782dbeab09eb88795a84aeded9/bootstrap/pkg/kfapp/gcp/gcp.go#L2186

From the above, it looks as if we need the user to enable them for either the CLI deployment or C2D - is that a correct assumption?

**Comment by sarahmaddox** [comment]
I see we do already tell them to enable the IAM API. I'll include a section in the C2D guide asking people to check the requirements. I'll also add the Cloud Resource Manager API to the list.
