### ISSUE TITLE
Update the complete name of Amazon EKS

### ISSUE THREAD

**Issue by arun-gupta** [kubeflow/website#1290]
Amazon EKS complete name is `Amazon Elastic Kubernetes Service`. https://www.kubeflow.org/docs/started/cloud/getting-started-aws/ is still using older name "Amazon Elastic Container Service for Kubernetes".

// @Jeffwan

**Comment by shanidchamal** [comment]
please find PR #1294

**Comment by sarahmaddox** [comment]
/assign @shanidchamal 

Thanks @shanidchamal
