### ISSUE TITLE
GitOps For Kubeflow Using Argo CD uses old kfctl

### ISSUE THREAD

**Issue by grischa** [kubeflow/website#1292]
https://www.kubeflow.org/docs/use-cases/gitops-for-kubeflow/

It still uses kfctl init and generate and refers to a non-existent script.

Would be great to have up to date documentation on using Argo with the new kfctl version 0.7.x and kustomise.

**Comment by sarahmaddox** [comment]
Thanks for raising this issue! The need to update the doc is recorded in issue https://github.com/kubeflow/website/issues/1259. I'll close this one, and we'll use the earlier issue to track the task.

/close
