### ISSUE TITLE
Broken links to Dockerfile locations

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1293]
On this page:
https://www.kubeflow.org/docs/reference/images/

The following links are broken:
https://github.com/datawire/ambassador/blob/master/Dockerfile
https://github.com/kubeflow/kubeflow/blob/master/components/jupyterhub/docker/Dockerfile

**Comment by jlewi** [comment]
@sarahmaddox should we remove this page? I think its going to be difficult to keep this up to date.

**Comment by sarahmaddox** [comment]
@JavaDerek What are your thoughts on keeping this page up to date?

**Comment by jj-794** [comment]
Here https://www.kubeflow.org/docs/reference/images/ we have a broken link: https://github.com/datawire/ambassador/blob/master/Dockerfile

**Comment by sarahmaddox** [comment]
Thanks @crobby!

/close
