### ISSUE TITLE
dsl-compile immediately crashes

### ISSUE THREAD

**Issue by thavlik** [kubeflow/website#1295]
Installed with `pip3 install https://storage.googleapis.com/ml-pipeline/release/latest/kfp.tar.gz --upgrade --user`. 
```
$ which dsl-compile 
/Users/thomashavlik/Library/Python/3.7/bin/dsl-compile
```
Invocation results in immediate segfault:
```
bash-5.0$ dsl-compile
Abort trap: 6
bash-5.0$ dsl-compile --help
Abort trap: 6
bash-5.0$ dsl-compile --version
Abort trap: 6
```
From zsh:
```
$ dsl-compile --help
zsh: abort      dsl-compile --help
```

Platform: Mac Mini 2018
Mac OSX 10.15.1 (Catalina)

**Comment by sarahmaddox** [comment]
/assign @Ark-kun 

@Ark-kun Please would you take a look at this issue with the DSL?

**Comment by Ark-kun** [comment]
> Abort trap: 6

There might be some problem with your python or OS environment (as the error does not show any python stack trace).
Can you verify the environment?

```
python3 -c 'import sys; print(sys.version)'
```

```
python3 -c 'import kfp; print(kfp.__version__)'
```

P.S. You can get help faster is you open issues in the https://github.com/kubeflow/pipelines repo.

**Comment by thavlik** [comment]
```
~/Repositories$ python3 -c 'import sys; print(sys.version)'

3.7.4 (default, Oct 12 2019, 19:06:48) 
[Clang 11.0.0 (clang-1100.0.33.8)]
```
```
~/Repositories$ python3 -c 'import kfp; print(kfp.__version__)'

zsh: abort      python3 -c 'import kfp; print(kfp.__version__)'
```
(abort trap 6 in bash, still)
Roger on opening the issue elsewhere. Totally didn't realize this was the website! I'm about to leave for the weekend so I'll take care of it Monday. I will close this for now.

**Comment by Ark-kun** [comment]
Can you also try `python3 -m pip install kfp --upgrade --user`?
