### ISSUE TITLE
Improve the documents of storage options

### ISSUE THREAD

**Issue by hongzhao-signifyd** [kubeflow/website#1296]
This doc is using ksonnet commands. I think it should provide other options like kustomize, kubectl commands.

https://www.kubeflow.org/docs/aws/storage/

**Comment by sarahmaddox** [comment]
Thanks for raising this issue! It's also reported in issue https://github.com/kubeflow/website/issues/1223. I'll close this issue and we can use the earlier issue to track the task.

/close
