### ISSUE TITLE
[0.7] Remove reference to Ambassador Service In Connecting To Jupyter Docs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1315]
The docs here mention Ambassador
https://www.kubeflow.org/docs/notebooks/setup/#install-kubeflow-and-open-the-kubeflow-ui

We no longer use Ambassador so we should update that doc.

Rather than duplicating the instructions for accessing the Kubeflow UIs I think we should just link to the page
https://www.kubeflow.org/docs/other-guides/accessing-uis/

**Comment by shanidchamal** [comment]
please see PR #1322 suggest changes if needed.

**Comment by sarahmaddox** [comment]
/assign @shanidchamal 

Thanks @shanidchamal

**Comment by sarahmaddox** [comment]
/close

Closed byhttps://github.com/kubeflow/website/pull/1322
