### ISSUE TITLE
Update samples page to show which version of Kubelow each sample works with

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1316]
This page 
https://www.kubeflow.org/docs/examples/kubeflow-samples/

lists a lot of samples that I don't think are updated for 0.7.

* Should we remove samples until they have been updated for 0.7?
* Should we add the [xgboost_synthetic](https://github.com/kubeflow/examples/tree/master/xgboost_synthetic) ?

   * That is probably the sample most up to date for 0.7

* [code_search](https://github.com/kubeflow/examples/tree/master/code_search) is pretty stale at this point as are some other samples so we should probably remove that one.

* I think @amygdala might have made some updates to github issue summarization recently

**Comment by jlewi** [comment]
@sarahmaddox suggested not removing the list of samples but instead with each one listing the Kubeflow versions they work with.

**Comment by janeman98** [comment]
@sarahmaddox Is there an easy way to find out what version these sample work with?

I have a quick look on these samples, most of them just point to "Getting Started with Kubeflow"
Semantic code search -- > Getting Started with Kubeflow (https://www.kubeflow.org/docs/started/getting-started/)
Financial time series --> KUBEFLOW_VERSION=0.2.5 ??
GitHub issue summarization --> v0.4.0-rc.2.
MNIST image classification -- > Getting Started with Kubeflow
Object detection - cats and dogs -- > Getting Started with Kubeflow
PyTorch MNIST -->  Getting Started with Kubeflow
Ames housing value prediction --> Getting Started with Kubeflow

**Comment by sarahmaddox** [comment]
@texasmichelle and @amygdala Can you help identify the Kubeflow version for each sample?

**Comment by amygdala** [comment]
I should have some time to tackle it week after next.  (Most aren't "mine" and I don't know their current status). 
The github summarization/pipelines one _is_ mine, and has been updated to work with 0.7. (Note: that's the `pipelines` subdir of that example.)

**Comment by hefedev** [comment]
I'd like to jump on this one if possible. 
To figure out which version works, I'll look at the CONFIG_FILE url and which master branch it points toward. This is always worked for me before.

**Comment by sarahmaddox** [comment]
/assign @hefedev 

Thanks @hefedev!

**Comment by sarahmaddox** [comment]
@hefedev I've moved this issue to **In progress** in the [doc sprint Kanban board](https://github.com/orgs/kubeflow/projects/21), because the issue is assigned to you. Happy sprinting!

**Comment by hefedev** [comment]
Thank you @sarahmaddox for the opportunity, I submitted my first changes for feedback. I'll get back on this asap.

**Comment by amygdala** [comment]
I'm not sure this should be closed yet? I believe we're still testing many of these examples with the KF 1 RC.  
cc @velascoluis, who is helping with this.

**Comment by sarahmaddox** [comment]
Thanks @amygdala that's excellent news. Let's keep this issue as closed, because it originally related to v0.7 and because @hefedev has implemented a solution using Hugo block parameters and the GitHub API.

How about raising another issue for v1.0. If we need to manually override the results from the API, we can do that via the parameters that feed into the block.

**Comment by amygdala** [comment]
Just a note so it doesn't get lost: https://github.com/kubeflow/examples/blob/master/pipelines/mnist-pipelines/mnist_pipeline.py turns out to be broken (in 0.7 too, I believe, given the nature of the probs).
