### ISSUE TITLE
Pipelines: add a link to this codelab: https://g.co/codelabs/kfp-gis

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1317]
As requested :) -- add a link somewhere to the github summarization *pipelines* codelab: https://g.co/codelabs/kfp-gis
cc @sarahmaddox 
(not to be confused with the 'non-pipelines' GH summarization example & codelab...)

**Comment by sarahmaddox** [comment]
Add the link on this page:
https://www.kubeflow.org/docs/pipelines/tutorials/cloud-tutorials/

/good-first-issue

**Comment by amygdala** [comment]
Actually, it turns out that this example does not (yet) run in 0.7 (related to some service account permissions changes, apparently).  I'll need to put in a PR to fix that before we list it for the new release.

**Comment by sarahmaddox** [comment]
/assign @amygdala 

@amygdala How's it going with the codelab update - is it safe to link to it from the docs yet?

**Comment by sarahmaddox** [comment]
Thanks @mageirakos!
/close
