### ISSUE TITLE
getting-started-minikube references non-existent script

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/website#1324]
this page https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/#quick-setup references setup-minikube.sh which was removed in v0.6.2

**Comment by sarahmaddox** [comment]
Thanks for raising this issue! We already have issue https://github.com/kubeflow/website/issues/1324 which reports the same problem. I'll close this issue, and we can use the earlier issue to track work.

/close

**Comment by kkasravi** [comment]
> Thanks for raising this issue! We already have issue #1324 which reports the same problem. I'll close this issue, and we can use the earlier issue to track work.

#1324 is this issue.

**Comment by sarahmaddox** [comment]
Oops sorry! Here's the right link: https://github.com/kubeflow/website/issues/1183
