### ISSUE TITLE
Kubeflow Deployment with kfctl_k8s_istio - <none> External IP

### ISSUE THREAD

**Issue by BeneaAlinAndrei** [kubeflow/website#1328]
Hello,

After i successfully deployed Kubeflow on my master node, i noticed that **`istio-ingressgateway `** is showing **`<none>`** **`EXTERNAL-IP `**, which is blocking the communication between the front end and the back end. 

i will mention that i have Kubernetes 1.14 and Kubeflow version 0.7. I had deployed the cluster on my master node. 

 I missed a step, and is  there any way to resolve this problem?

If anyone knows the answer and can help, thank you very much! 

https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

**Comment by sarahmaddox** [comment]
@jlewi Who is the best person to look into this issue?

**Comment by BeneaAlinAndrei** [comment]
> @jlewi Who is the best person to look into this issue?

Found the solution. In order to make it work you need to install an external load balancer.

A good solution for this problem is in the other tutorial: https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/

Just running the "Expose Load Balancer" step will resolve this problem. Maybe is an idea to put this step also in this tutorial.
