### ISSUE TITLE
Error running katacoda kubeflow deployment scenario

### ISSUE THREAD

**Issue by indranilr** [kubeflow/website#1329]
Getting below error while running katacode kubeflow deployment scenario.See screen shot below. 

kubeflow get pods returns no resources afterwards.

![image](https://user-images.githubusercontent.com/13346906/68494003-9dca5900-0273-11ea-82f0-250475034970.png)

**Comment by sarahmaddox** [comment]
Hallo @indranilr 

I think you're using the Katacoda tutorials at this location:
https://www.katacoda.com/kubeflow/scenarios/deploying-kubeflow

From your screenshot, it looks like the tutorial is quite out of date. It seems to be deploying Kubeflow v0.2.5, while the latest version of Kubeflow is v0.7.

May I suggest that you follow one of the deployment guides here:
https://www.kubeflow.org/docs/started/getting-started/

For example, if using Google Cloud Platform:
https://www.kubeflow.org/docs/gke/deploy/project-setup/

Or if deploying to an existing Kubernetes cluster:
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

**Comment by sarahmaddox** [comment]
@indranilr I'm going to close this issue, as it doesn't relate to the Kubeflow docs themselves. Please do take a look at the suggestions in my previous comment.

/close
