### ISSUE TITLE
Remove or fix link to devstats.kubeflow.org

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1331]
On this page:
https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

In this text:

>You can use this table to see how many contributions you’ve made
> Note: This only counts GitHub related ways of contributing

There's a link to the following URL, which gives a privacy error due to an out of date cert:
https://devstats.kubeflow.org/d/13/developers-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-period=y10

If you push pass the privacy error, you get a view that doesn't seem to show any useful data.

Should we remove the link and the surrounding text? Is there a different link to add in its place?

**Comment by sarahmaddox** [comment]
/cc @theadactyl 

@abhi-g Do you know whether we can fix the devstats site, replace the link, or should we remove the link altogether?

I can get this fixed during the upcoming doc fixit, if we know the answer.

**Comment by theadactyl** [comment]
Right now @jlewi has a notebook he's running stats from -- can we link to
that until we have a better public alternative? I dont think we have
resources to fix devstats in the near term.

**Comment by jlewi** [comment]
One option is to link to the http version
http://devstats.kubeflow.org/

We should try to get the cert fixed but its low priority.

**Comment by sarahmaddox** [comment]
OK, let's link to the HTTP version. To make sure there are some meaningful figures rather than an empty page, how about linking to the developer stats (since that's what the doc page mentions):
http://devstats.kubeflow.org/d/9/developers-summary

**Comment by sarahmaddox** [comment]
Thanks @drewylui!

/close
