### ISSUE TITLE
Change "good first issue" and "help wanted" links in contrib guide to include all of Kubeflow org

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1332]
On this page:
https://www.kubeflow.org/docs/about/contributing/#starter-issues

Change the link for **good first issue** to include all of Kubeflow org, not just kubeflow/kubeflow: use this link
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+org%3Akubeflow

Similarly for the **help wanted** label.

**Comment by sarahmaddox** [comment]
FYI - this answers a question that came up a few times at the contributor summit
/cc @theadactyl 
/cc @abhi-g 
/cc @jlewi

**Comment by abhi-g** [comment]
Thanks for creating the issue @sarahmaddox. I agree we should update it.

**Comment by jlewi** [comment]
@deepak2431  unfortunately I think we need to revert #1406 . The link only works if you are a member of the kubeflow GitHub org 

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+org%3Akubeflow

You can try it in an incognito browser; I get a 404.

I don't know of anyway to search issues in an org without being a member of the org.

**Comment by jlewi** [comment]
@deepak2431 would you mind opening a PR to revert your change?

**Comment by deepak2431** [comment]
@jlewi Hi, sure I will make a pull request by reverting back the changes. I have tested the link got the same error as you have mentioned above.
Thanks!

**Comment by sarahmaddox** [comment]
/assign

Thanks for the work on this, @deepak2431, and my apologies for not realizing that the suggested links work only for members of the Kubeflow org on GitHub.

I'll take this issue over. I think a good solution is to offer two versions of the "good first" issue link, for two different repos, and suggest that people look at the "good first issue" label in other repos too.
