### ISSUE TITLE
Website home page should not mention Ambassador

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1333]
The website home page mentions Ambassador, but I think Kubeflow v0.7 onwards no longer uses Ambassador:
https://www.kubeflow.org/

**Comment by sarahmaddox** [comment]
@jlewi Is it correct to say we should remove Ambassador from the home page? If yes, I can get this done during an upcoming doc fixit this week.

**Comment by jlewi** [comment]
The mention I see as "We also integrate with Istio and Ambassador for ingress,"
We still use Ambassador in some cases as part of external authentication so its not entirely untrue.

It would be good to have a way of crediting all the technologies and projects we build upon without getting into the specifics.

**Comment by sarahmaddox** [comment]
Thanks Jeremy, that's good enough for now. I'll close this issue.

/close
