### ISSUE TITLE
WtD fixit: Readability improvements for Securing Your Clusters

### ISSUE THREAD

**Issue by sxbfundi** [kubeflow/website#1367]
https://www.kubeflow.org/docs/gke/private-clusters/

* Expand abbreviations on first use.
* Add colons at end of all intro sentences.
* Add intro sentences where missing.
* Consider breaking up the very long numbered list.

**Comment by sarahmaddox** [comment]
Pull #1403 addresses this issue, but there are still more fixes to make - see the PR comment.

**Comment by sarahmaddox** [comment]
Thanks for the updates in your PR, @sxbfundi! I'll close this issue now, since we've finished the fixit. We'll tackle the remaining tidy-ups in our next fixit or random tech-writer read-through.

/close
