### ISSUE TITLE
Google Cloud for Kubeflow

### ISSUE THREAD

**Issue by bermudezmt** [kubeflow/website#1386]
https://www.kubeflow.org/docs/started/cloud/getting-started-gke/

The video on this page is out of date:
https://www.kubeflow.org/docs/started/cloud/getting-started-gke/

It uses the following video, which installs Kubeflow 0.5:
https://www.youtube.com/watch?v=AF-WH967_s4

There've been a number of changes to the Kubeflow installation processes since v0.5, both in the deployment UI and in the CLI. We should remove this video until we have a new one for Kubeflow v0.7.

**Comment by sarahmaddox** [comment]
I've raised an issue in the `kubeflow/examples` repo to request the updating of the video and related sample: https://github.com/kubeflow/examples/issues/680
