### ISSUE TITLE
question about designing

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/website#139]
when i create a study，are all trial running  concurrently，and it is too resource intensive，is there any policy to handle this？

**Comment by sarahmaddox** [comment]
/assign @abhi-g 

Abhishek, do you know the answer to this question, and is it something we should include in the docs?

**Comment by sarahmaddox** [comment]
/assign @richardsliu 

@richardsliu Do you have an answer to this question, and is it something we should document?

**Comment by richardsliu** [comment]
@wukong1992 Which version of Katib are you using? In v1alpha2 and later, this is controlled by this parameter: https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/experiments/v1alpha3/experiment_types.go#L39

**Comment by sarahmaddox** [comment]
Thanks @richardsliu! I've documented the `parallelTrialCount ` field in the latest Katib doc update - see PR https://github.com/kubeflow/website/pull/1480, which is currently under review. The doc preview is here: https://deploy-preview-1480--competent-brattain-de2d6d.netlify.com/docs/components/hyperparameter-tuning/experiment/#configuration-spec 

@wukong1992 The doc update will appear when the above PR is merged. I'll close this issue as answered. Please do re-open it if there's more doc work to be done.

/close
