### ISSUE TITLE
WtD fixit: Readability improvements for Pipelines Standalone Deployment in GCP

### ISSUE THREAD

**Issue by nkrish1983** [kubeflow/website#1391]
https://www.kubeflow.org/docs/pipelines/standalone-deployment-gcp/

NOTE: OPPORTUNITY FOR WORKING TOGETHER: This page needs quite a bit of work. Suggestion: Have two people work together, One person forks the repo and does the first PR, then when it's merged the second person forks the repo (including the updates) and does a second PR with more changes. Below are some items to fix, but there are more on the page too.
* Change bulleted lists to numbered where applicable, and fix syntax accordingly.
* Change "be able to customize based on your needs" to "be able to customize your deployment based on your needs".
* Change heading "Common Prerequisites" to sentence case."

**Comment by sarahmaddox** [comment]
Thanks @nkrish1983!

/close
