### ISSUE TITLE
Expand the KFServing docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1412]
We have an initial guide to KFServing:
https://www.kubeflow.org/docs/components/serving/kfserving/

We plan to improve the docs iteratively.

With reference to the excellent presentation at KubeCon NA in November:
https://www.youtube.com/watch?v=saMkA4fIOH8

Here are some suggestions from a recent email discussion:

> consider the following:
> - How to do a basic deployment using KFServing for any kind of model (probably already documented).
> - Creating an auto-scaling configuration
> - Requesting GPUs for the deployment
> - A/B deployment, or Canarying

> Essentially, a single document with increasing complexity of the deployment setup will be super helpful and allow users to iteratively reach their desired configuration starting with the simplest.

>  a tutorial style restructuring might help walking through a scenario a real world user is going through

>  would be great to document explainability and graph serving.

> as a notebook wherever possible

**Comment by meizabel** [comment]
@sarahmaddox Sarah, can I take this issue and elaborate the current version of the KFServing guide?

**Comment by sarahmaddox** [comment]
/assign @meizabel 

Thanks @meizabel It will be excellent to have your input here. The KFServing docs are marked in our plan for improving this month (March).

@animeshsingh and @ellis-bigelow do you have any more links to info that @meizabel can use as input? (Animesh and Ellis will be the tech reviewers for this update.)

We'd also like to find out what gaps there are - to what extent does the current doc answer the questions that users are asking, and what more info do we need. I've posted a message in the kubeflow-discuss mailing list asking if anyone has input.

**Comment by meizabel** [comment]
@sarahmaddox Thanks a lot for clarifications! I'll try to do my best. Also, please let me know how else I can help this month. Maybe there is also a bunch of small but important fixes...

**Comment by sarahmaddox** [comment]
@meizabel I haven't had any response to my post on kubeflow-discuss, so let's go ahead with what we have. Let me know if there's enough for you to work with on this issue. You can chat with community members in Kubeflow Slack, to ask questions and verify assumptions while working on the doc.

**Comment by sarahmaddox** [comment]
@meizabel How are you doing on this issue, and have you managed to make contact with people on Kubeflow Slack? If you have a partial update ready, it's fine to start a WIP PR in order to start gathering feedback. Let me know if you need any help.
