### ISSUE TITLE
Code is out of date on "Pipelines-Overview"

### ISSUE THREAD

**Issue by thundergolfer** [kubeflow/website#1417]
This page -> https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/

I was trawling the docs to find out whether Kubeflow's DSL could construct a DAG implicitly from the variables being passed around, and on the website it looked like it was, but then I looked at the code on `master` and it was using this newer `.after(...)` construct. 

I think this page should be updated 🙂

**Comment by sarahmaddox** [comment]
The screenshots of the pipeline graph and run are out of date too.

**Comment by sarahmaddox** [comment]
The following pages likely need an update too:
* https://www.kubeflow.org/docs/pipelines/sdk/build-component/
* https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/
