### ISSUE TITLE
Pipelines: Improve the docs on passing data between pipeline components

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1426]
Kubeflow v0.7 simplified the file I/O for passing data between pipeline components.

Weave a better story in the docs, using the following information sources:
* https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components.ipynb
* https://www.kubeflow.org/docs/pipelines/sdk/component-development/#components-and-data-passing
* https://www.kubeflow.org/docs/pipelines/sdk/parameters/ - probably remove this page and redirect to the improved docs.

**Comment by sarahmaddox** [comment]
@Ark-kun and @paveldournov FYI we should do this soon. :)

**Comment by Ark-kun** [comment]
@sarahmaddox 
It would be great to do this.

The https://github.com/Ark-kun/kfp_samples/tree/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs tutorial also demonstrates data passing for non-python components.

P.S. Please see the [Organize Pipelines samples and tutorials in an ordered curriculum](https://github.com/kubeflow/pipelines/issues/2490) for a proposed structure and order of tutorials. (it still might not cover "quickstart"-style tutorials).

**Comment by sarahmaddox** [comment]
@Ark-kun Is this issue something you can tackle? It's marked as P0 in the docs planning for this month.

**Comment by sarahmaddox** [comment]
From Pipelines team meeting today: @Ark-kun will own this. He has a notebook under development. He'll add a new doc specifically about passing data which introduces the concepts and summarises the steps, and then points to the notebook. He'll also merge content from existing pages and replace that content with a link to the new page.

/assign @Ark-kun
