### ISSUE TITLE
Add RBAC details to the docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1427]
The [Kubeflow v0.7 blog post](https://medium.com/kubeflow/kubeflow-v0-7-delivers-beta-functionality-in-the-leadup-to-v1-0-1e63036c07b8) has details on aggregated RBAC. It would be good to include them in the docs.

Maybe on this page?
https://www.kubeflow.org/docs/other-guides/multi-user-overview/

**Comment by meizabel** [comment]
@sarahmaddox Sarah, and can I take this issue too?

**Comment by sarahmaddox** [comment]
Actually, we've already updated the docs during the doc sprint, but we tracked the work in a different issue. Thanks for drawing my attention to this one, @meizabel  - I'll close this issue now.

/close
