### ISSUE TITLE
Update the Fairing docs for new import in v0.7

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1428]
From the [Kubeflow v0.7 blog post](https://medium.com/kubeflow/kubeflow-v0-7-delivers-beta-functionality-in-the-leadup-to-v1-0-1e63036c07b8):

The Fairing Python SDK is now a subpackage in the kubeflow python namespace. This means it can now be imported as follows:

```
from kubeflow import fairing
```

The fairing package still needs to be installed separately.

**Comment by sarahmaddox** [comment]
/assign @joeliedtke 

@joeliedtke Do you have bandwidth to fix up the Fairing docs?

**Comment by joeliedtke** [comment]
Sure, I'll put together a PR this week.

**Comment by joeliedtke** [comment]
Currently, the Fairing docs rely on example notebooks to demonstrate how to import Fairing. The notebook example has already been updated to use this syntax.  :)

**Comment by joeliedtke** [comment]
/open

After taking another look at this, there may be some changes required to ensure that the Kubeflow notebook example works.

**Comment by joeliedtke** [comment]
In [Fairing issue 381](https://github.com/kubeflow/fairing/issues/381), a user reported having trouble with the Fairing Kubeflow Notebook example. This appears to be an issue with the notebook image referencing the old Fairing library.

I filed a bug for this as [Kubeflow issue 4551](https://github.com/kubeflow/kubeflow/issues/4551).
