### ISSUE TITLE
Minikube for Kubeflow: Installation instructions for brew are outdated.

### ISSUE THREAD

**Issue by otaviocv** [kubeflow/website#1433]
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/

The documentation on the page above shows a cask to install minikube with brew but in the latest docs for minikube it shows a normal installation:

```
brew install minikube
```

**Comment by otaviocv** [comment]
I can work in the issue if it is possible.

**Comment by sarahmaddox** [comment]
@otaviocv Thanks! Yes, it would be great if you could work on the Minikube guide.

/assign @otaviocv
