### ISSUE TITLE
Kubeflow Deployment with kfctl_k8s_istio: kfctl deployment instructions use unknown flag

### ISSUE THREAD

**Issue by otaviocv** [kubeflow/website#1437]
Following the instructions in https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ to make a kubeflow deployment got an error for unknown shorthand flag.

In the [Set Up and Deploy Kubeflow](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/#set-up-and-deploy-kubeflow) section there are the following lines:

```
mkdir -p ${KF_DIR}
cd ${KF_DIR}
kfctl apply -V -f ${CONFIG_URI}
```
When running the last line with kfctl v0.7.0 I got this error:
```
$ kfctl apply -V -f ${CONFIG_URI}
Error: unknown shorthand flag: 'f' in -f
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

unknown shorthand flag: 'f' in -f
```

Not sure if this is documentation outdated or a kfctl bug.

**Comment by krishnadurai** [comment]
@otaviocv I did a test on the website instructions and it seems to work fine at my end.

This error may normally happen when `${CONFIG_URI}` is not set or empty.

**Comment by sarahmaddox** [comment]
@otaviocv Could you double-check that you're using kfctl v0.7.0? The info in the error response `kfctl apply [all(=default)|k8s|platform] [flags]` indicates an older version of kfctl. If v0.7.0 is indeed giving that response, then there's a bug in kfctl.

**Comment by otaviocv** [comment]
I've tried again on another computer a linux this time and it worked fine. The test above is on a macos, I will double check if this is a problem particular to a macos version.

**Comment by otaviocv** [comment]
Not sure what happened, it is working fine now.
