### ISSUE TITLE
Pipelines: De-emphasize ContainerOp in documentation

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/website#1439]
Many pages of our documentation use `ContainerOp` in examples.
`ContainerOp` usage has a number of problems, so we should probably de-emphasize it and replace with components wherever possible.

The main problem of `ContainerOp` is that it does not define a reusable component. By creating an instance of `ContainerOp`, the user creates an ad-hoc *task* object. That *task* is not a *component*. It cannot be shared or loaded. Some information is lost or missing (e.g. the input names and types). Even though the `ContainerOp` remains as an underlying implementation of a *Task*  entity, the users should be discouraged from instantiating `ContainerOp` themselves. Instead they should use `load_component*` and `func_to_container_op`.

The user should create a component definition. It takes about the same number of lines of code.
[106 - Creating components from command-line programs](https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb)

The initial tutorials should start with using external/existing components, then python components (`func_to_container_op` -> `component.yaml`) and container components (`component.yaml`).

See the [Organize Pipelines samples and tutorials in an ordered curriculum](https://github.com/kubeflow/pipelines/issues/2490) for a proposed structure and order of tutorials.

/cc @sarahmaddox @amygdala

**Comment by amygdala** [comment]
Should this remain open?...
