### ISSUE TITLE
Visualize Results in the Pipelines UI: Outdated links for components examples

### ISSUE THREAD

**Issue by otaviocv** [kubeflow/website#1444]
https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/

By the end of the page there are some links to components examples to show how to use the multiple methods of visualization. Some of them go to unknown pages:

* https://github.com/kubeflow/pipelines/blob/master/components/dataflow/predict/src/predict.py
* https://github.com/kubeflow/pipelines/blob/master/components/dataflow/tfma/src/model_analysis.py

I can try to fix this if it is possible. 😉

**Comment by sarahmaddox** [comment]
Thanks @otaviocv it would be great if you can fix these links.

/assign @otaviocv

**Comment by otaviocv** [comment]
After checking the [components](https://github.com/kubeflow/pipelines/tree/master/components) folder on the pipelines repository I found that the _tfma_ component, the example about a web app, and the _dataflow predict_ are, now, pointing to a `deprecated` [folder](https://github.com/kubeflow/pipelines/tree/master/components/deprecated/dataflow/tfma). 

After searching a bit on the components folder I couldn't find equivalents examples on other, not deprecated, folders. I couldn't also find another component that writes a web app or a table output.

Should we point the examples to this `deprecated` folder or create new components with examples of web app and table outputs?

**Comment by sarahmaddox** [comment]
@gaoning777 Can you help with this question?

**Comment by Freezaa9** [comment]
Hi, 

I don't know if it is possible to reopen this issue, but it would be appreciate to have a notebook to show the possibilities of visualyzing a HTML webb app in Kubeflow. Especialy the one shown by the image in the documentation. The example in the docs look really nice and interactive. 

Thanks a lot for the great work !

![image](https://user-images.githubusercontent.com/14346331/121904622-a3c6cc80-cd29-11eb-8e39-a5aa61f1c44e.png)
