### ISSUE TITLE
The section about "Using your own domain" is no longer accurate

### ISSUE THREAD

**Issue by yarongol** [kubeflow/website#1445]
https://www.kubeflow.org/docs/gke/custom-domain/

It contains references to files which no longer exist such as cloud-endpoints.yaml, basic-auth-ingress.yaml

**Comment by sarahmaddox** [comment]
Thanks for reporting this problem @yarongol. There's an existing issue that describes the problem: https://github.com/kubeflow/website/issues/1166

I'll close this issue, and we'll track the updates on the existing issue.

/close
