### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by joncwong** [kubeflow/website#1456]
The invite link for the Slack is no longer active. I would love to join it and contribute.

**Comment by cspavlou** [comment]
You can use this link: https://kubeflow.slack.com/join/shared_invite/enQtNDg5MTM4NTQyNjczLTdkNTVhMjg1ZTExOWI0N2QyYTQ2MTIzNTJjMWRiOTFjOGRlZWEzODc1NzMwNTMwM2EzNjY1MTFhODczNjk4MTk

We should update the website. The Slack invite link [here](https://www.kubeflow.org/docs/about/community/) is correct, but we haven't replaced the other one on the homepage.

**Comment by cspavlou** [comment]
I see that the Slack invite link was present in 2 pages: 

- https://www.kubeflow.org/docs/about/community/
- https://www.kubeflow.org/

On the homepage, there were two occurrences of the out-of-date invite link, I will send a PR to fix this

**Comment by cspavlou** [comment]
I created a PR to fix this: https://github.com/kubeflow/website/pull/1457

**Comment by sarahmaddox** [comment]
Thanks @cspavlou 
/assign @cspavlou
