### ISSUE TITLE
Documentation needed for installing KubeFlow on Openshift 4.x on AWS

### ISSUE THREAD

**Issue by vimalkansal** [kubeflow/website#1465]
Hi,

We need detailed documentation on deploying KubeFlow to an already provisioned Openshift cluster on AWS. I provisioned Openshift 4.2 cluster using IPI (Installer Provisioned Infrastructure) mechanism and followed the instructions to deploy KubeFlow on an already existing Kubernetes cluster - but failed. I did it multiple times and it failed. Openshift is one of the most popular distribution of Kubernetes, it will really help if detailed instructions could be provided.

**Comment by vpavlin** [comment]
@vimalkansal Just wanted to let yo know that OpenShift is not documented on Kubeflow.org - https://www.kubeflow.org/docs/openshift/

Hope it helps
