### ISSUE TITLE
Authenticating Kubeflow to GCP

### ISSUE THREAD

**Issue by dlahlou** [kubeflow/website#1474]
https://www.kubeflow.org/docs/gke/authentication/
In step number 4 : Manually create a profile for user1 and specify the GCP service account to bind in plugins field
How can I do this? I tried the following command : 

```
kubectl create -f - <<EOF
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
name: profileName   
spec:
owner:
kind: User
name: user1@email.com   
plugins:
- kind: WorkloadIdentity
spec:
  gcpServiceAccount: user1-gcp@project-id.iam.gserviceaccount.com
EOF
```

But I get the following error 
`Error from server (Forbidden): error when creating "STDIN": profiles.kubeflow.org is forbidden: User "system:serviceaccount:kubeflow-phaidara:default-editor" cannot create resource "profiles" in API group "kubeflow.org" at the cluster scope`

**Comment by sarahmaddox** [comment]
@kunmingg Can you help with this question?

**Comment by kunmingg** [comment]
Only cluster admin can create profile.
Can you verify you login account permission?

**Comment by dlahlou** [comment]
> Only cluster admin can create profile.
> Can you verify you login account permission?

This solves the problem
