### ISSUE TITLE
FAQ Kubeflow without ISTIO

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1493]
A common question is whether Kubeflow can be used without ISTIO.

A good response is illustrated here.
https://github.com/kubeflow/kubeflow/issues/4586#issuecomment-568762546

We should consider creating an FAQ and adding this to it.

**Comment by sarahmaddox** [comment]
Note: We also have issue https://github.com/kubeflow/website/issues/1532 which requests a page about Istio. If we create such a page, we should put the info about Kubeflow without Istio onto that page, and the FAQ page should just link to that page.

**Comment by sarahmaddox** [comment]
/assign @abhi-g 

@abhi-g I've assigned this issue to you, as you're tackling the related issue for the doc sprint. If you create a page about Istio, we don't need the FAQ. Instead, you can roll the info from this issue into the new page, and knock off both issues at once.

**Comment by sarahmaddox** [comment]
We now have a [page about Istio](https://www.kubeflow.org/docs/other-guides/istio-in-kubeflow/) that answers the question posed in this issue and gives details about Istio.
/close
