### ISSUE TITLE
Delete the TFServing ISTIO doc page

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1500]
Ref: #930 

I think we can just delete the page

https://www.kubeflow.org/docs/components/serving/istio/

This page has multiple subsections which I think should be revised; I might suggest the following

* [Routing with ISTIO vs. Ambassador](https://www.kubeflow.org/docs/components/serving/istio/#routing-with-istio-vs-ambassador)
   * I think we can just delete this subsection since we no longer use Ambasador

* [Rolling out a new model](https://www.kubeflow.org/docs/components/serving/istio/#rolling-out-new-model)
    * I think we can delete this 
    * Our solution for model rollouts is KFServing; so I think we can just get rid of this section

* [Metrics for ISTIO](https://www.kubeflow.org/docs/components/serving/istio/#metrics)
    * This feels a little bit out of place here.
    * I think we can just delete this as well
    * I think we need to figure out the overall monitoring story for Kubeflow (see kubeflow/kubeflow#4099); its likely that will be very platform specific; i.e. on GCP use stackdriver

**Comment by sarahmaddox** [comment]
+1 to deleting this page. That is, remove the file entirely. I've searched the docs for references to this page. When deleting the page, we must also remove the following references:

https://github.com/kubeflow/website/search?q=%22%2Fserving%2Fistio%2F%22&unscoped_q=%22%2Fserving%2Fistio%2F%22

**Comment by sarahmaddox** [comment]
> Ref: #930
>   * I think we need to figure out the overall monitoring story for Kubeflow (see [kubeflow/kubeflow#4099](https://github.com/kubeflow/kubeflow/issues/4099)); its likely that will be very platform specific; i.e. on GCP use stackdriver

Thanks @jlewi. We do have some platform-specific guidelines already:
* https://www.kubeflow.org/docs/gke/monitoring/
* https://www.kubeflow.org/docs/aws/logging/
