### ISSUE TITLE
Update the PyTorch Serving docs for 1.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1501]
This page is outdated
https://www.kubeflow.org/docs/components/serving/pytorchserving/

At a minimum we should remove the reference to ksonnet before 1.0.

For KF 1.0, should we continue to use Seldon to serve PyTorch models or can we switch to KFServing? 

/cc @animeshsingh @ellis-bigelow @cliveseldon

**Comment by jlewi** [comment]
@animeshsingh @ellis-bigelow @cliveseldon can anyone take a look at this?

**Comment by animeshsingh** [comment]
@jlewi @sarahmaddox letme take a look

**Comment by animeshsingh** [comment]
ok this should be removed. Both Seldon and KFServing have support for PyTorch, so an independent section doesn't make sense to me

**Comment by sarahmaddox** [comment]
Thanks @animeshsingh that makes sense. I'll remove the page and redirect incoming links to the [serving overview](https://www.kubeflow.org/docs/components/serving/overview/), which directs people to either Seldon or KFServing.

/assign

**Comment by sarahmaddox** [comment]
@animeshsingh Please would you review this PR and add /lgtm if you're happy with it:
https://github.com/kubeflow/website/pull/1555
