### ISSUE TITLE
Delete the TensorFlow batch predict page

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1502]
This page is very outdated
https://www.kubeflow.org/docs/components/serving/tfbatchpredict/

e.g. it is referencing ksonnet.

batch prediction is not in scope for Kubeflow 1.0 and its not clear exactly what our batch prediction story is.

The batch predict code hasn't been updated in over a year and its not clear what the path forward is.
https://github.com/kubeflow/batch-predict

@sarahmaddox any objection to deleting this page? Can we just delete it or should we add some sort of sentinel indicating the page has been removed so that old links still work?

**Comment by sarahmaddox** [comment]
My 2c is that, since the batch-predict repo exists as a component of Kubeflow, we should have a page describing it in the docs. But we should put a warning on the page (similar to the ones we've put for Alpha features) saying that this component is still in incubation and has minimal support.

See an example of an Alpha notice here:
https://www.kubeflow.org/docs/components/misc/metadata/

**Comment by sarahmaddox** [comment]
Here's a pattern to follow for deleting the content of this page and adding a "not supported" note:
https://www.kubeflow.org/docs/components/training/chainer/
(PR https://github.com/kubeflow/website/pull/1516)

**Comment by jspenc72** [comment]
@sarahmaddox What version of the 

> My 2c is that, since the batch-predict repo exists as a component of Kubeflow, we should have a page describing it in the docs. But we should put a warning on the page (similar to the ones we've put for Alpha features) saying that this component is still in incubation and has minimal support.
> 
> See an example of an Alpha notice here:
> https://www.kubeflow.org/docs/components/misc/metadata/

@sarahmaddox Should we add the Alpha notice in the 0.7 docs? and remove with the "not supported" note in v1.0?

**Comment by sarahmaddox** [comment]
/assign @jspenc72 

Thanks for taking this one on @jspenc72! Let's continue the discussion in your PR https://github.com/kubeflow/website/pull/1517
