### ISSUE TITLE
Update or delete the chainer doc page

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1503]
The chainer page is outdated
https://www.kubeflow.org/docs/components/training/chainer/

It is still referencing ksonnet

I think we need to get this page updated for Kubeflow 1.0

Here are a couple options

1. Delete the page since chainer is not in scope for 1.0
1. Update the docs to be accurate
1. Include a banner at the top of the page explaining that chainer is not in scope for 1.0 and that the docs are outdated

It doesn't look like the chainer code has been updated in over a year
https://github.com/kubeflow/chainer-operator

Given that it doesn't look like chainer is being actively developed my suggestion would be to just delete the docs. 

/cc @everpeace

**Comment by sarahmaddox** [comment]
My recommendation is to keep the page and put a banner at the top explaining that Chainer is not supported in this version of Kubeflow. (This applies to **Kubeflow v0.7**, which is the currently-documented version on kubeflow.org, as well as the upcoming **Kubeflow v1.0**). The banner should also link to the [Chainer GitHub repo](https://github.com/kubeflow/chainer-operator) for further details. Keeping the page gives people the info they need. If we simply remove the page, then people are not sure of the status of this component. They'll see the component in the [Chainer GitHub repo](https://github.com/kubeflow/chainer-operator) and in the earlier versions of the Kubeflow docs, and not be sure what its current status now is. 

If we decide to delete the doc, we should:
* Include a [redirect](https://github.com/kubeflow/website/blob/master/content/_redirects) that sends people to the [Chainer GitHub repo](https://github.com/kubeflow/chainer-operator). 
* Add to the note at the top of the Chainer repo [README](https://github.com/kubeflow/chainer-operator/blob/master/README.md). The note currently states that the component is experimental. We should add that it's not maintained beyond Kubeflow v0.6.

Who can confirm whether there's any intention to continue development of Chainer?

**Comment by jspenc72** [comment]
Just to confirm, we should indicate that chqiner is only working in kubeflow 0.6 and below?

**Comment by sarahmaddox** [comment]
From a docs point of view: The docs that we currently have do not work for Kubeflow v0.7.0 onwards.

**Comment by jspenc72** [comment]
Is there further discussion needed beyond that? I will specify kubeflow 0.6 in the docs? Is continued development on chainer relevant to  this decision if it's not in scope for 1.0?

**Comment by sarahmaddox** [comment]
@jspenc72 Let's give @jlewi the opportunity to reply to recent comments.

**Comment by sarahmaddox** [comment]
@jspenc72 Let's go ahead now. :) I've reviewed your PR.
