### ISSUE TITLE
Update the mxnet doc to use kustomize

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1504]
Ref: #930 

This page 
https://www.kubeflow.org/docs/components/training/mxnet/

Is still referring to ksonnet which is no longer used. There is a kutomize manifest here
https://github.com/kubeflow/manifests/tree/master/mxnet-job/mxnet-operator

So it should be pretty straightforward to update the docs to use kustomize instead of ksonnet to deploy.

/cc @Jeffwan

**Comment by sarahmaddox** [comment]
Thanks @EDGsheryl 
/close
