### ISSUE TITLE
Fix Markdown in Python Based Visualizations

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#1505]
Currently, the lists and code blocks in the **Using custom visualizations** and **Known limitations** sections are rendering incorrectly. Need to update the Markdown to ensure that the lists and code blocks render as intended.

**Comment by joeliedtke** [comment]
Affected sections of the page:

https://www.kubeflow.org/docs/pipelines/sdk/python-based-visualizations/#using-custom-visualizations
https://www.kubeflow.org/docs/pipelines/sdk/python-based-visualizations/#known-limitations

**Comment by joeliedtke** [comment]
[PR 1509](https://github.com/kubeflow/website/pull/1509) fixed the code sample formatting portion of this issue. The list formatting still needs work, which could require additional changes to the code sample formatting as well.

**Comment by kbhawkey** [comment]
Hello @joeliedtke ,
Just looked at the pages listed above. Is there still a rendering problem?
The yaml code block is not in the list (separate div), so appears left rendered.
Also, on my laptop, the screencast overflows the area, for example:
![screen_cast_pipeline_viz_2020-01-13 154847](https://user-images.githubusercontent.com/1696019/72291277-0986c480-361d-11ea-9b09-03de2390860e.png)

**Comment by joeliedtke** [comment]
The formatting for the code samples has been improved, however the list formatting is still broken in the sections indicated. Including your feedback about the screencast, here are the known formatting issues in this page:

- List formatting broken in **Using custom visualizations** and **Known limitations**. The code sample type (yaml, golang) may be contributing to the formatting issue along with Markdown formatting.
- The screencast in **Predefined TFX Visualization** overflows outside of the content area.

**Comment by kbhawkey** [comment]
I moved the code blocks in 8 spaces, though, there appears to be a styling issue when the code block attribute == `yaml`. Noted that other pages are not specifying a code block attribute.
