### ISSUE TITLE
Pipelines: would you add yaml spec and its flow?

### ISSUE THREAD

**Issue by sakaia** [kubeflow/website#1530]
it would be helpful to add the doc about yaml spec and its  flow

**Comment by sarahmaddox** [comment]
@sakaia Thanks for raising this issue! I'm guessing that the YAML file you're referring to is the kustomize KfDef config - is that right? If so, then this issue may be a duplicate of the existing issue https://github.com/kubeflow/website/issues/1442

**Comment by sakaia** [comment]
I am looking around kubeflow/pipeline code and recognized that it simply generate yaml file.

https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/compiler.py#L657

I hope any document between kubeflow and pipeline interface.

**Comment by sarahmaddox** [comment]
/cc @joeliedtke 
/cc @Bobgy 

@Bobgy Do you have any pointers about how we could document this?

**Comment by Bobgy** [comment]
Short answer, the spec is an implementation detail that should not be used directly.

Anyway, it is just argo workflow spec with some kubeflow pipeline metadata in annotations.

**Comment by Bobgy** [comment]
Yes, I also think that will help contributors. Thanks for the idea. Can you create an issue in kubeflow/pipelines repo, so we can track it.

**Comment by sakaia** [comment]
I create issue.

https://github.com/kubeflow/pipelines/issues/2857

**Comment by sarahmaddox** [comment]
/assign @Bobgy 
/close

Thank you @sakaia and @Bobgy! I'll close this issue now, since we're tracking the request for developer docs in the pipelines repo with issue https://github.com/kubeflow/pipelines/issues/2857.
