### ISSUE TITLE
Explain the usage of Istio within Kubeflow

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1532]
We need to better describe the use of Istio in Kubeflow. This came up in a discussion of docs to focus on for the February 2020 Kubeflow Doc Sprint.

To determine: 

* What questions should the doc answer?
* Which concepts should the doc explain?

**Comment by sarahmaddox** [comment]
Related issue: https://github.com/kubeflow/manifests/issues/644

**Comment by benjamintanweihao** [comment]
1. Why do we need Istio? Use case with examples would be very helpful.
2. Can we install Kubeflow _without_ Istio?
3. An initial explanation of Istio without too much jargon would be great too.

**Comment by sarahmaddox** [comment]
> 1. Why do we need Istio? Use case with examples would be very helpful.
> 2. Can we install Kubeflow _without_ Istio?
> 3. An initial explanation of Istio without too much jargon would be great too.

Thanks @benjamintanweihao that's very useful. There's a related issue requesting FAQ info on whether we can install Kubeflow without Istio: https://github.com/kubeflow/website/issues/1493. I've commented on that issue saying that if we create a page about Istio, that info should be on the page rather than in an FAQ.

**Comment by sarahmaddox** [comment]
@abhi-g can take this on for the doc sprint

/assign @abhi-g

**Comment by sarahmaddox** [comment]
@abhi-g I've moved this issue to **In progress** in the [doc sprint Kanban board](https://github.com/orgs/kubeflow/projects/21), because the issue is assigned to you. Happy sprinting!

**Comment by abhi-g** [comment]
Thanks Sarah. Looking forward to the doc sprint.
