### ISSUE TITLE
Pipelines: Question about multi-arch CPU or multi-storage-type node support

### ISSUE THREAD

**Issue by sakaia** [kubeflow/website#1534]
Is there any limitation document about multi-arch CPU and other support?

For me specify, If Kubernetes Nodes have multiple configuration (multi-arch or multi-storage-type).
Can we specify the kubeflow component level or the kubeflow pipeline level to the kubernetes nodes?

**Comment by sakaia** [comment]
From seeing the code.
amd64 and aarch64 switch code is apiserver and docker files.

And  kubeflow/pipeline component corresponds to container image (i.e. 1 to 1)
https://www.kubeflow.org/docs/pipelines/sdk/build-component/

Is Kubeflow/pipeline  component corresponds to kubernetes pod?
or kubeflow/pipeline pipeline corresponds to kubernetes pod?
(Since I want to know the each component can specify node implementation)
 
From seeing following, it does not mention container limitation about cpu and storage
https://www.kubeflow.org/docs/pipelines/reference/component-spec/

If operation granuality (Pod) is pipeline then it can use only one type of nodes.
If operation granuality (Pod) is component then it can use multiple type of nodes.

**Comment by sarahmaddox** [comment]
/assign @Ark-kun 
/cc @joeliedtke 

@Ark-kun Can you help with this question?

**Comment by Ark-kun** [comment]
`ContainerOp` objects support `.node_selector` and `.affinity`. I think you can use those for scheduling each task to the correct node.
