### ISSUE TITLE
Deploy using UI

### ISSUE THREAD

**Issue by ivryan** [kubeflow/website#1537]
Hi,
I'm encountering some issue to deploy kubeflow with 0.7.0 and 0.6.2 version using UI on GCP

After one hour this log appears on the console and nothing happens on GCP:

This is what I see on console:

2020-00-1613:25:02.739:Deploymentstatus:operationpending.
2020-00-1613:25:09.320:Deploymentstatus:operationpending.

Could you help me?

**Comment by jtfogarty** [comment]
Are you following these steps https://www.kubeflow.org/docs/gke/deploy/

You need to setup the project correctly, i.e. billing and api 
then you can deploy with the UI

**Comment by ivryan** [comment]
I've resolved using cli deploy method with kfctl_v1.0-rc.1-0 version

**Comment by sarahmaddox** [comment]
Thanks for letting us know, @ivryan. I'll close this issue, as we don't have enough info for a doc update. Please do re-open the issue if there's work to be done on the docs.

/close
