### ISSUE TITLE
kfctl: explain use of set-image-name

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/website#1539]
A new kfctl command was introduced in https://github.com/kubeflow/kfctl/pull/30 to help users do mass image mirrorings.
This is very useful in on-prem, airgapped installations.
We should include a doc explaining its use along with a couple of use-cases.

https://github.com/kubeflow/kubeflow/pull/4222

cc @xaniasd @sarahmaddox 
This is also a good candidate for the doc sprint!

**Comment by sarahmaddox** [comment]
Thanks @yanniszark - added to the doc-sprint list.

**Comment by fediazgon** [comment]
Taking this one. Seems something I can finish before the weekend. Please @sarahmaddox, assign me.

**Comment by sarahmaddox** [comment]
/assign @fediazgon 

thanks @fediazgon!

**Comment by JohnRobinv** [comment]
May I ask where is the guide to use kfctl set-image-name?
