### ISSUE TITLE
AWS: Authentication and TLS Support

### ISSUE THREAD

**Issue by charlesparasa** [kubeflow/website#1541]
https://www.kubeflow.org/docs/aws/authentication/

Aws does not provide with ARN for the custom domain has the auth.us-east-1.amazoncognito.com belongs to AWS and the document does not say how to configure the Custom Domain ARN.

And the cognitoUserPoolDomain : field parameter is confusing. domain/your-pool-name
for eaxmple : kubeflow.example.com/kubeflow (our pool name)

**Comment by Jeffwan** [comment]
`cognitoUserPoolDomain` is the cognito pool name. `Custom Domain ARN` will be addressed in #1435

**Comment by Jeffwan** [comment]
@charlesparasa Can you check if #1661 is clear enough for you?

**Comment by Jeffwan** [comment]
This has been address in #1661 and it's also a duplicate of #1435. I think we can close this one and track in #1435 

/close
