### ISSUE TITLE
Add an "Alpha" banner to the private GKE docs page

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1542]
The docs are here:
https://github.com/kubeflow/website/blob/6f0cc17a639a96444f64cfb097a22d827d679bf7/content/docs/gke/private-clusters.md

We should add a banner to the top of the page indicating private GKE is still in Alpha.

We can add a banner like the one on the upgrade page.
https://github.com/kubeflow/website/blob/master/content/docs/upgrading/upgrade.md

We might also want to add links to the known issues with installing Kubeflow on private GKE.

* kubeflow/kubeflow#3082 - Document use of VPC
* kubeflow/kubeflow#3210 - Replicating docker images to private GCR
* kubeflow/kubeflow#3650 - Installing ISTIO for Kubeflow with private GKE

**Comment by jtfogarty** [comment]
Another apparent blocker
[kubeflow/kfctl#158](https://github.com/kubeflow/kfctl/issues/158)
