### ISSUE TITLE
KFP: document upper limit on size of component i/o

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1548]
We should be precise in documenting what sized strings can be passed between components. (Not sure where that should best go... [here](https://www.kubeflow.org/docs/pipelines/sdk/build-component/#create-a-python-class-for-your-component)?)

[This tutorial](https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) just says that 'Small data size should not exceed few kilobytes.'.  Can we be more exact than that?

More context: There are many situations where you might try to pass 'fairly small' data (not talking about big datasets), and users need to know how small is 'small enough'.  E.g. I tried to pass a serialized pickled object between components and got what is a size-related error, though the error message is not very informative.  (`"This step is in Error state with this message: failed to save outputs: error decoding patch: json: Unmarshal(non-pointer map[string]interface {})"`).

**Comment by Ark-kun** [comment]
The limit is cumulative and hard to quantify exactly.
The JSON-serialized workflow object (including the workflow spec, all templates, all input and output parameter data, all artifact URIs and the status of all nodes) cannot exceed 512KiB in older versions of Kubernetes and 1MiB in newer versions.

I think this would be a rather confusing statement if we put it in that doc.

**Comment by amygdala** [comment]
Maybe we could just say something to give the ballpark idea, like 'the total input and output parameter data, plus other workflow config, can never exceed 1MB (and in older versions is restricted to 512K). If you exceed the limit, you will see an error like `<error description>`".

(Ideally the error message could be a bit better in surfacing what happened, as report of an unmarshalling error is not very intuitive — is it worth filing a separate bug on that?)
