### ISSUE TITLE
existing_arrikto: Add note about storage requirements

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/website#1551]
In the existing_arrikto guide, add a note on the storage requirements (default storage class) and point to the [dynamic provisioning guide](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) the user can follow if they don't have it in their environment.

/cc @cspavlou

**Comment by krishnadurai** [comment]
@yanniszark I've opened an issue kubeflow/website#1592 for making the naming convention of the configuration to kfctl_istio_dex.yaml

**Comment by sarahmaddox** [comment]
@yanniszark The new page is here: [kfctl-istio-dex](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/). Do we still need to add a note about storage requirements?

**Comment by sarahmaddox** [comment]
I'm closing this issue as obsolete, because the existing_arrikto config has now migrated to kfctl_istio_dex. Please do re-open this issue if there's still doc work to be done.
/close
