### ISSUE TITLE
End-to-end Kubeflow on GCP: remove requirement to use old v. of kustomize

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1553]
For this tutorial: https://www.kubeflow.org/docs/gke/gcp-e2e/ , this requirement: "Make sure you have version 2.0.3 of kustomize" seems problematic, especially since people are probably going to have an existing current install that they will need to be careful not to stomp on. (I've installed kustomize via homebrew, which gives me version 3.5.4... which still throws an error on this config).

The requirement to install a second version seemed okay as a stopgap, but it does not seem like the kustomize issue is going to be fixed in a reasonable time frame.  
So I wonder if the kustomize file/config for this example could be modified (maybe by hardwiring more of the config info?) so that the current version is usable instead.

Update: this should probably be a kubeflow/examples bug (too? instead?) but I wanted to capture it before I forgot.

**Comment by jlewi** [comment]
Bump to P0 because we should fix the E2E guide for 1.0.

Perhaps we can just change the example somehow to work around the kustomize bug?

Related issue #1554

**Comment by sarahmaddox** [comment]
@amygdala Are you working on this tutorial and if so, can I assign this issue to you?

**Comment by amygdala** [comment]
Dan S was the original author.  I think I'll check whether he has time to address it.  If not I can tackle it.  I'm not a kustomize expert, but worst case we can change the example to directly edit the yaml or something.

**Comment by amygdala** [comment]
See https://github.com/kubeflow/website/issues/1554 — converting this to a notebook-based example that uses raw yaml will address this issue as well (by rendering it obsolete).

**Comment by jlewi** [comment]
There is a notebook pending in kubeflow/examples#723
It doesn't use Kustomize.
After that is merged we need to update the docs to tell users to use that notebook.

**Comment by jlewi** [comment]
kubeflow/examples#723 has been merged. I need to update the website to point people to use the new example.
