### ISSUE TITLE
End-to-end example needs to be changed to deploy tfjob into user profile namespace

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1554]
https://www.kubeflow.org/docs/gke/gcp-e2e/
(I'll file a kubeflow/examples bug too).

Looks like this example is broken right now; looks like the tfjob needs to be deployed into a user profile namespace now. The quick workaround is to just direct the output of 'kustomize build' to a yaml file rather than piping directly to kubectl; then editing that file to change the namespace, then applying it.  The more principled fix would be to change the set of kustomize commands.

(for googlers, see [this discussion](https://groups.google.com/a/google.com/g/google-kubeflow-support/c/ZQixo8knLiA/m/QI9JijprEQAJ) for background)

**Comment by amygdala** [comment]
Also, I assume that we need to update the tfjob docs as well (https://www.kubeflow.org/docs/components/training/tftraining/).  Looks like either they need to deploy into a `kubeflow-<user>` namespace, or the `default-editor` k8s service account needs to be added to the namespace they want to use. 
(Perhaps this should be a separate bug).

**Comment by amygdala** [comment]
I'd put this as a 'p0' since it's the "getting started" tutorial.

**Comment by jal06** [comment]
When I run the examples for Katib (doc https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/ ), they run in the namespace kubeflow. Looks like they also must also run in a user namespace. Do you agree ? Do we need to open another ticket ? (sorry for asking those questions, I am new to kubeflow)

**Comment by jlewi** [comment]
@jal06 please open a separate issue for katib examples.

**Comment by jlewi** [comment]
Bump to P0 because we should fix for 1.0.

**Comment by sarahmaddox** [comment]
@amygdala Are you working on this tutorial and if so, can I assign this issue to you?

**Comment by jal06** [comment]
> 
> 
> @jal06 please open a separate issue for katib examples.

Thanks for your answer
I open a new issue for Katib : [https://github.com/kubeflow/website/issues/1599](url)

**Comment by sarahmaddox** [comment]
/cc @DanSanche 

@DanSanche I'm cc-ing you on this bug about the end-to-end tutorial (not the afore-mentioned Katib issue). @amygdala is planning to chat to you about it.

**Comment by sarahmaddox** [comment]
Related issue in the kubeflow/samples repo: https://github.com/kubeflow/examples/issues/713

**Comment by jlewi** [comment]
I might suggest that we create a notebook to run this mnist example. Similar to what we do for [xgboost_synthetic](https://github.com/kubeflow/examples/blob/master/xgboost_synthetic/build-train-deploy.ipynb)

The guide would then be

1. Deploy Kubeflow
1. Start a notebook
1. Clone kubeflow/examples
1. Open the notebook
1. Run the notebook

This has a couple advantages

1. It should make it easier to add E2E testing for the example
    * We can just run the notebook like we do for xgboost_synthetic and make sure it runs to completion
1. It should be much easier for users they can just run the notebook
1. We can potentially simplify the example by using RAW YAML rather than introducing kustomize
    * We can write simple python snippets to do any substitution necessary

**Comment by amygdala** [comment]
A notebook SGTM; leaving this issue open.
