### ISSUE TITLE
Automate the updating of the application version matrix (Kubeflow v1.0 onwards)

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1564]
From Kubeflow v1.0 onwards, the docs contain an application version matrix: https://master.kubeflow.org/docs/reference/version-policy/#kubeflow-application-matrix

The table shows, for each application, the application version that is in the manifest at the time when  the current version of Kubeflow (such as Kubeflow v1.0.0) was released.

It would be nice to automate the updating of the version numbers in the table.

**Comment by kbhawkey** [comment]
Hello @sarahmaddox .
Just reviewing this issue and wondering if you have further suggestions or a list of requirements?
Thanks!

**Comment by hefedev** [comment]
This is not my template, I this this is a good start to see what might come handy in the future. 

https://github.com/kaushalmodi/ox-hugo/blob/master/test/site/content/real-examples/multifractals-in-ecology-using-r.md

**Comment by sarahmaddox** [comment]
Hallo @kbhawkey this issue came up in a discussion with @jlewi and @abhi-g and @jbottum . The version numbers of the applications are held in the manifest files in this repo:
https://github.com/kubeflow/manifests

We'd need some script to run (perhaps as part of the Kubeflow release process) that pulls the relevant number out of the relevant file and plugs the number into the page. We'd probably need to use parameters, something like what this PR did:
https://github.com/kubeflow/website/pull/1620

That's about as much info as I have. @jlewi do you have any further suggestions?
