### ISSUE TITLE
Add to GKE troubleshooting Guide - Managed Certificates can fail if service management API not enabled

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1568]
kubeflow/kubeflow#4694 provides an example of the problem.

We should add appropriate troubleshooting information to the docs.

**Comment by jlewi** [comment]
Some information we should include in the guide.

1. Run the following command to check your certificate

    ```
    kubectl -n istio-system describe managedcertificate gke-certificate
    ```

    * The certificate status should be Active or Provisioning(means its not ready yet)
    * More info [here](https://cloud.google.com/load-balancing/docs/ssl-certificates?hl=en_US&_ga=2.164380342.-821786221.1568995229#certificate-resource-status)
    * Make sure the domain is correct
   
1. Get information about the certificate 
     
     ```
     gcloud beta --project=${PROJECT} compute ssl-certificates describe --global ${CERTIFICATE_NAME}
     ```  

     * Certificate name can be obtained from the previous step

1. Run the following command

    ```
    kubectl -n istio-system get ingress envoy-ingress -o yaml
    ```

    * Verify that the value of the annotation `networking.gke.io/managed-certificates` is set the name of the kubernetes managedcertificate resource which should be gke-certificate

    * Verify that a public ip address has been assigned(this will be listed in the status) e.g
      
       ```
      status:
         loadBalancer:
           ingress:
            - ip: 35.186.212.202
       ```
    * Verify that the DNS entry for the domain has propogated; you can do this using nslookup

      ```
      nslookup ${DOMAIN}
      ```
      
      * Domain with be the full qualified domain name which be the host value in the ingress e.g.

        ```
       ${KF_APP_NAME}.endpoints.${PROJECT}.cloud.goog
        ```
  * Managed certificates won't be able to provision the certificate if the DNS lookup doesn't work

**Comment by jlewi** [comment]
Also it looks like a major cause of "PROVISIONING_FAILED" errors could be LetsEncrypt rate limiting. I don't think this is working as intended; I believe lets encrypt rate limiting is supposed to be surfaced as a FAILED_RATE_LIMITED [docs](https://cloud.google.com/load-balancing/docs/ssl-certificates). 

In the interim, we should probably let people know that PROVISIONING_FAILED could be interpreted as rate limiting.

It looks like you can check lets encrypt ceritifcates at

https://crt.sh/?Identity=endpoints.kubeflow-ci-deployment.cloud.goog&iCAID=16418

But I'm not sure exactly how to interpret that to see if you are exceeding rate limits.

**Comment by sarahmaddox** [comment]
Here's the doc to update: https://master.kubeflow.org/docs/gke/troubleshooting-gke/

**Comment by meizabel** [comment]
I'd like to work on this issue. Can someone please assign me to it?

**Comment by sarahmaddox** [comment]
Thanks @meizabel!

/assign @meizabel

**Comment by meizabel** [comment]
@sarahmaddox Could you please move this issue into "PRs in Progress" column on a doc-sprint Kanban board? I appreciate your time and help!

**Comment by sarahmaddox** [comment]
Done. Thanks @meizabel! I see the PR too, and have marked it as in progress for the doc sprint.

**Comment by meizabel** [comment]
@sarahmaddox Thank you! I'll wait for your review.

**Comment by sarahmaddox** [comment]
> Also it looks like a major cause of "PROVISIONING_FAILED" errors could be LetsEncrypt rate limiting. I don't think this is working as intended; I believe lets encrypt rate limiting is supposed to be surfaced as a FAILED_RATE_LIMITED [docs](https://cloud.google.com/load-balancing/docs/ssl-certificates).
> 
> In the interim, we should probably let people know that PROVISIONING_FAILED could be interpreted as rate limiting.
> 
> It looks like you can check lets encrypt ceritifcates at
> 
> https://crt.sh/?Identity=endpoints.kubeflow-ci-deployment.cloud.goog&iCAID=16418
> 
> But I'm not sure exactly how to interpret that to see if you are exceeding rate limits.

@jlewi Are we still using Let's Encrypt certificates in the GCP deployment?

**Comment by sarahmaddox** [comment]
This is now fixed. Thank you @meizabel!
/close
