### ISSUE TITLE
Add deprecation notice about basic auth on GKE

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1571]
We should add a deprecation notice about basic auth support on GKE.

We will likely remove basic auth in a future release after making some simplifications in the use of IAP.

We should add notices:

Before the CLI instructions
https://www.kubeflow.org/docs/gke/deploy/deploy-ui/#authenticating-with-username-and-password

Before the UI instructions
https://www.kubeflow.org/docs/gke/deploy/deploy-ui/#authenticating-with-username-and-password

I think we can use a banner like we do for thinks that are Alpha but change it to Deprecated
https://www.kubeflow.org/docs/upgrading/upgrade/

**Comment by jlewi** [comment]
The diagram is awesome by the way.

**Comment by jlewi** [comment]
I will pick this up as part of the doc sprint.

**Comment by sarahmaddox** [comment]
Thanks @jlewi!

/assign @jlewi

**Comment by jlewi** [comment]
Fixed by #1630
