### ISSUE TITLE
Update ICP and IKS docs layout

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/website#1577]
Follow-on for @sarahmaddox comments - to be addressed in a subsequent PR.

Does this content make the existing guide to IBM Cloud Private redundant?
https://www.kubeflow.org/docs/started/cloud/getting-started-icp/

If yes, then I'd recommend changing the content of the existing guide to just link to your new guide, following the pattern of the other cloud docs like this one:
https://www.kubeflow.org/docs/started/cloud/getting-started-aws/

And also change the link on this page to point to your new section:
https://www.kubeflow.org/docs/started/getting-started/

On the other hand, if the ICP installation is a different thing, then we should put the ICP doc alongside the new IBM docs and mention both setups in the main getting-started page

**Comment by sarahmaddox** [comment]
Hallo @animeshsingh I've given this issue a P1 priority, because there's a good chance people will either be confused by the double set of docs, or miss one of the doc sets entirely.

Is this something you'd like to tackle during the doc sprint? :)

**Comment by animeshsingh** [comment]
I will try and find time this weekend. We will remove ICP from the mix.
