### ISSUE TITLE
Update Docs To Point To 1.0 RC

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1582]
We need to update the kubeflow website docs to put to the 1.0 RC

I.e we want the docs to point to the "v1.0.0" yaml files and the 1.0 RC for kfctl.

See docs:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#updating-version-numbers-etc-for-the-upcoming-release-major-minor-or-patch

**Comment by sarahmaddox** [comment]
We need to fix the versioning of the doc site first. See issue https://github.com/kubeflow/website/issues/1581

**Comment by jlewi** [comment]
@sarahmaddox I think that's fixed?
https://master.kubeflow.org should be pointing to master
https://www.kubeflow.org should be to pointing to the v0.7-branch

So I think we're good to start merging PRs to master updating the docs to use the 1.0 RC.

**Comment by sarahmaddox** [comment]
@jlewi Agreed - issue # 1581 is good, and we can start merging docs to master to use the 1.0 RC. We should be careful, however, when merging docs to master - don't merge a doc that has dependencies on things that are not yet ready to merge, or that contains TODOs. If merging a doc that needs further work, do so only if the doc itself has integrity, and make sure to add a P0 or P1 issue for the remaining work. The docs on master.kubeflow.org are publicly visible, and will become www.kubeflow.org as soon as we flip the switch, whether they're broken or not. I think this is an important message to convey to all contributors.
