### ISSUE TITLE
Remove our version banner customization when included in Docsy

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1588]
When PR https://github.com/google/docsy/pull/189 is merged into Docsy, we should remove our customizations for the version banner (see PR https://github.com/kubeflow/website/pull/1535) and use the theme templates instead.

**Comment by imskr** [comment]
@sarahmaddox Is anyone working on this?

**Comment by sarahmaddox** [comment]
@imskr I'll address this one myself when I next upgrade our version of Docsy. It's a bit of a complex process to upgrade and test the theme. Thanks for your interest though!

**Comment by sarahmaddox** [comment]
@imskr Are you looking for a meaty issue to get your teeth into? Issue # 1735 (**TensorFlow Serving** - specifically not linked from this issue as the two are not related) requires quite a bit of work, delving into samples to see if we have any that successfully use TFServing and then updating the page accordingly. I'd be happy with at least GCP or AWS working well.
