### ISSUE TITLE
Update documentation for kfctl_istio_dex.yaml in website

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/website#1592]
Documentation for yaml config kfctl_istio_dex in the website needs to be updated in order to:

1. Accommodate comments removed from the KfDef config files. (kubeflow/manifests#826)
1. Convert naming to kfctl_istio_dex (kubeflow/manifests#599)

/assign @krishnadurai 
/cc @yanniszark @johnugeorge 
/area docs
/priority p1

Relates to #1582

**Comment by jlewi** [comment]
@yanniszark @krishnadurai is anyone working on this?

**Comment by yanniszark** [comment]
I believe @krishnadurai said he was working on it a couple of days ago.
@krishnadurai does that still hold?
I can take it up if you're too overloaded.

**Comment by krishnadurai** [comment]
@jlewi @yanniszark I apologise for delaying this. I've made a PR #1707 to address this issue. PTAL.

**Comment by sarahmaddox** [comment]
This is done.
/close
