### ISSUE TITLE
Add a community panel to the Kubeflow front page

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1595]
From a recent user survey we learned that people don't easily find the links to Slack, the mailing list, or other community resources.

To make it easier to find this and other community info, we could add a new panel on the Kubeflow front page (https://www.kubeflow.org/), perhaps underneath the list of components. The panel should be similar to the **What is Kubeflow** panel that's already on the page. In the new community panel, describe the community, invite people to take part, and link to the [community page](https://www.kubeflow.org/docs/about/community/).

**Comment by simmscg** [comment]
@sarahmaddox I'll take a swing at this one.

**Comment by sarahmaddox** [comment]
Great, thanks @simmscg!

/assign @simmscg
