### ISSUE TITLE
Add a "Use Cases" page to the Kubeflow docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1596]
From the January user survey, this is the type of information people expect to see in a "Use Cases" section of the docs:

**Why/when to use Kubeflow** - this is the purpose of a doc that describes use cases. The doc helps people decide whether Kubeflow is the right solution for their ML workload.

**Use cases to list** - these are the use cases that Kubeflow enables. For each use case, we should provide a short description of (a) what we mean by this particular use case, and (b) how Kubeflow enables the use case, and a link to a relevant doc within the doc set:
* Deploying and managing a complex ML system at scale
* Experimentation with training an ML model
* Setting up a platform for ML applications
* Tuning the model hyperparameters during training,
* Data versioning
* CI/CD for ML
* End to end hybrid and multi-clouds ML workloads

Note: This issue is a follow-on from issue https://github.com/kubeflow/website/issues/1422, which described how the existing use cases section was much visited, but people were not finding what they needed in that section. We therefore deleted the section. We now want to replace it with a single page, as described above.

Suggested location for the page: A new page in the [About](https://www.kubeflow.org/docs/about/) section.

**Comment by jbottum** [comment]
@sarahmaddox I will start to work on some content for this

**Comment by sarahmaddox** [comment]
Thanks @jbottum - @elviraux is working on this one too. The two of you should chat. I'm looking forward to seeing this page as it's high-value to Kubeflow users, especially people exploring and evaluating Kubeflow.

**Comment by elviraux** [comment]
@jbottum https://docs.google.com/document/d/1emDtEXJ4CKqYq1evjDW4laLTlKml8U1bKfL-Aw6ubok/edit#
