### ISSUE TITLE
clarify webapp section of "Visualize Results in the Pipelines UI"

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1598]
https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/#web-app

In this section, I'm wondering what the "storage" metadata field does, and whether specifying 'storage': 'gcs'' like the example does, requires that the source be a GCS URL.  (and if so, are there other allowed values for 'storage').

It would be helpful to elaborate a bit.

**Comment by jtfogarty** [comment]
priority p2
