### ISSUE TITLE
Idenitfy topics for Blog posts

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#16]
Create a list of topics from 0.1 release (such as features from the release) that we'd want to create blog posts for. Note that we'd be creating separate issues for writing out each of those blog posts, and the determining the release schedule.

**Comment by pdmack** [comment]
Inaugural blog post should be written by the stakeholders IMHO.

**Comment by sarahmaddox** [comment]
I'm closing this issue, as it's a process issue for the blog and for product management, rather than a documentation-related issue.

/close
