### ISSUE TITLE
Add banner to all doc pages which are out of date for 1.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1605]
We should define a common banner that we add to any pages which are not up to date for Kubeflow 1.0.

We can look at the banner that we put on archived versions of the docs for an example.

@sarahmaddox any suggestions about how we should create the banner and what it should say?

**Comment by jlewi** [comment]
Some pages that are out of date:
https://www.kubeflow.org/docs/gke/custom-domain/

**Comment by sarahmaddox** [comment]
I think it'd be good to add a tempate (shortcode) for the banner here:
https://github.com/kubeflow/website/tree/master/layouts/shortcodes

We could call it `needs-update.html`.

Format should be similar to this shortcode:
https://github.com/kubeflow/website/tree/master/layouts/shortcodes

But change `alert-primary` to `alert-warning` in the div styling.

Suggested wording:

```
This page needs updating. The instructions don't work for Kubeflow {{% kf-latest-version %}}.
```

**Note:** I'm reasonably sure the above inclusion of a shortcode within another shortcode will work. Needs testing.

To use the shortcode, include the following at the top of the page:

```
{{% needs-update %}}
```

**Comment by sarahmaddox** [comment]
Closing this issue, as we've created the template and added it to the mentioned page. If we identify other pages that need the banner, we should open a new issue.

/close
