### ISSUE TITLE
Unable to update kustomize/istio-install/kubectl image

### ISSUE THREAD

**Issue by stomplee** [kubeflow/website#1612]
I'm trying to update kubeflow images to point to a private registry due to company security requirements and I've been able to successfully update the image location for all kubeflow images save for one.

The one in question is the docker.io/istio/kubectl image configured in the /kustomize/istio-install/base/kustomization.yaml file.  

ie: 
[ec2-user@ip-10-0-0-170 Kubeflow]$ cat kustomize/istio-install/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-noauth.yaml
namespace: kubeflow
images:
- name: docker.io/istio/kubectl
  newName: docker.io/istio/kubectl
  newTag: 1.1.6

If I make a change to the newName: field and then run kfctl apply I get the following error output:

[error.txt](https://github.com/kubeflow/website/files/4172657/error.txt)

If I do the same process and update the kustomization.yaml files for all other kubeflow images to re-point them to private registry locations and run kfctl apply it all works like a charm.

What needs to be done in order to update the kubectl image to point to an image hosted on a private repo?

**Comment by sarahmaddox** [comment]
@richardsliu @jlewi This issue is probably one for kubeflow/kubeflow rather than for the website.

**Comment by stomplee** [comment]
Apologies, I should have raised it in the correct spot.

**Comment by stomplee** [comment]
This should be moved to kubeflow/kubeflow.  I was able to work around the problem by deleting the newName: and newTag: entries related to kubectl image from the ./kustomize/istio-install/base/kustomization.yaml file and to edit ./kustomize/istio-install/base/istio-noauth.yaml directly to update the image to point to a new location.  Seems to be some bug in the way kustomize tries to update the image+tag value for this component.

**Comment by sarahmaddox** [comment]
Thanks @stomplee I don't have access to move this issue to kubeflow/kubeflow. Please could you take a look to see if any of the following issues cover the problem you're seeing:
https://github.com/kubeflow/kubeflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+private+kfctl+image

If not, please would you raise an issue in https://github.com/kubeflow/kubeflow/issues

I'll close this issue in the website repo, as it doesn't look like something we can fix in the docs.
/close
