### ISSUE TITLE
Fix a few doc style issues in the Seldon guide

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1615]
https://master.kubeflow.org/docs/components/serving/seldon/

The Seldon doc needs a bit of tech writer attention:
* Remove the first heading, as it's a duplication of the page title.
* Change passive to active: ""Full documentation for running Seldon inference is provided within the Seldon documentation site.""
* Change heading to sentence case: ""Kubeflow Specifics"".
* Change the numbered list to a bulleted list and make the list items parallel.
* Change the first occurrence of ""Examples:"" (not the heading) to a full sentence and reflect the fact that it introduces just one example.

**Comment by kbhawkey** [comment]
Hello @sarahmaddox . If this issue is still open, I can start working on the changes.

**Comment by sarahmaddox** [comment]
Great, thanks @kbhawkey 

/assign @kbhawkey

**Comment by sarahmaddox** [comment]
This is done
/close
