### ISSUE TITLE
KFP on GCP: clarify when it's necessary to use the 'use_gcp_secret' annotation

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1616]
With the hosted pipelines beta, users will see the following checkbox.  It gives the all-cloud-platform scope to the cluster VMs (using the default vm service account). If the user does this, they do not need to separately set up and mount a service account secret.

![Screenshot 2020-02-07 12 08 25](https://user-images.githubusercontent.com/115093/74063856-3e7d0180-49a6-11ea-91fd-0ad6d73c52ba.png)

HOWEVER, all of our existing GCP-focused KFP examples, which use `.apply(gcp.use_gcp_secret('user-gcp-sa'))` to give a pipeline step access to SA credentials, will break under those circs (since the secret's not mounted).  The user needs to create a new version of such a pipeline with those annotations removed, to run successfully with hosted pipelines set up as shown.

We need to make sure we document this clearly -- at least in the hosted pipelines docs, and probably at the KF end too.  (It will still break a lot of people though, who don't read the docs closely.)

cc @sarahmaddox @joeliedtke 

for googlers, see also https://b.corp.google.com/issues/149107499

**Comment by joeliedtke** [comment]
Users need to be able to understand when to use use_gcp_secret(), and why. Consider adding a doc for pipeline components that authenticate with external resources. This could give users an overview of the general case, and direct users to cloud specific guides.
