### ISSUE TITLE
Fix list formatting on the GKE CLI deployment page

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1621]
The list numbering is broken here:
https://master.kubeflow.org/docs/gke/deploy/deploy-cli/#alternatively-set-up-your-configuration-for-later-deployment

Strategies that usually work:
* First check the indentation.
* If the indentation is good, try removing the language indicators (such as `bash`) next to the three ticks that start code formatting.

**Comment by Swikar** [comment]
Hello @sarahmaddox I am going to work on fixing this issue. Would you please assign to me? Thanks Swikar

**Comment by sarahmaddox** [comment]
Thanks @Swikar! 

/assign @Swikar
