### ISSUE TITLE
Tech writer revisions needed - Overview of Kubeflow Pipelines

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#1623]
Page: [Overview of Kubeflow Pipelines](https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/)

Here are a few issues that I noticed while reviewing this page:

- [What is Kubeflow Pipelines](https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/#what-is-kubeflow-pipelines): This section describes Kubeflow Pipelines (KFP) as being a part of Kubeflow. I'd recommend revising this to describe that KFP is deployed with Kubeflow, or that it can be installed standalone and linking to:  https://www.kubeflow.org/docs/pipelines/installation/overview/
-  [Architectural overview](https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/#architectural-overview): 
  - Broken Markdown link **Orchestration controllers**.
  - PV abbrev, is defined and not used in **Artifact storage**

**Comment by kbhawkey** [comment]
Hello @joeliedtke ,
If this issue is open, would you assign me. I may need to ask for some more details.
Thanks!

**Comment by sarahmaddox** [comment]
@kbhawkey and @joeliedtke Can we close this issue or is there still work to do?

**Comment by kbhawkey** [comment]
👀

**Comment by kbhawkey** [comment]
Hi! I _think_ most or all of the points noted by @joeliedtke are completed?
