### ISSUE TITLE
GCP Hosted ML Pipelines Mailing List - Address Not Found

### ISSUE THREAD

**Issue by ofaz** [kubeflow/website#1627]
The link to apply for Alpha access to GCP Hosted ML pipelines at https://www.kubeflow.org/docs/pipelines/installation/overview/#gcp-hosted-ml-pipelines returns:

`550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser w11si699990wmk.0 - gsmtp`

This is prevent users from apply for alpha access and occurrences of this have been reported to the kubeflow-discuss mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubeflow-discuss/etUgxdXvF_A/TJ_hcbqxAgAJ

**Comment by ofaz** [comment]
@sarahmaddox @joeliedtke - as per Sarahs Slack message I have opened this ticket. It would seem that I'm unable to assign the ticket to Joe directly however. (https://kubeflow.slack.com/archives/CA4M298LD/p1581285707007400)

**Comment by sarahmaddox** [comment]
I see that this PR addresses the issue of the mailing list: https://github.com/kubeflow/website/pull/1628

**Comment by alan-krumholz** [comment]
This also affects us. We also want to request access to this Alpha release :)

**Comment by joeliedtke** [comment]
Thank you for raising this issue, this has been corrected in [kubeflow/website pull #1628](https://github.com/kubeflow/website/pull/1628). Changes to the Kubeflow website are currently being published to master.kubeflow.org, here is the updated [Installation options](https://master.kubeflow.org/docs/pipelines/installation/overview/) page. The correct email address to request access to the alpha is [kfp-mkp-alpha-feedback@google.com](mailto:kfp-mkp-alpha-feedback@google.com).
