### ISSUE TITLE
Website Generation Instructions for Pipeline API

### ISSUE THREAD

**Issue by OfficePop** [kubeflow/website#1643]
Flagging this issue as something I plan to work on during the Kubeflow Spring 2020 Doc Sprint. 

The goal will be to create a set of instructions users can follow in order to generate the [Pipelines API Reference](https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/) when there is a need for updates.

SMEs for the process include @IronPan.

@sarahmaddox could you apply the labels to this when you have a chance?

**Comment by sarahmaddox** [comment]
Thanks @OfficePop 

/assign @OfficePop
