### ISSUE TITLE
document how to define metadata file outputs from the KFP SDK

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1653]
See https://github.com/kubeflow/pipelines/issues/2995 . I can take this on, once I learn how to do it :)

**Comment by amygdala** [comment]
/kind bug
...as it doesn't work without explicit declaration of output(s)

**Comment by sarahmaddox** [comment]
/assign @amygdala 

Thanks @amygdala

**Comment by amygdala** [comment]
let's keep open

**Comment by Bobgy** [comment]
Duplicate of https://github.com/kubeflow/website/issues/2021
