### ISSUE TITLE
Minikube: Error in "kubectl apply -V -f ${CONFIG_FILE}"

### ISSUE THREAD

**Issue by daniel-bejarano** [kubeflow/website#1660]
Hi there!

I've been following the steps outlined in Kubeflow's docs to run kubeflow locally. After installing kubectl and minikube, and running a minikube cluster (4 cpus, 8096 of memory, and 40G of size) I get an error when installing kubeflow on my cluster. I did as outlined [here](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/) and [here](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)

I'm able to download the kfctl yaml file (I tried version 0.7.1, 0.7.2, v1.0-rc.1 and v1.0-rc.3-1). I have tried from both kubernetes-cli versions 1.17.2 and 1.15.2. I'm using minikube version 1.17.2. I also wanted to try an earlier version of minikube, but haven't found a way to access those.

With "kfctl apply -V -f ${CONFIG_FILE}" I get it to start deploying, but it then keeps returning the error below:

Error error when creating "/tmp/kout585525314": CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.properties[children].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[endpoint].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[configMapKeyRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[fieldRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[resourceFieldRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[secretKeyRef].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[resources].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[spec].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root]

ANY help would be greatly appreciated. Thank you!

**What did you expect to happen:**
To deploy Kubeflow on minikube

**Environment:**
- OS: macOS Mojave 10.14.6
- kubernetes-cli: sha 3b5ade0b8dbc8344a6b9c28517d84057410595b2 & b426e0a3bf5842bc4f944bb64c3c6634f212d763
- minikube: 1.17.2
- kfctl: 0.7.1, 0.7.2, v1.0-rc.1 and v1.0-rc.3-1

**Comment by sarahmaddox** [comment]
Thanks so much for reporting this issue @daniel-bejarano! We've held some discussions and decided we should remove the Minikube guide, as it's no longer feasible to deploy Kubeflow on Minikube in the way originally envisaged.

I've created issue https://github.com/kubeflow/website/issues/1662 requesting that we remove the page, so that we're no longer misleading people.

**Comment by sarahmaddox** [comment]
I'll close this issue as answered. Thanks again for trying the deployment. You may like to use one of the following solutions instead:
* https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/
* https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikf/

/close
