### ISSUE TITLE
AWS: third party user pool federation

### ISSUE THREAD

**Issue by theofpa** [kubeflow/website#1665]
Later on, we can add more docs to talk about third party user pool federation. This is good enough now.

_Originally posted by @Jeffwan in https://github.com/kubeflow/website/pull/1661_

**Comment by Jeffwan** [comment]
We will submit a PR to resolve this one and #1672. They belong to same improvement.

**Comment by PatrickXYS** [comment]
Will help on this issue from now.

**Comment by Jeffwan** [comment]
As this PR https://github.com/kubeflow/website/pull/1780is merged, we can close this issue

/close
