### ISSUE TITLE
[AWS] Add instruction to use external mysql database for metadata and pipeline

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#1669]
Currently, we use PersistVolume based mysql database for these projects and upgrade becomes a challenges. One solution is to use external mysql database to host data. 

We already have a change https://github.com/kubeflow/manifests/pull/906 here.

**Comment by wdhorton** [comment]
I'm going to work on this issue

**Comment by sarahmaddox** [comment]
Thanks @wdhorton!

/assign @wdhorton

**Comment by sarahmaddox** [comment]
@wdhorton Did you make any progress on this doc update?

**Comment by wdhorton** [comment]
@sarahmaddox Sorry for the delay, I'm currently working on it and expect to have some docs written in the next couple of days
