### ISSUE TITLE
[AWS] Add instruction to use S3 directly to host pipeline data

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#1670]
Changes need to be done on the argo workflow controller configmap side, pipeline apiServer and frontend side. 

I am preparing an overlay which can simplify setups.

**Comment by eterna2** [comment]
I have some overlays on my repo too. Abit outdated thou.

Just to add. U might want to add in the configmap so that tensorboard viewer can access the tf logs from s3.

https://github.com/e2fyi/kubeflow-aws
