### ISSUE TITLE
Link to algorithms that can be used

### ISSUE THREAD

**Issue by TristansCloud** [kubeflow/website#1685]

**Comment by sarahmaddox** [comment]
Hallo @TristansCloud Thanks for raising this issue. Please could you add more detail about the request. For example, does the request apply to a specific page in the docs, or perhaps the information is missing entirely? 

If I understand the request correctly, you're looking for examples of various ML algorithms running on Kubeflow - is that right?

We've just created the use cases page - does this page help clarify the way you can use Kubeflow?
https://www.kubeflow.org/docs/about/use-cases/

**Comment by sarahmaddox** [comment]
Closing this issue, as there's currently not enough information to act upon it. Please do re-open the issue if you have more details.
/close
