### ISSUE TITLE
Update remaining examples on Katib page to use namespace as in the first example

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1686]
Page: https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/

In PR https://github.com/kubeflow/website/pull/1633, we updated the [first example](https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/#example-using-random-algorithm) to show how to specify a namespace before applying the YAML file. We should follow the same pattern for the other 2 examples on the page: [TensorFlow example](https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/#tensorflow-example) and [PyTorch example](https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/#pytorch-example).

On the same page, we should also update the describe experiment commands, as suggested by @jal06 in a comment on PR # 1633:

>in the kubectl describe experiment commands, please could you replace the namespace `kubeflow` by the user profile namespace ?
The command `kubectl -n kubeflow describe experiment random-example` returns: 
`Error from server (NotFound): experiments.kubeflow.org "random-example" not found`

>Instead of `kubectl -n kubeflow describe experiment random-example` , I think that `kubectl -n <your user profile namespace> describe experiment random-example` should be better.

>This replacement must be done for the 3 examples 
- random-example
- tfjob-example
- pytorchjob-example

**Comment by Klaven** [comment]
may I please do this? new here, just looking for some ways to contribute, will go ahead and start working working on this later this week... unless I hear otherwise! :)

**Comment by sarahmaddox** [comment]
Yes please!
/assign @Klaven

**Comment by sarahmaddox** [comment]
@Klaven How are you progressing with this issue? If you don't have bandwidth to do it, I'll assign it to @meizabel since she's able to start work on it.

**Comment by Klaven** [comment]
I am so sorry. :bow: I am going to get this done today. My life kind of got really crazy and honestly I forgot about it. Again, very sorry. Working on it right now. :bow:

**Comment by Klaven** [comment]
hopefully @meizabel has not started working on it. if you have. I apologize even more. I'm a terrible person. again sorry @sarahmaddox.

**Comment by Klaven** [comment]
I posted the above PR. :bow: again I apologize this took me so long! Will pick up another one later this week!

**Comment by sarahmaddox** [comment]
Fixed by https://github.com/kubeflow/website/pull/1813
Thanks @Klaven 
/close
