### ISSUE TITLE
Two Custom KFP component links 404

### ISSUE THREAD

**Issue by benmathes** [kubeflow/website#1687]
On https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/

The link to the TFMA component 404s
The link to the dataflow predict component also 404s

Note both are in `.../components/dataflow/...`

![image](https://user-images.githubusercontent.com/545846/74453555-69000c00-4e37-11ea-8e7c-b5c53c28482e.png)

**Comment by janeman98** [comment]
It seems the files are deleted in [issue #2203](https://github.com/kubeflow/pipelines/issues/2203) / [PR #2161](https://github.com/kubeflow/pipelines/pull/2161)

/cc @gaoning777

**Comment by janeman98** [comment]
Hi @gaoning777 , @sarahmaddox ,

Should we restore these 2 files? If not, maybe,  delete these 2 links in the [website](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/)?

**Comment by janeman98** [comment]
Hi @gaoning777 , @sarahmaddox 

Any update on this? I can restore these 2 files or just delete these 2 links in the website.  Please let me know which way is better.

**Comment by sarahmaddox** [comment]
/assign @joeliedtke 

@joeliedtke Would you be able to answer @janeman98's question?

**Comment by joeliedtke** [comment]
These two components are deprecated. I'll dig into this to see if the pipeline was revised using different components, or if the example needs to be revised.

TFMA - https://github.com/kubeflow/pipelines/tree/dc5aab6687c7dee37834b3f4be1ca6851a59337a/components/deprecated/dataflow/tfma/src

Dataflow predict - 
https://github.com/kubeflow/pipelines/tree/dc5aab6687c7dee37834b3f4be1ca6851a59337a/components/deprecated/dataflow/predict/src
