### ISSUE TITLE
The Kubeflow website currently hangs when you open a new page

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1691]
The Kubeflow website currently hangs when you open a new page. If you hit refresh, the page then loads.

The problem doesn't seem to occur in Firefox, but it does occur in Chrome.

DevTools shows this error in the console, which may be related:
`DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map`

To investigate:

We've recently added a Python script in a `scripts` directory:
https://github.com/kubeflow/website/blob/master/scripts/validate-urls.py

PR:
https://github.com/kubeflow/website/pull/1684

I can't find any info on whether Hugo does something specific with s `scripts` folder.

One thing to try is reverting the PR and seeing if that fixes the problem.

**Comment by sarahmaddox** [comment]
/cc @jlewi 

/assign @zhenghuiwang 

@zhenghuiwang Could you investigate?

**Comment by sarahmaddox** [comment]
However, the problem is most likely to be Netlify, even tho the [Netlify status page](https://www.netlifystatus.com/) currently doesn't show any issues. I'm pretty sure I've successfully loaded doc pages since the above-mentioned PR was submitted.

**Comment by zhenghuiwang** [comment]
The website is working fine for me right now. Is it still happing?

**Comment by sarahmaddox** [comment]
Thanks @zhenghuiwang it's working fine now. I'll close this issue.
/close
