### ISSUE TITLE
Getting started multipass feedback

### ISSUE THREAD

**Issue by andaag** [kubeflow/website#1694]
The guide for setting up virtual environment has improved drastically since the last time I tried. My first experience was mostly me trying to debug istio instead of me trying to test the product.

This time it almost worked instantly. (Following https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/ on ubuntu 18.04)

The only things that did not work where listed in the microk8s common issues list. I'd like to see a mention in the documentation page that there are solutions for common issues on microk8s webpage, and maybe also mentioning the microk8s.inspect tool, as that was quite useful to point me at the right problems.

Thanks, things have drastically improved for getting a demo up and running! 👍.

**Comment by sarahmaddox** [comment]
Thanks for the feedback @andaag this is great to hear.

@ammarn911 Congratulations and thank you! Your update has significantly improved the UX for getting started with Kubeflow using MicroK8s on Linux.

+1 to the suggestion to add info about the MicroK8s common issues and inspection tool.

This MicroK8s doc includes some common issues and info about the inspection tool:
https://microk8s.io/docs/troubleshooting

Recommendation: Add a link in the **Next steps** section on this page, pointing to to the MicroK8s doc:
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/

**Comment by Klaven** [comment]
@sarahmaddox I dont mind doing this one! I'll even try and get it done faster then the last one! :) Missed the community meeting this morning, but plan to be there next week!

**Comment by sarahmaddox** [comment]
Thanks @Klaven 
/assign @Klaven

**Comment by sarahmaddox** [comment]
This is now done.
/close
