### ISSUE TITLE
[GCP] Update docs for private clusters and VPC service controls for 1.0

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1705]
The docs on using VPC Service controls to secure Kubeflow on GCP need to be updated.
https://www.kubeflow.org/docs/gke/private-clusters/#enable-vpc-service-controls-in-your-project

Related issues:

kubeflow/kubeflow#3210 - Replicating images to private GKE
kubeflow/kubeflow#3650 - ISTIO on private GKE

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/1769

**Comment by sarahmaddox** [comment]
/assign @zhenghuiwang 

@zhenghuiwang I'm assigning this to you, as I understand you're working on a solution for the config of private clusters. Let me know when you're ready to work with me on the updating of the website docs. We'll take a look and decide whether we need more than one doc, based on your findings.

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/1811

**Comment by sarahmaddox** [comment]
This PR proposes an update to the private clusters page too: https://github.com/kubeflow/website/pull/1563
There hasn't been any activity on the PR for a while. It may be worth checking in with the author.

**Comment by jbottum** [comment]
@zhenghuiwang Hi Zhenghui - We have two users (US Bank and Raymond James) who are tracking this development.   Will this be available in Kubeflow 1.1?  Should we set-up a meeting to discuss the status with the potential users?

**Comment by jlewi** [comment]
@zhenghuiwang isnt working on this.

We are trying to get docs for using VPC-SC with blueprints ready for 1.1. I give it about 50% confidence that it will land for 1.1

**Comment by jlewi** [comment]
Related issue: kubeflow/pipelines#3347

**Comment by jlewi** [comment]
Updated docs are here:
https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/deploy_private.md

We either need to copy this over to the website or update the website to point at those docs.

**Comment by 8bitmp3** [comment]
@jlewi I can assist with updating the site (Hugo). Copying it over makes sense, so there's less clicks/friction in terms of user experience. cc @sarahmaddox

**Comment by 8bitmp3** [comment]
@Bobgy 

Guide: "How to secure Kubeflow clusters using VPC service controls and private GKE"

- So, this is outdated: https://github.com/kubeflow/website/blob/master/content/en/docs/gke/private-clusters.md (site: https://www.kubeflow.org/docs/gke/private-clusters/)

- And this is @jlewi 's new doc: https://github.com/kubeflow/website/blob/master/content/en/docs/gke/private-clusters.md

If you have time, can you help me figure our what needs to go and what can stay? Cheers!!

**Comment by 8bitmp3** [comment]
Thanks @jlewi https://github.com/kubeflow/website/pull/2190
