### ISSUE TITLE
Deploy using CLI - specify APIs to be enabled before deploying

### ISSUE THREAD

**Issue by Svendegroote91** [kubeflow/website#1709]
It would be great if it would be specified which APIs you need to enable (Compute Engine, Deployment manager, IAM, Kubernetes Engine API) before you can actually run the kubeflow deployment script.

https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

**Comment by sarahmaddox** [comment]
Thanks for raising this issue @Svendegroote91. We do have an item in the "Before you start" section of the CLI guide, saying that the GCP project must meet the minimum requirements described in the [project setup guide](https://www.kubeflow.org/docs/gke/deploy/project-setup/). The setup guide lists the required APIs. It's tricky to repeat all the info in the CLI guide, as it would make the guide really long.

I'm going to close this issue as answered, but please do re-open it if you think we should do more work on it.

/close
