### ISSUE TITLE
Export the NAMESPACE variable before using it

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#171]
On the JupyterHub page, we start by telling folks to run this command:
kubectl get svc -n=${NAMESPACE}

But we haven't set the variable. By default, the deployment uses namespace "kubeflow", so we should set the variable to "kubeflow" before using it.

https://www.kubeflow.org/docs/guides/components/jupyter/

This issue was probably caused when we split the user guide into separate pages, and this page therefore assumes the variable has been set. We should check other pages for similar assumptions.

**Comment by Akado2009** [comment]
Greetigns!

Can I work on it?
