### ISSUE TITLE
microk8s.enable kubeflow does not print access ports

### ISSUE THREAD

**Issue by darkopevec** [kubeflow/website#1718]
This is the output I get when successfully running microk8s.enable kubeflow:
‘‘‘
Congratulations, Kubeflow is now available.
The dashboard is available at https://localhost/

    Username: admin
    Password: E9V2T81JOT6KTX02KXG27SOS3WT8AA

To see these values again, run:

    microk8s.juju config kubeflow-gatekeeper username
    microk8s.juju config kubeflow-gatekeeper password
‘‘‘
But I have no idea how to access the dasboard, notebooks or how to get the Ambassador PORT

**Comment by natalytvinova** [comment]
Hitting the same issue

**Comment by sarahmaddox** [comment]
@carmine Please would you take a look at this issue?
