### ISSUE TITLE
Error with kfctl build -V -f ${CONFIG_URI} using kfctl_aws.v1.0.0.yaml

### ISSUE THREAD

**Issue by AndrewMcFarren** [kubeflow/website#1734]
Error:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file:  (kubeflow.error): Code 400 with message: invalid config: version not supported; supported versions: v1alpha1, v1beta1, got v1

_**Did the following:**_

wget https://github.com/kubeflow/kfctl/releases/download/v1.0-rc.4/kfctl_v1.0-rc.3-1-g24b60e8_linux.tar.gz

tar -xvf kfctl_v1.0-rc.3-1-g24b60e8_linux.tar.gz

export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml"

export AWS_CLUSTER_NAME=kubeflow-demo
export KF_NAME=${AWS_CLUSTER_NAME}

export BASE_DIR=/home/ubuntu
export KF_DIR=${BASE_DIR}/${KF_NAME}

Error:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file:  (kubeflow.error): Code 400 with message: invalid config: version not supported; supported versions: v1alpha1, v1beta1, got v1

**Comment by sarahmaddox** [comment]
@Jeffwan This may have something to do with the recent doc updates. Could you have a look?

/assign @Jeffwan

**Comment by Jeffwan** [comment]
If user use 1.0-rc kfctl, converters  map should have `v1` supported. Based on the logs, it's very possible user still use old kfctl version. 

https://github.com/kubeflow/kfctl/blob/94c35cfa53235961a329cefd144ecf524fe5cea4/pkg/kfconfig/loaders/loaders.go#L141-L158

Please check `kfctl version` and `which kfctl`, try to see if you latest one is under your path and being used.

**Comment by AndrewMcFarren** [comment]
Thank you for the support!  I had kftctl still in /usr/local/bin that I needed to remove.
