### ISSUE TITLE
TensorFlow Serving

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/website#1735]
https://www.kubeflow.org/docs/components/serving/tfserving_new/

I've come accross the following problems on this page:

- This example uses the configmaps "mnist-v1-config" and "s3-config" in the example YAML scripts. However, the resource definitions for the config maps are not included and no explanation is provided for what they should look like.

- the S3 example has the following annotation "sidecar.istio.io/inject: null" which nich not accepted when calling `kubectl apply`.

- In the S3 example there is a mismatch in the app names: "s3" and "mnist".
- This I am not able to fully verify, but as far as I can see `http://EXTERNAL_IP:8500/v1/models/mnist:predict` only works if you've installed Kubeflow with no authorisation via Istio. As far as I can tell the TF models fail to serve if using authentication

**Comment by imskr** [comment]
@sarahmaddox I can get my hands dirty on this!

**Comment by sarahmaddox** [comment]
Excellent, thanks @imskr!
/assign @imskr

**Comment by jal06** [comment]
I still have this issue with Kubeflow 1.1 deployed on GCP using GCP blueprints (and IAP)
@karlschriek : did you find how to run this example ? Did you find the description of the configmap ?

**Comment by akhimji** [comment]
+1 with regards
 
`This example uses the configmaps "mnist-v1-config" and "s3-config" in the example YAML scripts. However, the resource definitions for the config maps are not included and no explanation is provided for what they should look like.`

Not defined in example
`      - configMap:
          name: mnist-v1-config
`
