### ISSUE TITLE
AWS install kubeflow page format issue

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#1736]
My code changes bring a format issue here. I notice they behave differently in upstream and my local dev env. Not sure if that's the problem of we use different hugo version. I need to fix this problem first. 

https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
![image](https://user-images.githubusercontent.com/4739316/75174557-a0976f80-56e5-11ea-921c-0c404e757082.png)

http://localhost:1313/docs/aws/deploy/install-kubeflow/
![image](https://user-images.githubusercontent.com/4739316/75174616-c45ab580-56e5-11ea-804b-974151c09e7d.png)

**Comment by sarahmaddox** [comment]
This is done
/close
