### ISSUE TITLE
Investigate Kubeflow on Minikube and document the installation if feasible

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1751]
In issue https://github.com/kubeflow/website/issues/1662, we removed the guide for running Kubeflow on Minikube. The reasons were that the way we'd documented the deployment of Kubeflow on Minikube was no longer feasible, and we'd had no success in creating a new guide.

The original guide to Minikube still exists in the [Kubeflow v0.7 docs](https://v0-7.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/), but was not working even at that time. 

This new issue tracks work to investigate ways of deploying Kubeflow on Minikube and testing the deployment by means of a hello world ML task.

Furthermore, we'd like an indication of how we can ensure that the doc is kept up to date going forward, by continuous or consistent testing against the latest Kubeflow release.

**Comment by sarahmaddox** [comment]
/assign @janeman98 

@janeman98 I'm assigning this to you with thanks :) as you've already started this work in PR https://github.com/kubeflow/website/pull/1743

**Comment by janeman98** [comment]
@sarahmaddox 

PR #1743 include the instruction for installation of minikube, Kubeflow 1.0, compilation of  a pipeline sample (sequential.py), upload of  compiled pipeline application,  and **execution of such application in the Kubeflow central dashboard**. Will that be good enough to test the deployment is good?

**Comment by sarahmaddox** [comment]
@abhi-g Please would you give your take on this question?

> PR #1743 include the instruction for installation of minikube, Kubeflow 1.0, compilation of a pipeline sample (sequential.py), upload of compiled pipeline application, and **execution of such application in the Kubeflow central dashboard**. Will that be good enough to test the deployment is good?

**Comment by abhi-g** [comment]
@janeman98 In general, compilation of a pipeline sample, upload and execution should be a good test for the deployment. Unfortunately sequential.py Pipeline is not a good pipeline to test KF functionality because it doesn't invoke any of the ml operations. It simply downloads a file from GCS and prints it to the logs. 

I think when I mentioned mnist example, I meant this notebook: https://github.com/kubeflow/examples/blob/master/mnist/mnist_vanilla_k8s.ipynb which you can try running onto your minikube kubeflow.

**Comment by janeman98** [comment]
@abhi-g 

Thanks for the notebook url. When I run the notebook, I am hitting problems here and there and I will document the solutions/workaround on the side.  I do have a question: I am hitting following problem while running this notebook, 
`FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/namespace'`

Which pod is I should look into? 
`notebook-controller-deployment-7db57b9ccf-vw9vw`
`jupyter-web-app-deployment-89789fd5-cjkwf`
or other??

**Comment by janeman98** [comment]
See PR #1743.

**Comment by sarahmaddox** [comment]
We can close this one now!

**Comment by janeman98** [comment]
Thanks @sarahmaddox and @abhi-g !
