### ISSUE TITLE
Investigate changed scrolling behavior on Kubeflow website pages

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1754]
The scrolling behavior has recently changed on the Kubeflow website pages: Instead of moving directly to a linked heading or when the user does Ctrl-F/Cmd-F to find text, the website now scrolls noisily down to the relevant section.

A possible cause is this new line in the project CSS variables:
https://github.com/kubeflow/website/blob/master/assets/scss/_variables_project.scss#L8

The following PR added that section to the file as part of a fix for the accessibility of the home page:
https://github.com/kubeflow/website/pull/1676

We should confirm whether that change is needed for the accessibility fixes. If not, we should remove it. If yes, then maybe there's some way we can restrict the scrolling behavior to the landing page, perhaps by creating a style specifically for the landing page.

**Comment by sarahmaddox** [comment]
@simmscg Do you have any info that may help diagnose/fix this issue?

**Comment by simmscg** [comment]
The change isn't required for accessibility. The line was removed as internal CSS from `_index.html` and moved to scss as part of #1676 to keep things clean. I hadn't realised the effect was intended to be limited to the home page, so it's currently operating globally.

Looking into a fix now.

**Comment by simmscg** [comment]
PR: https://github.com/kubeflow/website/pull/1755

**Comment by sarahmaddox** [comment]
This is fixed.
/close
