### ISSUE TITLE
Openshift 3.11

### ISSUE THREAD

**Issue by magick93** [kubeflow/website#1756]
Please describe how to install on Openshift 3.11 as this is still widely used.

**Comment by sarahmaddox** [comment]
@vpavlin Please would you comment on this request?
/assign @vpavlin

**Comment by sarahmaddox** [comment]
@vpavlin Please would you give your opinion on this request?

**Comment by vpavlin** [comment]
Hi, I have just noticed this when the stale bot pinged - we do not plan to provide any guidance on how to install KF on OPenShift 3.11 - the version Kubernetes running there is quite old and all our resources are focused on OpenShift 4.
