### ISSUE TITLE
Securing Your Clusters = missing cert-manager.yaml file

### ISSUE THREAD

**Issue by anifort** [kubeflow/website#1769]
https://www.kubeflow.org/docs/gke/private-clusters/

It seems that this documentation is not compatible with KFv1. Following the instructions step 7 under Deploy Kubeflow with Private GKE

Remove components which are not useful in private clusters:
cd ${KF_DIR}/kustomize
kubectl delete -f cert-manager.yaml

There is not such a file -> cert-manager.yaml

**Comment by sarahmaddox** [comment]
/assign @zhenghuiwang 

Assigning this to @zhenghuiwang as he's working on an update to the docs for private GKE clusters.
