### ISSUE TITLE
Kubeflow Deployment with kfctl_k8s_istio

### ISSUE THREAD

**Issue by gtarcoder** [kubeflow/website#1775]
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

Failed to install kubeflow on an existing k8s cluster.  After I installed kubeflow following these docs https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ , https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/ . I can not access to centralboard. 
Executing `kubectl get pods -n kubeflow` ,  gets following results:
NAME                                                           READY   STATUS             RESTARTS   AGE
`centraldashboard-869f55ddbd-mwkg4         0/1     CrashLoopBackOff   2          31s`

Executing `kubectl logs -n kubeflow centraldashboard-869f55ddbd-mwkg4 ` gets following results:
`
> kubeflow-centraldashboard@0.0.2 start /app
> npm run serve

> kubeflow-centraldashboard@0.0.2 serve /app
> node dist/server.js
`

**Comment by krishnadurai** [comment]
Hello @gtarcoder, can we get the output of
```

**Comment by gtarcoder** [comment]
@krishnadurai here is the output
Name:               centraldashboard-869f55ddbd-mwkg4
Namespace:          kubeflow
Priority:           0
PriorityClassName:  <none>
Node:               45.255.133.241/45.255.133.241
Start Time:         Thu, 05 Mar 2020 17:30:03 +0800
Labels:             app=centraldashboard
                    app.kubernetes.io/component=centraldashboard
                    app.kubernetes.io/instance=centraldashboard-v1.0.0
                    app.kubernetes.io/managed-by=kfctl
                    app.kubernetes.io/name=centraldashboard
                    app.kubernetes.io/part-of=kubeflow
                    app.kubernetes.io/version=v1.0.0
                    kustomize.component=centraldashboard
                    pod-template-hash=869f55ddbd
Annotations:        <none>
Status:             Running
IP:                 192.168.106.95
Controlled By:      ReplicaSet/centraldashboard-869f55ddbd
Containers:
  centraldashboard:
    Container ID:   docker://d0dba45e8e519c578058a2fdfc3cef46846b6387e105cb748a1a9efd40db0749
    Image:          gcr.io/kubeflow-images-public/centraldashboard:v1.0.0-g3ec0de71
    Image ID:       docker-pullable://gcr.io/kubeflow-images-public/centraldashboard@sha256:82b7ffe3b65715acf2c24980909e4e97dbcef963652f76ca7efea42ea7a07191
    Port:           8082/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 05 Mar 2020 17:56:13 +0800
      Finished:     Thu, 05 Mar 2020 17:56:14 +0800
    Ready:          False
    Restart Count:  10
    Liveness:       http-get http://:8082/healthz delay=30s timeout=1s period=30s #success=1 #failure=3
    Environment:
      USERID_HEADER:               kubeflow-userid
      USERID_PREFIX:               
      PROFILES_KFAM_SERVICE_HOST:  profiles-kfam.kubeflow
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from centraldashboard-token-4qfbz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  centraldashboard-token-4qfbz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  centraldashboard-token-4qfbz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                     Message
  ----     ------     ----                   ----                     -------
  Normal   Scheduled  28m                    default-scheduler        Successfully assigned kubeflow/centraldashboard-869f55ddbd-mwkg4 to 45.255.133.241
  Normal   Pulled     27m (x5 over 28m)      kubelet, 45.255.133.241  Container image "gcr.io/kubeflow-images-public/centraldashboard:v1.0.0-g3ec0de71" already present on machine
  Normal   Created    27m (x5 over 28m)      kubelet, 45.255.133.241  Created container centraldashboard
  Normal   Started    27m (x5 over 28m)      kubelet, 45.255.133.241  Started container centraldashboard
  Warning  BackOff    3m40s (x120 over 28m)  kubelet, 45.255.133.241  Back-off restarting failed container

**Comment by krishnadurai** [comment]
@gtarcoder is the central-dashboard the only pod failing or is it the same with most or all pods in Kubeflow namespace.
Could you please provide more information on your setup?

Kubernetes version:
Platform: (Microk8s with Linux/ GKE etc)
Cluster description:

Could you see if there are other pods failing and if they are failing, can you post their logs?

**Comment by gtarcoder** [comment]
only the central-dashboard pod fail. Here is the snapshot.
![image](https://user-images.githubusercontent.com/11898942/75975343-4b443500-5f13-11ea-8fab-24cc826b9bd7.png)

my setup configurations:
Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0
kfctl version: (use kfctl version): v1.0-0-g94c35cf
Kubernetes platform: (e.g. minikube) rancher
Kubernetes version: (use kubectl version): v1.14.3, git commit 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
OS (e.g. from /etc/os-release): ubunt16.04

**Comment by sarahmaddox** [comment]
@krishnadurai and @gtarcoder do you have any updates on this issue?

**Comment by gtarcoder** [comment]
https://github.com/kubeflow/kubeflow/issues/4832

**Comment by gtarcoder** [comment]
kubeflow/kubeflow#4832 here is the same issue, I close this issue now since it can be resolved, thanks.

**Comment by gtarcoder** [comment]
kubeflow/kubeflow#4832 here is the same issue, I close this issue now since it can be resolved, thanks.
