### ISSUE TITLE
getting-started-gke - TPUs

### ISSUE THREAD

**Issue by erkolson** [kubeflow/website#178]
The introduction states: "GPUs and TPUs can be used to accelerate your work".  It is pretty clear how to utilize GPUs but it is never described how to utilize TPUs.

**Comment by sarahmaddox** [comment]
We now have a guide to TPUs here:
https://www.kubeflow.org/docs/gke/customizing-gke/#add-cloud-tpus-to-your-cluster

/close

**Comment by erkolson** [comment]
Thanks!
