### ISSUE TITLE
Do we no need to prepare a storage class for the kubeflow_1.0_kfctl_istio_dex_installation?

### ISSUE THREAD

**Issue by alforik** [kubeflow/website#1782]
The kubeflow_1.0_kfctl_istio_dex_installation
https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/   does not have a storage class description.

The kubeflow_1.0_kfctl-k8s-istio_installation
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/    have a storage class description.

Do we no need to prepare a storage class for the kubeflow_1.0_kfctl_istio_dex_installation?

**Comment by sarahmaddox** [comment]
/assign @krishnadurai 

@krishnadurai Please would you take a look at this question?

**Comment by krishnadurai** [comment]
@alforik if you are looking to install this on an on-premise Kubernetes installation, you would need to prepare the storage class.

Let me modify the documentation to reflect this.

**Comment by sarahmaddox** [comment]
@krishnadurai Are you able to send a PR to update the docs for this issue?

**Comment by krishnadurai** [comment]
Hello @sarahmaddox,

Thanks for the reminder, I have now added the necessary changes the docs in #1834.
