### ISSUE TITLE
questions on how fairing ClusterBuilder finds the source

### ISSUE THREAD

**Issue by shichengsg001** [kubeflow/website#1789]
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-5ecb290db21d> in <module>
      8                                                  pod_spec_mutators=[fairing.cloud.gcp.add_gcp_credentials_if_exists],
      9                                                  context_source=cluster.gcs_context.GCSContextSource())
---> 10 cluster_builder.build()
     11 logging.info(f"Built image {cluster_builder.image_tag}")

~/.local/lib/python3.6/site-packages/kubeflow/fairing/builders/cluster/cluster.py in build(self)
     61         )
     62         self.preprocessor.output_map[dockerfile_path] = 'Dockerfile'
---> 63         context_path, context_hash = self.preprocessor.context_tar_gz()
     64         self.image_tag = self.full_image_name(context_hash)
     65         self.context_source.prepare(context_path)

~/.local/lib/python3.6/site-packages/kubeflow/fairing/preprocessors/base.py in context_tar_gz(self, output_file)
     92                 logging.debug("Context: %s, Adding %s at %s", output_file,
     93                               src, dst)
---> 94                 tar.add(src, filter=reset_tar_mtime, arcname=dst, recursive=False)
     95         self._context_tar_path = output_file
     96         return output_file, utils.crc(self._context_tar_path)

/usr/lib/python3.6/tarfile.py in add(self, name, arcname, recursive, exclude, filter)
   1934 
   1935         # Create a TarInfo object from the file.
-> 1936         tarinfo = self.gettarinfo(name, arcname)
   1937 
   1938         if tarinfo is None:

/usr/lib/python3.6/tarfile.py in gettarinfo(self, name, arcname, fileobj)
   1805                 statres = os.lstat(name)
   1806             else:
-> 1807                 statres = os.stat(name)
   1808         else:
   1809             statres = os.fstat(fileobj.fileno())

FileNotFoundError: [Errno 2] No such file or directory: 'Dockerfile.model'

**Comment by sarahmaddox** [comment]
@shichengsg001 Thanks for reporting this error. Please would you add a link to the doc page where you found the notebook, or to the notebook itself, to help us troubleshoot the problem?

**Comment by shichengsg001** [comment]
Hi. Sarah. thank you for fast reply, the example I am using this note books mnist/mnist_gcp.ipynb 
ti is from this repo:
https://github.com/kubeflow/examples.git

it failed at this step. complaining about Dockerfile.model not found
Run the next cell and wait until you see a message like Built image gcr.io/<your-project>/fairing-job/mnist:<1234567>.

**Comment by sarahmaddox** [comment]
Thanks for the additional info @shichengsg001 

@amygdala Do you have any idea what's going wrong here? @shichengsg001 is encountering the error in section **Use Kubeflow Fairing to build the Docker image** of this notebook:
https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb

/assign @amygdala

**Comment by amygdala** [comment]
hi  @shichengsg001 , the `Dockerfile.model` file is in the same directory as that notebook.  Do you have the full contents of that directory checked out/downloaded?

**Comment by shichengsg001** [comment]
HI. @amygdala , thank your for your reply, seems like I need to upload the content under /examples/mnist to the notebook server, but it is not mentioned in the notebook.

Now I am hitting this error:
Forbidden: 403 POST https://storage.googleapis.com/storage/v1/b?project=XXXXX Insufficient Permission

Could you please explain who is calling this url? and what permission should I get?

**Comment by amygdala** [comment]
hi @shichengsg001 ,
That's good feedback to add some info to the notebook regarding needing the other content.  I'll create a separate issue to do that.

That 403 error looks like a GCS (Cloud Storage) permissions issue— perhaps the GCS bucket is not created, or you're accessing one in a project for which you don't have permissions.  To double check: you should run this example from a [Kubeflow notebook](https://www.kubeflow.org/docs/notebooks/) to get the credentials set up properly for you.
If you're already doing that, I suspect that something went wrong/was skipped with one of the setup steps. Can you double check that you edited the notebook cells with your project info etc. where that was indicated?

Btw, [this codelab](https://codelabs.developers.google.com/codelabs/kubeflow-introduction/index.html?index=..%2F..index#0) might be useful.  It walks through initial setup in more detail.

**Comment by shichengsg001** [comment]
Hi, @amygdala 
Thank you for your reply, 
I do have access to GCS, Could you explain what is the storage for? And what piece of code is for setting the bucket?

Best Regards

**Comment by shichengsg001** [comment]
Hi. @amygdala 

I think this line doesn't work,
credentials = GoogleCredentials.get_application_default()

I installed Kubeflow with this file: kfctl_k8s_istio.v1.0.1.yaml

I tried to read the documentation about ClusterBuilder, but I didn't find anything useful

Could you please tell me what is the context_source parameter expecting?

Best Regards

**Comment by amygdala** [comment]
Ah, I believe that this example notebook [requires the IAP on GKE ](https://github.com/kubeflow/examples/tree/master/mnist#mnist-on-kubeflow-on-gcp) installation.  E.g. the IAP config described [here](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#prepare-your-environment).
This will set up your GCP credentials properly.  For other installations, you would have to do a bit more extra work to set up your credentials in your notebook environment.
So the easiest fix might be to deploy a new IAP-enabled cluster.  As an alternative to the command-line deployment, you can also try this web app:  https://deploy.kubeflow.cloud/#/deploy  .

**Comment by shichengsg001** [comment]
HI. @amygdala 

Thank you for your reply, but actually I am more interested in how to use the fairing library, I couldn't found any useful documents online, appreciate if you enlighten me how to set the context for ClusterBuilder. My company wants to use Kubeflow across different plateform, so the IAP way is not applicable to us.

**Comment by amygdala** [comment]
hi @shichengsg001 ,
Here is some documentation on fairing: https://www.kubeflow.org/docs/fairing/.  
If you don't want to use the Kubeflow GKE IAP install, in particular you might be interested in these pages that go through more detail on credentials setup:
https://www.kubeflow.org/docs/fairing/gcp/configure-gcp/,  and
https://www.kubeflow.org/docs/fairing/azure/

(cc @jlewi , the notebook author,  in case there are more detailed fairing issues)

**Comment by jlewi** [comment]
@shichengsg001 if you'd like more information about fairing and the ClusterBuilder in particular could you please open up a new issue and cc @jinchihe  (primary fairing author) with as much information as you could provide about what you would like to do and what your question is.

**Comment by jinchihe** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'Dockerfile.model'

The `Dockerfile.model`  do exist here https://github.com/kubeflow/examples/tree/master/mnist 

@shichengsg001 I think you are not run Jupyter Notebook in the `mnist` directory, in other directory? please check that.

By the way, if have more problem, i suggest log the issue under `kubeflow/examples`

**Comment by shichengsg001** [comment]
Hi. @jinchihe 

I have upload all content to /home/jovyan in the notebook container

Now the issue is how to set the context_source? I suppose the context_source is to pick up dockerfile and files which are needed to be built into the image. so I tried to set context_source='dir:///home/jovyan' for for ClusterBuilder to pickup the files from local. but it doesn't work

could you please explain how to set context_source for clusterBuilder?

appreciate you could give example of the object format of the context_source separately to pick files from local and from GCS.

also if I am chose to use GCS, do I need to package the dataset , dockerfile and python scripts together and save to the GCS bucket?
