### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by cspavlou** [kubeflow/website#1793]
The [invite link](https://kubeflow.slack.com/join/shared_invite/enQtNDg5MTM4NTQyNjczLTdkNTVhMjg1ZTExOWI0N2QyYTQ2MTIzNTJjMWRiOTFjOGRlZWEzODc1NzMwNTMwM2EzNjY1MTFhODczNjk4MTk) for the Kubeflow Slack workspace is no longer active

@jlewi is it possible to create a link that doesn't expire?

**Comment by sarahmaddox** [comment]
Just checked the Slack docs: You need to be a Workspace Owner or Admin in order to create an invitation link. I don't have the right access, and I therefore can't see the options in the *expiry* menu when creating a new invitation link.

**Comment by sarahmaddox** [comment]
@abhi-g Do you have access to create a new Slack invitation link for Kubeflow, and to check what the expiry options are?

**Comment by abhi-g** [comment]
/cc @theadactyl @jlewi 
I don't have access to slack administration

**Comment by jlewi** [comment]
@sarahmaddox I made you a slack owner as well.

**Comment by sarahmaddox** [comment]
Fixed by https://github.com/kubeflow/website/pull/1802
/close

**Comment by cspavlou** [comment]
@sarahmaddox , we have to update the Slack links on the website. Currently, only the [community page](https://www.kubeflow.org/docs/about/community/) has the correct link. I will make a PR to fix all the links. Does the new link expire or is it permanent?

**Comment by sarahmaddox** [comment]
Thanks for the PR @cspavlou 
The new link is permanent, according to the GitHub "invitations" UI.
