### ISSUE TITLE
Support for Chinese translated site

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#18]
With a large amount of interest in Kubeflow coming from China, we should figure out how to support a Chinese translated site. Can this be automated translation?

**Comment by dtaniwaki** [comment]
I'd love to help the Japanese translation of the site.

**Comment by abhi-g** [comment]
Thanks Daisuke. We are using Hugo to create the static site. I’ll look up
on how can we leverage any internationalization capabilities it might have.
Please see if you could explore as well.

Regards
Abhishek

**Comment by abhi-g** [comment]
@dtaniwaki Please join the #website channel on kubflow.slack.com and I can provide further details on how to go about adding Japanese documentation.

**Comment by dtaniwaki** [comment]
I joined it!

**Comment by gaocegege** [comment]
I'd appreciate it if we could maintain a Chinese version.

https://gohugo.io/functions/i18n/ may be helpful for us.

**Comment by abhi-g** [comment]
I agree.

Thanks for the pointer to the i18n documentation. We discussed today in
website standup to get the config ready for i18n once are deployment docs
are ready. I won’t have bandwidth before that to make the config changes
before that.

Abhishek

**Comment by gaocegege** [comment]
SGTM

Thanks :smile:

**Comment by sarahmaddox** [comment]
Related issue: https://github.com/kubeflow/website/issues/1128

**Comment by sarahmaddox** [comment]
The product requirements doc is ready for review: http://bit.ly/kubeflow-i18n

I've scheduled it for discussion in the Kubeflow community meeting on March 24, PT.
