### ISSUE TITLE
Set up a GCP Project

### ISSUE THREAD

**Issue by j-wezel** [kubeflow/website#1814]
I think in https://www.kubeflow.org/docs/gke/deploy/project-setup/, step 4 should mention to enable 
Cloud Build API.

**Comment by imskr** [comment]
Can I add that?

**Comment by sarahmaddox** [comment]
@j-wezel I installed Kubeflow 1.0.0 rc4 on GCP without enabling the Cloud Build API. Could you give us more information about why we need to enable it. For example, is it a new requirement for Kubeflow 1.0.1, or did you get an error when running a particular Kubeflow application?

**Comment by j-wezel** [comment]
Well you will need it later on when Fairing builds containers with models to be served. Fair enough, it's not required per se, so that should go into the description.

**Comment by sarahmaddox** [comment]
Thank you for the additional information @j-wezel 

@imskr Yes, please do create a PR to add the requirement for enabling the API, with a note that it's required if you plan to use [Fairing](https://www.kubeflow.org/docs/fairing/) in your Kubeflow cluster.

/assign @imskr
