### ISSUE TITLE
Standalone deployment does not work

### ISSUE THREAD

**Issue by chongkong** [kubeflow/website#1840]
Following from https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/

I cannot do [Deploying Kubeflow Pipelines](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines) part.

```shell
kubectl apply -k https://github.com/kubeflow/pipelines/manifests/kustomize/base/crds?ref=$PIPELINE_VERSION
zsh: no matches found: https://github.com/kubeflow/pipelines/manifests/kustomize/base/crds?ref=0.2.5
```

I think command should be changed.

**Comment by joeliedtke** [comment]
/cc @rmgogogo 

@rmgogogo would know more than I do, but here are a couple quick questions that might help:

- What version of `kubectl` are you using? To get the version, run `kubectl version`.
- Have you tried running this script in bash? I'm not terribly familiar with zsh, and I don't think that zsh would affect this command, but after a search I did come across some similar cases where switching to bash helped.
