### ISSUE TITLE
Storage Options in AWS docs

### ISSUE THREAD

**Issue by millstx** [kubeflow/website#1847]
https://www.kubeflow.org/docs/aws/storage/

Hi Im running 1.0.1 for aws and ks doesnt exist as a command and kfctl generate no longer exists and is replaced with build. 

also the efs_csi driver of kf_app directory doesnt exist 

i think this needs updating 

how can i get efs working in kubeflow in 1.0.1, im running kfctl v1.0.1-0-gf3edb9b

thanks

Tony

**Comment by sarahmaddox** [comment]
@millstx thanks for raising this issue.

@Jeffwan would you be able to take a look? This issue is also related to https://github.com/kubeflow/website/issues/1223

/assign @Jeffwan

**Comment by Jeffwan** [comment]
I ask my teammate to fix that. It needs some code change and it should be fixed by next week

**Comment by Jeffwan** [comment]
Please check details here. https://www.kubeflow.org/docs/aws/storage/

Feel free to reopen if above guidance can not solve your problem
