### ISSUE TITLE
Failed to delete app when following Delete using CLI Page

### ISSUE THREAD

**Issue by DesmondH0** [kubeflow/website#1858]
When following `[Delete using CLI](https://www.kubeflow.org/docs/gke/deploy/delete-cli/)` page

It will have the following error when trying to remove app:
couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 400 with message: cannot find ClusterName within KfDef, this may cause error deletion to clusters.

I am now deleting the app via GCP deployment manager

**Comment by jlewi** [comment]
Closing this issue because we are moving to blueprints for GCP and not using kfctl.
So you would delete Kubeflow just by running appropriate kubectl commands.
https://github.com/kubeflow/gcp-blueprints/tree/master/kubeflow
