### ISSUE TITLE
Update Kubeflow Pipelines Standalone Deployment documentation to refrense to the latest version

### ISSUE THREAD

**Issue by JohanWork** [kubeflow/website#1862]
Today the document refrences to 0.2.5 but 0.3.0 is out .
https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/

Happy to make a contribute if you point me to the right direction!

**Comment by janeman98** [comment]
@JohanWork 

You can follow the instruction in https://github.com/kubeflow/website#creating-and-updating-the-kubeflow-docs

**Comment by sarahmaddox** [comment]
Thanks @JohanWork! The version number for Pipelines is held in this file:
https://github.com/kubeflow/website/blob/master/layouts/shortcodes/pipelines/latest-version.html

/cc @Bobgy 
/cc @rmgogogo 
/cc @joeliedtke

**Comment by JohanWork** [comment]
Thnx @sarahmaddox pushed a pr for it [here](https://github.com/kubeflow/website/pull/1866)

**Comment by joeliedtke** [comment]
/close

This doc is now referencing 0.5.1.
