### ISSUE TITLE
Add Kubeflow introductory video to website

### ISSUE THREAD

**Issue by kweinmeister** [kubeflow/website#1863]
This feature request is to add the [Kubeflow 101 video](https://www.youtube.com/watch?v=cTZArDgbIWw) to the [About Kubeflow page](https://www.kubeflow.org/docs/about/kubeflow/).

**Comment by Heena-PyCloud** [comment]
I will work on this.
/assign

**Comment by Heena-PyCloud** [comment]
@sarahmaddox 
Hi Sarah,
Should I place the video in last line of section **Getting started with Kubeflow** in this page
https://www.kubeflow.org/docs/about/kubeflow/
To be specific, below line 21 in kubeflow.md.

**Comment by sarahmaddox** [comment]
/assign @Heena-PyCloud 

Thanks @Heena-PyCloud! Your suggested location looks great.

**Comment by sarahmaddox** [comment]
Fixed by PR https://github.com/kubeflow/website/pull/1865

/close
