### ISSUE TITLE
Kubeflow resource requirement

### ISSUE THREAD

**Issue by navo1194** [kubeflow/website#1878]
It would be really helpful if resource(cpu, memory) requirement is also given for kubeflow.

**Comment by janeman98** [comment]
Will this help?
https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements

**Comment by navo1194** [comment]
Hi,

The link which you have sent is the minimum resource requirement for
kubernetes, I need resource requirement for kubeflow.
Please help me with this.

Regards,
Navodita Jaiswal

**Comment by navo1194** [comment]
Could you please clarify this address path for me?
