### ISSUE TITLE
Deploy using UI

### ISSUE THREAD

**Issue by NicoG94** [kubeflow/website#1885]
https://deploy.kubeflow.cloud/ does not let me check into my Google Account using Firefox 74.0.1 (64-Bit)
with Chrome it works

**Comment by sarahmaddox** [comment]
Thanks for raising this issue @NicoG94. I'd recommend that you raise it in the https://github.com/kubeflow/kubeflow repo, as it's not something we can fix in the docs.

**Comment by jlewi** [comment]
Closing this issue. In addition to @sarahmaddox 's comment
deploy.kubeflow.cloud is now deprecated and we recommend folks use the CLI.
