### ISSUE TITLE
Update Auth information on the website

### ISSUE THREAD

**Issue by elviraux** [kubeflow/website#1888]
Add https://github.com/kubeflow/manifests/tree/master/dex-auth docs
and more detailed information around profiles and groups

https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#batch-creation-of-user-profiles here we need to show that multiple users can be added to a single profile

**Comment by lalithvaka** [comment]
Here are some of the detailed topics that needs additional documentation 
- Enabling Low level kubectl access for AuthN/AuthZ , 
        - is it enabled by default along with profile creation?
        - how can this be enabled for each user? Examples?
        - Is it enabled in 1.0.0 or 1.0.1?
- Profile capacity limit possibilities and examples
        - add examples
        - link to the spec
- AuthN/AuthZ capability matrix for 0.7 vs 1.0.0 vs 1.0.1 releases

**Comment by jtfogarty** [comment]
If a user logs into Kubeflow via DEX/AD where this user has;

- never logged in before
- is not a contributor on any namespace

The system prompts the user to create a namespace.

If the user has been assigned as a contributor to a namespace, the system also prompt them to create a namespace the first time they log in.

**Comment by jtfogarty** [comment]
@lalithvaka can you define what 'Low level kubectl access' means

**Comment by lalithvaka** [comment]
> @lalithvaka can you define what 'Low level kubectl access' means

@jtfogarty Jeff, was referring to the concepts laid out in  https://docs.google.com/presentation/d/1j5tBrCkLNG-QxTl44iv-x5KpCapnczpxCbUzSciA2l8/edit#slide=id.g70b2208acc_1_807 slide 19 through 25

**Comment by lalithvaka** [comment]
> If a user logs into Kubeflow via DEX/AD where this user has;
> 
> * never logged in before
> * is not a contributor on any namespace
> 
> The system prompts the user to create a namespace.
> 
> If the user has been assigned as a contributor to a namespace, the system also prompt them to create a namespace the first time they log in.

@krishnadurai , based on this verification by @jtfogarty every user is getting a new profile created on a successful authN even if the user is not an admin and already assigned as a contributor to another namespace created by the admin. Should this be treated as a defect and shall I create an issue? or is this the expected behavior? Can this be disabled for the short term and where is this logic?

**Comment by lalithvaka** [comment]
> Here are some of the detailed topics that needs additional documentation
> 
> * Enabling Low level kubectl access for AuthN/AuthZ ,
>   - is it enabled by default along with profile creation?
>   - how can this be enabled for each user? Examples?
>   - Is it enabled in 1.0.0 or 1.0.1?
> * Profile capacity limit possibilities and examples
>   - add examples
>   - link to the spec
> * AuthN/AuthZ capability matrix for 0.7 vs 1.0.0 vs 1.0.1 releases

Whats the difference between Kubernetes quota vs resource quota spec on Kubeflow? Are all objects https://kubernetes.io/docs/concepts/policy/resource-quotas/#viewing-and-setting-quotas listed here (compute-resources / object-counts) is supported in Kubeflow profiles (assuming these are namespaces)? or just the ones listed in the example below?

https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/config/samples/profile_v1beta1_profile.yaml

resourceQuotaSpec:
    hard:
      cpu: "10"
      memory: 20Gi
      pods: "20"

**Comment by sarahmaddox** [comment]
Related:
https://github.com/kubeflow/website/issues/1066
https://github.com/kubeflow/website/issues/1280

**Comment by lalithvaka** [comment]
> Related:
> #1066
> #1280

@sarahmaddox  would be great to have the following addressed in the manual profile creation https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#batch-creation-of-user-profiles

Profile capacity limit possibilities and examples
add examples
link to the supported capacity limit spec

I see a small example here - https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/config/samples/profile_v1beta1_profile.yaml
