### ISSUE TITLE
Tracking issue: Rendering oddities cause by change to Goldmark renderer

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#1891]
We're upgrading to the latest version of the Docsy theme and to Hugo 0.68.3. From Hugo 0.60 onwards, the default Markdown renderer is Goldmark rather than the current default BlackFriday (see [Hugo docs](https://gohugo.io/getting-started/configuration-markup#goldmark)). We can choose to force the use of BlackFriday rather than Goldmark if necessary, but we're told that Goldmark gives a better overall experience (although both Goldmark and BlackFriday have their own set of oddities).

Let's list any breakages we find in the [preview from PR # 1870](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/) so that we can decide whether to upgrade then fix the oddities, or to force the use of BlackFriday renderer.

* Numbered list is broken when it includes code snippets: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/other-guides/kustomize/#applying-the-configuration-to-your-kubeflow-cluster
* Numbered list is broken when it includes an indented bulleted list: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/gke/deploy/project-setup/

**Comment by janeman98** [comment]
Numbered list is broken here : https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/central-dash/overview/#using-kubectl-and-port-forwarding

**Comment by janeman98** [comment]
Link for "feedback" display source in [Beta section](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/metadata/)
![image](https://user-images.githubusercontent.com/52723717/79148875-1aa9b380-7d7b-11ea-9b6b-04eefa863ea8.png)

**Comment by janeman98** [comment]
Same for [Alpha section](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/training/chainer/): 

![image](https://user-images.githubusercontent.com/52723717/79159182-79c3f400-7d8c-11ea-9541-f377a76991ac.png)

**Comment by janeman98** [comment]
Content outside the code block [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/training/tftraining/#troubleshooting): 
![image](https://user-images.githubusercontent.com/52723717/79159795-914fac80-7d8d-11ea-9a24-5b97d90976c7.png)

[Current/correct version](https://www.kubeflow.org/docs/components/training/tftraining/#troubleshooting):
![image](https://user-images.githubusercontent.com/52723717/79159858-b47a5c00-7d8d-11ea-94ce-9713f16d18f9.png)

**Comment by janeman98** [comment]
Numbered list are broken here : https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/hyperparameter-tuning/hyperparameter/#tensorflow-example

**Comment by janeman98** [comment]
Table is not displayed properly [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/serving/overview/#multi-framework-serving-with-kfserving-or-seldon-core):
![image](https://user-images.githubusercontent.com/52723717/79160930-7bdb8200-7d8f-11ea-8048-d9dd2f752478.png)

**Comment by janeman98** [comment]
Numbered list is broken here: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/components/serving/kfserving/#use

**Comment by janeman98** [comment]
Numbered list is broken after # 7 : https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/notebooks/setup/#create-a-jupyter-notebook-server-and-add-a-notebook

**Comment by janeman98** [comment]
Numbered list is broken here : https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/pipelines/pipelines-quickstart/#deploy-kubeflow-and-open-the-pipelines-ui

**Comment by janeman98** [comment]
Italic text is not displayed properly [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/pipelines/overview/concepts/run/)
![image](https://user-images.githubusercontent.com/52723717/79166903-01186400-7d9b-11ea-8611-40fffad60e54.png)

From the source, look like this happen after adding an id?
`<a id=recurring-run> 
A *recurring run* , or job in the Kubeflow Pipelines [backend APIs](https://github.com/kubeflow/pipelines/tree/06e4dc660498ce10793d566ca50b8d0425b39981/backend/api/go_http_client/job_client), is a repeatable run of
a pipeline. The configuration for a recurring run includes a copy of a pipeline
with all parameter values specified and a 
[run trigger](/docs/pipelines/concepts/run-trigger/).
You can start a recurring run inside any experiment, and it will periodically
start a new copy of the run configuration. You can enable/disable the recurring
run from the Kubeflow Pipelines UI. You can also specify the maximum number of
concurrent runs, to limit the number of runs launched in parallel. This can be
helpful if the pipeline is expected to run for a long period of time and is
triggered to run frequently.`

**Comment by janeman98** [comment]
Numbered list is broken here : https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/pipelines/sdk/install-sdk/#set-up-python

**Comment by janeman98** [comment]
Subtitle does not displayed properly [here:](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/pipelines/sdk/best-practices/)
![image](https://user-images.githubusercontent.com/52723717/79167507-6587f300-7d9c-11ea-82d3-8cf28c643147.png)

**Comment by janeman98** [comment]
Text in **source** row is not display properly [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/pipelines/sdk/output-viewer/): 
![image](https://user-images.githubusercontent.com/52723717/79167852-4b024980-7d9d-11ea-833c-5dacf934b085.png)

**Comment by janeman98** [comment]
Numbered list is broken after bullet 4 [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/pipelines/upgrade/#reinstalling-kubeflow-pipelines).

**Comment by janeman98** [comment]
Numbered list after bullet 2 is broken [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/gke/customizing-gke/#customizing-kubernetes-resources).

**Comment by janeman98** [comment]
Additional ``` [here](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/gke/customizing-gke/#customizing-kubernetes-resources)

![image](https://user-images.githubusercontent.com/52723717/79170059-12fe0500-7da3-11ea-9aef-b55fce2597e8.png)

**Comment by janeman98** [comment]
Numbered list is broken after bullet 2  here : https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/upgrading/upgrade/#upgrades-from-earlier-versions-of-kubeflow

**Comment by janeman98** [comment]
@sarahmaddox 
Above is a long list, feel free to let me know if there is anything I can help with.

**Comment by sarahmaddox** [comment]
Thanks for this excellent investigative work @janeman98 

I've now fixed some of the worst problems as part of PR https://github.com/kubeflow/website/pull/1870:

* Fixed list formatting in kfctl/kustomize guide, just to prove that it's possible to fix this type of list rendering issue.
* Fixed layouts for alpha and beta banners.
* Fixed table in the serving overview page.
* Fixed italics and links in the concepts page for pipeline run.
* Added closing  `</a>` tags to fix broken headings after HTML anchors on various pages.
* Fixed rendering of cell within table for Pipelines output viewer.

Next steps, after PR https://github.com/kubeflow/website/pull/1870 is merged:
* Fix the broken lists mentioned in comments above, and check for other similar breakages.
* Search for all HTML anchors like `<a id="some-id"` and add the closing `</a>` tag if missing, to fix subsequent links etc.

Given the above, I think it's OK to submit PR https://github.com/kubeflow/website/pull/1870 then fix the remaining rendering issues afterwards, in subsequent PR(s). @janeman98 what do you think, and do you have bandwidth to help with those subsequent fixes?

**Comment by sarahmaddox** [comment]
/assign @janeman98 

Assigning @janeman98 for further help with this issue.

**Comment by janeman98** [comment]
@sarahmaddox 
Sure, I will start fixing the rest after PR 1870 is merged.
