### ISSUE TITLE
Istio in Kubeflow diagram is not accurate

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/website#1903]
/bug

Hi all.
I was at this page in docs (https://www.kubeflow.org/docs/other-guides/istio-in-kubeflow/) and bumped into this diagram:

![Istio in Kubeflow](https://www.kubeflow.org/docs/images/Istio-in-KF.svg)

It is a very nice diagram, but the last parts of it (4 and 5) aren't exactly accurate.

What really happens is:
3. The request is validated and an identity header is attached to the http request (`x-goog-authenticated-user-email` or `kubeflow-userid`).

Now there are two scenarios:
* The request is going to a web app backend (e.g., Jupyter Web App). In that case, the application checks if the user is authorized via SubjectAccessReview, to check if the user has the necessary K8s RBAC.
* The request is going to a sensitive network resource, e.g. a user's Jupyter Notebook IDE. In that case, there are Istio RBAC rules in place to make sure the user is authorized to access the service.

The notebook controller is never in the path of any request, nor does it act as a server.
(Self-plug:) We do an overview of how we do authn/authz in Kubeflow in our San Diego talk with @krishnadurai . See 5:40-9:00, it's just 3.5 minutes but I think it helps because it's visualized as well.
http://www.youtube.com/watch?v=qyUyYLvmKHY&t=5m40s

@abhi-g is there any chance the source of the diagram is available in order to make changes there? 
/cc @jlewi

**Comment by jtfogarty** [comment]
/area docs
priority p1

**Comment by abhi-g** [comment]
@jtfogarty the underlying diagram is available in Kubeflow team drive > Doc Diagrams > Istio in KF. Please feel free to update. 

Also consider how much of detail to abstract out to make it easier to understand vs. adhering to explicit details for correctness.

**Comment by yanniszark** [comment]
@abhi-g thanks! :smile: 
Also a PR for this could include the consequences of not using Istio:
https://github.com/kubeflow/kubeflow/issues/4935#issuecomment-615256808
