### ISSUE TITLE
Step in Installing kustomize throws an error

### ISSUE THREAD

**Issue by arshashi** [kubeflow/website#1917]
Following the link https://www.kubeflow.org/docs/other-guides/kustomize/ to install kustomize.

when I tried to run the mv command mentioned below, throws an error.  It looks like tar ball is not extracting with the name of the file. Instead i noticed that it extracts as the file "kustomize" under the current directory.

Error:
$ mv kustomize_*_${opsys}_amd64 ${HOME}/bin/kustomize
mv: cannot stat ‘kustomize_*_linux_amd64’: No such file or directory

-------
Move the binary:
**mv kustomize_*_${opsys}_amd64 ${HOME}/bin/kustomize**

**Comment by janeman98** [comment]
Thanks @arshashi . Very good catch!

/assign
