### ISSUE TITLE
Facing Issue while running mnist_gcp.ipynb

### ISSUE THREAD

**Issue by abhiverma1924** [kubeflow/website#1918]
While following the step given in the mnist tutorial I was trying to run mnist_gcp.ipynb some error occurred while running first few blocks.
Command '['pip3', 'install', '--user', '-r', 'requirements.txt']' returned non-zero exit status 1.
I am unable to find the a way to solve this can anyone take a look at it.

**Comment by sarahmaddox** [comment]
@abhiverma1924 Can you give more details of the issue you encountered? Are you running this version of [mnist_gcp.ipynb](https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb)?

**Comment by btphan95** [comment]
I'm having the same error while running the notebook following this Google Colab:
https://codelabs.developers.google.com/codelabs/kubeflow-introduction

The command notebook_setup.notebook_setup() gives this error:
```
CalledProcessError                        Traceback (most recent call last)
<ipython-input-3-b1e5ce107a08> in <module>
      1 import notebook_setup
      2 reload(notebook_setup)
----> 3 notebook_setup.notebook_setup()

~/examples/mnist/notebook_setup.py in notebook_setup(platform)
     24 
     25   logging.info("pip installing requirements.txt")
---> 26   subprocess.check_call(["pip3", "install", "--user", "-r", "requirements.txt"])
     27 
     28   clone_dir = os.path.join(home, "git_tf-operator")

/usr/lib/python3.6/subprocess.py in check_call(*popenargs, **kwargs)
    309         if cmd is None:
    310             cmd = popenargs[0]
--> 311         raise CalledProcessError(retcode, cmd)
    312     return 0
    313 

CalledProcessError: Command '['pip3', 'install', '--user', '-r', 'requirements.txt']' returned non-zero exit status 1.
```

**Comment by abhiverma1924** [comment]
@btphan95 @sarahmaddox yes, I am talking about the same issue.

**Comment by abhiverma1924** [comment]
> @abhiverma1924 Can you give more details of the issue you encountered? Are you running this version of [mnist_gcp.ipynb](https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb)?
Yes, I am taking about the same file.
