### ISSUE TITLE
deploy.kubeflow.cloud not working

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/website#1922]
Upon navigating to this url, a modal appears with this text:
"Config loading Error
Failed to load user config from a18d7b07/bootstrap/config/kfctl_gcp_iap.0.6.2.yaml"
and the "Create Deployment" is greyed out and remains greyed out even if the form is filled out properly.

**Comment by bdoohan-goog** [comment]
Visiting https://deploy.kubeflow.cloud/#/deploy I am received an error saying that site cannot be reached. Has this site been deprecated?

**Comment by 8bitmp3** [comment]
https://deploy.kubeflow.cloud is indeed offline 

/assign @Bobgy

**Comment by Bobgy** [comment]
No, it's no longer supported

**Comment by bdoohan-goog** [comment]
Thank you both
