### ISSUE TITLE
The current tool for API docs generation is unusable

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/website#1924]
The current tool we use, [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs), is unusable right now for updating existing API reference docs or generating new API reference for new controllers. We need to fix the existing issues or create an alternative solution. A couple of existing issues are outlined below:
* The obscure error message `type invalid type has kind=Unsupported which is unhandled` appears in https://github.com/kubeflow/website/pull/1899#issuecomment-614159752 and https://github.com/ahmetb/gen-crd-api-reference-docs/issues/10. 
* This tool does not support Go Modules yet as mentioned in https://github.com/ahmetb/gen-crd-api-reference-docs/issues/12 and https://github.com/kubeflow/kubeflow/issues/3723#issuecomment-585394918. 
* Hacky workarounds are required for generating API reference docs for new controllers as discussed in https://github.com/kubeflow/kubeflow/issues/3723. It will be impossible to maintain and non-trivial to reuse for generating docs for new controllers. 

If anyone would like to fix the issues mentioned above or create an alternative solution, please comment on this issue. 

Also cc'ing a few folks who were part of the discussion in https://github.com/kubeflow/website/pull/1899: 
@sarahmaddox @zhenghuiwang @kbhawkey @rlenferink

**Comment by terrytangyuan** [comment]
This should not be closed. We need. solution for this.

**Comment by kbhawkey** [comment]
Hi @terrytangyuan .
You may be interested in this new tool, https://github.com/tengqm/genref.
I have not read through the changes, but thought it may help to generate a controller API.
