### ISSUE TITLE
Guidance on compute resources kubeflow need for AWS users 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#1929]
https://github.com/kubeflow/kubeflow/issues/4972#issuecomment-620941016

It's better for us to mention what kind of instance type and how many instances are needed to run kubeflow on AWS. 

User won't meet resource problems.

**Comment by 8bitmp3** [comment]
Assigning this to @Jeffwan (the author) to make sure we have Assignees here :)

/assign @Jeffwan
