### ISSUE TITLE
End-to-end Kubeflow on AWS

### ISSUE THREAD

**Issue by radhakrishnang** [kubeflow/website#1940]
https://www.kubeflow.org/docs/aws/aws-e2e/
In general those who work as data scientist, need not be a expert in docker, AWS, kubernets, 
the kubeflow setup on AWS is bit vauge and not clear, please create a documentation for Kubeflow on AWS with the simple use case and scheduling of the pipeline

**Comment by 8bitmp3** [comment]
@Jeffwan @PatrickXYS do you by any chance want to look at this? Cheers

**Comment by PatrickXYS** [comment]
Thanks @8bitmp3  for heads up.

@radhakrishnang You can follow our [EKS Kubeflow Workshop](https://github.com/aws-samples/eks-kubeflow-workshop)

**Comment by Jeffwan** [comment]
@radhakrishnang 

You are supposed to look at  https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ but not e2e flow.  Install kubeflow on AWS just need 4-5 command line runs. Feel free to have a try

**Comment by radhakrishnang** [comment]
@Jeffwan  Thanks I have set up kubeflow following eks workshop, 
end to end - i am referring to kubeflow pipeline 
can you guys add one more pipeline example for kubeflow to sagemaker using sklearn or tensorflow for binary classification

**Comment by theofpa** [comment]
> In general those who work as data scientist, need not be a expert in docker, AWS, kubernets,
> the kubeflow setup on AWS is bit vauge and not clear

@radhakrishnang , Arrikto launched [MiniKF in AWS marketplace](https://aws.amazon.com/marketplace/pp/B08MBGH311?qid=1606062605249&sr=0-1&ref_=srh_res_product_title#pdp-overview) earlier this month, which simplifies further the setup for a data scientist.

**Comment by Evanto** [comment]
Hi @radhakrishnang, we're building [SAKK](https://github.com/provectus/sak-kubeflow) - a Terraform-based tool that allows configuring EKSs cluster with Kubeflow declaratively using IaC approach, deploy them with a couple of commands, quickly replicate and augment your clusters with any new resources, and automate them with GitOps.  The [Quickstart](https://github.com/provectus/sak-kubeflow/blob/init/QUICKSTART.md) includes an example of uploading the `kmeans_mnist` demo pipeline with SageMaker algorithm `kmeans-mnist-pipeline`.  Would this help?

**Comment by thesuperzapper** [comment]
@Evanto is your SAKK project active? If not, you might want to consider contributing to the new [argoflow](https://github.com/argoflow/argoflow) distribution.
