### ISSUE TITLE
Pipelines API Reference Documentation Typo

### ISSUE THREAD

**Issue by aoliu95** [kubeflow/website#1941]
https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/

Issue with GET /apis/v1beta1/runs Requested Parameter Description

Example should be 

> (Example, "name asc" or "id desc")

Instead of 

> (Example, "name asc" or "id des")

**Comment by janeman98** [comment]
/assign @joeliedtke 
Please unassign if you don't have bandwidth to work on this.

**Comment by amygdala** [comment]
The fix is in, but the ref docs need to be regenerated and the site updated.  Not sure of the process for that.
/assign @joeliedtke
