### ISSUE TITLE
Install kubeflow on private GKE

### ISSUE THREAD

**Issue by snowlover173** [kubeflow/website#1947]
As the documentation is not ready yet, I put information here for anyone who might be looking for it.
If you try to install kubeflow with cli:

1-follow the link below except the line kfctl apply:
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/
instead of kfctl apply please run :
kfctl build -V -f ${CONFIG_URI}

a)       Kfctl build -V -f ${CONFIG_URI}
b)       After running build, inside the directory that you are at(kf-dir), you can see the following if you run : ls
c)       gcp_config, Kustomize, kfct_gcp_iap.v1.0.1.yaml
 
2-  cd to gcp_config and you can see the cluster files:
cluster-kubeflow.yaml
b.  Cluster.jinja
 
3-  In cluster.jinja add the following 2 lines under the {cluster name}
properties:
    parent: projects/{{ env['project'] }}/locations/{{ properties['zone'] }}
    zone: {{ properties['zone'] }}
    cluster:
      name: {{ CLUSTER_NAME }}
      network: {{ properties['network-name'] }}                      -- add this line
      subnetwork: {{ properties[‘node-subnet’] }}                    --- add this line
      initialClusterVersion: "{{ properties['cluster-version'] }}"
      resourceLabels:
 
 
and then scroll down to when the condition of private subnet is checking:
    
  {% if properties['securityConfig']['privatecluster'] %}
      ipAllocationPolicy:
        createSubnetwork: false   make sure it is false(by default it is true)
        useIpAliases: true 
 
 
 
4-  In the cluster-kubeflow.yaml add the following 2 lines:
 
cluster-version: "1.14"
    network-name:   kfp-my-network-name    add this line (your network name)
    node-subnet:  kfp-my-private-subnet-name   add this line (your private subnet name)
    cpu-pool-enable-autoscaling: true
    cpu-pool-initialNodeCount: 2
    cpu-pool-machine-type: n1-standard-8
 
 
make sure you change the following values for the keys mentioned below(you need to scroll down to see them):
 
gpu-pool-max-nodes: 0.   by default it is 10, please change it to zero to make it work in any region that doesnt have GPU.
privatecluster: true      by default it is false , we need to change it to true.
 
 
5-  After making these changes please go back to the kf-dir where the file : kfct_gcp_iap.v1.0.1.yaml is.
And run : Kfctl apply -V -f kfct_gcp_iap.v1.0.1.yaml
 
 
Please add to this issue with your findings to help the community until the documentation gets updated.

**Comment by jtfogarty** [comment]
I have the added issue of having no default networks in the gcp project. 
I believe the below is causing an error
```
storage.jinja:        
privateNetwork: projects/{{ env['project'] }}/global/networks/default
```

**Comment by jtfogarty** [comment]
you have bad characters in the subnet 
```
`
```
vs `'`
```
network: {{ properties['network-name'] }} -- add this line
subnetwork: {{ properties[‘node-subnet’] }} --- add this line
```
