### ISSUE TITLE
Install Kubeflow on IBM Cloud instructions - "ibmcloud cs cluster config" fails

### ISSUE THREAD

**Issue by ptitzler** [kubeflow/website#1948]
In https://www.kubeflow.org/docs/ibm/install-kubeflow/ step 4:

```
ibmcloud cs cluster config $CLUSTER_NAME
```

results in 

```
ibmcloud cs cluster config ptitzler-kubeflow
FAILED
Incorrect Usage.
...

USAGE:
        ibmcloud ks cluster config --cluster CLUSTER
```

My IBM Cloud CLI setup:

```
ibmcloud version
ibmcloud version 1.0.0+908f90a-2020-03-30T10:19:41+00:00

ibmcloud plugin list
Listing installed plug-ins...

Plugin Name                            Version   Status   
cloud-functions/wsk/functions/fn       1.0.39       
cloud-object-storage                   1.1.3        
container-registry                     0.1.464      
container-service/kubernetes-service   1.0.57       
machine-learning                       3.0.2  
```

To make this work I had to run 

```
ibmcloud cs cluster config --cluster $CLUSTER_NAME
```

Please note that there have been changes to the plugin that render the following instruction invalid too

```
Follow the instructions on the screen to EXPORT the correct KUBECONFIG value to point to the created cluster.
```

**Comment by ptitzler** [comment]
@Tomcli @janeman98 fyi

**Comment by janeman98** [comment]
Thanks @ptitzler.
In the past, I normally used GUI to create my kubernetes cluster in IBM cloud. Now, I have lost my environment to test/verify this.
Would you mind submitting a PR to fix this?

**Comment by ptitzler** [comment]
Certainly, will do!

**Comment by Tomcli** [comment]
I checked the [IBM Cloud docs](https://cloud.ibm.com/docs/containers?topic=containers-cs_cluster_tutorial) and looks like the new version of the IBM Cloud is using `ibmcloud ks cluster config --cluster CLUSTER`. @ptitzler would you mind also change the `cs` part to `ks` as well?

**Comment by ptitzler** [comment]
It appears that there are some major changes that I'll have to incorporate as well in the update. Many of the listed commands don't work as is anymore, as outline [here](https://cloud.ibm.com/docs/containers?topic=containers-cs_cli_changelog#10).
> Version 1.0 of the CLI plug-in was released on 16 March 2020. This version contains permanent syntax and behavior changes that are not backwards compatible.
