### ISSUE TITLE
doc set_*_request as well as set_*_limit annotations

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#1954]
https://www.kubeflow.org/docs/gke/pipelines/enable-gpu-and-tpu/

Here and elsewhere we mention specifying k8s limits, e.g. `set_gpu_limit`.  We should mention that `set_xxx_request` also works.  e.g. https://github.com/kubeflow/pipelines/blob/62e33c711b12ebeb60d5fb393e9484f2b297bcac/sdk/python/kfp/dsl/_container_op.py#L249

(from a customer query)

**Comment by amygdala** [comment]
let's keep open, still worthwhile...

**Comment by h20170167** [comment]
Hi Can i work on this issue

**Comment by hbelmiro** [comment]
@Vipin0608 this issue is from 4 years ago. The code of that page doesn't even exist in this repo anymore.
If you want to work on that, you need to do it at https://github.com/GoogleCloudPlatform/kubeflow-gke-docs.
I'm closing this issue.

/close
