### ISSUE TITLE
Access Control for Azure Deployment

### ISSUE THREAD

**Issue by knlp** [kubeflow/website#1956]
https://www.kubeflow.org/docs/azure/authentication/

The correct way to edit external firewall is to run:
kubectl edit -n istio-system svc/istio-ingressgateway

And add:
  loadBalancerSourceRanges:
  - 10.0.0.0/8
for internal LB
or
  loadBalancerSourceRanges:
  - 130.211.204.1/32
  - 130.211.204.2/32
for external LB

So it would look like this:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 130.211.204.1/32
  - 130.211.204.2/32

After saving the file, the loadBalancerSourceRanges item will be moved up in the file.

**Comment by berndverst** [comment]
Makes sense to me since Kubeflow cannot be installed without Istio. @knlp would you like to make the PR to the page and tag me for review?

https://github.com/kubeflow/website/blob/master/content/en/docs/azure/authentication.md

**Comment by 8bitmp3** [comment]
Hi @knlp, just checking if there's been any progress - did you decide to make a pull request as @berndverst suggested? Thanks!

/assign @berndverst

**Comment by berndverst** [comment]
I'll update the docs and will close this out.
