### ISSUE TITLE
Dead links in Visualize Results in the Pipelines UI

### ISSUE THREAD

**Issue by hayato-maki** [kubeflow/website#1966]
The following links in [Visualize Results in the Pipelines UI](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/#introduction), Section **Source of examples on this page** are dead, maybe because of https://github.com/kubeflow/pipelines/pull/2161

- The [tfma component](https://github.com/kubeflow/pipelines/blob/master/components/dataflow/tfma/src/model_analysis.py) which writes out the data for the web-app viewer.

- The [dataflow predict component ](https://github.com/kubeflow/pipelines/blob/master/components/dataflow/predict/src/predict.py)which writes out the data for the table viewer.

https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/

**Comment by janeman98** [comment]
Thanks @hayato-maki for reporting this.
It seems this is already reported in issue #1687 and @joeliedtke is working on this. 

/assign @joeliedtke
