### ISSUE TITLE
[GCP] Document no UI Deployment story for KF 1.1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1968]
There are currently no plans to support Click To Deploy for Kubeflow 1.1 on GCP.
So as part of the Kubeflow 1.1. release we should update the website documentation to point people to deploy using the CLI.

**Comment by Swikar** [comment]
You mean delete "Deploy using UI" section completely from doc? https://www.kubeflow.org/docs/gke/deploy/deploy-ui/

**Comment by jlewi** [comment]
Docs have been updatedd.
https://master.kubeflow.org/docs/gke/deploy/deploy-ui/

**Comment by Ark-kun** [comment]
What was the main reason for removing this functionality? Was it still working at the point of deletion?
