### ISSUE TITLE
"NOVOPRIME" UI seen after kubeflow deploy finish

### ISSUE THREAD

**Issue by linpingta** [kubeflow/website#1973]
Hi guys,

I try to deploy kubeflow with the tutorial https://www.kubeflow.org/docs/gke/deploy/deploy-cli/ ,  after I run "kfctl apply -V -f ${CONFIG_FILE}" and finally I see "Applied the configuration Successfully!",  then I wait half an hour and try to visit "https://<KF_NAME>.endpoints.<project-id>.cloud.goog/" as tutorial described.

However, when I visit  my url, "http://chutkubeflow.endpoints.tchu-test.cloud.goog/Account/Login?ReturnUrl=%2F", I see a logo "NOVOPRIME  Log into your account" and ask me to input username/password. There isn't any description about how to input these information in the tutorial, and I try with my google account and not work.

Could you tell me it's normal or not?  or how should I input username/password?  I used a proxy to visit url and I am not sure whether it causes trouble,  thanks.

**Comment by jbottum** [comment]
@linpingta Hi Chu - Thanks for your note.   We need more info i.e. which platform, which version of  Kubeflow, which version of K8s, etc.    thanks.

**Comment by linpingta** [comment]
@jbottum , thanks for your help.

Platform:  Google Cloud Platform
kubeflow version: kfctl v1.0.2-0-ga476281
k8s version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compile
r:"gc", Platform:"linux/amd64"}

please tell me if not enough

**Comment by jbottum** [comment]
@linpingta Hi, I dont think that we are formally support KF on K8s 1.18.   Can you use K8s 1.15 or 1.16 ?

**Comment by linpingta** [comment]
Actually, I don't configure k8s version, I just configure step by step as https://www.kubeflow.org/docs/gke/deploy/deploy-cli/ described, could you tell me how to change the version of k8s?

**Comment by linpingta** [comment]
Hi @jbottum , I find I am wrong about URL, because it should be "https://chukubeflow.endpoints.tchu-test.cloud.goog" instead of "https://chutkubeflow.endpoints.tchu-test.cloud.goog",  however, when I visit the new url, it tells "the site can't be reached".

And I try to "curl -k https://chukubeflow.endpoints.tchu-test.cloud.goog -v" , it tells :

    * Rebuilt URL to: https://chukubeflow.endpoints.tchu-test.cloud.goog/
    * Could not resolve host: chukubeflow.endpoints.tchu-test.cloud.goog
    * Closing connection 0

Any suggestion for this problem?

**Comment by linpingta** [comment]
it seems my problem, I try with a new oAuth and a new app, it works now, thanks.
