### ISSUE TITLE
Missing how to connect to Pipeline REST API for MiniKF on GCP

### ISSUE THREAD

**Issue by finalspy** [kubeflow/website#1978]
I followed the tutorial to install MiniKF on GCP : 
https://www.kubeflow.org/docs/started/workstation/minikf-gcp/

Hoping to be able to try the Pipelines REST API in V1.0 but unfortunately this part is missing in the documentation and I can't get it to work. 

Please could you help on this by adding some documentation ?

**Comment by jbottum** [comment]
@cspavlou Hey Chris, could you please comment on this?

**Comment by 8bitmp3** [comment]
(Just assigning this to committers from `docs/started/workstation`, so we don't have unassigned Issues - this should hopefully help with tracking and stale Issues)

/assign @alfsuse @jlewi @RFMVasconcelos

**Comment by alfsuse** [comment]
I  wonder if we need a small section around how to use pipeline API common to all the various deployment. Something on the line [this](https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/)  but specifically for API only... I can create a Jupyter notebook and some step-by-step scripts/doc that can be referenced in other pages and used directly by the user into the environment (MiniKF,Minikube etc..) as a sort of playground. What do you think @8bitmp3 @jlewi ? If you're okay I'll open a PR and will work in this starting from next week,

**Comment by jlewi** [comment]
The KFP folks would be the best people to talk to about this.
