### ISSUE TITLE
Docs pointing at FEAST

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#1981]
We should probably add a link in our docs pointing people at FEAST for a feature store.

One place this could go would be under:
https://www.kubeflow.org/docs/components/

We could either create a new sub page for it or we could just add a link to the FEAST docs on
https://www.kubeflow.org/docs/components/misc/

/assign @woop

**Comment by woop** [comment]
Thanks for creating this. Just adding a comment so that I can be assigned.

**Comment by jlewi** [comment]
@woop If you send me a PR adding yourself to 
https://github.com/kubeflow/internal-acls/blob/6451842c1a35ff4794dfe26bcfb02587e252edf9/github-orgs/kubeflow/org.yaml#L230

You can join the Kubeflow ORG so issues can be assigned to you.

**Comment by woop** [comment]
> @woop If you send me a PR adding yourself to
> https://github.com/kubeflow/internal-acls/blob/6451842c1a35ff4794dfe26bcfb02587e252edf9/github-orgs/kubeflow/org.yaml#L230
> 
> You can join the Kubeflow ORG so issues can be assigned to you.

Created here: https://github.com/kubeflow/internal-acls/pull/259

**Comment by imskr** [comment]
@jlewi If no one is working. I can work on this!

**Comment by woop** [comment]
> @jlewi If no one is working. I can work on this!

@imskr I've started working on this, but happy to collaborate if you want. I'm on the Kubeflow Slack if you want to discuss.

**Comment by woop** [comment]
Hey @jlewi, I've submitted #2009. Is that what you had in mind?

**Comment by jlewi** [comment]
@woop yes.
