### ISSUE TITLE
NVIDIA Tesla K80 Accelerators not mentioned in the main Deploy via CLI webpage

### ISSUE THREAD

**Issue by yashjakhotiya** [kubeflow/website#1987]
The default GCP configuration needs NVIDIA Tesla K80 Accelerators and zones which provide this accelerator need to be selected. This info is not mentioned in the main Deploy via CLI webpage and is in the Customizing Kubeflow on GKE webpage. Even though a user does not wish to customize their deployments, they need to know this info.

**Comment by 8bitmp3** [comment]
(Just assigning this to folks from GCP from `docs/gcp/OWNERS` for formality so we don't have unassigned Issues - hope this helps with tracking and stale Issues)

/assign @rmgogogo @Bobgy @joeliedtke

**Comment by rmgogogo** [comment]
"The default GCP configuration needs NVIDIA Tesla K80 Accelerators and zones which provide this accelerator need to be selected. "

I may didn't get the meaning. Would you detail more?
GPU is optional to KFP. If KFP user workload wants GPU, then the cluster can have GPU node pool.
https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/gpu/gpu.ipynb

**Comment by Bobgy** [comment]
already added this information: https://www.kubeflow.org/docs/gke/deploy/deploy-cli/
