### ISSUE TITLE
Wrong or outdated setting (Authorized domains) in GKE guide

### ISSUE THREAD

**Issue by gindeleo** [kubeflow/website#199]
The [GKE getting started guide](https://www.kubeflow.org/docs/started/getting-started-gke/) describes an `Authorized domains` field in the consent screen section (see last point):

Set up your OAuth consent screen:
- Configure the consent screen.
- Under Email address, select the address that you want to display as a public contact. You must use 
- either your email address or a Google Group that you own.
- In the Product name box, enter a suitable name like kubeflow.
- Under **Authorized domains** enter  `<project>.cloud.goog`

However the GCP [consent screen](https://console.cloud.google.com/apis/credentials/consent) section does not have a `Authorized domains` field.

**Comment by sarahmaddox** [comment]
Thanks @gindeleo you're right - the **Authorized domains** field doesn't appear by default. I've added a comment on issue #177, which reports the same problem. I'll mark this issue as a duplicate of that one, since that one is older and has more comments.

**Comment by sarahmaddox** [comment]
Duplicate of #177
