### ISSUE TITLE
Troubleshooting guide directs to delete the wrong thing

### ISSUE THREAD

**Issue by mmwebster** [kubeflow/website#1997]
In [troubleshooting instructions for deleting the GKE Certificate](https://www.kubeflow.org/docs/gke/troubleshooting-gke/#gke-certificate-fails-to-be-provisioned), the listed command is `kubectl -n istio-system delete ingress envoy-ingress`, rather than `kubectl -n istio-system delete managedcertificate gke-certificate`

**Comment by janeman98** [comment]
Thanks @mmwebster for submitting this issue.
/cc @abhi-g

**Comment by 8bitmp3** [comment]
Thanks @mmwebster !

/assign @Bobgy

**Comment by Bobgy** [comment]
@8bitmp3 let's address this separately.
/assign @jlewi 
Can you take a look at this issue? I'm not familiar with the reported problem.
