### ISSUE TITLE
[IBM cloud] provides doc on how to secure kubeflow deployment

### ISSUE THREAD

**Issue by shawnzhu** [kubeflow/website#2000]
The default deployment via `kfctl_ibm.yaml` will result a gateway exposed via HTTP instead of HTTPS. while there is method to make HTTPS possible with also other tweaks to achieve a secure multi-tenant setup, including:

* [Direct encrypted traffic from IBM Cloud Kubernetes Service Ingress to Istio Ingress Gateway](https://istio.io/latest/blog/2020/alb-ingress-gateway-iks/)
* [Be able to authenticate user against GitHub](https://github.com/kubeflow/manifests/issues/1201)

I've gone through a number of steps to secure the gateway of kubeflow with multi-tenant setup, want to share the outcome about

**Comment by janeman98** [comment]
Thanks @shawnzhu for submitting issue. 
Will you be interested in submitting a PR to add such info?

**Comment by shawnzhu** [comment]
> Will you be interested in submitting a PR to add such info?

Yes, was going to create a PR soon

**Comment by shawnzhu** [comment]
Things in my mind:

1. [ ] expose kubeflow dashboard via HTTPS by ingress gateway
1. [ ] authenticate kubeflow user via [IBM Cloud AppID](https://cloud.ibm.com/catalog/services/appid) (which will simplify the installation process with more flexibility) instead of dex (documented path)
1. [ ] uses ICR - #2046 

@adrian555 @animeshsingh any comments?

**Comment by 8bitmp3** [comment]
Hey @shawnzhu, do you know what is still outstanding after we worked on https://github.com/kubeflow/website/pull/2071 (merged)? If nothing, can you please close this Issue? Thanks!

**Comment by shawnzhu** [comment]
closed by #2071
