### ISSUE TITLE
[gcp] granting users to kubeflow permission doc can hardly be found

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/website#2003]
Here's the doc
https://www.kubeflow.org/docs/gke/customizing-gke/#add-users-to-kubeflow

IMO, it should probably belong to a doc by itself to make sure people don't miss it.

**Comment by 8bitmp3** [comment]
Hey @Bobgy, do you think the _Add Users to Kubeflow on GKE_ section deserves its own page, such as _Authenticating Kubeflow to GCP_, which lives here: https://www.kubeflow.org/docs/gke/authentication/? I ran "add users to kubeflow" in the internal search powered by Google and there was nothing on page 1:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19637339/85183261-01454c00-b283-11ea-816b-7937934b3a24.png">

**Comment by Bobgy** [comment]
Yes, I agree. Probably the section itself is too little for a standalone page right now, but maybe we can find more content sitting together over time and we may retitle that article.

Suggestions:
1. We have a standalone page for introducing adding users to kubeflow
2. Put a link in next steps sections of both https://www.kubeflow.org/docs/gke/deploy/deploy-ui/#next-steps and https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#next-steps
