### ISSUE TITLE
Install Kubeflow AWS Instructions Missing Key Information

### ISSUE THREAD

**Issue by ctrahey** [kubeflow/website#2005]
https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

This page mentions setting `$AWS_CLUSTER_NAME`, but my research shows that more is necessary to get Kubeflow to play nicely with EKS. Specifically, the `metadata.name` field in the applied yaml must exactly match the EKS cluster name, in order for the installation to understand that the cluster is indeed an EKS cluster, even if the `$AWS_CLUSTER_NAME` variable is properly set (in fact, as of `v1.1-rc.0` of kfctl, that variable is not referenced in the source code).

This is either a simple documentation issue, or else the code could be updated to allow the cluster name to be specified dynamically.

**Comment by ctrahey** [comment]
More specifically, `metadata.name` is passed to [this AWS API url](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html) (via the AWS Go SDK). I'm not certain if that mean an exact match, or if some mutation happens along the way.

**Comment by ctrahey** [comment]
[Here is a Slack thread](https://kubeflow.slack.com/archives/CKBA5D0MU/p1591907416318600) with a little more context. 
Also adding this to improve the discoverability of the solution for any searchers:

Ensuring that `metadata.name` is the same as your EKS cluster name solves this error:
```
Code 500 with message: coordinator Apply failed for aws:  (kubeflow.error): Code 400 with message: IAM for Service Account is not supported on non-EKS cluster
```

**Comment by PatrickXYS** [comment]
Thanks for proposing the issue, I'll help here. 

/assign

**Comment by Jeffwan** [comment]
This is reasonable request, we can simplify this part for sure.

**Comment by 8bitmp3** [comment]
@Jeffwan @PatrickXYS is there anything that can be done by your team soon from the AWS side or do you want to put this on hold? Thanks 👍
