### ISSUE TITLE
Deploying Kubeflow: how to without OAuth?

### ISSUE THREAD

**Issue by wardVD** [kubeflow/website#2033]
There are multiple mentions of not having to use OAuth for setting up Kubeflow, but step 7 on [this page](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) does not give you an alternative if you haven't done this...

![image](https://user-images.githubusercontent.com/2136274/87013504-0a16a700-c1cb-11ea-914e-fd3827d91bf9.png)

**Comment by Bobgy** [comment]
"not having to use OAuth for setting up Kubeflow" is no longer supported
