### ISSUE TITLE
Deploying microk8s v1.18 kubeflow for remote connections

### ISSUE THREAD

**Issue by tomalbrecht** [kubeflow/website#2035]
It took some time for me to find a solution. Maybe you would like to extend the documentation? I'd do it myself, but I am not up to date with web-development.

Let's say I have a machine with GPU I want to install microk8s (v1.18) with kubeflow enabled on. This machine should work as a "server" and accept incoming traffic on kubeflow dashboard. Microk8s now has a way to configure this - even it's not yet documented. It's easy to set up, if you know what to do. I think this information can help other people, so it should be integrated into the documentation somehow.

You can find the steps here: https://github.com/ubuntu/microk8s/issues/1366#issuecomment-654411307

**Comment by DavidSpek** [comment]
This seems to be related to Charmed Kubeflow from Canonical. Maybe you can open up an issue on their GitHub for them to add it to their documentation?
https://github.com/juju-solutions/bundle-kubeflow
https://microk8s.io/docs/addon-kubeflow

**Comment by tomalbrecht** [comment]
See the solution here: https://github.com/ubuntu/microk8s/issues/1366#issuecomment-654411307
