### ISSUE TITLE
Contradiction in supported k8s versions

### ISSUE THREAD

**Issue by linkvt** [kubeflow/website#2042]
Hi,

there documentation of the supported k8s versions is contradictory: https://www.kubeflow.org/docs/started/k8s/overview/

It says
> Kubeflow does not work on Kubernetes 1.16.

But shows kubeflow being usable up to 1.18 in the table below.

Thanks

**Comment by jacquev6** [comment]
The commit introducing the inconsistency is https://github.com/kubeflow/website/commit/e6af138fab10786a95246b05fea3cd0c62415897. Its message states that "Kubeflow 1.0 is
compatible with Kubernetes 1.16".

**Comment by 8bitmp3** [comment]
@linkvt Thanks for bringing this up. Just saw this, I'm relatively new here.

It appears to have no known issues, is compatible, but not validated by CI: https://github.com/kubeflow/website/pull/1933#issuecomment-625622178

> Compatible (no known issues): No known issues on deploying this Kubeflow release on the specific k8s version, but this is not validated by CI.

Perhaps, rephrasing "Kubeflow does not work on Kubernetes 1.16" is due?

Also, updating that sentence can help resolve similar issues, such as 
https://github.com/kubeflow/website/issues/2130
https://stackoverflow.com/questions/63261483/kubeflow-1-0-on-kubernetes-1-16-compatibility

WDYT @Bobgy @jacquev6 @yanniszark @jlewi ?

Thanks all!

/assign @yanniszark @8bitmp3 @Bobgy

**Comment by Bobgy** [comment]
FYI, at least KFP caching won't work with 1.18 in KF 1.1.
The next KFP release 1.0.1 will fix the issue

**Comment by Bobgy** [comment]
Sounds good, we should say 1.16 is supported now

**Comment by Bobgy** [comment]
hmmm, hold on the doc is asking about k8s existing deployment, @swiftdiaries @krishnadurai do you have any insights about this?

**Comment by swiftdiaries** [comment]
KF is supported on 1.16 with the both the vanilla k8s configs

**Comment by 8bitmp3** [comment]
@Bobgy I can open a PR for https://www.kubeflow.org/docs/started/k8s/overview/ (https://github.com/kubeflow/website/blob/master/content/en/docs/started/k8s/overview.md)

Current docs (note the out of date status):

```
...
{{% alert title="Out of date" color="warning" %}}
This guide contains outdated information pertaining to Kubeflow 1.0. This guide
needs to be updated for Kubeflow 1.1.
{{% /alert %}}

...

* The recommended Kubernetes version is {{% kubernetes-tested-version %}}.
  Kubeflow has been validated and tested on Kubernetes
  {{% kubernetes-tested-version %}}.
  - Your cluster must run at least Kubernetes version
    {{% kubernetes-min-version %}}.
  - Kubeflow **does not work** on Kubernetes
    {{% kubernetes-incompatible-versions %}}.
...
```

1. Do we need a new Hugo shortcode name for 1.16 (https://github.com/kubeflow/website/blob/master/README.md#using-hugo-shortcodes)
- I couldn't find it https://github.com/kubeflow/website/tree/master/layouts/shortcodes
- or maybe we remove the reference to 1.16? ("~~Kubeflow **does not work** on Kubernetes~~")

2. The table says v1.16 has "no known issues" - should we change this to "compatible"?

<img width="700" alt="image" src="https://user-images.githubusercontent.com/19637339/92329651-b278a880-f060-11ea-9348-556dd7e7718c.png">

Thanks!

**Comment by Bobgy** [comment]
@8bitmp3 Thanks a PR will be helpful!

Yes, I think we should change 1.16 to compatible.
I don't think we can make a recommendation of k8s version for all platforms (each platform might be different), so probably there isn't a need to create a shortcode.

**Comment by 8bitmp3** [comment]
Hi @linkvt I think https://github.com/kubeflow/website/pull/2186/files should resolve this issue 👍 If so, can you close it? If there're more questions, don't hesitate to ask/reopen!

**Comment by linkvt** [comment]
Thanks, yes this looks better!

There is still one big general thing annoying us a lot and that is the really bad support of officially supported Kubernetes versions. I know that this is a larger topic and ofc don't want this fixed here but just want to say this:

How can it be that such a popular project is not able to give an answer about the compatibility to the current [three officially supported versions](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions) 1.17, 1.18 and 1.19.
I personally would never state that my product/project has "no known issues" as this basically means: Feel free to do the testing yourself as we don't do it.

I completely understand that kubeflow is rather targeted at cloud kubernetes instances which usually have older k8s versions available, but not giving compatibility for a single officially supported version like 1.17 makes it a harder choice for vanilla on-prem solutions.
I appreciate the work done in this project but this is the only project I know/use with a k8s support policy like this and I don't understand why.

Thanks again @8bitmp3 for the fix, this _rant_ was not directed at you but maybe one of the few major kubeflow contributors also referenced in this issue will think about this problem.
