### ISSUE TITLE
Our blog / additional resources page needs restructuring

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#205]
Our blog is currently at this location:
https://www.kubeflow.org/blog/

And has the heading "Additional Resources - Blog, Talks & Videos".

We should restructure this section of the site, so that:
1) The current page, "Additional Resources - Blog, Talks & Videos", allows us to distinguish between (a) the blog, which is time-stamped and (b) other resources, which are not time-stamped.

2) The blog should rprominently show the date of each blog post - preferably in the URL, but otherwise prominently on the page.

**Comment by abhi-g** [comment]
I completely agree that we need to redo the Kubeflow blog page to be more like Blog  with time-stamped posts.

**Comment by abhi-g** [comment]
+1 to comments. I still need to figure out how to enable comments with Hugo. And, we'd need to setup some spam filtering.

**Comment by pdmack** [comment]
https://utteranc.es/ looks interesting. Basically the comments would become GitHub issues in our website repo?

`When Utterances loads, the GitHub issue search API is used to find the issue associated with the page based on url, pathname or title. If we cannot find an issue that matches the page, no problem, utterances-bot will automatically create an issue the first time someone comments.`

**Comment by abhi-g** [comment]
that sounds nice! I am still concerned about spam posts/comments (regardless of whichever tool we use). Any thoughts?

**Comment by chrisheecho** [comment]
Are we planning to separate out Blog, Talk,Videos or just all in one page?

**Comment by sarahmaddox** [comment]
I've copied the suggestion of adding comments to issue [#290](https://github.com/kubeflow/website/issues/290).

The other aspects of this issue (#205) are complete. The "Additional Resources" page is now called just "Blog" and the blogs are time-stamped.

I'm therefore closing this issue.

/close
