### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by rajivsam** [kubeflow/website#2053]
https://www.kubeflow.org/docs/components/metadata/

Step 2 for installing the metadata component is incomplete. Please update and provide the complete commands. Right now it is:
cd manifests/metadata
kustomize build overlays/db | kubectl apply -n kubeflow -f -

Not sure what follows after "... kubeflow-f -"

**Comment by jbottum** [comment]
Hi @rajivsam which environment are deploying Kubeflow into i.e. AWS, GCP, on-prem ?
