### ISSUE TITLE
Update AWS installation docs for v1.1.0

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#2061]
We want to roll out some doc changes to adopt latest manifests for v1.1.0 release. 

- [x] #2014 
- [x] #2026 
- [x] #2063 
- [x] Updates Installation guidance to use latest v1.1-branch manifests and kfctl

**Comment by PatrickXYS** [comment]
The issue will be addressed by this PR: https://github.com/kubeflow/website/pull/2015
