### ISSUE TITLE
[IBM] Update the multi-user instructions

### ISSUE THREAD

**Issue by adrian555** [kubeflow/website#2069]
The current multi-user instructions need to be updated.

1) the dex configmap example does not work as is, could be due to the format.
2) the explanation of using `localhost:8080` as the URL.
3) in long run, we should use IBM backed ID to authenticate.

For release 1.1, we should at least finish 1) and 2).

**Comment by adrian555** [comment]
cc @animeshsingh

**Comment by animeshsingh** [comment]
also make multi-user Pipelines a key focus from docs perspective

**Comment by shawnzhu** [comment]
> the explanation of using localhost:8080 as the URL.

I will document how to enable HTTPS under #2000 so that it can support the KFP multi-user requirement for using a secure public endpoint.

**Comment by shawnzhu** [comment]
@adrian555 My plan in order:

1. [ ] cover the HTTPS setup plus dex updates #2071
1. [ ] document requirement brought up by KFP multi-user feature.
1. [ ] prefer IBM Cloud AppID to Dex - involve changes to kubeflow/manifests
