### ISSUE TITLE
Deploy using MiniKube on Linux

### ISSUE THREAD

**Issue by abhishekvermasg** [kubeflow/website#2070]
https://www.kubeflow.org/docs/started/workstation/minikube-linux/

This instruction gives error and yet, no workarounds or anything helpful has been written here regarding this.

kfctl apply -V -f ${CONFIG_URI}

**Comment by jbottum** [comment]
Hi @abhishekvermasg did you get this resolved ?  Have you tried MiniKF,  https://www.arrikto.com/s/6c15b060-62f8-4c9b-9364-8e2a6b4ade53/?submissionGuid=fd86e035-2011-4de4-a090-ad2c76c0cf74
