### ISSUE TITLE
Jupyter notebooks should be moved under components

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#2075]
Right now jupyter-notebooks appear as top level item in the left hand navigation.

All the other applications are under the components of Kubeflow section.

Is there a reason to treat notebooks differently? 

Can we move them into the components of kubeflow sections.

/assign @kimwnasptd 
/assign @StefanoFioravanzo 

@kimwnasptd and @StefanoFioravanzo as the owners of notebooks could you please look into fixing this? Likewise could you please create an appropriate OWNERs file.

**Comment by kimwnasptd** [comment]
I'll take a look on this one.

@jlewi wrt the OWNERS file, did you mean to create one kubeflow/website or in kubeflow/kubeflow? With a quick glance on kubeflow/website I don't see any other OWNERS files.

**Comment by jlewi** [comment]
I mean in kubeflow/website you should create an OWNERs file to cover the jupyter docs and reflect ownership of those docs.

**Comment by jlewi** [comment]
Still relevant.
Related #2293

**Comment by thesuperzapper** [comment]
/close
This move has happened with the work related to https://github.com/kubeflow/website/issues/2465
