### ISSUE TITLE
Why are pipelines docs not under components?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#2076]
The pipelines docs appear to be split

There is a top level page for pipelines and then there is a page under components of kubeflow?

Could we move all of the pipelines docs under components of Kubeflow so that it is more consistent with how we handle the other applications in Kubeflow?

/assign @joeliedtke 
/cc @Bobgy

**Comment by Bobgy** [comment]
I don't think we have bandwidth to handle this within current timeframe.
There are links from other websites that point to documentation here too

**Comment by jlewi** [comment]
@Bobgy I believe you can create redirects for the old pages 
https://github.com/kubeflow/website/blob/master/content/en/_redirects

I don't think it is blocking

/cc @joeliedtke
