### ISSUE TITLE
Doc for running TensorBoard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#208]
We should have a component page that explains how to run TensorBoard.

We should explain how to connect to it
  1. Using kubectl port-forward
  1. IAP using GKE.

**Comment by theofpa** [comment]
Tensorboard is an istio virtualservice:

`$ kubectl describe virtualservice tensorboard -n kubeflow | grep Prefix
        Prefix:  /tensorboard/tensorboard/
$ kubectl get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP
istio-ingressgateway   LoadBalancer   <intenal-ip>   <external-ip>
`
so visiting http://<external-ip>/tensorboard/tensorboard/ works

More dashboards are available this way, we can create a list of them in a page for operations as part of #753
