### ISSUE TITLE
Remove Kubeflow 0.6 section in Authenticating Kubeflow to GCP?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/website#2091]
https://www.kubeflow.org/docs/gke/authentication/

Shall we remove the section about "Kubeflow v0.6 and before: GCP service account key as secret"?
I think it's been a while, keeping it on the page is only getting confusing. We can just mention workload identity now.

/assign @jlewi 
What do you think?

**Comment by jlewi** [comment]
@Bobgy  LGTM
