### ISSUE TITLE
Link on this website no longer supported

### ISSUE THREAD

**Issue by ShaneZhong** [kubeflow/website#2095]
https://master.kubeflow.org/docs/gke/deploy/deploy-ui/

**Comment by 8bitmp3** [comment]
@anton-wundeman For Kubeflow 1.0, the link to deploying with UI is: https://v1-0-branch.kubeflow.org/docs/gke/deploy/deploy-ui/ (you can switch branches in the docs to find the guides to older KF versions).

As far as I know, from Kubeflow 1.1:

>... deploying Kubeflow via the click to deploy web application is no longer supported. Please use kustomize and kpt to deploy Kubeflow.

(It should say that in the docs).

Similar Issue https://github.com/kubeflow/website/issues/2103

/assign @Bobgy @8bitmp3 @RFMVasconcelos 
cc @jlewi

**Comment by jlewi** [comment]
Like the docs says, deploing with the UI is no longer supported.
