### ISSUE TITLE
Deploy using UI

### ISSUE THREAD

**Issue by anton-wundeman** [kubeflow/website#2103]
https://www.kubeflow.org/docs/gke/deploy/deploy-ui/

The link is broken:
https://master.kubeflow.org/docs/gke/deploy/deploy-ui/deploy-cli.md

**Comment by 8bitmp3** [comment]
Hi @anton-wundeman Thanks for bringing this up, appreciate it!

/assign @Bobgy @8bitmp3 @RFMVasconcelos

**Comment by 8bitmp3** [comment]
@anton-wundeman For Kubeflow 1.0, the link to deploying with UI is: https://v1-0-branch.kubeflow.org/docs/gke/deploy/deploy-ui/ (you can switch branches in the docs to find the guides to older KF versions).

As far as I know, from Kubeflow 1.1:

>... deploying Kubeflow via the click to deploy web application is no longer supported. Please use kustomize and kpt to deploy Kubeflow.

Similar Issue https://github.com/kubeflow/website/issues/2095. 

Does this resolve the Issue?

**Comment by jlewi** [comment]
@8bitmp3 Deploying with the UI is no longer supported even for older versions.

The link to "deploy using kustomize and kpt" appears to link to https://www.kubeflow.org/docs/gke/deploy/deploy-cli/ which is correct; fixed by #2119
