### ISSUE TITLE
Need OWNERs file in subdirectories of docs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#2109]
Most of the subdirectories in docs  lack owners files
https://github.com/kubeflow/website/tree/master/content/en/docs

Each of these directories should probably have an OWNERs file indicating who is responsible for the docs.

@8bitmp3 and @RFMVasconcelos could you help drive this?

**Comment by 8bitmp3** [comment]
@jlewi 💯

Just to be clear: we should create an `OWNERS` file in each sub-directory (without a suffix/extension). This will be similar to what we've got in `/kubeflow/kubeflow/blobl/master/OWNERS`, such as:

```
# We want to rely on fine grained OWNERs files.
  - jlewi
  - [github_handle2]
  - [github_handle3]
```

- To implement this, we can have one draft PR that encapsulates all `OWNERS` file additions to [`/kubeflow/website/docs`](https://github.com/kubeflow/website/tree/master/content/en/docs)
- In it, we can tag each of the `docs` original creators and contributors per org (independent, SaaS, or cloud provider, for example)
- If they confirm they or someone else is in charge of the docs - that'll be 👍 and we push/change the commit(s)

WDYT?

**Comment by RFMVasconcelos** [comment]
Hi @jlewi, @8bitmp3 this looks cool, happy to help drive!

**Comment by jlewi** [comment]
@8bitmp3 However, you want to do it sounds good to me. Breaking it up into many PRs might help so you don't get blocked waiting on the tail end of approvers.

**Comment by 8bitmp3** [comment]
fyi I'm making a comprehensive list of:

- `docs` directories and subdirectories with `OWNERS` files + corresponding (open/closed) PRs
- `docs` directories and subdirectories that should be updated (and a list of potential approvers based on the commit history)

cc @jlewi
