### ISSUE TITLE
service "istiod" not found

### ISSUE THREAD

**Issue by jagadeeshi2i** [kubeflow/website#2117]
I tried following KF docs to install Istio along with kubeflow and it throws the following error: `Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found`. Link: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

**Comment by 8bitmp3** [comment]
Hey @Jeffwan @PatrickXYS @ricoms. Can one of you please take a look at this Issue if you can?

**Comment by PatrickXYS** [comment]
> I tried following KF docs to install Istio along with kubeflow

By default, you only need to install the `kfctl_aws_v1.1.0.yaml` file and istio has already been integrated into the manifest.

Any changes did you make on your side?

**Comment by jagadeeshi2i** [comment]
I was trying to install v1.0.1.

**Comment by jbottum** [comment]
Hi @jagadeeshi2i did you get this resolved?  can we close this issue?

**Comment by summerisc** [comment]
I am seeing the same error using v1.2.0 for installation for on-prem servers, any chance this issue was looked into and had a solution already?
