### ISSUE TITLE
Bug in IBM cloud kubeflow installation

### ISSUE THREAD

**Issue by condaatje** [kubeflow/website#2129]
`kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80` 

as listed at [https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow/#verify-installation](https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow/#verify-installation) returns error:

 `Error from server (NotFound): namespaces "istio-system" not found`

**Comment by condaatje** [comment]
Appears to be from missing istio system. Can close if that sounds right.

**Comment by Tomcli** [comment]
@condaatje https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow/#verify-installation does its job to identify your Kubeflow installation is broken. Do you see any error when you run the `kfctl apply` command?

**Comment by 8bitmp3** [comment]
(Just assigning this to IBMers from `docs/ibm/OWNERS` for formality so we don't have unassigned Issues - this should help with tracking and stale Issues)

/assign @adrian555 @animeshsingh @shawnzhu

**Comment by shawnzhu** [comment]
Out of the step 1 of https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow/#verify-installation

> Check the resources deployed correctly in namespace kubeflow
>    ```kubectl get all -n kubeflow```

What's the output when you run ☝️ command?

**Comment by condaatje** [comment]
Sorry guys just checking back in on this some days later to close the loop - issue was a missing istio installation. Thank you for the help.
