### ISSUE TITLE
Does kubeflow work on 1.16 or not?

### ISSUE THREAD

**Issue by KatyaRuth** [kubeflow/website#2130]
In this doc, you have some conflicting information: https://www.kubeflow.org/docs/started/k8s/overview/

On one line, you say "Kubeflow does not work on Kubernetes 1.16."
However, in the chart below, it states that Kubeflow has no known issues with Kubernetes 1.16. So which is it? Does it not work, or are there no known issues?

It's confusing.

**Comment by 8bitmp3** [comment]
@KatyaRuth Thanks for bringing this up.

It appears to have no known issues, is compatible, but not validated by CI: https://github.com/kubeflow/website/pull/1933#issuecomment-625622178

> Compatible (no known issues): No known issues on deploying this Kubeflow release on the specific k8s version, but this is not validated by CI.

Perhaps, rephrasing "Kubeflow does not work on Kubernetes 1.16" is due - WDYT @jlewi ?

**Comment by 8bitmp3** [comment]
Also, updating that sentence can help resolve similar issues, such as https://stackoverflow.com/questions/63261483/kubeflow-1-0-on-kubernetes-1-16-compatibility

**Comment by 8bitmp3** [comment]
Hi @KatyaRuth I think https://github.com/kubeflow/website/pull/2186/files should resolve this issue 👍 If so, can you close it? If there're more questions, don't hesitate to ask/reopen!
