### ISSUE TITLE
difficult

### ISSUE THREAD

**Issue by aytuns** [kubeflow/website#2134]
steps are difficult for beginners to follow

**Comment by 8bitmp3** [comment]
Hey @aytuns Thanks for raising the Issue here. Can you please provide the links to the docs you used and the general nature of the task(s) you're trying to accomplish with Kubeflow/Kubeflow Pipelines? We'd love to help you and improve the documentation. Cheers!

/assign @8bitmp3

**Comment by alfsuse** [comment]
I can help as well @8bitmp3 feel free to assign me too!
