### ISSUE TITLE
New docs - Installing Kubeflow on-prem behind proxy

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2137]
As discussed in the on-prem WG, we should add docs on how to install Kubeflow behind a corporate proxy. 

Jeff Fogarty shared the following steps:

> Use the below steps to install Kubeflow behind a proxy server.
> 
> Please note that these steps assume Docker, on each kubernetes node, has access through the proxy.  
> 
> 1) Create alias for proxy
> `alias https='https_proxy=https://server:port'`
> 
> 2) Download kfctl
>    `https wget https://github.com/kubeflow/kfctl/releases/download/v1.1.0/kfctl_v1.1.0-0-g9a3621e_linux.tar.gz` extract to /usr/local/bin
> 
> 3) Download the kfdef yaml file kfctl_k8s_istio.yaml
>    `https wget https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_istio_dex.v1.1.0.yaml`
> 
> 4) Download Manifest 
>    `https wget https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz`
> 
> 5) Modify kfctl_k8s_istio.yaml changing the below;
> 
> FROM
> ```
>   repos:
>   - name: manifests
>     uri: https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz
> ```
> TO
> ```
>   repos:
>   - name: manifests
>     uri: file:/absolute/path/v1.1-branch.tar.gz
> ```
> 
> 6) Run build 
> `kfctl build -V -f kfctl_k8s_istio.yaml`
> 
> 7) Run apply
> `kfctl apply -V -f kfctl_k8s_istio.yaml`

I am looking for the right place in the docs to add this. Was hoping to get some suggestions. 

@jlewi @8bitmp3 @Bobgy what do you think?

**Comment by snowneji** [comment]
Hello, I tried the approach shared, but still got the following error and it keeps retrying. I saw a similar error is another issue but it was related to Istio version (1.7.x doesn't work): 

```
WARN[0022] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout498148947": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:266"
WARN[0022] Will retry in 3 seconds.                      filename="kustomize/kustomize.go:267"
```
Then I try to inspect the pods under namespace `cert-manager`, looks the image pulling process was problematic since it tries to pull image from  `Pulling image "quay.io/jetstack/cert-manager-cainjector:v0.11.0"`, and it cannot be completed because I'm under corporate environment:
```
NAME                                           READY   STATUS              RESTARTS   AGE
pod/cert-manager-cainjector-774bd85548-c5k45   0/1     ImagePullBackOff    0          62s
pod/cert-manager-f8f6c65f9-skk54               0/1     ErrImagePull        0          62s
pod/cert-manager-webhook-59fb566ff-9d6tc       0/1     ContainerCreating   0          62s
```

Any ideas to fix this?

**Comment by snowneji** [comment]
Okay, it was caused by our corporate environment blocked most of the public docker registries which were defined in the manifest. I had to write a script to replace all the public registries with internal proxies, which fixed the issue.

**Comment by RFMVasconcelos** [comment]
Thank you for sharing your solution @snowneji and sorry for the lack of reply. Since this thread was for updating docs, which has been done I will close it and expect people to create issues if they face one. 

/close

**Comment by jhattingh** [comment]
@snowneji Do you mind expanding on the script you created to setup the proxy? I'm currently stuck here as well. 

Thanks in advance. :)

**Comment by snowneji** [comment]
Sure, so basically I'm following the above approach except I need to:

1. Fork the repo and work on the branch corresponding to this archive: `https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz`
2. use the following script to replace the public repos by the proxies of your corporate:
```
import os

if __name__ == "__main__":

    for dname, dirs, files in os.walk("./manifests"):
        for fname in files:
            if '.yaml' in fname:
                fpath = os.path.join(dname, fname)
                with open(fpath) as f:
                    s = f.read()
                s = s.replace("quay.io", {INTERNAL_PROXY})
                s = s.replace("gcr.io", {INTERNAL_PROXY})
                s = s.replace("registry-1.docker.io", {INTERNAL_PROXY})
                s = s.replace("us.gcr.io", {INTERNAL_PROXY})
                s = s.replace("nvcr.io", {INTERNAL_PROXY})
                # s = s.replace("docker.io",  {INTERNAL_PROXY})

                

                s = s.replace("argoproj/argoui:v2.3.0", {INTERNAL_PROXY})
                s = s.replace("metacontroller/metacontroller:v0.3.0", {INTERNAL_PROXY})
                s = s.replace("mysql:8", {INTERNAL_PROXY})
                s = s.replace("mpioperator/mpi-operator:latest", {INTERNAL_PROXY})
                s = s.replace("kubeflow/mxnet-operator", {INTERNAL_PROXY})
                s = s.replace("tensorflow/tensorflow:1.8.0", {INTERNAL_PROXY})
                s = s.replace("argoproj/workflow-controller:v2.3.0", {INTERNAL_PROXY})
                s = s.replace("mxjob/mxnet-operator:v1beta1", {INTERNAL_PROXY})
                s = s.replace("$(registry)/kfserving-controller", {INTERNAL_PROXY})
                
             
                with open(fpath, "w") as f:
                    f.write(s)

```

3.  push the changes to your own Github repo and tag the new version, then download the `tar.gz` archive.
