### ISSUE TITLE
Need docs for TFJobs UI

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#214]
_From @jlewi on April 3, 2018 18:33_

Need docs for TFJobs UI.

At a minimum need to specify what URL to use (at lest until we have central UI).

Looks like we need to use tfjobs/ui/

/cc @wbuchwalter 

_Copied from original issue: kubeflow/kubeflow#573_

**Comment by sarahmaddox** [comment]
_From @jlewi on May 26, 2018 18:23_

Looks like the port its listening on is 8080

**Comment by chrisheecho** [comment]
@sarahmaddox this is something that we would definitely like to have for 0.4 Do you think we will be able to do this for 0.4?

**Comment by sarahmaddox** [comment]
@chrisheecho I'm sorry, I'm a little out of touch at the moment due to other priorities. Do you have a date for 0.4. Also do you or @jlewi have some idea of the scope of the docs needed, to help us decide on the size of this task?

**Comment by jlewi** [comment]
@sarahmaddox We will cut 0.4 by mid December. 

The scope is what you mentioned in the initial comment of this issue. So fairly narrow.

**Comment by sarahmaddox** [comment]
Thanks Jeremy. Yes, let's aim to have this doc update done for v0.4.

**Comment by sarahmaddox** [comment]
URL is:
https://<deployment-name>.endpoints.<project>.cloud.goog/tfjobs/ui/
