### ISSUE TITLE
Page "Kind started guide" not found

### ISSUE THREAD

**Issue by jcRisch** [kubeflow/website#2141]
Hi, 

The page "Kind started guide" does not exist anymore ([https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-kind/](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-kind/)) .
The link can be found here: [https://www.kubeflow.org/docs/started/workstation/getting-started-linux/](https://www.kubeflow.org/docs/started/workstation/getting-started-linux/),

**Comment by RFMVasconcelos** [comment]
Hi @jcRisch Thank you for pointing this out. I will create a PR to fix this.

**Comment by jcRisch** [comment]
I wrote [an article](https://medium.com/@jcrsch/end-to-end-kubeflow-installation-on-your-personal-computer-with-kind-baa0d72cf88) on medium describing my KF installation with Kind.
