### ISSUE TITLE
[GCP] Add to troubleshooting timeout waiting for cluster

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#2152]
See: https://github.com/kubeflow/kubeflow/issues/5223#issue-681102888

Users are reporting timeouts waiting for the cluster to bee ready; e.g.

```
kubectl --context=kf-mgmnt wait --for=condition=Ready --timeout=600s  containercluster kf
error: timed out waiting for the condition on containerclusters/kf
```

We should add instructions to the [GCP troubleshooting guide](https://www.kubeflow.org/docs/gke/troubleshooting-gke/) for how to handle that error.

The way to troubleshoot the error is to run

```
kubectl --context ${MGMTCONTEXT} get containercluster -n ${PROJECT}  -o yaml
```

This should provide information on the underlying error about why the cluster can't be created.

**Comment by Ajakhongir** [comment]
When I run following command:
`kubectl --context=$MGMT_NAME --namespace $KF_PROJECT get containercluster -o yam`

I have got this output:
`apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""`
