### ISSUE TITLE
Kubeflow installation steps are not updated with kubeflow v1.1

### ISSUE THREAD

**Issue by arshashi** [kubeflow/website#2164]
Kubeflow installation steps are not updated with kubeflow v1.1. URL: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#notes-on-the-configuration-file
1.  With new kubeflow v1.1 yaml file, there is no existence of the istio-crds and istio-install. and also the default password in static file doesnt exist.  Similarly with Log in with LDAP / Active Directory

This page needs modification as per v.1.1

Notes on the configuration file
Configuring your installation with kfctl_istio_dex.v1.1.0.yaml has a few options you should consider:
Disabling istio installation - If your Kubernetes cluster has an existing Istio installation you may choose to not install Istio by removing the applications istio-crds and istio-install in the configuration file kfctl_istio_dex.v1.1.0.yaml.

Default password in static file configuration for Dex - The configuration file kfctl_istio_dex.v1.1.0.yaml contains a default staticPasswords user with email set to admin@kubeflow.org and password 12341234. You should change this configuration or replace it with a Dex connector.

2. After un-installation also, below webhooks still exists and doesnt get removed as part of kubeflow removal process
kubectl get mutatingwebhookconfigurations katib-mutating-webhook-config
kubectl get validatingwebhookconfigurations katib-validating-webhook-config

**Comment by jbottum** [comment]
@krishnadurai Hey Krishna - Have you seen this issue ?

**Comment by 8bitmp3** [comment]
@jbottum I'll set the assign label to you for now to make sure we don't have a blank "Assignees" section

/assign @jbottum

cc @Bobgy

**Comment by 8bitmp3** [comment]
gently pinging @jbottum 

@Bobgy @RFMVasconcelos we're getting ready for v1.2 - can you recommend someone who can revisit this asap pls? Guide: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#notes-on-the-configuration-file

**Comment by ronytesler** [comment]
any update?

**Comment by Bobgy** [comment]
/cc @kubeflow/arrikto 

Probably one of you might want to take this?

**Comment by thesuperzapper** [comment]
We are unlikely to continue updating the docs for 1.1 at this stage (with 1.3 out).

/close
