### ISSUE TITLE
[Makefile:132: hydrate-kubeflow] Error 1

### ISSUE THREAD

**Issue by ryo-matsuzaka** [kubeflow/website#2166]
At [Deploy using kubectl and kpt](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/), 
when I run `make apply`, then I got the bellow error.

```
./kustomize build --load_restrictor none -o .build/kubeflow-apps ./instance/kustomize/kubeflow-apps
Error: accumulating resources: accumulateFile "accumulating resources from '../../../upstream/manifests/stacks/gcp': read /home/uyorikazatsuma/kubeflow/upstream/manifests/stacks/gcp: is a directory", accumulateDirector: "recursed accumulation of path '/home/uyorikazatsuma/kubeflow/upstream/manifests/stacks/gcp': accumulating resources: accumulateFile \"accumulating resources from '../../pipeline/installs/multi-user': read /home/uyorikazatsuma/kubeflow/upstream/manifests/pipeline/installs/multi-user: is a directory\", accumulateDirector: \"recursed accumulation of path '/home/uyorikazatsuma/kubeflow/upstream/manifests/pipeline/installs/multi-user': accumulating resources: accumulateFile \\\"accumulating resources from 'api-service': read /home/uyorikazatsuma/kubeflow/upstream/manifests/pipeline/installs/multi-user/api-service: is a directory\\\", accumulateDirector: \\\"couldn't make target for path '/home/uyorikazatsuma/kubeflow/upstream/manifests/pipeline/installs/multi-user/api-service': json: unknown field \\\\\\\"env\\\\\\\"\\\"\""
make: *** [Makefile:132: hydrate-kubeflow] Error 1
```

How can I solve this error?
Maybe it is related to [this](https://github.com/kubernetes-sigs/kustomize/issues/2279).

**Comment by Bobgy** [comment]
@ryo-matsuzaka Did you install kustomize 3.2.1?
It seems the kustomize breaking change after that --- "removal of env field support"

**Comment by Bobgy** [comment]
Upstream issue in kubeflow: https://github.com/kubeflow/manifests/issues/538

**Comment by angoothachap** [comment]
@Bobgy Yes, I did use 3.2.1 as in the [documentation](https://www.kubeflow.org/docs/gke/deploy/management-setup/#install-the-required-tools). Do you suggest using a lower version?

**Comment by Bobgy** [comment]
No, that's correct, let me try to reproduce

**Comment by rcarmstrong** [comment]
Experiencing the same issue when running `make apply` for a GCP deployment, specifically when it hits `kustomize build --load_restrictor none -o .build/kubeflow-apps ./instance/kustomize/kubeflow-apps`, I get the following error:

```Error: accumulating resources: accumulateFile "accumulating resources from '../../../upstream/manifests/stacks/gcp': read /home/rarmstrong/kubeflow/deployment/upstream/manifests/stacks/gcp: is a directory", accumulateDirector: "recursed accumulation of path '/home/rarmstrong/kubeflow/deployment/upstream/manifests/stacks/gcp': accumulating resources: accumulateFile \"accumulating resources from '../../pipeline/installs/multi-user': read /home/rarmstrong/kubeflow/deployment/upstream/manifests/pipeline/installs/multi-user: is a directory\", accumulateDirector: \"recursed accumulation of path '/home/rarmstrong/kubeflow/deployment/upstream/manifests/pipeline/installs/multi-user': accumulating resources: accumulateFile \\\"accumulating resources from 'api-service': read /home/rarmstrong/kubeflow/deployment/upstream/manifests/pipeline/installs/multi-user/api-service: is a directory\\\", accumulateDirector: \\\"couldn't make target for path '/home/rarmstrong/kubeflow/deployment/upstream/manifests/pipeline/installs/multi-user/api-service': json: unknown field \\\\\\\"env\\\\\\\"\\\"\""```

Is there a know work around? Thank you.

**Comment by Bobgy** [comment]
This looks exactly like https://github.com/kubeflow/metadata/issues/202

Can you confirm kustomize version by
```
kustomize version
```
Or edit the file in the error message to replace the env field with envs as suggested in above issue

**Comment by thesuperzapper** [comment]
This has been resolved by the new manifests refactor https://github.com/kubeflow/manifests/issues/1777

But google does need to update their distribution docs on the website.

/close
