### ISSUE TITLE
Add requirement of dynamic volume provisioner?

### ISSUE THREAD

**Issue by sirkkalap** [kubeflow/website#2172]
Later at https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ it is stated that "This Kubeflow deployment requires a default StorageClass with a dynamic volume provisioner."

I wonder if this should also be stated in the requirements page: https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements

Or is this just specific to the Kubeflow Deployment with kfctl_k8s_istio ?

**Comment by sirkkalap** [comment]
I am a little bit confused at the end of the https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ page. 

It seems to me that dynamic volume provisioner is after all optional. There seem to be instructions to manually manage PVs instead of dynamic volume provisioner.

Maybe the document could be clarified a bit to make it obvious if DVP is actually a requirement?

**Comment by jbottum** [comment]
@sirkkalap Hi Petri - DVP is valuable for several workflows i.e. Do you expect to use Persistent Volumes for your data (in notebooks).   Where are you deploying i.e. GCP, AWS, other ?

**Comment by 8bitmp3** [comment]
/assign @Bobgy 

(I think @jlewi has previously committed to the doc)

It probably makes sense to add to the minimum requirements/prerequisites that the KF deployment needs a default StorageClass with a dynamic volume provisioner (DVP) - at least in the beginning of `docs/started/k8s/kfctl-k8s-istio/` (and possibly to `https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements`) as @sirkkalap said.

WDYT?

**Comment by jlewi** [comment]
I think there are a couple applications that will dynamically provision a volume. For example the jupyter web app will dynamically provision a PD to use as storage for your notebook server.

The jupyter web app supports the case where you don't have a dynamic provisioner.

**Comment by jlewi** [comment]
@8bitmp3 I would suggest routing this issue to the OWNERs of kfctl-k8s-istio deployment. Is the OWNERs file up to date?

**Comment by 8bitmp3** [comment]
@jlewi The OWNERS should be good for getting started guides (`docs/started/`) - we've recently refreshed it. I don't think the kfctl-k8s-istio guide (`docs/started/k8s/kfctl-k8s-istio/`) contributors - @swiftdiaries, you and @sarahmaddox - are listed there though. Shall we ask @swiftdiaries to look into this issue?

**Comment by jlewi** [comment]
https://github.com/kubeflow/website/tree/master/content/en/docs/started/k8s

Is missing an OWNERs file. We should figure out an appropriate OWNERs file and then route this issue to it.
I'm not an OWNER of this deployment platform.

I think OWNERs are @yanniszark @swiftdiaries

**Comment by 8bitmp3** [comment]
@jlewi OWNERS added. 

@yanniszark @swiftdiaries can you take a look at this issue please? Much obliged

**Comment by 8bitmp3** [comment]
@Bobgy How do you think we should proceed here? The issue is getting stale. Cheers

**Comment by Bobgy** [comment]
/assign @yanniszark @swiftdiaries
Friendly ping again.

@8bitmp3 don't worry, you don't need to make sure everything is fixed. The owners should follow up with these issues at their own schedule
