### ISSUE TITLE
Clarify which versions of Kubernetes are supported

### ISSUE THREAD

**Issue by jpetazzo** [kubeflow/website#2178]
https://www.kubeflow.org/docs/started/k8s/overview/ states that "Kubeflow does not work on Kubernetes 1.16" but then the table below states otherwise.

Given that Kubernetes 1.16 is not maintained anymore (Kubernetes maintains its three latest minor releases, so as of September 2020, that's 1.17, 1.18, and 1.19) what is the recommended Kubernetes version to use Kubeflow?

Thank you!

**Comment by 8bitmp3** [comment]
Thanks for bringing this up @jpetazzo 

/assign @Bobgy @8bitmp3 

cc @jlewi 

@Bobgy You mentioned in https://github.com/kubeflow/website/issues/2042 v1.16 is supported now - how do we go about v1.17, v1.18, and v1.19? Cheers!

Similar issues: https://github.com/kubeflow/website/issues/2130, https://github.com/kubeflow/website/issues/2042

**Comment by 8bitmp3** [comment]
@jpetazzo I think https://github.com/kubeflow/website/pull/2186#event-3769970959 should resolve this issue 👍 If so, can you close it? If there're more questions, don't hesitate to ask/reopen!
