### ISSUE TITLE
Tensorflow training and serving workflow

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#22]
Step-by-step walkthrough of a Tensorflow training and model serving example.
 - Using public datasets available on GCS
 - Using a local dataset.

**Comment by gaocegege** [comment]
Now TF training has two version: v1alpha1 and v1alpha2, and I think we should provide two version for users.

**Comment by sarahmaddox** [comment]
We now have a detailed guide, which links to an end-to-end example:
https://www.kubeflow.org/docs/components/training/tftraining/

I'm going to close this issue, but please do re-open it if there's more work to be done or a specific example that would be useful.

/close
