### ISSUE TITLE
[DOC] Missing minimum system requirements for 1.1

### ISSUE THREAD

**Issue by raphaelauv** [kubeflow/website#2205]
https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements

The Kubernetes Versions 1.1 is not present in the compatibility matrix

**Comment by 8bitmp3** [comment]
Hey @raphaelauv We're having a similar discussion about this here https://github.com/kubeflow/website/issues/2264 and will update by adding a column for KF v1.1.

If this is the same topic, can you close this Issue and contribute to 2264? Thanks a lot!

**Comment by raphaelauv** [comment]
ok , thanks
