### ISSUE TITLE
[no known issues] seldon-core does not work on k8s 1.18

### ISSUE THREAD

**Issue by sakaia** [kubeflow/website#2207]
This is related to **no known issues**.

Following document says **no known issues**. But Kubeflow 1.0 with k8s 1.18 matrix should be **incompatible**
https://github.com/kubeflow/website/blob/master/content/en/docs/started/k8s/overview.md

But seldon-core has reported issues on k8s 1.18 CRD incompatibility

- [(github)seldon-core-operator CRD's incompatible with K8s v1.18 #1675](https://github.com/SeldonIO/seldon-core/issues/1675)
- [(Kubeflow 1.0)Seldon Core Serving](https://v1-0-branch.kubeflow.org/docs/components/serving/seldon/)
- [(Kubeflow 1.1)Seldon Core Serving](https://www.kubeflow.org/docs/components/serving/seldon/#seldon-serving)

**Comment by bdlb77** [comment]
Per https://github.com/SeldonIO/seldon-core/issues/1675 It seems like the fix for Seldon's compatibility with v1.18 is in master and will be shipped in the next release

**Comment by sakaia** [comment]
@bdlb77 kubeflow 1.0  is planned to update seldon-core version to 1.3?

**Comment by bdlb77** [comment]
@sakaia  Ah correct I overlooked this. I apologize. I imagine currently a workaround would be to pull the Kubeflow manifests locally and updated the Seldon component until Kubeflow cuts a release that incorporates the new Seldon release

**Comment by sudivate** [comment]
@cliveseldon @ryandawsonuk

**Comment by DavidSpek** [comment]
This seems to be a duplicate of https://github.com/kubeflow/website/issues/2206. In my comment you can see a pull request I have that works around this issue and a method for you to apply it as well.

**Comment by cliveseldon** [comment]
Yes, we will need to do an update for this. Will try to work on it in next week.
