### ISSUE TITLE
Is application matrix outdated?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/website#2208]
I updated KFP status in application matrix in https://github.com/kubeflow/website/pull/2204. Because, I was removing the outdated banner, so I want to confirm if any application still has outdated information on that page: https://www.kubeflow.org/docs/reference/version-policy/.

@8bitmp3 found owners below
I began looking at the OWNERS in reach of the repos that is not KFP. Here's a list of folks excluding @jlewi:

1. Chainer operator: https://github.com/kubeflow/chainer-operator - https://github.com/kubeflow/chainer-operator/blob/master/OWNERS

> approvers:
>   -  everpeace
>   - disktnk
>  
> reviewers:
>   - gaocegege

2. Feature store: Feast https://github.com/feast-dev/feast - https://github.com/feast-dev/feast/blob/master/OWNERS

> approvers:
>   - davidheryanto
>   - khorshuheng
>   - pyalex
>   - woop
>   - zhilingc
> reviewers:
>   - ches
>   - davidheryanto
>   - khorshuheng
>   - pyalex
>   - woop
>   - zhilingc

3. Hyperparameter tuning: Katib https://github.com/kubeflow/katib - https://github.com/kubeflow/katib/blob/master/OWNERS

> approvers:
>     - gaocegege
>     - hougangliu
>     - johnugeorge
>     - andreyvelich
> reviewers:
>     - sperlingxx
>     - c-bata

4. KFServing: https://github.com/kubeflow/kfserving/blob/master/OWNERS

> approvers:
>   - ellistarn
>   - yuzisun
>   - cliveseldon
>   - animeshsingh
>   - rakelkar
> reviewers:
>   - iamlovingit
>   - ifilonenko
>   - jinchihe
>   - salanki
>   - tomcli
>   - pugangxa
>   - yuzliu

5. https://github.com/kubeflow/metadata/blob/master/OWNERS
6. https://github.com/kubeflow/mpi-operator/blob/master/OWNERS
7. https://github.com/kubeflow/mxnet-operator/blob/master/OWNERS
8. https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/OWNERS
9. https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/OWNERS
10. https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/OWNERS
11. https://github.com/kubeflow/pytorch-operator/blob/master/OWNERS
12. https://github.com/SeldonIO/seldon-core/blob/master/OWNERS
13. https://github.com/kubeflow/tf-operator/blob/master/OWNERS

cc @RFMVasconcelos fyi

_Originally posted by @8bitmp3 in https://github.com/kubeflow/website/pull/2204#issuecomment-696872889_

**Comment by Bobgy** [comment]
@everpeace @disktnk @davidheryanto @khorshuheng @pyalex @woop @zhilingc @gaocegege @hougangliu @johnugeorge @andreyvelich @animeshsingh @tomcli

Can you confirm whether https://www.kubeflow.org/docs/reference/version-policy/ is up-to-date for your application?

also is there a better way we can do this next time, instead of pinging everyone manually

**Comment by woop** [comment]
It's up to date for Feast. I added the documentation and versioning information specifically for 1.1. It didn't exist for 1.0. 

@Bobgy do you know why the [documentation](https://www.kubeflow.org/docs/components/feature-store/overview/) says `This guide contains outdated information pertaining to Kubeflow 1.0. This guide needs to be updated for Kubeflow 1.1.` when it was only released for 1.1?

What can I do to fix that?

**Comment by woop** [comment]
> also is there a better way we can do this next time, instead of pinging everyone manually

Feast and the feature store components will now be owned by the [Feature Store SIG](https://github.com/kubeflow/community/blob/master/OWNERS_ALIASES#L2). 

I was hoping that no "manual pinging" would be necessary since the docs should be up to date. But otherwise you can ping the three of us.

**Comment by 8bitmp3** [comment]
To keep track of things:

/assign @8bitmp3 @Bobgy @RFMVasconcelos

**Comment by 8bitmp3** [comment]
@RFMVasconcelos - if it's up-to-date, shall we remove the banner?

> ...do you know why the documentation says This guide contains outdated information pertaining to Kubeflow 1.0. This guide needs to be updated for Kubeflow 1.1. when it was only released for 1.1?

Thanks @woop !

**Comment by Bobgy** [comment]
Thanks @woop for confirmation!
I've removed the banner in #2204, the banner is just some text in the markdown, you can remove it in PRs.
