### ISSUE TITLE
Deploying Kubeflow Pipelines Standalone on a local cluster with kind, k3s, and k3s on WSL

### ISSUE THREAD

**Issue by gtoonstra** [kubeflow/website#2209]
https://www.kubeflow.org/docs/pipelines/installation/localcluster-deployment/

At the very end after deploying kubeflow, it doesn't list the URL with which the UI can be accessed

**Comment by 8bitmp3** [comment]
@gtoonstra Thanks fro raising the issue here. Can you help provide the paragraph/sentence with a missing URL? cc @alfsuse (the author). Thank you!!

**Comment by alfsuse** [comment]
Hi, @gtoonstra thanks for pointing out I've created a PR to add the method to access the URL at the end of the documentation.
Great catch!

@8bitmp3 I've assigned you to the PR to review it, I've also added an alternative method to access K3s from the host when it runs on WSL2 to make the life of people easier.

**Comment by paveldournov** [comment]
Is the UI URL documentation fixed? I don't see it on https://www.kubeflow.org/docs/pipelines/installation/localcluster-deployment/

**Comment by alfsuse** [comment]
> Is the documentation to get the UI URL to the pipelines console fixed? I don't see it on https://www.kubeflow.org/docs/pipelines/installation/localcluster-deployment/

Great catch  @paveldournov seems we delete it by mistake in the last re-work I've opened up a PR to fix it here https://github.com/kubeflow/website/pull/2292
