### ISSUE TITLE
kubeflow versioning page is not updated to latest one

### ISSUE THREAD

**Issue by arshashi** [kubeflow/website#2211]
please share when are you going to update the version compatibility of kubeflow. as we know kubeflow v1.1 is released and we are waiting for the compatible kubernetes details to be updated along with other notes.
https://www.kubeflow.org/docs/started/k8s/overview/

**Comment by 8bitmp3** [comment]
Thanks for bringing this up @arshashi !

@Bobgy we've recently updated the table (https://github.com/kubeflow/website/pull/2186) - let me know if it'd be safe to remove the banner that says:

> Out of date
> This guide contains outdated information pertaining to Kubeflow 1.0. This guide needs to be updated for Kubeflow 1.1.

Cheers

cc @RFMVasconcelos

**Comment by DavidSpek** [comment]
I am running on Charmed Kubernetes 1.19 and the only 2 issues I have are https://github.com/kubeflow/pipelines/issues/4505 and the issue I have a pull request out for https://github.com/kubeflow/manifests/pull/1558. The pull request fixes the one issue and the issue with the cache deployment doesn't seem to hinder my use of Kubeflow much at the moment.

**Comment by Bobgy** [comment]
We should ask k8s deployment owners
/assign @swiftdiaries @krishnadurai

**Comment by arshashi** [comment]
Few details are not updated w.r.t installation instructions for kf defv1.1

below details are not valid under Notes on the configuration file. I am not sure other details whether any changes are really required.

Disabling istio installation - If your Kubernetes cluster has an existing Istio installation you may choose to not install Istio by removing the applications istio-crds and istio-install in the configuration file kfctl_istio_dex.v1.1.0.yaml

Default password in static file configuration for Dex - The configuration file kfctl_istio_dex.v1.1.0.yaml contains a default staticPasswords user with email set to admin@kubeflow.org and password 12341234. You should change this configuration or replace it with a Dex connector
