### ISSUE TITLE
I am not able to install MiniKF from market place on gcp

### ISSUE THREAD

**Issue by MKRNaqeebi** [kubeflow/website#2216]
https://www.kubeflow.org/docs/started/workstation/minikf-gcp/

I used these instructions and get errors 
![Screenshot from 2020-09-26 12-16-11](https://user-images.githubusercontent.com/15781272/94335962-c462c100-fff8-11ea-8537-5e9045ed7fc8.png)

**Comment by jbottum** [comment]
Hi @MKRNaqeebi, thanks for opening this issue.  Are you using a "free" account with GCP or one that you have to pay for? which region are you trying to deploy into ?   @cspavlou Chris, do you see anything here?

**Comment by MKRNaqeebi** [comment]
@jbottum I have fixed this issue by changing SSD type "standard"
thanks

**Comment by dimara** [comment]
@MKRNaqeebi from the initial comment I see that GCP reported the "strange" error below:
```
Manifest expansion encountered the following errors: Traceback....
Use Python 3 when When using password generation: Resource password.py Resource config
```
Can you somehow reproduce this? Can you please also elaborate on:
> I have fixed this issue by changing SSD type "standard"

What `Disk Type` works and what doesn't? Are you referring to the `Boot` disk or the `Data` one? Are you deploying on a specific zone?
