### ISSUE TITLE
Kubeflow homepage - daily / monthly / all-time visitors

### ISSUE THREAD

**Issue by MaanavD** [kubeflow/website#2220]
Hi! I was interested in stats for how many people (unique) were accessing Kubeflow's homepage over different time periods (daily, monthly, yearly, all time) and was told this was likely the best place to get that information!

I think the community would love to know as well.

Tagging
@joeliedtke

**Comment by jbottum** [comment]
@MaanavD  thanks for your question.  You might bring this up on Tuesday's Community meeting.
