### ISSUE TITLE
Should provide more documentation on backfilling

### ISSUE THREAD

**Issue by bsikander** [kubeflow/website#2259]
I am not sure but documentation is not enough and it is expecting prior knowledge to some of the concepts like backfilling. People with no prior background will have difficulty in understanding what does "Catch Up" means. e.g. If my `start date` and `end date` are in the past and I have `Catch up` enabled with a `Run every` of `1 week`, what is the behavior going to be?

As soon as first run finishes, will the second one start immediately or since I specified `Run ever` to be `1 week`, it will start after a week?

**Comment by joeliedtke** [comment]
Is there a specific doc that this issue refers to?

**Comment by bsikander** [comment]
I created this issue based on the missing informatin that I saw in this page -> https://v0-6.kubeflow.org/docs/pipelines/overview/concepts/run/

**Comment by bsikander** [comment]
I am also willing to contribute but would need guidance since I am new to it.
