### ISSUE TITLE
We need to install both istioctl and asmctl to deploy Kubeflow on GKE

### ISSUE THREAD

**Issue by kelvins** [kubeflow/website#2272]
In the [`Install the required tools`](https://github.com/kubeflow/website/blob/master/content/en/docs/gke/deploy/deploy-cli.md#install-the-required-tools) section, from the [`Deploy using kubectl and kpt`](https://github.com/kubeflow/website/blob/master/content/en/docs/gke/deploy/deploy-cli.md) documentation, we need to install both binaries (`istioctl` and `asmctl`) from the [`Preparing to install Anthos Service Mesh`](https://cloud.google.com/service-mesh/docs/archive/1.4/docs/gke-install-new-cluster#preparing_to_install_anthos_service_mesh) instructions, not only `istioctl`. It would be great to add this information to the documentation.

**Comment by 8bitmp3** [comment]
Thank you @kelvins. Yeah, Anthos Service Mesh is a Google Cloud flavor of Istio Mesh (AFAIK) and part of this larger Anthos platform. 

And, as you mentioned, the official GCP [instructions](https://cloud.google.com/service-mesh/docs/archive/1.4/docs/gke-install-new-cluster#preparing_to_install_anthos_service_mesh
) state that users have to download `istio-X.X.X-asm...tar.gz` and extract it, which "returns" `istioctl` and `asmctl`.

---

Assigning team Google Cloud from `docs/gke`:

/assign @joeliedtke @rmgogogo @Bobgy 

---

Should we just add a few words - "and `asmctl`" - to Step 7:

```diff
- 1.  Follow the instructions from [Preparing to install Anthos Service
-     Mesh](https://cloud.google.com/service-mesh/docs/archive/1.4/docs/- gke-install-new-cluster#preparing_to_install_anthos_service_mesh)
-     to install `istioctl`.
+ 1.  Follow the instructions from [Preparing to install Anthos Service
+     Mesh](https://cloud.google.com/service-mesh/docs/archive/1.4/docs/gke-install-new-cluster#preparing_to_install_anthos_service_mesh)
+     to install `istioctl` and `asmctl`.

    Note, the `istioctl` downloaded from above instructions is specific to Anthos
    Service Mesh. It is different from the `istioctl` you can download on
    https://istio.io/.

<a id="prepare-environment"></a>
## Prepare your environment

1. Log in. You only need to run this command once:
...
```

WDYT? PTAL. Thank you all

**Comment by kelvins** [comment]
Thanks @8bitmp3. Adding "and `asmctl`" to Step 6 is enough, IMO.

**Comment by rmgogogo** [comment]
@Bobgy SG from multi-user case perspective?

**Comment by Bobgy** [comment]
From the doc, it seems `asmctl` is used for validation.
> asmctl: You use asmctl to help validate your security configuration after installing Anthos Service Mesh. (Currently, asmctl isn't supported on GKE on-prem.)

Is it necessary?

**Comment by kelvins** [comment]
I could not find any reference to `asmctl` in the Makefiles (management and kubeflow clusters). I suppose it is being used internally by `istioctl`. When trying to deploy Kubeflow without `asmctl` installed, we were having a problem related to an unsupported `env` key in one of the manifests (unfortunately I don't remember exactly which one). We spent a few minutes debugging it and found that `asmctl` was missing, but the error message was unclear about that.

**Comment by Bobgy** [comment]
I am not sure about
> When trying to deploy Kubeflow without asmctl installed, we were having a problem related to an unsupported env key in one of the manifests (unfortunately I don't remember exactly which one)

because there were previous reports of missing the env key and that's when people downloaded istioctl from opensource website, not from Google. I successfully deployed with just istioctl downloaded from Google documentation.

**Comment by kelvins** [comment]
I'm not sure, but maybe that's what happened to us. If that is the case, feel free to close this issue, please.
