### ISSUE TITLE
MiniKF deployment is no longer available on GCP Marketplace?

### ISSUE THREAD

**Issue by kenly-ldk** [kubeflow/website#2279]
I am trying to follow the article (https://www.kubeflow.org/docs/started/workstation/minikf-gcp/) to launch Minikf on GCP Marketplace, however, it seems that the MiniKF Page (https://console.cloud.google.com/marketplace/details/arrikto-public/minikf?q=minikf&id=1f5eac28-1808-4969-b6fa-2cc231a23f45) is no longer available

![image](https://user-images.githubusercontent.com/61054674/95846417-fce6f680-0d7d-11eb-9c6b-6da464866c5a.png)

A manual search through marketplace also doesn't return any result:

![image](https://user-images.githubusercontent.com/61054674/95846525-1be58880-0d7e-11eb-83f3-c9190230d44f.png)

**Comment by jbottum** [comment]
Hi @kenly-ldk, yes MiniKF is available on GCP, but there appears to be an issue accessing in the marketplace.   We are looking into this and will circle back when resolved.

**Comment by jbottum** [comment]
@cspavlou Chris, will you please take a look at this ?  Thanks1

**Comment by cspavlou** [comment]
Hi @kenly-ldk , thanks for the heads up. Everything should be back to normal now :) 

Thanks again!

**Comment by kenly-ldk** [comment]
Thanks a lot everyone for looking into this so quickly. I can confirm that it is back to normal as well :)
