### ISSUE TITLE
Kubeflow Deployment with kfctl_k8s_istio

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/website#2289]
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

The section Disabling istio installation, is not compatible with the kfctl_k8s_istio.v1.1.0.yaml file as downloaded via kfctl build.

The instructions appear to refer to an older version of this yaml file.

What if one already has Knative installed?
What if one already has Seldon installed?

None of these cases are spelled out in terms of what to comment out in the yaml file.

**Comment by 8bitmp3** [comment]
Thank you for raising this issue @ReggieCarey 👍

@swiftdiaries I think you were one of the last committers to the docs, can you PTAL? 

Link: https://github.com/kubeflow/website/blob/master/content/en/docs/started/k8s/kfctl-k8s-istio.md

cc @Bobgy @jlewi 

/assign @swiftdiaries @Bobgy
