### ISSUE TITLE
How I use the operator?

### ISSUE THREAD

**Issue by dagilgon** [kubeflow/website#2298]
How I use the operator?

**Comment by moficodes** [comment]
The operator runs on KFDef. Just like the kfctl tool. 

We were keeping track of the operator in [this repo](https://github.com/IBM/KubeflowDojo/blob/master/HandsOn/Deployment/kubeflow-on-minikube.md#2-kubeflow-deployment-through-kubeflow-operator) that we use for teaching kubeflow. But I think we will have to update the website.
