### ISSUE TITLE
On Premise documentation 

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/website#230]
When running kubeflow on premise in a multi-cluster environment, it is helpful to have specific instructions 
http access into kubeflow is available by setting the Ambassador service spec.type to NodePort

`kubectl edit svc ambassador -n kubeflow`
From
    `type: ClusterIP`
To
   `type: NodePort`

To revert back to ClusterIP the NodePort value must be removed 
From
`nodePort: 30679`
to `nodePort: `
As well as `type: ClusterIP`

Detailed instruction on running kubeflow behind a corporate proxy would also be helpful
I'm happy to provide detail

**Comment by jtfogarty** [comment]
I believe the correct way to do his is to ` ks param set jupyterhub jupyterHubServiceType NodePort` and then do `ks apply default`

**Comment by sarahmaddox** [comment]
We now have docs for multinode cluster installation:
https://www.kubeflow.org/docs/other-guides/kubeflow-on-multinode-cluster/

/close
