### ISSUE TITLE
Document how to configure/customize JupyterHub

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#232]
We should add docs explaining how users can customize JupyterHub

This comment has some information that could be used as the initial basis
https://github.com/kubeflow/kubeflow/issues/1585#issuecomment-423612976

**Comment by sarahmaddox** [comment]
/assign
/close

Fixed in https://github.com/kubeflow/website/pull/633

See [how to configure a custom notebook](https://www.kubeflow.org/docs/notebooks/custom-notebook/) and related pages.
