### ISSUE TITLE
Broken links in KFServing documentation

### ISSUE THREAD

**Issue by jal06** [kubeflow/website#2329]
A few links are broken in [KFserving documentation](https://www.kubeflow.org/docs/components/serving/kfserving/)
(Return code 404)

Here are the broken links :
Sample notebooks 
    SDK client https://github.com/kubeflow/kfserving/blob/master/docs/samples/client/kfserving_sdk_sample.ipynb

Monitoring
    [Install Metrics, Logging and Tracing](https://knative.dev/docs/serving/installing-logging-metrics-traces/)
    [Accessing metrics](https://knative.dev/docs/serving/accessing-metrics/)
    [Accessing logs](https://knative.dev/docs/serving/accessing-logs/)
    [Debugging performance issue](https://knative.dev/docs/serving/debugging-performance-issues/)

Use SDK
    [Follow the example](https://github.com/kubeflow/kfserving/blob/master/docs/samples/client/kfserving_sdk_sample.ipynb) to use the KFServing SDK to create, patch, roll out, and delete a KFServing instance.

**Comment by 8bitmp3** [comment]
Thank you @jal06 !

/assign @adrian555 @animeshsingh @cliveseldon @ellistarn @ryandawsonuk @Tomcli @yuzisun
(OWNERS for the KFServing docs)

Please take a look 👍

**Comment by tcnt** [comment]
In knative docs several documents are removed as described in https://github.com/knative/docs/pull/2954. (for knative v016)

The links are available in knative v015 like https://knative.dev/v0.15-docs/serving/installing-logging-metrics-traces/
I can change the docs if needed to the v015 version as v015 is also used in https://github.com/kubeflow/kfserving/blob/master/hack/quick_install.sh

The SDK link is something I also noticed on the kfserving readme which I changed in https://github.com/kubeflow/kfserving/pull/1193. I could do the same update for the website.

So please let me know if these changes makes sense, and then I will do the update.

**Comment by tcnt** [comment]
@yuzisun 
Looking a bit further I see there is a reference to https://github.com/knative/docs/pull/2946 where the following is mentioned
_Removed all logging, metrics, tracing docs that refer to or depend on the old monitoring stack, since this was deprecated in 0.14 and is removed in 0.19._
Should we not delete the whole monitoring section in the documentation(website and readme on github kfserving) as it refers to knative monitoring(now deprecated) and we have no control of the external links?
Now it looks like we show kserving monitoring on the website while it is actually knative.

**Comment by yuzisun** [comment]
@tcnt there is already a PR in KFS https://github.com/kubeflow/kfserving/pull/1162 to update the deprecated knative monitoring, how about remove those references from Kubeflow website and direct to  [KFS monitoring section](https://github.com/kubeflow/kfserving#setup-monitoring) ?

**Comment by tcnt** [comment]
@yuzisun I like that idea. Then we still have a reference to monitoring on the website, while maintaining the links in one place at [KFS monitoring section](https://github.com/kubeflow/kfserving#setup-monitoring).

I will look into it tomorrow and make changes for both the monitoring section and sample notebook reference on the website.

**Comment by yuzisun** [comment]
> @yuzisun I like that idea. Then we still have a reference to monitoring on the website, while maintaining the links in one place at [KFS monitoring section](https://github.com/kubeflow/kfserving#setup-monitoring).
> 
> I will look into it tomorrow and make changes for both the monitoring section and sample notebook reference on the website.

Thanks @tcnt !

**Comment by tcnt** [comment]
@yuzisun the pull request is merged. What is the next step to close the issue?
Is this something to be done by the requestor @jal06 ?

**Comment by jal06** [comment]
@tcnt 
That's great. Thanks a lot.
I think I can close this issue now.
