### ISSUE TITLE
TensorFlow Training (TFJob)

### ISSUE THREAD

**Issue by arunnalpet** [kubeflow/website#2331]
https://www.kubeflow.org/docs/components/training/tftraining/

The docker images used for tf-smoke-gpu doesnt seem to exist. 

Can it be updated with the right ones?

**Comment by OmriShiv** [comment]
It seems to be available on dockerhub: https://hub.docker.com/layers/kubeflow/tf-benchmarks-cpu/v20171202-bdab599-dirty-284af3/images/sha256-966c3a60b83fc7601613aef7ed74a24dbd24d7815c4c7738ad60379de7fd0c97?context=explore

It might need to be moved to gcr or the documentation needs to be updated

**Comment by Aut0R3V** [comment]
It's outdated. I'd like to work on this.
