### ISSUE TITLE
Authentication using OIDC in Azure

### ISSUE THREAD

**Issue by Subhraj07** [kubeflow/website#2335]
https://www.kubeflow.org/docs/azure/authentication-oidc/

I have created a change request on alignment for while trying to edit **kubectl edit -n kubeflow gateways.networking.istio.io kubeflow-gateway** as it is really confusing while someone who doesn't know much about yaml while trying to follow the step. 

I have faced the same issue as well.

PFA proposed request.
![Screenshot from 2020-11-05 09-57-44](https://user-images.githubusercontent.com/14942913/98197728-5f7e7d00-1f4d-11eb-8d3b-b001e1d01f76.png)

**Comment by 8bitmp3** [comment]
/assign @nilspohlmann @vsetty-msft @eedorenko @sudivate @yilun-msft @shbijlan

(fyi the OWNERS file for Azure is still being updated)

**Comment by yilun-msft** [comment]
@Subhraj07 and @8bitmp3 Thanks for the suggestion, The work is in progress, see https://github.com/kubeflow/website/pull/2323. It's pending approval and should be merged soon.

**Comment by yilun-msft** [comment]
The PR https://github.com/kubeflow/website/pull/2323 is merged. @8bitmp3 if you could kindly close this issue? Thanks a lot.

**Comment by 8bitmp3** [comment]
Awesome, thank you @yilun-msft 

/close

**Comment by Subhraj07** [comment]
@8bitmp3 

Thank you...
