### ISSUE TITLE
Add slack to Website

### ISSUE THREAD

**Issue by josepalafox** [kubeflow/website#234]
The kubeflow slack didn't appear to be linked in any way to the Kubeflow website. Might be good to add a button or reference to this in the additional resources section or the footer of the page template. Discussed with @texasmichelle

**Comment by sarahmaddox** [comment]
The Slack channel is linked on the "Community" page, which contains both a link to the Slack invitation and a link to the channel itself:
https://www.kubeflow.org/docs/about/community/

I think it'd be nice to link to the Slack channel in the header/footer, but I think we need to redesign the site  to fit in Slack and other links. I'm currently investigating a new theme for the site, which would include better linking of community resources.

@josepalafox and @texasmichelle Are you happy if we close this issue at this point, given the Slack channel is included in the "Community" section of the site?

**Comment by sarahmaddox** [comment]
I'm closing this issue, because I think my previous comment answers it. Please do re-open the issue if you think it still needs work.

/close
