### ISSUE TITLE
Kubeflow v1.2 docs - updating shortcodes for config files and KFDefs

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2366]
Hi all! 

The docs release [guide](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#create-website-branch) suggests updating **all** the config and URI [shortcodes](https://github.com/kubeflow/website/tree/master/layouts/shortcodes) for the new versioning:

![image](https://user-images.githubusercontent.com/27001378/99950720-e10b4300-2d74-11eb-9dc2-b4ecc3982ceb.png)

I recall from the v1.1 release that platforms were not ready for this change, and in fact, some of these are still in v1.0, e.g. [gcp-iap](https://github.com/kubeflow/website/blob/master/layouts/shortcodes/config-file-gcp-iap.html). 

Do we know which should be updated at this point to v1.2 and which should stay as they are?

**Comment by Bobgy** [comment]
You can skip the gcp-iap config, because it shouldn't be used anywhere. We need to clean up

**Comment by RFMVasconcelos** [comment]
Thank you for the clarification @Bobgy. I should perhaps ping other platform owners in this issue.

**Comment by RFMVasconcelos** [comment]
@Jeffwan could you please verify this on the AWS front?
@animeshsingh could you please verify this on the IBM front?
@Bobgy for the pipelines folder, how should we proceed?

**Comment by PatrickXYS** [comment]
From AWS side, we're ready for 1.1 changes. Will send PR for 1.2 doc changes

**Comment by Bobgy** [comment]
We don't need to change pipeline folder, it has its own release schedule
