### ISSUE TITLE
Install Kubeflow on IBM Cloud, deploy step points to wrong location

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [kubeflow/website#2371]
https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow/

Step 7 of the install instructions for IBM Cloud says:
```
Deploy Kubeflow:

kfctl apply -V -f ${CONFIG_URI}
```

The apply command should point to the local yaml config file created in the previous step and not the CONFIG_URI env var. Instructions to install on other platforms have the following step before the apply command:
```
Set an environment variable pointing to your local configuration file:

export CONFIG_FILE=${KF_DIR}/kfctl_k8s_istio.v1.1.0.yaml
```

Then the apply step uses the CONFIG_FILE env var:
```
kfctl apply -V -f ${CONFIG_FILE}

```

**Comment by 8bitmp3** [comment]
/assign @animeshsingh @shawnzhu @Tomcli 

PTAL 🙏

**Comment by Tomcli** [comment]
I think we fixed a while back, but the default instructions still pointing to v1.1 two weeks ago so it created some confusion. The new v1.2 instructions should addressed this issue.

**Comment by Tomcli** [comment]
/close

this link is already fixed
