### ISSUE TITLE
Kubeflow Deployment with kfctl_k8s_istio

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/website#2380]
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

Note, the following (quoted docs below)  is completely useless in getting access to Kubeflow after a deployment:

What is the default dns name inside the cluster?
What is the dns name for access outside this cluster?
How do we check if the dns name for the service has been deployed?

You need to consider your audience.  It's not K8S operators.  I don't or should not need to know istio in order to use Kubeflow - wasn't that kind of the idea behind Kubeflow?

There's not even enough information to begin to troubleshoot any particular problem that might occur.

Don't get me wrong, I'm happy this open source effort is here - But, you really gotta give us some clue as to how to proceed.

> Access the Kubeflow user interface (UI)
> 
> After Kubeflow is deployed, the Kubeflow Dashboard can be accessed via istio-ingressgateway service. If loadbalancer is not available in your environment, NodePort or Port forwarding can be used to access the Kubeflow Dashboard. Refer to Ingress Gateway guide.
>

**Comment by 8bitmp3** [comment]
cc @swiftdiaries @yanniszark @Bobgy @joeliedtke @jlewi @RFMVasconcelos
