### ISSUE TITLE
KFServing broken links

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2382]
There seems to be a lot of broken links in the [KFServing docs page](https://master.kubeflow.org/docs/components/serving/kfserving/). 

@animeshsingh could I gently ask you or someone from the Serving WG to take a look? 

Many thanks!

**Comment by 8bitmp3** [comment]
@yuzisun 

Did KFServing framework samples (TensorFlow, PyTorch, etc) get moved from `/samples` to `samples/v1beta1` and `samples/v1alpha2`? 

Commit: https://github.com/kubeflow/kfserving/commit/2f4f28a2c94086229d9d1e436c04d6f14d0b21c0#diff-859ee7723d23e50a9e8402e9393307865a30f00aab8b7180bb494815db927d3e

https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1

**Comment by 8bitmp3** [comment]
@yuzisun Hi, can you PTAL. Thank you!

cc @RFMVasconcelos

**Comment by yuzisun** [comment]
@8bitmp3 Yes that's correct, since we are releasing 0.5 with v1beta1 API, examples are classified into v1alpha2 and v1beta1
