### ISSUE TITLE
Broken Link on "Tools for serving > Overview"

### ISSUE THREAD

**Issue by tholor** [kubeflow/website#2384]
Page: https://www.kubeflow.org/docs/components/serving/overview/
Link: Pytorch "Sample"
Error: 404

![image](https://user-images.githubusercontent.com/1563902/100735820-20b7d780-33d2-11eb-9a84-dec78371b8f6.png)
![image](https://user-images.githubusercontent.com/1563902/100735930-5230a300-33d2-11eb-8eea-ab079acc998f.png)

**Comment by 8bitmp3** [comment]
@yuzisun 

Did KFServing framework samples (TensorFlow, PyTorch, etc) get moved from `/samples` to `samples/v1beta1` and `samples/v1alpha2`? 

Commit: https://github.com/kubeflow/kfserving/commit/2f4f28a2c94086229d9d1e436c04d6f14d0b21c0#diff-859ee7723d23e50a9e8402e9393307865a30f00aab8b7180bb494815db927d3e

https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1
