### ISSUE TITLE
Broken Link for Multi-framework serving with KFServing or Seldon Core

### ISSUE THREAD

**Issue by devil-cyber** [kubeflow/website#2387]
## Sample for the framework  having sub-feature TensorFlow, Xgboost, PyTorch, etc all links are broken
https://www.kubeflow.org/docs/components/serving/overview/
![Table](https://user-images.githubusercontent.com/1563902/100735930-5230a300-33d2-11eb-8eea-ab079acc998f.png)

**Comment by 8bitmp3** [comment]
@adrian555 @animeshsingh @cliveseldon @ellistarn @ryandawsonuk @Tomcli @yuzisun PTAL (`/serving` OWNERS)

**Comment by 8bitmp3** [comment]
Related issue https://github.com/kubeflow/website/issues/2382

cc @RFMVasconcelos

**Comment by 8bitmp3** [comment]
Related issue https://github.com/kubeflow/website/issues/2384

**Comment by 8bitmp3** [comment]
@yuzisun 

Did KFServing framework samples (TensorFlow, PyTorch, etc) get moved from `/samples` to `samples/v1beta1` and `samples/v1alpha2`? 

Commit: https://github.com/kubeflow/kfserving/commit/2f4f28a2c94086229d9d1e436c04d6f14d0b21c0#diff-859ee7723d23e50a9e8402e9393307865a30f00aab8b7180bb494815db927d3e

https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1

**Comment by yuzisun** [comment]
@8bitmp3 yes they are moved to v1ahpha2 directory, need to fix the links then

**Comment by devil-cyber** [comment]
Can I fix that Link then ?
