### ISSUE TITLE
End-to-end story to use components cohesively since we position Kubeflow as a comprehensive platform

### ISSUE THREAD

**Issue by davidyuyuan** [kubeflow/website#2399]
This issue is stemmed from https://github.com/kubeflow/community/pull/440, Restructuring Kubeflow docs proposal.

We have many excellent components. It requires some coordination and cooperation to make components working together smoothly, expecially for users without extensive experiences. It might be a bit more than documentation.

In particular, what do we do to guide users to use all components cohesively? Could there be a overall playbook to lead users stepping through their journey for ML end-to-end? How can users use components in the correct orders? How can they take results from one component and feed them into the next component?

**Comment by RFMVasconcelos** [comment]
Thank you for starting this @davidyuyuan ! 

I hope we can create such a guide in the near future
