### ISSUE TITLE
Serving non TF models using Seldon

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#24]
A walkthrough of training Scikit or XGBoost models and deploy using Seldon.

**Comment by sarahmaddox** [comment]
We now have samples linked from the Seldon guide:
https://www.kubeflow.org/docs/components/serving/seldon/

We also have KFServing examples here:
https://www.kubeflow.org/docs/components/serving/kfserving/

I'm going to close this issue, but pease do re-open it if there's more work to be done.

/close
