### ISSUE TITLE
Move info about IAP and TFServing to the docs website

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#240]
Move this info to the docs website, and then add a link from the GitHub repo to the docs (so we don't duplicate the info):
https://github.com/kubeflow/kubeflow/blob/430d4f7ae16af389ac570182af519f6571f160cf/docs/gke/tf_serving_iap.md

That will make the info easier to find, and ensure we keep it up to date.

**Comment by sarahmaddox** [comment]
We now have this doc on the website: https://www.kubeflow.org/docs/components/serving/tfserving_new/#sending-prediction-request-through-ingress-and-iap

TODO: 
* Compare the info and see if anything needs to be added to the website.
* Remove the content from the repo and link to the website doc instead.

**Comment by janeman98** [comment]
@sarahmaddox , I can work on this.

**Comment by sarahmaddox** [comment]
Thanks @janeman98 

/assign @janeman98
