### ISSUE TITLE
Kubeflow Docs: Updating Diagrams

### ISSUE THREAD

**Issue by Evanto** [kubeflow/website#2415]
I was going through pages of Kubeflow documentation and thought that many of the diagrams look dated at least in the terms of graphic style (maybe also in readability and essence). It seems that there is a lot of room for improvement in the quality of graphic content. 

Maybe we could work out a single modern style to create graphics for Kubeflow docs. Can we discuss it and see what can be done? What do you guys think? 

Some examples of pages with diagrams that can potentially be improved: 
- https://www.kubeflow.org/docs/started/kubeflow-overview/
- https://www.kubeflow.org/docs/started/getting-started/ 
- https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/  
- https://www.kubeflow.org/docs/components/serving/kfserving/ 

Other diagrams can be checked out here: 
https://github.com/kubeflow/website/tree/master/content/en/docs/images

**Comment by elizgarcia5** [comment]
good on my
