### ISSUE TITLE
Simplify kubeflow

### ISSUE THREAD

**Issue by futurexskill** [kubeflow/website#2422]
Simplify KubeFlow for data scientists. All we need is is a pip install kubeflow

**Comment by Aut0R3V** [comment]
I think this PR is a bit incomplete. Can you specify where exactly this instruction is missing?

**Comment by thesuperzapper** [comment]
Kubeflow is not possible to install with pip, it is a Kubernetes platform.

/close

**Comment by RFMVasconcelos** [comment]
+1 

We're doing a lot of work to make it just `juju deploy Kubeflow` or `microk8s enable kubeflow` but it's a lot of underlying K8s things going on.
