### ISSUE TITLE
Need an upgrade guide

### ISSUE THREAD

**Issue by ssiegel95** [kubeflow/website#2429]
Current update guide is empty.

**Comment by Aut0R3V** [comment]
Isn't that document related to this one : https://v0-5.kubeflow.org/docs/pipelines/upgrade/

**Comment by ssiegel95** [comment]
Thanks for the reply @Aut0R3V. I should have been more explicit, sorry. The issue I was reporting was for [the main page](https://www.kubeflow.org/docs). When you click on [Upgrading Kubeflow](https://www.kubeflow.org/docs/upgrading) in the lower left pane, you are taken to what is effectively a blank page:


![image](https://user-images.githubusercontent.com/12914116/103572843-3c177600-4e9b-11eb-9a73-7d65e839dce9.png)

**Comment by Aut0R3V** [comment]
Can any of the members comment on this? If this is a replica of any previous issues it can be closed. Or else I'd like to send in a PR for this. @Bobgy @marcusturewicz

**Comment by Bobgy** [comment]
Looks like the last clean up PR was not complete: https://github.com/kubeflow/website/pull/2275.
We should also delete the upgrade folder.

Regarding request to upgrade guide, each distribution will need to own its own upgrade guide. E.g. for GCP, the upgrade guide lives in https://www.kubeflow.org/docs/gke/deploy/upgrade/
