### ISSUE TITLE
Deploying Kubeflow behind a proxy server

### ISSUE THREAD

**Issue by chinmay22897** [kubeflow/website#2434]
https://www.kubeflow.org/docs/other-guides/kubeflow-behind-proxy/

It do tells us how to install kubeflow behind proxy but nothing on how to configure further more things, for instance I am not able to download anything from inside my pipeline components and the error I get is "no route to host" which is indirectly related to proxy related only, I have searched everywhere but found no fix for this or the ways to bypass proxy from inside standard containers.

**Comment by markqiu** [comment]
I also encountered the same problem. Excuse me, where can I find the information?

**Comment by jbottum** [comment]
@markqiu The Kubeflow Community has not provided that documentation.    You might try the On-Prem SIG (please find notes here...there is a meeting next Wednesday). https://docs.google.com/document/d/1Qs94d9RPxqiZJnTRvL9iHZrx_jnf59HyJFnbyi1AYjQ/edit#heading=h.w4esj4yrc6i

Alternatively, you might try a vendor who provides Kubeflow consulting services for on-prem installations.
