### ISSUE TITLE
Need OWNERS for shortcodes

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2436]
Given the lack of individual OWNERS for shortcodes, it has been unclear which can be updated right at the outset of a new release, and which can not. 

Platform and WG leads should be the OWNERs of the shortcodes, so they can tell us when these can be updated and approve such change, not requiring root approvers for it. 

See [issue](https://github.com/kubeflow/website/pull/2423)

cc @Bobgy @8bitmp3

**Comment by berndverst** [comment]
For Azure there is a separate folder with our short codes. Please add an OWNER file there and add myself @berndverst and @aronchick to it as approvers.

**Comment by 8bitmp3** [comment]
@RFMVasconcelos ping me if you need assistance and if you've created a PR already, let's link this Issue in it `https://github.com/kubeflow/website/issues/2436`
