### ISSUE TITLE
Management cluster setup kpt version incompatibility

### ISSUE THREAD

**Issue by sidpalas** [kubeflow/website#2437]
https://www.kubeflow.org/docs/gke/deploy/management-setup/

The latest version of kpt (`v0.37.1`) is not compatible with this step:
```
kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 "${MGMT_DIR}"
```
(https://www.kubeflow.org/docs/gke/deploy/management-setup/#setting-up-a-management-cluster)

By installing kpt `v0.35.0` I was able to get it to work.

**Comment by Bobgy** [comment]
As explained in https://github.com/kubeflow/gcp-blueprints/issues/183#issuecomment-755873147, I think the error message can be ignored for now. All the following steps should succeed without even downgrading kpt.

**Comment by sidpalas** [comment]
Thanks @Bobgy -- Do you think it makes sense to call this out in the deployment steps on the website so that people who encounter it in the future know that they can proceed?

**Comment by Bobgy** [comment]
@sidpalas yes, that would be great

**Comment by sidpalas** [comment]
Great -- I can create a PR calling this out
