### ISSUE TITLE
Typo on doc page for "Installing Kubeflow Instructions for Kubeflow deployment with Kubeflow Operator"

### ISSUE THREAD

**Issue by javajon** [kubeflow/website#2456]
On the page [Installing Kubeflow: Instructions for Kubeflow deployment with Kubeflow Operator](https://www.kubeflow.org/docs/operator/install-kubeflow/) there instructions say:

`yq w ${KFDEF} 'metadata.name' ${KUBEFLOW_DEPLOYMENT_NAME} > ${KFDEF}.tmp && mv ${KFDEF}.tmp ${KFDEF}`

**The parameter `w` should instead be an `e`**, however because this is a documentation page, it should be 'eval' to spell it out for readers. 

Suggestion: The instructions are a bit verbose and could just be reduced to a one liner:

`yq eval '.metadata.name = "kubeflow"' -i ${KFDEF}`

A suggestion is to make it easier by putting a default metadata.name=kubeflow in the kfdef sources. But if the name must not be there, perhaps put in a tag that the ubiquitous `envsubst` can replace rather than having to install a tool such as yq.

**Comment by pushkarv** [comment]
The -i option works:
yq w -i ${KFDEF} 'metadata.name' ${KUBEFLOW_DEPLOYMENT_NAME} > ${KFDEF}.tmp && mv ${KFDEF}.tmp ${KFDEF}
