### ISSUE TITLE
Restructure Components section

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#2465]
@RFMVasconcelos , one suggestion that came out of the last community meeting was to see if we can start work on some of the uncontroversial parts of the restructuring plan ([Kubeflow/Community PR #440](https://github.com/kubeflow/community/pull/440)) that you proposed. From this meeting, the community seems to agree that we can move forward with the proposed changes to the Components section.

If there are no objections, I propose that we use this issue to coordinate the work for updating the Components section. Here is the proposed structure for the Components section:

- **Components** (remove "of Kubeflow", components reordered as per user journey)
  - Central Dashboard
    - Central Dashboard 
    - Registration Flow
  - Notebook Servers (moved to under components, renamed from "Jupyter Notebooks")
    - Overview of Jupyter Notebooks in Kubeflow
    - Set Up Your Notebooks
    - Create a Custom Jupyter Image
    - Submit Kubernetes Resources
    - Build a Docker Image on GCP
    - Troubleshooting Guide
  - Kubeflow Pipelines (add "Kubeflow", remove redirects)
    - Pipelines Quickstart
    - Installing Pipelines
      - Installation Options for Kubeflow Pipelines
      - Kubeflow Pipelines Standalone Deployment
      - Deploying Kubeflow Pipelines on a local cluster
    - Understanding Pipelines
      - Overview of Kubeflow Pipelines
      - Introduction to the Pipelines Interfaces
      - Concepts
    - Building Pipelines with the SDK
      - Introduction to the Pipelines SDK
      - Install the Kubeflow Pipelines SDK
      - Build Components and Pipelines
      - Create Reusable Components
      - Building Python function-based components
      - Best Practices for Designing Components
      - Pipeline Parameters
      - Python Based Visualizations
      - Visualize Results in the Pipelines UI
      - Pipeline Metrics
      - DSL Static Type Checking
      - DSL Recursion
      - Using environment variables in pipelines
      - GCP-specific Uses of the SDK
      - Manipulate Kubernetes Resources as Part of a Pipeline
    - Multi-user Isolation for Pipelines
    - Caching
    - Upgrading
    - Samples and Tutorials
      - Using the Kubeflow Pipelines Benchmark Scripts
      - Using the Kubeflow Pipelines SDK
      - Experiment with the Kubeflow Pipelines API
      - Experiment with the Pipelines Samples
      - Run a Cloud-specific Pipelines Tutorial
    - Troubleshooting
    - Reference
      - Component Specification
      - Pipelines API Reference
      - Pipelines SDK Reference
  - Frameworks for Training
    - Chainer Training
    - MPI Training
    - MXNet Training
    - PyTorch Training
    - TensorFlow Training (TFJob)
  - Tools for Serving
    - Overview
    - KFServing
    - Seldon Core Serving
    - BentoML
    - NVIDIA Triton Inference Server
    - TensorFlow Serving
    - TensorFlow Batch Prediction
  - Katib
    - Introduction to Katib
    - Getting Started with Katib
    - Running an Experiment
    - Resuming an Experiment
    - Overview of Trial Templates
    - Using Early Stopping
    - Katib Configuration Overview
    - Environment Variables for Katib Components
  - Metadata
  - Fairing 
    - Overview of Kubeflow Fairing
    - Install Kubeflow Fairing
    - Configure Kubeflow Fairing
    - Fairing on Azure
    - Fairing on GCP
    - Tutorials
    - Reference
  - Feature Store
    - Introduction to Feast
    - Getting started with Feast
  - Nuclio functions (remove "Miscellaneous" layer)
  - Istio (remove "usage in Kubeflow")
  - Multi-Tenancy (remove "in Kubeflow")
    - Introduction to Multi-user Isolation
    - Design for Multi-user Isolation
    - Getting Started with Multi-user Isolation  
  - Gang-scheduling (current "Job scheduling" - only keep if has owners)

**Comment by joeliedtke** [comment]
I propose that we update the Components section within the docs folder (keeping `/docs/components` instead of moving to `/components`). This reduces the effort required to implement these changes, and reduces the number of redirects that are necessary. My understanding is that the weight that search engines give a link is shared when a page is redirected (and shared several ways if a page redirects multiple times). So, this has the added benefit of helping us with SEO.

**Comment by thesuperzapper** [comment]
Sounds good @joeliedtke, do you think its realistic to aim to _**implement these changes within the next week**_?

This will give time for WGs to update their component docs ahead of Kubeflow 1.3's release in 1 month.

**Comment by thesuperzapper** [comment]
@animeshsingh @Bobgy @joeliedtke what are your comments? 
(Specifically, related to how we implement these changes, not the changes themselves, which have already been agreed to in: https://github.com/kubeflow/community/pull/440)

Also cc @castrojo who is wanting to get involved in this kind of stuff.

**Comment by RFMVasconcelos** [comment]
@joeliedtke, I think this is a great start! 

I've started this [project](https://github.com/kubeflow/website/projects/2), so we can add smaller chunks as issues and track the progress of the overall initiative.

We might want to split this initiative into several sub-tasks - e.g. 1. rename Components section; 2. Rename and move Notebooks section under Components; etc. 

So, let me create a bunch of issues that encompass this first part of moving things under components.

**Comment by Bobgy** [comment]
Agree with the overall structure, some individual items were discussed in their issues.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos just wondering how far along the implementation of this is?

I still see some strangeness on https://www.kubeflow.org/docs/components/
* "Kubeflow Pipelines" is not under "components"
* There are a bunch of things which are not components under "components"

**Comment by RFMVasconcelos** [comment]
@thesuperzapper, for Pipelines I've just made final commits on #2505 to address some concerns with redirects. I'll bring it to the Kubeflow pipelines meeting in 5 minutes so we can get that merged.

As per other non components things under components what do you think should definitely be repositioned?

**Comment by RFMVasconcelos** [comment]
FYI @thesuperzapper Pipelines under Components just got merged

**Comment by RFMVasconcelos** [comment]
We are now at the state proposed in this issue, let's close this one and if there are other proposed changes to the components section we can create separate issues/PRs. 

Thank you for the help @joeliedtke @Bobgy @thesuperzapper !
