### ISSUE TITLE
Moving `Notebook Servers` section under `Components`

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2468]
As part of #2465, we need to move the `Notebook Servers` section to under `Components`. 

Would moving the `/notebooks` folder under `/components/` automatically do the trick? 

I am not too familiar with `Netlify` and `Hugo` yet. It seems that `/notebooks` has a similar folder structure to things like `/components/katib`.

If so, this should be easy. We just need to at the end of this process manage `weight` on `_index.md` to make sure the order is correct.

**Comment by RFMVasconcelos** [comment]
cc @kubeflow/wg-notebooks-leads

**Comment by RFMVasconcelos** [comment]
@thesuperzapper could you please bring this topic to the notebooks discussion? :)

**Comment by thesuperzapper** [comment]
sure @RFMVasconcelos

**Comment by thesuperzapper** [comment]
@RFMVasconcelos wg-notebooks discussed this at our latest meeting, and are more than happy for the move.

Since you have moved lots of the other components, you might be the best person to make this change quickly?

**Comment by RFMVasconcelos** [comment]
Done!
