### ISSUE TITLE
Moving `Kubeflow Pipelines` section under `Components`

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2470]
As part of #2465, we need to move the `Kubeflow Pipelines` section to under `Components`. 

(same as in #2468)

Would moving the `/pipelines` folder under `/components/` automatically do the trick? 

I am not too familiar with `Netlify` and `Hugo` yet. It seems that `/pipelines` has a similar folder structure to things like `/components/katib`.

If so, this should be easy. We just need to at the end of this process manage `weight` on `_index.md` to make sure the order is correct.

**Comment by RFMVasconcelos** [comment]
@kubeflow/wg-pipeline-leads would you be able to take on this effort?

**Comment by RFMVasconcelos** [comment]
@kubeflow/wg-pipeline-leads would any of the lead be able to take on this change?

**Comment by Bobgy** [comment]
/assign

I'm on vacation, will work on this when I am back.

**Comment by RFMVasconcelos** [comment]
@Bobgy, thanks for the heads-up! Enjoy your vacation :)

**Comment by RFMVasconcelos** [comment]
@Bobgy I went ahead and created a PR  :) -» #2505
