### ISSUE TITLE
Move istio usage under `Components`

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2471]
See #2465.

[Istio usage in Kubeflow](https://www.kubeflow.org/docs/other-guides/istio-in-kubeflow/) is now in `Further setup & troubleshooting` in the docs, and in the folder it is under `/other-guides/istio-in-kubeflow.md`
 
We should move it under `Components/Istio`. 

It still has an out of date banner, which we should look to verify & remove.

**Comment by RFMVasconcelos** [comment]
@Bobgy @joeliedtke @animeshsingh What is your take on this? 

If we're to create a `Components/Istio` section, who do you think are good OWNERS for it?

**Comment by Bobgy** [comment]
I can be one of the owners, open to add more people responsible for istio Integration 

/Cc @PatrickXYS 
Do you want to be part of this?

**Comment by Bobgy** [comment]
I guess also @yanniszark ?

**Comment by PatrickXYS** [comment]
> I can be one of the owners, open to add more people responsible for istio Integration
> 
> /Cc @PatrickXYS
> Do you want to be part of this?

Yeah would be happy to contribute as well
