### ISSUE TITLE
Gang-scheduling under `Components` OR kill

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2472]
See #2465. 

Today's [Job Scheduling guide](https://www.kubeflow.org/docs/other-guides/job-scheduling/) under `Further setup & troubleshooting`, should according to community agreement be under `Components`. 

This project seems to be in `alpha` stage and `out of date`. 

I am not sure of what is the policy for project sunsetting, but this seems to be one that is sunsetting. We should add OWNERS to it, and update, or kill it.

**Comment by RFMVasconcelos** [comment]
cc @Bobgy @joeliedtke @animeshsingh do you know if this project has continuity and OWNERS to maintain docs or if we should remove it?

**Comment by RFMVasconcelos** [comment]
It seems hard to trace at this point who created this doc. Nothing in the [commit history](https://github.com/kubeflow/website/commits/master/content/en/docs/other-guides/job-scheduling.md).

**Comment by Bobgy** [comment]
I think it's very related to training WG.
/assign @kubeflow/wg-training-leads

**Comment by k82cn** [comment]
We'd like to help on keeping it up-to-date :)

**Comment by Bobgy** [comment]
So I think it'll be a good fit to move to a section under probably `components/training/gang-scheduling`

**Comment by gaocegege** [comment]
I think so. It will be better.

**Comment by Bobgy** [comment]
/assign @k82cn

@gaocegege 
Thanks for confirmation!

**Comment by RFMVasconcelos** [comment]
There are other components that fit into an `extra` or `more` category. Please see #2486 and #2488.

Should we add gang-scheduling there, or under training would be the best?

**Comment by william-wang** [comment]
@RFMVasconcelos Thanks for your information. gang-scheduling under training directory would be the best from my view.  Whenever user go through the traing guide , they can see the gang-scheduling and configure them together at once. It might be more convinient for user.

**Comment by RFMVasconcelos** [comment]
@k82cn Please let me know when you create a PR to move Gang to under training, so we can close this PR. :)

**Comment by william-wang** [comment]
@RFMVasconcelos The PR has been created. Here is the link: https://github.com/kubeflow/website/pull/2508

**Comment by RFMVasconcelos** [comment]
Hey @william-wang, the PR does not achieve the desired goal, please see my comment in it :)

**Comment by RFMVasconcelos** [comment]
This is being resolved in #2508, so I think we can close this issue. 

/close
