### ISSUE TITLE
Remove "Miscellaneous" layer & keep "Nuclio Functions" OR kill

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2473]
See #2465. 

[Page under review](https://www.kubeflow.org/docs/components/misc/nuclio/).

Today's `Misc` section under `Components`only has `Nuclio functions` which is out of date. If this is a used component, then it should have OWNERS and it's place under components. If not, we should kill it. 

Up for discussion :)

**Comment by RFMVasconcelos** [comment]
@aronchick @Bobgy @joeliedtke @animeshsingh Do you know if `Nuclio functions` has any potential OWNERS who can maintain docs, or if we should discontinue it?

**Comment by RFMVasconcelos** [comment]
From [commit history](https://github.com/kubeflow/website/commits/master/content/en/docs/components/misc/nuclio.md), it's not traceable who created this doc, and who might be a good owner.

**Comment by Bobgy** [comment]
I don't have a good idea too, +1 to kill

We can always add it back from history if someone come to it later.

**Comment by RFMVasconcelos** [comment]
One alternative would be to aggregate these under `/components/more`, as there are other optional components - see #2486.

**Comment by Bobgy** [comment]
I'd prefer keeping docs that have active maintainers. If it doesn't, right now it's only negative impact to the entire website

**Comment by Bobgy** [comment]
So if we cannot find one, delete is better.

**Comment by RFMVasconcelos** [comment]
Sounds good! Let's delete for now then!
