### ISSUE TITLE
Create `Add-ons` section under `Components` ?

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2486]
There are a few components with no clear OWNERS - see #2472 and #2473 - and [Rok](https://www.kubeflow.org/docs/other-guides/integrations/data-management/) which today is on `other-guides/integrations/data-management/`, which in my opinion could make it as `/Components/More`. 

This way we would centralize these unmaintained pages and get OWNERS for this group. 

@jbottum @cvenets what do you think from Rok standpoint? 

@animeshsingh @Bobgy @joeliedtke @8bitmp3 @thesuperzapper @mameshini WDYT?

**Comment by Bobgy** [comment]
We've got resolution for nuclio and gang. What should we do with Rok?

I don't have a good idea right now. Should it be a standalone section in components?

**Comment by RFMVasconcelos** [comment]
Looking at the notes from the last meeting I am unsure if Rok falls into this classification since it's proprietary.
![Screenshot from 2021-02-11 10-19-47](https://user-images.githubusercontent.com/27001378/107624420-be414a00-6c52-11eb-97e9-6340667ace7f.png)

Happy to act in whatever the community feels is good practice.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I think if you have the time, you can just raise separate PR's and let the community decide on each one.

To be specific, I think we should have a new section of the docs for 'proprietary stuff'.

**Comment by cvenets** [comment]
@RFMVasconcelos @Bobgy we can take responsibility of the Rok part and even provide more documentation as needed, noting exactly how it integrates with Kubeflow and that it is proprietary software, so that it is 100% clear to the community.

We are fine with both solutions of either putting it as an item in "Components" or under a new "Proprietary Components" section. We will make sure to note clearly on the docs that Rok is proprietary software in any case, if we don't want to create a new section for just one item.

**Comment by RFMVasconcelos** [comment]
@cvenets @thesuperzapper I think that adding yet another section "Proprietary Components" may make things more confusing for users, we're generally reducing the options so it's more clear what to do. Also, I think Rok is the only exception for the moment, so it would sit alone there.

One option I see is to have a `More` or `Add-ons` section under `Components`, where we would list things that are not part of core Kubeflow usage, like Feast, Rok, Nuclio, etc. And in the case of Rok as it is proprietary we could find a way to say that very clearly on the page, either through a banner or in the title. 

Sounds good?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I am still not sure we have the right solution

After some more thought, I think this should be the plan:
1. We are planning to move each component's docs to their own websites soon (so they can be versioned independently from Kubeflow itself)
2. The component docs should only reference features in the open-source version of the component
3. We should **not host** distribution docs on kubeflow.org (but we can link to external docs, for distributions which meet some criteria)
     * NOTE: this is similar to how Kubernetes doesn't host the GKE/EKS docs, but references them as partners
3. Then if a distribution of Kubeflow has some proprietary feature, it should be described in the external docs for that distribution

**Comment by mameshini** [comment]
I think it makes sense to have Add-Ons Section for Kubeflow add-ons that are not deployed with upstream Kubeflow by default, but can be used in addition with upstream Kubeflow to enhance certain capabilities.  For example Arrikto Rok data management.  Prometheus and Grafana for monitoring of Kubeflow components or monitoring of models.  Apache Kafka for data streaming.  This section can start with just Rok and Prometheus, and hopefully additional content will be added quickly.  Any supported add-on/integration is a valuable part of Kubeflow platform.  They key is "supported" by a vendor/project and tested with Kubeflow project.  Unsupported/outdated add-ons should be deprecated to avoid user confusion.

**Comment by castrojo** [comment]
I think "Add-Ons" or "Ecosystem" is best for now, we should just land those there so we can concentrate on the more urgent pages. 

The K8s solution is a top-level "Partners" page that can hold all of these, and then we have all this information there and it's cleanly separated from the pure upstream docs, however that's extra work, maybe we land it this way now and then split it up post 1.3?

**Comment by RFMVasconcelos** [comment]
I'm ok with doing `Add-ons`, however, looking now at the pages we have to populate this section:

* Gang scheduling -» Moving under training - see #2472 
* Nuclio functions -» Decided to archive - see #2473 
* Rok -» The page seems outdated, and not to provide much value in it's [current state](https://www.kubeflow.org/docs/other-guides/integrations/data-management/) - Does Arrikto want to update the page to justify the creation of `add-ons` section before v1.3? 
* Istio -» Does not really feel like an `Add-on` as it's mandatory component

I like @mameshini's vision of having pages for Prometheus, Kafka, and other integrations! This requires content creation though, and I haven't seen too much interest lately on creating such pages. We can ask the community if someone is willing to do it.

We can have this as a longer term goal.

**Comment by RFMVasconcelos** [comment]
This is very well addressed by #2536. Closing this proposal.

/close
