### ISSUE TITLE
Add "Resources" and organize content under it

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2491]
Following the latest community discussions and the Kubeflow docs restructure [proposal](https://github.com/kubeflow/community/pull/440/files), we should add the concept of "Resources", with the following structure:

- **Resources** (remove "Tutorials, Samples, and Shared")
  - Kubeflow Samples
  - Codelabs, Workshops, and Tutorials
  - Blog Posts
  - Videos
  - Shared Resources and Components

**Comment by thesuperzapper** [comment]
I am closing in preference of https://github.com/kubeflow/website/issues/2759, feel free to reopen if we want to add a resources again in future.
/close
