### ISSUE TITLE
Upgrading Kubeflow Pipelines: Do instructions only apply for Google Cloud?

### ISSUE THREAD

**Issue by benjamintanweihao** [kubeflow/website#2503]
The "Upgrading Kubeflow Pipelines" simply provides a link to Google Cloud for information about upgrading. This is confusing:

* Does this mean that the instructions only apply to Google Cloud deployments?
* What does this mean for on-prem deployments? 

It is not clear if the provided [matrix](https://www.kubeflow.org/docs/gke/pipelines/upgrade/#upgrade-related-feature-matrix) refers to _only_ Google Cloud deployments.

**Comment by Bobgy** [comment]
Hi @benjamintanweihao The standalone upgrade guide applies to on prem.

The other guides only apply for GCP.
