### ISSUE TITLE
Outdated 'Notebook Servers' pages

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2514]
All the pages under [Notebook Servers](https://www.kubeflow.org/docs/components/notebooks/) appear still as 'Outdated', let's aim at having them up to date for the v1.3 release. 

Could one of the @kubeflow/wg-notebooks-leads verify if this documentation is up to date, in which case we can remove the banner, or if it needs refreshing? 

Many thanks!

**Comment by DavidSpek** [comment]
@RFMVasconcelos From quickly going through the quickly everything looks up to date. However, there is a lot of information that should be added and the sections of specific for GCP should probably be removed. I'll go through the docs more thoroughly tomorrow and create a PR with some changes.

**Comment by RFMVasconcelos** [comment]
Thank you for tackling this @DavidSpek!
