### ISSUE TITLE
Outdated `Frameworks for training` pages

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2516]
[example](https://www.kubeflow.org/docs/components/training/chainer/)

cc @kubeflow/wg-training-leads

**Comment by RFMVasconcelos** [comment]
@kubeflow/wg-training-leads any chance someone could take a look at these pages?

**Comment by RFMVasconcelos** [comment]
An OK of whether they are up to date would go a long way.

**Comment by RFMVasconcelos** [comment]
Example:
https://www.kubeflow.org/docs/components/training/tftraining/

**Comment by terrytangyuan** [comment]
I think some of them are outdated. It's hard to keep these pages up-to-date. It would be better to provide a script to automatically update them based on README from each project.

**Comment by andreyvelich** [comment]
@terrytangyuan @gaocegege @johnugeorge @ChanYiLin @Jeffwan What should we do with the docs for the Kubeflow 1.3 release ?
Does anyone have enough time to update them on this week ?

**Comment by terrytangyuan** [comment]
I can help update some of the pages for operators this week too if needed.

**Comment by RFMVasconcelos** [comment]
This has been tackled in #2584 

/close
