### ISSUE TITLE
Broken Link - other-guides/job-scheduling/

### ISSUE THREAD

**Issue by sathishvj** [kubeflow/website#2520]
https://www.kubeflow.org/docs/other-guides/job-scheduling/

**Comment by 8bitmp3** [comment]
Thanks @sathishvj The link doesn't appear under `docs/other-guides`. Can you let us know how you came across the page so we can fix the broken links in other docs? Thanks cc @RFMVasconcelos

**Comment by sathishvj** [comment]
If you do this google search, it shows up: https://www.google.com/search?q=kubeflow+pipelines+built-in+scheduler 

So, where exactly is the documentation for job scheduling?

**Comment by RFMVasconcelos** [comment]
Hey! This page was moved to under training -» https://www.kubeflow.org/docs/components/training/job-scheduling/

**Comment by RFMVasconcelos** [comment]
I will add this to automated redirects!
