### ISSUE TITLE
Adding a community-managed GA code to the website

### ISSUE THREAD

**Issue by castrojo** [kubeflow/website#2522]
In the Community Meeting on 23 Feb we asked Google for some access to the Google Analytics so that we can have the data to make better decisions when restructuring docs. 

Google told us that corporate policy would make this unfeasible. David Aronchick proposed just adding a 2nd GA code to the website/docs so that there can be a clear separation between a corporate account and one run by the community. There was lazy concensus during the meeting on this. 

As far as I can tell there's no policies in the project on how "the community" can manage a google account (bus factor, trust, etc.), so that needs to be solved still, so just opening this up as a placeholder.

cc @RFMVasconcelos

**Comment by thesuperzapper** [comment]
@castrojo do you want to raise a proposal on `kubeflow/community` with a solution for how to assign access to this new Google analytics account? (I am not sure how GA works with assigning other people as 'viewers')

Currently most ACL is assigned in https://github.com/kubeflow/internal-acls. However, we still need a super-admin account to bootstrap the Google Analytics account, the password for which, will need to be somehow owned by the community.

Obviously this issue will come up again (and more significantly) after the formation of the "Technical Steering Committee"(https://github.com/kubeflow/community/issues/495) as all current super-admin accounts (for things like: GitHub and Google Groups) will need be handed over to the members of that committee.

**Comment by jlewi** [comment]
> David Aronchick proposed just adding a 2nd GA code

Wouldn't a 2nd GA code run into the same problem with Google corporate policies? 

> There was lazy concensus during the meeting on this.

Did anyone from Google actually say a 2nd GA code would be ok?

**Comment by castrojo** [comment]
> Did anyone from Google actually say a 2nd GA code would be ok?

There were googlers at the meeting but none that could speak to this, which is why I filed this in github as an item.

**Comment by RFMVasconcelos** [comment]
One potential path to get this done is:
1. Create a generic gmail address e.g. `kubeflow-docs-tracking@gmail.com`
2. Provide credentials of this account to a few leads in the community
3. Generate a tracking code from the new GA account
4. Make a PR that adds this code to the website
5. Provide view access to community members upon request

I'm happy to proceed if the community feels this is the way to go.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos can you add this issue to the 1.3 project https://github.com/kubeflow/website/projects/2

If you think it makes sense? Having analytics will definitely help us prioritise the docs, which I imagine will get more traffic after 1.3.

**Comment by thesuperzapper** [comment]
Wait, its already there, lol.

**Comment by RFMVasconcelos** [comment]
Yes, I made this suggestion 10 days ago, and put it on the project, but did not act on it yet. @castrojo was having discussions with Google on this regard I believe. Any news?

**Comment by castrojo** [comment]
Nothing new to report, I don't think we should block 1.3 on this though unless we hear something really soon.

**Comment by RFMVasconcelos** [comment]
I believe this would still be super valuable for the community! 

@Bobgy any chance we can make this happen?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos as discussed above, I think it's on us (maintainers of the website) to set up a new Google Analytics and manage our own auth.
