### ISSUE TITLE
Move "KFServing" to "Components"

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2535]
We should ensure all core Kubeflow components live directly under the `Components` section.

Currently, "KFServing" lives under`Components / Tools for Serving` (along with many other docs for serving tools which are not part of Kubeflow).

I think we should move it directly under `Components`, otherwise it sends some mixed messages about what is officially part of Kubeflow.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos what are your thoughts?

**Comment by RFMVasconcelos** [comment]
Thank you @thesuperzapper for starting this. I fully agree! KFServing is a great tool by the community and should have more emphasis! 

Happy to make a PR

**Comment by thesuperzapper** [comment]
I highly doubt there would be any conflict from others if you made a PR.

Also, I think we should split up the components, as proposed in https://github.com/kubeflow/website/issues/2536

**Comment by RFMVasconcelos** [comment]
Sounds good! I'll give it a go

**Comment by RFMVasconcelos** [comment]
The PR for this has been merged! 🎉 

/close
