### ISSUE TITLE
Split "Components" section into "Core Components" and "External Components"

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2536]
While it's awesome we now have all components living under one section, this has caused users to become confused about what is actually part of Kubeflow, and what is external.

### My proposal is to split "Components" into:
* `Core Components` (all components owned by a Kubeflow WG)
* `External Components` (all other components we want to highlight)

### Proposed Structure:
```
Core Components:
- Central Dashboard
   - ... same ...
   - + Multi-Tenancy [moved]
- Notebooks [rename from "Notebook Servers"]
   - ... same ...
- Pipelines [rename from "Kubeflow Pipelines"]
   - ... same ...
- Metadata
   - ... same ...
- Katib
   - ... same ...
- KFServing
   - ... same ...
- Training Operators [rename from "Frameworks for Training"]
   - ... same ...
- Fairing
   - ... same ...
```
```
External Components:
- Istio
   - ... same as before ...
- Tools for Serving
   - ... same as before ...
- Feature Store
   - ... same as before ...
```

**Comment by thesuperzapper** [comment]
I think the docs OWNERS can make a call on this one as its a pretty simple change.

So, @animeshsingh @Bobgy @joeliedtke @RFMVasconcelos, whats your thoughts?

**Comment by RFMVasconcelos** [comment]
I like this proposal! There is still space to improve in the structure.

My only concern is lots of navigation given more nesting. We could alternatively create only the `Comunity components` section and have the `Core components` right under `Components`. 

I think we're better than now with either solution.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I think minimising the depth of the page tree is important (so no further nesting, please).

But if you only want to rename one section you could also have:
- Components (same definition as "Core Components" above)
- Community Components (same as above)

But I like the idea of "Core Components" as it highlights which ones are owned by the Kubeflow community.

**Comment by RFMVasconcelos** [comment]
Oh! Sorry, I misread your proposal as:
* `Components/Core Components`
* `Components/Community Components`

+1 to your proposal

**Comment by Bobgy** [comment]
Sounds reasonable to me!

@joeliedtke what do you think about it?

**Comment by andreyvelich** [comment]
Just to make a point that `Frameworks for Training` is the core Kubeflow component we should include this in `Components/Core Components`
Besides that, I agree with the Proposal.

cc @kubeflow/wg-training-leads

**Comment by terrytangyuan** [comment]
"confused about what is actually part of Kubeflow" - I guess I am more confused after this is splitted into two parts. Is there a definition for being "part" of Kubeflow? Is there a process in place to "graduate" a project to be "part" of Kubeflow? Aren't Kubeflow WGs formed by the community too and the word "Community Components" is confusing?

Should Metadata be removed or moved to the second part as the project is being archived?

Does Fairing belong to one of the WGs?

**Comment by jbottum** [comment]
suggestion - if we are going to classify a components as a "core component", then it probably needs to have higher level of support i.e. owned by an active working group, have a roadmap, supporting a stable version (or driving to a stable version per the KF stable definition), and active users.

**Comment by thesuperzapper** [comment]
@terrytangyuan as proposed above, "Core Components" are anything owned by a working group, whereas "Community Components" are anything which is related to Kubeflow, but not owned by the project WGs.

NOTE: we could call then "Contrib Components", to make this more clear.

NOTE: you can see what each WG owns by checking "subprojects" under [wgs.yaml](https://github.com/kubeflow/community/blob/master/wgs.yaml#L136-L139)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I think we should try do this before the 1.3 distributions are finalised (6th April 2021)

## My final structure proposal 
(NOTE: I think "External Components" is more clear than "Community Components")

```
Core Components:
- Central Dashboard
   - ... same ...
   - + Multi-Tenancy [moved]
- Notebooks [rename from "Notebook Servers"]
   - ... same ...
- Pipelines [rename from "Kubeflow Pipelines"]
   - ... same ...
- Metadata
   - ... same ...
- Katib
   - ... same ...
- KFServing
   - ... same ...
- Training Operators [rename from "Frameworks for Training"]
   - ... same ...
- Fairing
   - ... same ...
```
```
External Components:
- Istio
   - ... same as before ...
- Tools for Serving
   - ... same as before ...
- Feature Store
   - ... same as before ...
```

**Comment by Bobgy** [comment]
Another naming proposal

What do you think about "components" vs "contrib"? I think shorten to one word and not reuse the term component makes it clearer

**Comment by RFMVasconcelos** [comment]
I very much like your last proposal @thesuperzapper and I'm happy to make a PR on it. 

A few possible changes: 
```
Components:
- Central Dashboard
   - ... same ...
   - + Multi-Tenancy [moved]
- Notebook Servers [keep as technically more accurate » we made this change recently from "Notebooks"]
   - ... same ...
- Kubeflow Pipelines [keep for SEO and clarity purposes » we made this change recently from "Pipelines"]
   - ... same ...
- Metadata
   - ... same ...
- Katib
   - ... same ...
- KFServing
   - ... same ...
- Training Operators [rename from "Frameworks for Training"]
   - ... same ...
- Fairing « IF ACTIVE - there seems to be no WG
   - ... same ...

```
External add-ons
- Istio
   - ... same as before ...
- Tools for Serving
   - ... same as before ...
- Feature Store
   - ... same as before ...
```

**Comment by thesuperzapper** [comment]
@RFMVasconcelos looks good to me

**Comment by Bobgy** [comment]
Multi-Tenancy [moved]
I'd suggest keeping it as a component, because pipelines, notebooks and central dashboard are all implementing the same convention for multi tenancy

**Comment by RFMVasconcelos** [comment]
If everyone agrees, I can make a PR with these changes then: 

```
Components:
- Central Dashboard
   - ... same ...
- Notebook Servers [keep as technically more accurate » we made this change recently from "Notebooks"]
   - ... same ...
- Kubeflow Pipelines [keep for SEO and clarity purposes » we made this change recently from "Pipelines"]
   - ... same ...
- Metadata
   - ... same ...
- Multi-Tenancy
   - ... same ...
- Katib
   - ... same ...
- KFServing
   - ... same ...
- Training Operators [rename from "Frameworks for Training"]
   - ... same ...
- Fairing « IF ACTIVE - there seems to be no WG
   - ... same ...
```
```
External add-ons
- Istio
   - ... same as before ...
- Tools for Serving
   - ... same as before ...
- Feature Store
   - ... same as before ...
```

**Comment by RFMVasconcelos** [comment]
Any ideas on what to do with `Fairing`?

**Comment by Jeffwan** [comment]
> - Training Operators [rename from "Frameworks for Training"]
+1 agree.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos just leave it under "core" for now, there is no reason to presume a decision on fairing.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos while fairing would not meet the definition of being owed by a working group, I think it's probably inevitable that one will be formed. Therefore, it makes sense to leave it under core for now.

**Comment by terrytangyuan** [comment]
Looks great!

**Comment by thesuperzapper** [comment]
@terrytangyuan can you clarify if you were refering to the (`Core Components` and `External Components`) names, or (`Components` and `External add-ons`)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos also, I think `Notebook Servers` should be called `Kubeflow Notebooks` for the same reasons as `Kubeflow Pipelines` is called that. (Given the name Notebook Servers is ambiguous)

**Comment by terrytangyuan** [comment]
> @terrytangyuan can you clarify if you were referring to the (`Core Components` and `External Components`) names, or (`Components` and `External add-ons`)

I meant `Training Operators [rename from "Frameworks for Training"]` and (`Components` and `External add-ons`).

**Comment by thesuperzapper** [comment]
@Bobgy I strongly believe multi-tenancy should live under "Central Dashboard" as it's clearly not a "Component" but a "feature", and that feature is clearly related to the "Central Dashboard".

**Comment by kimwnasptd** [comment]
I would also agree with @RFMVasconcelos and prefer to stick with `Noteook servers` for now, since this sections describe how people can run Notebook servers on Kubeflow. I think that adding a Kubeflow prefix in-front will promote the notion that some Notebooks are Kubeflow while others are not.

Also regarding `Tensorboard` and `Volume Management`, I also believe that these should not be placed inside the `Notebook servers` section since there's no hard dependency between them. But we can definitely have the discussion of where to place these components in the future, once these components mature a little bit more and get more integrated with other Kubeflow components [ i.e. filtering PVCs that are mounted by a Notebook, Pipeline step etc ]

**Comment by thesuperzapper** [comment]
@RFMVasconcelos sounds like your proposal is a GO then, as stated in your comment https://github.com/kubeflow/website/issues/2536#issuecomment-809232345

**Comment by RFMVasconcelos** [comment]
I am OOO this week, but I will be back next Monday and will make a PR, if that's ok.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos As always, contributing is a volunteer thing, and I appreciate your effort, it has massively improved the docs for the community!

**Comment by shannonbradshaw** [comment]
@RFMVasconcelos PR #2626 should fix this issue. I believe we're done making changes now. #2626 is ready for review.

**Comment by RFMVasconcelos** [comment]
Thanks for this @shannonbradshaw :rocket:
