### ISSUE TITLE
Proposal: Add OWNERS to Components section

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2537]
I propose adding an OWNERS file to oversee the `Components` section of the website and off-load root OWNERS, accelerating PR review and merging. 

@Bobgy @joeliedtke @animeshsingh @8bitmp3 @thesuperzapper WDYT?

**Comment by 8bitmp3** [comment]
👍  @RFMVasconcelos

**Comment by Bobgy** [comment]
I don't see why that's necessary

If you move sth, you need to update redirect rules => requires root OWNERS.

If you create/update, each component's OWNERS should take the responsibility.

**Comment by RFMVasconcelos** [comment]
That is a good point @Bobgy, I had this in mind not exactly for this current refactor, where the changes are `mv`, which (point taken) need root approval anyway.

I was thinking that with this we would have one more layer of OWNERs to review and approve changes long-term, off-loading root, but I'm ok with having these changes run by root and have OWNERs for every individual component - there are a few missing like `metadata` but I can take a look into that.

In the meantime, @thesuperzapper proposed #2539, which would solve the same problem through more capacity in root.

**Comment by RFMVasconcelos** [comment]
Given @Bobgy's point, happy to close this.

/close
