### ISSUE TITLE
Deploy to GKE doc: master is hard coded in the command to download kfctl.sh

### ISSUE THREAD

**Issue by sijieamoy** [kubeflow/website#254]
https://www.kubeflow.org/docs/started/getting-started-gke/

Deploy Kubeflow on Kubernetes Engine, step 1 Run the following script to download kfctl.sh:

`curl https://raw.githubusercontent.com/kubeflow/kubeflow/master/scripts/download.sh | bash`

Should be:

`curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash`

Ideally also provide a way to help users choose which version to use.

**Comment by sarahmaddox** [comment]
Thanks for reporting this error! It seems to have been fixed now:

```
mkdir ${KUBEFLOW_REPO}
cd ${KUBEFLOW_REPO}
export KUBEFLOW_TAG=v0.3.1

curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
https://www.kubeflow.org/docs/started/getting-started-gke/
```
I'll close this issue but please do re-open it if the problem recurs.

/close
