### ISSUE TITLE
Kubeflow 1.3 release doc updates

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/website#2546]
Creating an issue to track updates preparing for Kubeflow 1.3 doc release.

**Comment by Bobgy** [comment]
I'm following https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#lifecycle.

I just forked current master branch as `v1.2-branch`, and pinned www.kubeflow.org to `v1.2-branch`.
It's OK to move forward with large changes preparing for the next release now.

**Comment by RFMVasconcelos** [comment]
Thank you for taking on this work @Bobgy !

**Comment by RFMVasconcelos** [comment]
I have just created #2547 #2548 #2549 #2550 #2551 to move all `platforms` under `distributions` 

cc @Bobgy @joeliedtke @animeshsingh @8bitmp3 @yanniszark

**Comment by thesuperzapper** [comment]
@RFMVasconcelos before we close this, I think we should make https://www.kubeflow.org/ default to master branch, as there is nothing 1.3 specific in master, (and it is much better structured).

Also we should resolve the issue about not having `v1.2` in the dropdown (https://github.com/kubeflow/website/issues/2564)

**Comment by RFMVasconcelos** [comment]
@thesuperzapper this is part of the [docs release process](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#version-the-website). I will follow these steps to have Kubeflow.org point to master and there will be v1.2 in the selector.

This is a state in transition. When we point it to `master` (by EOW latest) this will be resolved.

**Comment by RFMVasconcelos** [comment]
In fact, trying to do this now I realize this is [done on Netlify](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#changing-the-version-wwwkubefloworg-points-to) which I have not played with yet, I am not sure this is googlers only. I think @Bobgy did this for us in the previous release.

I think the best thing to do is for me to get the `master branch` ready to be pointed to, and @Bobgy, to point kubeflow.org to `master` once he feels comfortable with the status.

**Comment by RFMVasconcelos** [comment]
Sounds good @Bobgy ?

**Comment by thesuperzapper** [comment]
I think we can try and resolve https://github.com/kubeflow/website/issues/2536 before doing the master switch.

If your willing to make a PR @RFMVasconcelos?

**Comment by Bobgy** [comment]
Sure, for any netlify related steps. You can ping @joeliedtke or me about them.

**Comment by RFMVasconcelos** [comment]
Given the ETA for [release process](https://github.com/kubeflow/manifests/issues/1777) » Step 6: Tuesday, EOD 2021-04-06 [Pacific Time] 

Should we aim at pointing the docs to `master` at that same time? And push to have as many improvements as possible by then? 

@joeliedtke would you be able to make the necessary netlify changes by then? 

thoughts? @Bobgy @thesuperzapper @yanniszark @8bitmp3 @animeshsingh @castrojo

**Comment by Bobgy** [comment]
IIUC, I think we need to wait for at least most distributions are ready with their docs, so it will very likely be a later time than that date

**Comment by RFMVasconcelos** [comment]
That is a good point @Bobgy! 

It does raise some concerns - what if distribution X does not have the resources to update docs within the next months? In the past we added the "Outdated" banners to guide users to what docs are outdated, while not freezing improvements. 

I think that the current `v1.2-branch` is now at a worse state than `master`, so pointing docs to `master` would IMO add value to users and should be done sooner rather than later.

**Comment by thesuperzapper** [comment]
@Bobgy We should aim to point the docs at `master` on or before "Step 6" `EOD 2021-04-06 [Pacific Time]`

Note that "Step 6" is the offical release for Kubeflow 1.3 (From the OSS community perspective), as after that date a distribution could release Kubeflow 1.3 to their users. (There is no reason to penalise the faster distributions if the slow ones aren't ready)

Also, there is a case to point at `master` even earlier as  @RFMVasconcelos said, due to `master` being MUCH cleaner than `v1.2-branch`.

**Comment by Bobgy** [comment]
I don't understand the benefit, at that date, no distribution is ready to release and there can be issues found that require a rc1. Why would that be a date to switch to master branch?

I love the improvements in master branch, but as they are mostly information restructuring, I don't feel the urgency to release them. Can we wait until most of the next release is ready?

I think it's reasonable to set a cut date for doc when at least 2 distributions are ready. What do you think?

**Comment by thesuperzapper** [comment]
@Bobgy I think it's just semantics, as some of the smaller distributions will be ready in the first few days.

This is the same as how Kuberntes does not delay their release if GKE is not ready (just as an example, not picking on GKE).

Furthermore we would have to open the debate of what a "distribution" even means, as we have no validation process right now, which is not really a discussion we need to start just before 1.3 is released.

**Comment by Bobgy** [comment]
Can I confirm if we align on this?
Doc switch to master should happen after manifests cut 1.3.0 tag.

**Comment by RFMVasconcelos** [comment]
@Bobgy I agree that docs should only be released once people can use them in the equivalent release. 

I think this problem arrives from the fact that we're synchronizing a docs release with a docs restructuring, and so by holding off both, we keep users in a non-optimal information structure when we have a better alternative. 

I don't see urgency in pointing to master from the docs release, but I do see it from the docs restructure standpoint. 

I am unsure on what percentage of the docs is actually tied to a specific version of KF, I would say that the rate of change in docs has been fairly slow and that we likely will need only a few version-specific changes. 

WDYT?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @Bobgy I think its probably OK to move to point at `master` now, mostly as there is very little `1.3` specific docs, but the structure is MUCH better.

**Comment by RFMVasconcelos** [comment]
+1 ! :)

**Comment by Bobgy** [comment]
What do you think about merging master to v1.2 branch? If the restructuring is what you care about

**Comment by thesuperzapper** [comment]
@Bobgy this is a good idea, we should probably just take `master`'s commits and put them into `v.1.2`

**Comment by RFMVasconcelos** [comment]
+1. That is a good idea!

**Comment by RFMVasconcelos** [comment]
Are there any v1.3 specific commits we should cherry-pick out of this move? 

If not, I can simply make a PR to merge all the commits currently in `master` to `v1.2-branch`.

**Comment by RFMVasconcelos** [comment]
@Bobgy @thesuperzapper WDYT?

**Comment by Bobgy** [comment]
I am not aware of anything, +1 to merge branches.

**Comment by thesuperzapper** [comment]
@Bobgy +1 definitely lets do this ASAP as it will help users a lot with the better structure

I think you can go ahead and do this @Bobgy 

While there are a few more changes pending, we can do them after taking all the current `master` commits into `v1.2-branch`:
* Remove "Workstation Installation": https://github.com/kubeflow/website/issues/2565
* Refactor "Components": https://github.com/kubeflow/website/issues/2536#issuecomment-809232345
* Refactor "Getting Started": https://github.com/kubeflow/website/issues/2590

**Comment by RFMVasconcelos** [comment]
@Bobgy @thesuperzapper for reference I brought this up in the last community meeting and there were no objections. 

Also, nobody pointed out a v1.3 specific commit that should be left out. So I think we are good to go. I will make a PR today 🚀

**Comment by RFMVasconcelos** [comment]
@Bobgy, at what point do you think we should move the docs to point to `master` again?

**Comment by RFMVasconcelos** [comment]
There are a bunch of ongoing fixes being done in `master` - e.g. #2593 - which would be great to make effective

**Comment by RFMVasconcelos** [comment]
And unfortunately this is taking a bit longer as well #2612

**Comment by Bobgy** [comment]
@thesuperzapper I personally think as long as master branch is not confusing in obvious ways, it's okay to switch.

In previous releases, we wait until most distributions are ready, but I don't think that is necessary, as long as each distribution can release their docs on their own, it's fine.

**Comment by RFMVasconcelos** [comment]
@Bobgy I agree! 

#2612 has been merged, so we already have a good structure of the docs. :tada: But in any case, small fixes and updates are being done in master now that are relevant for v1.3 users - e.g. #2595. I propose we move to `master` branch as most [distributions appear now ready](https://github.com/kubeflow/manifests/issues/1798#issuecomment-823663721) for this release :)

**Comment by RFMVasconcelos** [comment]
I just realized that `GCP` and `Azure` appear not ready according to the list, we may want to wait for it to be the case as these are obviously big distributions :)

**Comment by RFMVasconcelos** [comment]
One great change we are working on is #2611 which would be amazing to have already as part of user journey today, as we release v1.3 with the new blog. 

@Bobgy do you think this is possible?

**Comment by RFMVasconcelos** [comment]
@Bobgy @joeliedtke @animeshsingh @thesuperzapper @castrojo @jbottum @cvenets @yanniszark @theadactyl 

We just merged the last PRs that IMO were critical for a successful v1.3 release, we now just need to point the website to `master` » #2633 for these changes to be effective :tada: @Bobgy @joeliedtke do you think you can review the master branch, verify if all is in order to proceed, and if so action #2633?

Many thanks to all for this push!

**Comment by thesuperzapper** [comment]
@Bobgy I think we are all good to make the switch to master tonight/ASAP, as we are about to release the 1.3 blog.

**Comment by Bobgy** [comment]
Discussed over the release meeting, I'm going to change website to master branch right now.
I'm going to sleep, so bear in mind someone still needs to change the version menu to 1.3.

**Comment by thesuperzapper** [comment]
To close out this issue, we just need to fix issue: https://github.com/kubeflow/website/issues/2657

I believe we can track other doc issues separately, for example:
1. "remove distribution docs from kubeflow.org" (issue: https://github.com/kubeflow/website/issues/2629)
2. "update component docs for Kubeflow 1.3" (issue: https://github.com/kubeflow/website/issues/2658)
3. "refactor About / Getting Started + create Concepts section"(issue: https://github.com/kubeflow/website/issues/2659)
4. "clean up Troubleshooting section" (issue: https://github.com/kubeflow/website/issues/2616)
5. "add "Resources" and organize content under it" (issue: https://github.com/kubeflow/website/issues/2491)

**Comment by RFMVasconcelos** [comment]
I've made a couple of PRs to solve #2657

**Comment by RFMVasconcelos** [comment]
@thesuperzapper @Bobgy could you please review and LGTM #2666 and #2667 ? :)

Thank you @thesuperzapper for listing what's left! Let's try to use the `Kubeflow Docs Restructure` project still for kanban.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos can you add me as an editor on that project? I cant add cards right now

https://github.com/kubeflow/website/projects/2

**Comment by RFMVasconcelos** [comment]
For sure! I thought this was open to the community, let me check how to open permissions

**Comment by RFMVasconcelos** [comment]
This is very strange, there is no `settings` where I can tweak projects permissions. Can others move cards in the [project](https://github.com/kubeflow/website/projects/2)?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I personally use [projects which are on the kubeflow organisation](https://github.com/orgs/kubeflow/projects), but if you are the owner of the docs refactor project, you should be able to:
1. Open the project
2. Click the Hamburger menu on the top right
3. Click the 3 dot menu
4. Click settings
5. Add Collaborators

**Comment by RFMVasconcelos** [comment]
@thesuperzapper thank you for the guidance! 

I don't see settings, maybe I am not an owner? I did create the project and am able to use it... 
![Screenshot from 2021-05-05 13-52-38](https://user-images.githubusercontent.com/27001378/117143934-44c87c00-ada9-11eb-90cd-15cffb2afce7.png)

@Bobgy do you see settings?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I created [a project on the kubeflow org](https://github.com/orgs/kubeflow/projects/45) for the docs and made you `admin` on it, everyone else is only a `reader` unless we explicitly add them).

It's probably easier to just move over to that one, where we have actual admin access, feel free to change the structure, etc.

**Comment by RFMVasconcelos** [comment]
@thesuperzapper thanks for this! 
LGTM

We can classify the current `Docs Restructure` project as finished, and track continuous improvements there. Lets start porting items to that board, and next week I will take some time to organize them if you don't get to it before me :)

**Comment by RFMVasconcelos** [comment]
I believe we can now close this tracking issue! 

Thank you all for the amazing work :)
