### ISSUE TITLE
Overview of Deployment on an Existing Kubernetes Cluster

### ISSUE THREAD

**Issue by sohailanjum97** [kubeflow/website#2561]
https://www.kubeflow.org/docs/started/k8s/overview/

as per the documentation the kubernetes 1.20 is not compatible with all the versions of kubeflow. Does anyone tested already if yes  suggest me something. 
Do I need to reinstall the kubernetes cluster and go to kubernetes version 1.14.? or is there any other solution like anyone tested any version of kubeflow with kubernetes 1.20.

**Comment by thesuperzapper** [comment]
Please refer to the new [Installing Kubeflow](https://www.kubeflow.org/docs/started/installing-kubeflow/) page for options relating to installing Kubeflow on existing clusters, the page you linked to has since been removed.

/close
