### ISSUE TITLE
Make v1.2 selectable on the version drop-down 

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2564]
Currently, you cannot select the v.1.2 docs branch on https://www.kubeflow.org/
![Screen Shot 2021-03-24 at 12 48 49](https://user-images.githubusercontent.com/5735406/112242388-e08da500-8c9f-11eb-9462-9d811133b130.png)

Additionally, think we should make the default branch `master` as soon as possible (and leave `master` as default until 1.4 is about to be released). This will mean that the "distributions" (and other) changes are displayed when a user goes to https://www.kubeflow.org/

**Comment by thesuperzapper** [comment]
What are your thoughts @RFMVasconcelos @Bobgy?

**Comment by RFMVasconcelos** [comment]
@thesuperzapper this is part of the [docs release process](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#version-the-website). I will follow these steps to have Kubeflow.org point to `master` and there will be `v1.2` in the selector. 

This is a state in transition. When we point it to Master (by EOW latest) this will be resolved.

**Comment by Bobgy** [comment]
@RFMVasconcelos is right on this. Let's track on the main issue https://github.com/kubeflow/website/issues/2546
