### ISSUE TITLE
Move "Workstation Installation"  under "Distributions"

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2565]
Currently, there is a confusing "Workstation Installation" page under "Getting Started" containing docs for the `MiniKF` and `MicroK8S Add-on` distributions.

Clearly they cannot be treated as special, and should be moved to "Distributions".
 
### Proposed structure (to split them up):

```
Distributions:
- MiniKF
   - Overview [renamed from  "Workstation Installation / MiniKF"
   - Deploy Kubeflow using MiniKF on AWS
   - Deploy Kubeflow using MiniKF on Google Cloud

- MicroK8S Add-on:
   - Overview [renamed from "Workstation Installation / Kubeflow on MicroK8s"
   - Kubeflow on Linux
   - Kubeflow on macOS
   - Kubeflow on Windows

- ...
```

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @Bobgy what do you think about moving "Workstation Installation" under "Distributions"?

**Comment by RFMVasconcelos** [comment]
@thesuperzapper I agree that both `MiniKF` and `MicroK8s` docs should live under distributions (this was part of my initial [proposal](https://github.com/kubeflow/community/pull/440/files)). 

In my view `Getting Started` should be a guide that maps to distributions. Today,

   - Kubeflow on Linux
   - Kubeflow on macOS
   - Kubeflow on Windows

map to a few distributions `MicroK8s`, `MiniKF`, `Minikube` (which is kfctl based). So my idea was to move any distributions out of that getting started and have just the map there.

**Comment by RFMVasconcelos** [comment]
I am happy to move both `MicroK8s` and `MiniKF` to distributions :) 

We then can think of what to do with those lists of `Kubeflow on X`

**Comment by RFMVasconcelos** [comment]
WDYT?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos if your willing to make the PR, I am willing to review!

**Comment by RFMVasconcelos** [comment]
@thesuperzapper definitely willing to do this :) I can only commit to early next week though, a bit oversubscribed until EOW. I suggest we don't block the pointing to master based on this. Does this sound reasonable?

**Comment by RFMVasconcelos** [comment]
I will try to get it done before!

**Comment by cvenets** [comment]
This sounds good to me as well for MiniKF. I would propose the following wording on the titles to be accurate and easily consumable by end users:

```
- MiniKF
    - MiniKF on AWS (via the Marketplace)
    - MiniKF on GCP (via the Marketplace)
    - MiniKF on laptop/desktop (using Vagrant)
    
- MicroK8S Add-on:
   - Overview [renamed from "Workstation Installation / Kubeflow on MicroK8s"
```

**Comment by RFMVasconcelos** [comment]
@cvenets I like it, my only concern is:
`(via the Marketplace)` adds clarity but will wrap. Maybe we can add it in the subtitle? 

I will ask our `MicroK8s` lead regarding the second one :)

**Comment by cvenets** [comment]
Maybe the following then?

```
- MiniKF
    - MiniKF on AWS Marketplace
    - MiniKF on GCP Marketplace
    - MiniKF on laptop/desktop
 ```

**Comment by Bobgy** [comment]
Totally agree with you!

**Comment by RFMVasconcelos** [comment]
@cvenets, just made a PR with the naming you suggested for MiniKF » #2576, please review so it is aligned with your messaging :)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos while we have merged https://github.com/kubeflow/website/pull/2577, what are we going to do with the remaining sections under "Getting Started"/"Workstation Installation":
`Kubeflow on Linux`, `Kubeflow on macOS`, `Kubeflow on Windows`

**Comment by RFMVasconcelos** [comment]
@thesuperzapper thank you for pointing this out! 

In my opinion, the next step is to refactor the [getting started page](https://www.kubeflow.org/docs/started/getting-started/). There has been some initial work on this [here](https://github.com/kubeflow/website/issues/2293), but we kind of left it for later.

Having now a good list of distributions, we can create the right map for them as "Getting started guide". Having that, the `Getting Started/Workstation Installation` list should become redundant and could be simply removed.

**Comment by cvenets** [comment]
@RFMVasconcelos I agree completely with you. Now that we moved everything under distributions the `Workspace Installation` section should just be removed. It is completely redundant, independently of what we do with the "Getting Started" page.

Also, now that we've fixed the distributions section and we also have instructions from the Manifests WG, IMHO the "Getting Started" page (https://master.kubeflow.org/docs/started/getting-started/) should become as simple as:

1. Do you want to install Kubeflow on your own?
   Please see the installation instructions provided by the Kubeflow Manifests WG here: https://github.com/kubeflow/manifests#kubeflow-manifests
2. Do you want to use a Kubeflow distribution?
   Please see all available Kubeflow distributions here: https://master.kubeflow.org/docs/distributions
   
This will make things much simpler, cleaner, and easier for the end user to navigate the structure, without looking at duplicate information.

What do you think? If you agree we can take a stab on this page if that would be helpful to you.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @cvenets I have raised a new proposal for the "Getting Started"/"Installing Kubeflow" structure.

https://github.com/kubeflow/website/issues/2590

**Comment by RFMVasconcelos** [comment]
Thank you for your proposals @cvenets and @thesuperzapper ! I have followed-up on #2590. 

As per the `Workstation Installation` list, I am happy to remove it, I think we should include some type of guidance of local installation in the new getting started section. I will add this in #2590.

**Comment by cvenets** [comment]
Thank you @RFMVasconcelos. Yes, let's remove it to close this issue, and we can discuss the Getting Started page in #2590 then. I've commented as well.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @cvenets I have created https://github.com/kubeflow/website/pull/2605, to resolve this (not sure if I should also remove other references to the deleted pages?)

**Comment by cvenets** [comment]
Yes, we should definitely delete all references to these pages, but I'm not sure how many of these exist. I'll let @RFMVasconcelos comment on this.
