### ISSUE TITLE
Version dropdown not visible on Mobile Chrome

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2568]
Currently the version dropdown is not visible on Mobile Chrome (even in desktop mode)

![Screenshot_20210324-154130](https://user-images.githubusercontent.com/5735406/112258036-ea240680-8cb9-11eb-8234-0a81e31533ae.png)

**Comment by thesuperzapper** [comment]
@Arhell said he would take a look at this https://github.com/kubeflow/website/pull/2705#issuecomment-841853647

**Comment by thesuperzapper** [comment]
@Arhell if you didn't know, you can also see this behaviour with chrome developer tools.

![Screen Shot 2021-05-17 at 10 27 05 am](https://user-images.githubusercontent.com/5735406/118414739-753ddd80-b6fa-11eb-805d-bd1852514700.png)

**Comment by Arhell** [comment]
@thesuperzapper can be closed

**Comment by thesuperzapper** [comment]
resolved by https://github.com/kubeflow/website/pull/2728

/close
