### ISSUE TITLE
Deploy using kubectl and kpt

### ISSUE THREAD

**Issue by drPytho** [kubeflow/website#2570]
https://master.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/#install-the-required-tools

Says that 
> Note: Prior to Kubeflow v1.2, Kubeflow was compatible only with Kustomize v3.2.1. Starting from Kubeflow v1.2, you can now use the latest Kustomize versions to install Kubeflow.

Since the [13th of Feb Kubeflow 4.0.0  was released](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.0.0) and does not seem to be working.

Would suggest updating the doc to represent this.

**Comment by SaschaHeyer** [comment]
agree with @drPytho 
https://github.com/kubeflow/kubeflow/issues/5755
