### ISSUE TITLE
Edit dex-auth parameters in the KfDef File

### ISSUE THREAD

**Issue by Dimiftb** [kubeflow/website#2587]
Hi everyone, 

I'm new to Kubernetes and Kubeflow. I've got a question regarding installing Kubeflow from this guide: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/

In particular this bit: 

<img width="847" alt="image" src="https://user-images.githubusercontent.com/26279721/113868519-a8aa5580-97a7-11eb-806a-467cfda3829e.png">

It says if default credentials need to be changed to edit the dex-auth application parameters in the KfDef file. The default credentials are nowhere to be seen in the file https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml 

I attempted to add them to it without success. I always get:
`well-defined vars that were never replaced: dex_domain,static_email,static_password_hash`

Could someone shed some light please? Thank you very much.

**Comment by yanniszark** [comment]
Hi @Dimiftb! This particular installation (`kfctl_istio_dex`) is not supported by any party in 1.2.
I would recommend trying out the instructions for Kubeflow 1.3 Release Candidate here: https://github.com/kubeflow/manifests/tree/v1.3.0-rc.0#readme

**Comment by Dimiftb** [comment]
Hi @yanniszark, 

Thank you very much. This new way to install components seems so much easier. One thing that's unclear to me, though is when I try to install the Kubeflow components here: 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/26279721/113881343-40ae3c00-97b4-11eb-96e5-9fcdffd6212f.png">

I get:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/26279721/113881146-1197ca80-97b4-11eb-8853-8349a0edf9d4.png">

What do I have to do before installing the components with kustomize?

**Comment by Dimiftb** [comment]
For anyone else wondering until they update the docs.

You can simply clone repository, then

since kustomize v4.0 flags are different: 

`--load_restrictor` becomes `--load-restrictor` and `none` becomes `LoadRestrictionsNone` 

E.G. `kustomize build --load-restrictor=LoadRestrictionsNone common/kubeflow-roles/base | kubectl apply -f -`

I'm closing this now, appreciate your help @yanniszark.
