### ISSUE TITLE
Change UI component of GKE end-to-end guide to not use a separate IP address

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#260]
The initial version of the GKE end-to-end guide ([PR #151](https://github.com/kubeflow/website/pull/151)) uses a separate IP address for the web UI. 

Since we go to the trouble of setting up a static domain earlier on, we shouldn't use a separate IP address in the web UI step. One approach could be to add a service definition similar to tf-hub-lb or central-dashboard.

**Comment by sarahmaddox** [comment]
@amygdala I'm tempted to close this issue as obsolete. WDYT? Here's the [doc](https://www.kubeflow.org/docs/gke/gcp-e2e/#access-the-web-ui-in-your-browser) and the related [sample README](https://github.com/kubeflow/examples/blob/master/mnist/README.md)

**Comment by amygdala** [comment]
yes, IIRC that got addressed... let's close it.
