### ISSUE TITLE
Blog Posts

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2601]
https://www.kubeflow.org/docs/examples/blog-posts/

It seems that we are not pointing to the latest blogs from here. I would suggest a simple link to [Kubeflow blog](https://blog.kubeflow.org/).

**Comment by thesuperzapper** [comment]
This is part of the https://github.com/kubeflow/website/issues/2807 proposal, I will close this for now so we can discuss there.

/close
