### ISSUE TITLE
Broken link on install page

### ISSUE THREAD

**Issue by akhimji** [kubeflow/website#2602]
https://www.kubeflow.org/docs/other-guides/kustomize/#specifying-a-configuration-file-when-initializing-your-deployment

When you install Kubeflow, the deployment process uses one of a few possible YAML configuration files to bootstrap the configuration.  ---> You can see all the configuration files on GitHub. <---

points to  (https://github.com/kubeflow/manifests/tree/master/kfdef)

**Comment by RFMVasconcelos** [comment]
Fix merged.

/close
