### ISSUE TITLE
Upgrade the GKE end-to-end guide to latest Kubeflow version

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#261]
The initial version of the GKE end-to-end guide ([PR #151](https://github.com/kubeflow/website/pull/151)) uses Kubeflow v0.2.7. We should upgrade to v0.3 with `kfctl` and test the entire procedure end to end.

**Comment by sarahmaddox** [comment]
Progress update: I've chatted with the engineer who wrote the sample used in the GKE end-to-end guide (@DanSanche). He will upgrade the sample, then we can upgrade the docs. Time estimate for the sample update is January.

**Comment by DanSanche** [comment]
If 0.4 is ready by the time I'm able to get to this, should we skip 0.3 and just update the sample to 0.4? Or would it be helpful to have a 0.3 sample either way?

**Comment by sarahmaddox** [comment]
If 0.4 is ready by the time you start, then yes, let's skip 0.3. Ideally we should keep the sample up to date with the latest release. That said, I don't think the jump from 0.3.4 to 0.4 will be as big as the jump from 0.2 to 0.3.4, in terms of this particular tutorial. So, don't wait for 0.4 if it's not available when you're ready to start.

**Comment by jlewi** [comment]
There is an RC for 0.4 available now.

**Comment by jlewi** [comment]
Can we update the End to End Guide to refer to the getting started instructions rather than duplicating the instructions for setting up Kubeflow?

**Comment by sarahmaddox** [comment]
I'll look at doing that when the GKE getting-started guide is in better shape, so that we have a good landing for the link from the e2e guide. Ideally, people doing the end-to-end tutorial should be able to do the setup entirely in the UI, but that's not clear in the getting-started guide at the moment. We need to make sure people don't get confused by instructions that don't apply to them. Fixing up the getting-started guide is next on my list of items to tackle. See issue [#384](https://github.com/kubeflow/website/issues/384).

**Comment by sarahmaddox** [comment]
/assign

I'm working with @DanSanche on this issue.

**Comment by sarahmaddox** [comment]
Starting the doc upgrade now.
