### ISSUE TITLE
Clean up `Troubleshooting` section

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2616]
Following the latest community discussions and the Kubeflow docs restructure [proposal](https://github.com/kubeflow/community/pull/440/files), we should add the concept of "Troubleshooting", with the following structure:

- **Troubleshooting** (created with files from current section "Further Setup and Troubleshooting")
  - Frequently Asked Questions
  - Troubleshooting
  - Usage Reporting
  - Support

**Comment by thesuperzapper** [comment]
I am closing this in preference of https://github.com/kubeflow/website/issues/2760, feel free to reopen if we want to make a troubleshooting section again in the future.
/close
