### ISSUE TITLE
Refactor `About` and `Getting Started` sections to `Getting started` and `Community`

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2617]
In order to finish the effort started in [Docs Restruture Proposal](https://github.com/kubeflow/community/pull/440), we should make the required changes to get to the following structure:

- **Getting started**
  - Introduction (current About/Kubeflow)
  - Getting started (current `Getting started/Installing Kubeflow` updated to guide users to platforms & methods)
  - Concepts (current Kubeflow Overview)
  - Use Cases (current About/Use Cases)
  - Install Kubeflow (current `Installing Kubeflow`, to redirect to `Deployment` homepage)

- **Community** 
  - About (current About/Community)
  - Contributing (current About/Contributing to Kubeflow + details on Working Groups)
  - Documentation (merge current About/Docs + About/Style Guide for Kubeflow docs)
  - Events (current About/Events Calendar)
  - Google Summer of Code (current About/Google Summer of Code)

**Comment by thesuperzapper** [comment]
I think this isn't quite the best structure approach, I think we can leave the community and project wide stuff under the "About" section.

I have raised an alternate issue to discuss this option: https://github.com/kubeflow/website/issues/2659

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I think this isn't quite the best structure approach, I think we can leave the community and project wide stuff under the `About` section.

I have raised an alternate issue to discuss this option: https://github.com/kubeflow/website/issues/2659

**Comment by RFMVasconcelos** [comment]
@thesuperzapper I agree that there is room to improve. Let's discuss on #2659 

/close
