### ISSUE TITLE
Google search results show "An error occurred" as the title for about/kubeflow

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#2618]
See this screenshot:
![Screen Shot 2021-04-15 at 9 10 04 PM](https://user-images.githubusercontent.com/1447785/114957649-7647ca80-9e2f-11eb-823c-7e1909586496.png)

Potentially relevant:
https://stackoverflow.com/questions/38943067/snippet-in-google-search-contains-an-error-occurred-try-watching-this-video-on

**Comment by RFMVasconcelos** [comment]
Nice catch @shannonbradshaw! This is odd. The link points to the [About Kubeflow page](https://www.kubeflow.org/docs/about/kubeflow/).

@Bobgy @joeliedtke would you have an insight on how to fix this?

**Comment by shannonbradshaw** [comment]
@Bobgy or @joeliedtke any thoughts on this. It's pretty ugly when someone does a Google search for Kubeflow.

**Comment by Bobgy** [comment]
This is strange, could it be a temporary failure when a google bot was scanning the website?
I'll try to debug this

**Comment by shannonbradshaw** [comment]
@RFMVasconcelos @Bobgy I submitted PR #2655 as an attempt to fix this. See my comments there about my hypotheses. Happy to take other suggestions.

**Comment by Bobgy** [comment]
/reopen
Let's keep it open until we verify the fix.
I will ask from Google side if I can access google search site management for kubeflow.org to request a reindex

**Comment by shannonbradshaw** [comment]
This is fixed.

![Screen Shot 2021-04-29 at 12 43 34 PM](https://user-images.githubusercontent.com/1447785/116587992-033b5b00-a8e9-11eb-965c-39bed5821f61.png)

**Comment by Bobgy** [comment]
Ohhh great, thank you so much @shannonbradshaw!

Didn't have time to check how to force a re index, looks like it just happened automatically

**Comment by RFMVasconcelos** [comment]
Awesome job @shannonbradshaw 🎉
