### ISSUE TITLE
Outdated "Tutorial: End-to-end Kubeflow on GCP"

### ISSUE THREAD

**Issue by halvgaard** [kubeflow/website#2619]
The end-to-end KubeFlow GCP tutorial https://www.kubeflow.org/docs/gke/gcp-e2e/
contains an out of date warning:
"Out of date: This guide contains outdated information pertaining to Kubeflow 1.0. This guide needs to be updated for Kubeflow 1.1."

Does the tutorial work or is this simply a warning because the version changed? I plan to run this tutorial soon and could provide feedback.

Also the "tf.train" link is broken. Should be: https://www.tensorflow.org/api_docs/python/tf/train and not "api_guides/python/train"

**Comment by shannonbradshaw** [comment]
@halvgaard did you run this tutorial to see whether it still works?

**Comment by halvgaard** [comment]
@shannonbradshaw I have been playing around with AI platform Pipelines on GCP instead to avoid all the cumbersome KubeFlow setup steps. Unless Pipelines is thrown out of GCP when AI platform Unified takes over, then I might just stick with that. Would still like to know if someone managed to run through this without problems due to the flagged updates mentioned.

**Comment by halvgaard** [comment]
I am trying to run the notebook but fails with "module 'kubeflow.fairing' has no attribute 'cloud'. I also had to install a missing package "msrestazure". So stuck here right now.

**Comment by halvgaard** [comment]
The tutorial link is broken now. Assume it has been moved here: https://www.kubeflow.org/docs/examples/kubeflow-samples. But without the original text and links. So guess we can close this one.
