### ISSUE TITLE
Remove unsupported Metadata component from the docs

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#2631]
kubeflow/metadata appears to be dropped from KF:
- UI: https://github.com/kubeflow/manifests/pull/1619
- Backend: https://github.com/kubeflow/manifests/pull/1638
- Centraldashboard entries: https://github.com/kubeflow/kubeflow/pull/5404
Do we agree that it should be dropped from the docs as well?

**Comment by shannonbradshaw** [comment]
cc: @RFMVasconcelos @Cventes

**Comment by Bobgy** [comment]
+1, we should remove it.

Pipelines WG will start adding new metadata doc as part of Pipelines.

/Cc @kubeflow/wg-pipeline-leads

**Comment by thesuperzapper** [comment]
@Bobgy did you make a tracking issue to add metadata docs under the pipelines section?

I am a bit worried that users will never see it, given how many docs are in the pipelines section.
