### ISSUE TITLE
Broken Links on KF Operator -> Installing Kubeflow docs

### ISSUE THREAD

**Issue by D1o0g9s** [kubeflow/website#2632]
https://www.kubeflow.org/docs/distributions/operator/install-kubeflow/

First 3 links on the documentation are broken:
1. Operator -> introduction <- 
2. -> Install the Kubeflow Operator <-
3. Kubeflow -> manifests <-

**Comment by himanshu9345** [comment]
@RFMVasconcelos , Can you please assign this to me?

**Comment by RFMVasconcelos** [comment]
@himanshu9345 I can :) 

/assign @himanshu9345 

For future reference, you are able to assign issues to yourself by commenting `/assign`
