### ISSUE TITLE
change target branch to master

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2633]
As discussed in https://github.com/kubeflow/website/issues/2546#issuecomment-823431454, and as part of the [Kubeflow release process](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#version-the-website), we should move the default `kubeflow.org` branch target back to `master`.

This will allow users to actually see the 1.3 specific docs when they browse to https://kubeflow.org

**Comment by thesuperzapper** [comment]
@Bobgy I think you are the only one who can do this!

**Comment by Bobgy** [comment]
Did we discuss this in the community meeting and agree on a timeline?
/cc @joeliedtke 

I can do this upon a agreed date.

**Comment by RFMVasconcelos** [comment]
+1 to the priority of this step.

**Comment by thesuperzapper** [comment]
@Bobgy we plan to publish the 1.3 blog in a few hours, if possible can you do this change ASAP?

cc @castrojo

**Comment by Bobgy** [comment]
Done
