### ISSUE TITLE
content navbar is not readable

### ISSUE THREAD

**Issue by lluunn** [kubeflow/website#264]
<img width="347" alt="screen shot 2018-10-15 at 14 29 14" src="https://user-images.githubusercontent.com/32310205/46979528-b8d59400-d086-11e8-9b51-51664f6e5bf4.png">

**Comment by sarahmaddox** [comment]
+1. I'm currently investigating a different theme for the Kubeflow website (Docsy) which will help solve this issue.

**Comment by sarahmaddox** [comment]
The Docsy theme is now live on the site, and this issue is fixed.
/close
