### ISSUE TITLE
Installation page: Roll your own option should be first, distributions should follow

### ISSUE THREAD

**Issue by cvenets** [kubeflow/website#2644]
@RFMVasconcelos from your comment in the corresponding PR:
https://github.com/kubeflow/website/pull/2611#issuecomment-824698167

I understand that you needed to merge to unblock and move forward, but I don't think that we had community consensus for changing the ordering of options, from my initial suggestion here:
https://github.com/kubeflow/website/issues/2590
which triggered the whole refactoring in the first place.

There were specific reasons I proposed having the "roll your own" option first:

1. The section is very short, so the reader can skim through it very fast and decide without having to scroll a big table until they reach to it. Both options show in the screen without having to scroll.
2. We actually now have a single-line command to install everything on any conformant Kubernetes cluster, if someone strives just for ease of use. This is actually much easier to install than most of the distributions, if one looks at the rest of the docs. 
3. We want people to test this and report bugs, so that the Manifests WG can fix early.

So, I think we should bring back the ordering to what it was in the original proposal and PR.

**Comment by thesuperzapper** [comment]
I strongly believe we should encourage users to  make use of supported distributions, if only so that environment-specific issues do not spam our issue trackers.

Additionally, installing using the manifests is the more advanced option, and so it makes very little sense to include it first.

**Comment by RFMVasconcelos** [comment]
I am open to either option. I do believe that users will find it harder to install directly from the manifests than from packaged distributions and that advanced options normally come later. But I am open to acting on any community decision.

**Comment by shannonbradshaw** [comment]
So @thesuperzapper and @Bobgy are both speaking in favor of encouraging users to make use of supported distributions on this thread. Can we please get Arrikto Enterprise Kubeflow listed among distributions in the docs? It is a VERY well supported distribution. There is a well-funded company built entirely around supporting this distribution. How about it?

**Comment by thesuperzapper** [comment]
Given the discussion, I will close this.
/close
