### ISSUE TITLE
The installation page does not mention anything about installing Kubeflow on local / standalone kubernetes cluster

### ISSUE THREAD

**Issue by nikhilbandi** [kubeflow/website#2651]

**Comment by RFMVasconcelos** [comment]
Thank you for this feedback @nikhilbandi. I have created a PR that improves readability. 

For reference you have 2 options - [manifests](https://github.com/kubeflow/manifests#installation), or a distribution from the list. Each distribution has their own docs. You have platform specific distributions, such as `Kubeflow on GCP` and multi-platform distributions, e.g. `Charmed Kubeflow Operators`
