### ISSUE TITLE
update doc version dropdown with v1.3

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2657]
We have set the target branch of https://kubeflow.org to `master` (see https://github.com/kubeflow/website/issues/2633).

However, the dropdown box on the top right has `v1.2`, we should update this to name `master` as `v1.3`.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos are you able to do this?

**Comment by RFMVasconcelos** [comment]
Thanks for bringing this up @thesuperzapper! 

I have just created 2 PRs that should fix this. 

cc @Bobgy

**Comment by berndverst** [comment]
@RFMVasconcelos I reviewed both PRs. Looks good - thanks for doing this.

**Comment by RFMVasconcelos** [comment]
Awesome! Both have been merged! Thank you @berndverst. 

/close

**Comment by RFMVasconcelos** [comment]
It is officially working! :)

**Comment by RFMVasconcelos** [comment]
cc @thesuperzapper @Bobgy
