### ISSUE TITLE
update component docs for Kubeflow 1.3

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2658]
Currently, we have released Kubeflow 1.3, but have not updated the [component docs](https://www.kubeflow.org/docs/components/).

__This issue is to track the progress of each components docs:__
- [ ] central dashboard 
   - Docs Link: https://www.kubeflow.org/docs/components/central-dash/
   - Tracking Issue: #2664
- [x] notebook servers
   - Docs Link: https://www.kubeflow.org/docs/components/notebooks/
   - Tracking Issue: https://github.com/kubeflow/website/issues/2637
- [x] kubeflow pipelines
   - Docs Link: https://www.kubeflow.org/docs/components/pipelines/
   - Tracking Issue: _TBA_
- [x] kfserving
   - Docs Link: https://www.kubeflow.org/docs/components/kfserving
   - PR: https://github.com/kubeflow/website/pull/2595
- [x] katib
   - Docs Link: https://www.kubeflow.org/docs/components/katib/
   - Tracking Issue: _TBA_
- [x] training operators
   - Docs Link: https://www.kubeflow.org/docs/components/training/
   - Tracking Issue: _TBA_

**Comment by thesuperzapper** [comment]
Can the WG leads please create an issue for their component and link it here?

@kubeflow/wg-notebooks-leads (Central Dashboard, Notebooks)
@kubeflow/wg-pipeline-leads (Pipelines)
@kubeflow/wg-serving-leads (KFServing)
@kubeflow/wg-automl-leads (Katib)
@kubeflow/wg-training-leads (Training Operators)

**Comment by yuzisun** [comment]
@thesuperzapper serving WG has already finished up the doc update for 1.3! 
https://github.com/kubeflow/website/pull/2595

**Comment by terrytangyuan** [comment]
I believe the docs for training operators have been done previous, e.g. https://github.com/kubeflow/website/pull/2586.

**Comment by andreyvelich** [comment]
The Training and AutoML WG docs have been updated already.
cc @kubeflow/wg-automl-leads @kubeflow/wg-training-leads

**Comment by RFMVasconcelos** [comment]
@thesuperzapper thank you for this! I have created an issue to track central dashboard (#2664) - I think that we should have 1 docs page per tab in the central dashboard, WDYT?

**Comment by Tomer23** [comment]
The component doc for [multi-tenancy](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually) also needs updating:

In 1.3 kf uses istio 1.9 which depreciated rbac.istio.io/v1alpha1/ServiceRoleBinding and replaced it with AuthorizationPolicy. The doc for manual profile creation does not reflect that.

**Comment by thesuperzapper** [comment]
Bumping, as there are still component docs which have not been updated for Kubeflow 1.3.

**Comment by thesuperzapper** [comment]
Closing because 1.3 came out a long time ago.
