### ISSUE TITLE
Refactor `About` / `Getting Started` + create `Concepts` section

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2659]
I believe we should refactor the `About` / `Getting Started` sections, and create a new `Concepts` section.

__For example, the structure could be:__
```
About:
- Introduction 
   - (move from: about/kubeflow)
- Use Cases 
   - (move from: about/use-cases)
- Official Blog 
   - (new page) 
   - link to the blog
- Official Slack 
   - (new page) 
   - link to slack inviter
- Contributing to Kubeflow 
   - (move from: about/contributing)
   - give practical tips for how to get involved in the project 
   - move all current contributing guides under here, like docs
- Report issues with Kubeflow
   - (new page) 
   - point people to the correct git-repo for issues on components
   - ** this name can change, but the idea is how to get in touch with the devs
- Working Group Calendars
   - (new page) 
   - link to the WG-managed calendars

Getting Started:
- Installing Kubeflow

Concepts:
- Overview
   - (move from: started/kubeflow-overview)
- Multi-Tenancy 
   - (move from: components/multi-tenancy)
```

**Comment by shannonbradshaw** [comment]
I think we should deal with Multi-Tenancy in a separate issue. It's not really related to the about/intro material in the same way the rest of the sections we're discussing here are.

**Comment by shannonbradshaw** [comment]
@thesuperzapper in addition to leaving multi-tenancy out of scope for this issue, I suggest at least the following two changes to what you've proposed above:
1. Integrate the content in started/kubeflow-overview and about/kubeflow into a single page called "Introduction to Kubeflow" under "About". Also, I think the content in these pages (at least in about/kubeflow) should be edited to remove outdated or unnecessary information.
2. Move "Installing Kubeflow" to the top-level in the Table of Contents and eliminate the "Getting Started" section.

**Comment by RFMVasconcelos** [comment]
Thank you for working on this proposal @thesuperzapper! 

I like @shannonbradshaw 's additions. If we were to keep "Getting Started", I would suggest moving "Contributing to Kubeflow" under it, as it is also an onboarding. But I +1 moving install to top navigation.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos and @shannonbradshaw I have made a new issue for moving the `Installing Kubeflow` section to the root, as I think it's a pretty non-controversial change on its own.

We can discuss splitting/changing/etc the `About` section after we move `Installing Kubeflow`

**Comment by thesuperzapper** [comment]
@RFMVasconcelos and @shannonbradshaw Oops, I forgot to link the issue: https://github.com/kubeflow/website/issues/2671

**Comment by thesuperzapper** [comment]
I am closing this in favour of a more specific proposal for only the `about` section: https://github.com/kubeflow/website/issues/2807

/close
