### ISSUE TITLE
Update Kubeflow dashboard docs for v1.3

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2664]
With the Kubeflow v1.3 release, the central dashboard has changed with new tabs and functionalities. 

There should be an update in documentation with screenshots to guide navigation. 

cc @kubeflow/wg-notebooks-leads 

__This issue is to track the progress of each page:__
- [ ] central dashboard overview
   - Docs Link: https://www.kubeflow.org/docs/components/central-dash/overview/
   - Tracking Issue: _TBA_
- [ ] registration flow
   - Docs Link: https://www.kubeflow.org/docs/components/central-dash/overview/
   - Tracking Issue: #2665
- [ ] Volumes tab (NEW)
   - Docs Link: new
   - Tracking Issue: _TBA_
- [ ] Tensorboard (NEW)
   - Docs Link: new
   - Tracking Issue: _TBA_

**Comment by kimwnasptd** [comment]
Hey @RFMVasconcelos, I can take a stab at updating the images for the Central Dashboard, and the Registration Flow, as well as updating the list of items that belong to the dashboard https://www.kubeflow.org/docs/components/central-dash/overview/#overview-of-kubeflow-uis.

Also note that the 1.3 dashboard will not have an entry for `Models`. We will add it soon, but it's not part of the 1.3 release. But we can definitely also track the new `Tensorboards` item in that list as well.

**Comment by kimwnasptd** [comment]
Assigning myself to work for the first two items, but I can work on the other two once we discuss where we want to add the extra apps for Volume Management and Tensorboard.

cc @shannonbradshaw @cvenets 
/assign @kimwnasptd

**Comment by RFMVasconcelos** [comment]
Thank you for your help and clarifications @kimwnasptd !! 🚀 

> once we discuss where we want to add the extra apps for Volume Management and Tensorboard.

For clarity, what do you mean? where the docs will sit?
