### ISSUE TITLE
IAP config files outdated! 

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2668]
IAP config files are outdated, are they still relevant?

According to the [website release guide](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#updating-version-numbers-etc-for-the-upcoming-release-major-minor-or-patch) this should be updated in every release. However there are some that still are in version v0.7

@Bobgy @joeliedtke any ideas of how to update / remove this?

**Comment by zijianjoy** [comment]
Thank you @RFMVasconcelos ! I am going to update GCP related documentations. At that time I can validate and update the IAP config and other GKE items too.

**Comment by RFMVasconcelos** [comment]
Great @zijianjoy, thank you!

@Bobgy @andreyvelich @animeshsingh @Tomcli for things like istio, istio-dex, openshift, ibm. Could you take a look into updating or deprecating these files? What action makes sense here? :)

![image](https://user-images.githubusercontent.com/27001378/116688882-3f38f380-a9af-11eb-97be-8d1a0ff0c17c.png)

**Comment by Tomcli** [comment]
We can take care the IBM files
cc @nakfour @vpavlin for the openshift documentation

**Comment by RFMVasconcelos** [comment]
unstale
