### ISSUE TITLE
Split `Getting Started` into `Installing Kubeflow` and `Concepts`

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2671]
The `Getting Started` section has become very small.

__I think there is significant benefit if we do the following:__
1. Move the `Installing Kubeflow` page to the root of the docs
    * this will let users immediately see where they can learn how to install Kubeflow
2. Create a new `Concepts` section at the root
    * this section will cover core principals/features which span across all components
3. Move the `Getting Started/Kubeflow Overview` page to `Concepts`
4. Move the `Components/Multi-Tenancy` page to `Concepts`

__NOTE:__ Obviously we will update the `Kubeflow Overview` and `Multi-User` pages, but we should do this AFTER we move them to their new home.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos if you agree do you have capacity to make this change?

**Comment by thesuperzapper** [comment]
@shannonbradshaw thoughts?

**Comment by thesuperzapper** [comment]
@shannonbradshaw I think you might have misunderstood what I was proposing.

My proposal would result in the following structure:
```
About (NO CHANGE)
- Introduction to Kubeflow (NO CHANGE)
- ...

Concepts (NEW SECTION)
- Conceptual Overview (MOVED OUT OF: "Getting Started")
- Multi-Tenancy (MOVED OUT OF: "Components")

Installing Kubeflow (MOVED OUT OF: "Getting Started")

Components (NO CHANGE)
- Central Dashboard (NO CHANGE)
- ...

External Add-Ons (NO CHANGE)
- Istio (NO CHANGE)
- ...

...
```

__NOTE:__ This is an iterative step, we should re-factor/split-up the `About` section __next__

Also, I strongly disagree with putting `Multi-Tenancy` at the root, and believe we need to create a `Concepts` section, as there will certainly be more high-level design concepts we want to highlight to users.

Also, what are your thoughts about this @RFMVasconcelos?

**Comment by thesuperzapper** [comment]
As a side note, I think we should rename "Installing Kubeflow" to "Deploying Kubeflow" as this better covers managed services, (which aren't "Installed")

**Comment by RFMVasconcelos** [comment]
Do feel free to ping me on any priority thread that you need my eyes on :)

**Comment by shannonbradshaw** [comment]
@thesuperzapper I did not misunderstand. I simply disagree and provided a rationale as to why. It sounds like you disagree with what I'm proposing, but I have not seen you state a rationale as to why you oppose placing multi-tenancy at the top level. Also, I'm not sure I've seen a rationale as to why you believe started/kubeflow-overview should be placed in the same section. Why would we place a conceptual overview together with a topic like multi-tenancy in the same section?

**Comment by thesuperzapper** [comment]
@shannonbradshaw my assumptions/logic is:
1. We want to provide a "feature" view of Kubeflow in the docs, rather than only a component view like right now
   * Therefore, we should create a new top-level section of the docs called `Features` (or `Concepts`)
1. The `Features` section should have an "overview" page
   * Therefore, we can use `started/kubeflow-overview` as a stating point for this "overview"
1. `Multi-Tenancy` is a "feature" of the platform  (which cut across multiple components)
   * Therefore, `Multi-Tenancy` should live in the `Features` section

Note, because we will have more "features" than just `Multi-Tenancy` we dont want to put it at the top level on its own.

What part are you disagreeing with?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos did you get a chance to look at this split, as described in: https://github.com/kubeflow/website/issues/2671#issuecomment-829723462

**Comment by RFMVasconcelos** [comment]
It looks like we are tackling 3 problems here: 

1. Installing Kubeflow to top level. > everyone seems to agree with the move
2. What to do with `multi-tenancy`? > no consensus yet > Started issue #2736
3. Where to move `Getting started/Kubeflow overview` to remove `Getting Started` 

I would suggest actioning move (1), discuss (2) in #2736 and move (3) under about so we can remove `Getting Started` and then we refactor all things under about. 

WDYT?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos sounds good if you want to make PR's, I will review.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos  I actually think we can keep `Installing Kubeflow` under `Getting Started`, allowing us to add other pages to `Getting Started` as well.

For example, we could add an `Getting Started / Examples` page, like I proposed in https://github.com/kubeflow/website/issues/2759

**Comment by thesuperzapper** [comment]
I am going to close this in preference of leaving the "Getting Started" section, so https://github.com/kubeflow/website/issues/2760 and https://github.com/kubeflow/website/issues/2759 can add things to the Getting Started section.

Regarding "Concepts" I think we can place them under "Getting Started" also, as proposed in: https://github.com/kubeflow/website/issues/2803
