### ISSUE TITLE
Rendering style for <code> inside a note is barely legible

### ISSUE THREAD

**Issue by evilnick** [kubeflow/website#2677]
The style for `<code>` elements of docs inside a note renders as a very light grey which is barely legible. For example:

```
{{% alert color="warning" %}}
To deploy `kubeflow`, you'll need at least 50Gb available of disk, 14Gb of RAM, and 2 CPUs available in your machine/VM.
If you have fewer resources, deploy `kubeflow-lite` or `kubeflow-edge`.
[/note]
{{% /alert %}}
```

Renders as:

![Screenshot from 2021-04-29 13-04-19](https://user-images.githubusercontent.com/115290/116548550-4d720b80-a8ec-11eb-9111-62cf42ab6dc8.png)

**Comment by RFMVasconcelos** [comment]
I believe this has been fixed. 

/close
