### ISSUE TITLE
improve the `Kubeflow Pipelines`docs

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2683]
Currently, the `Components / Kubeflow Pipelines` section is very hard to navigate:
https://www.kubeflow.org/docs/components/pipelines/

__Some ideas:__
1. Create an `Overview` "landing" page:
    * users should go here first, to start their "Pipelines" docs journey
    * explain what pipelines does, and point to "next steps" of what the user should read
    * NOTE: there is the `Pipelines Quickstart` but this is about "how to deploy", not "what is pipelines"
1. Remove the `Upgrading` page:
   * right now it's just a link to upgrade GCP's distribution of Kubeflow...
1. Move `Multi-user Isolation for Pipelines` under `Understanding Pipelines`
   * this helps de-clutter the root of the docs tree
1. Move `Caching` under `Understanding Pipelines`
   * this helps de-clutter the root of the docs tree
1. Rename `Building Pipelines with the SDK` to `Pipelines SDK`
   * prevents the text wrapping, and is more clear

**Comment by thesuperzapper** [comment]
@kubeflow/wg-pipeline-leads what are your thoughts on these suggestions?

**Comment by Bobgy** [comment]
/cc @joeliedtke 
already has some plans to improve, can you take a look?

**Comment by thesuperzapper** [comment]
@Bobgy I still think points 2/3/4/5 are important (and can be easily done with a very small PR).

Point 1 is a bit more work so can be discussed later.

Do you want us to make the PR (for you to approve), or does someone on pipelines want to do it?

**Comment by thesuperzapper** [comment]
This issue will be resolved by https://github.com/kubeflow/website/pull/3063
