### ISSUE TITLE
create visual separation for the expanded docs sections

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2684]
Currently, its not clear which sub-sections are under the currently expanded heading, what can we do to visually distinguish, the currently expanded headings?

__Kubeflow Pipelines Example (Current State):__
![Screen Shot 2021-04-30 at 12 49 04 pm](https://user-images.githubusercontent.com/5735406/116642540-7e1c7880-a9b2-11eb-863d-ce476e6e1577.png)

__Kubeflow Pipelines Example (With vertical bars):__
![Screen Shot 2021-04-30 at 12 49 04 pm](https://user-images.githubusercontent.com/5735406/116642880-26cad800-a9b3-11eb-8a08-2f6d253ff2ad.png)

Mockup is not the best, but you get the idea of what I am trying to achieve.

Thoughts?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @shannonbradshaw what are your thoughts?

**Comment by RFMVasconcelos** [comment]
Sure, I think this adds clarity. Maybe a simpler to implement method is to make every expanded section `active`:

![image](https://user-images.githubusercontent.com/27001378/116692582-7c53b480-a9b4-11eb-86b3-35ec88c94c9d.png)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos The behaviour of the menu has changed after the docsy update from https://github.com/kubeflow/website/pull/2705.

Now only the "expanded" sections are visible, this is more clean, but I am not sure if its better for users, as they might not realise there are more sections to view:
![image](https://user-images.githubusercontent.com/5735406/121463845-e4aba200-ca06-11eb-9b9c-be550693ce4d.png)

**Comment by thesuperzapper** [comment]
Closing because as stated in https://github.com/kubeflow/website/issues/2684#issuecomment-858285392, the behavior has changed, reducing the need for a seperator.
