### ISSUE TITLE
create `priority/p3` tag

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2695]
Currently we cant ask the bot to `/priority p3` as this tag is missing from the repo.

We should add it, just like it exists on `kubeflow/kubeflow`: 
https://github.com/kubeflow/kubeflow/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2Fp3

**Comment by thesuperzapper** [comment]
@Bobgy since you are one of the only "writers" on the repo, can you do this?

**Comment by Bobgy** [comment]
Sure, just configured that
