### ISSUE TITLE
Install Kubeflow on OpenShift contains broken markdown and invalid kfDef link

### ISSUE THREAD

**Issue by ptitzler** [kubeflow/website#2701]
Section "Installing Kubeflow" in https://www.kubeflow.org/docs/distributions/openshift/install-kubeflow/ has a markdown issue and the referenced YAML file does not exist.

![image](https://user-images.githubusercontent.com/13068832/117500494-926ff080-af31-11eb-8a1e-1ea118aeb084.png)

**Comment by himanshu9345** [comment]
We need to just remove ")" from the link at the end, will update here. You can assign it to me

**Comment by himanshu9345** [comment]
![Screenshot from 2021-06-16 23-06-21](https://user-images.githubusercontent.com/8727605/122325100-f35af300-cef7-11eb-8987-0055d2182377.png)
I have updated the link, I can create a merge request for this change.

**Comment by yhwang** [comment]
PR: https://github.com/kubeflow/website/pull/2942 should related to this
