### ISSUE TITLE
Usage Reporting - Is this Out of Date? 

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2708]
https://www.kubeflow.org/docs/other-guides/usage-reporting/

> Reporting usage data is one of the most significant contributions you can make to Kubeflow

@animeshsingh @joeliedtke @Bobgy should we remove the Out of date banner here? Would you know who could review that this document is up to date?

**Comment by RFMVasconcelos** [comment]
I arrived to this page from the `Usage Reporting` link in the Kubeflow Dashboard

**Comment by Bobgy** [comment]
I can confirm we removed usage tracking, so the whole page can be deleted

**Comment by RFMVasconcelos** [comment]
Thank you for the quick reply @Bobgy ! I will make a PR to remove the page then ;)
