### ISSUE TITLE
Kubeflow icon was not showing up

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/website#2711]
<img width="478" alt="Screen Shot 2021-05-12 at 12 33 41 PM" src="https://user-images.githubusercontent.com/37026441/118034011-5a482380-b31e-11eb-97dc-dced2fa2519e.png">

When opening kubeflow.org, the browser tab should show kubeflow icon, but it is not showing up in my case. Does it apply to others as well?

**Comment by himanshu9345** [comment]
I checked it works for me, I think is a browser/internet issue.
![Screenshot from 2021-05-12 20-34-37](https://user-images.githubusercontent.com/8727605/118060837-b1bbb300-b361-11eb-94ef-0db5f2983b53.png)

**Comment by RFMVasconcelos** [comment]
Good on my side as well

**Comment by zijianjoy** [comment]
I see, then it is probably just my machine. It is not blocking me for any development. Thank you both for confirming!
