### ISSUE TITLE
Many links on Kubeflow External Add-ons page are broken

### ISSUE THREAD

**Issue by rickysage** [kubeflow/website#2718]
Website URL : https://www.kubeflow.org/docs/external-add-ons/feature-store/getting-started/

Example Section links :

https://docs.feast.dev/user-guide/getting-training-features
https://www.kubeflow.org/docs/components/pipelines/pipelines-overview
https://docs.feast.dev/user-guide/getting-online-features
https://www.kubeflow.org/docs/components/pipelines/pipelines-overview
https://github.com/feast-dev/feast/tree/master/examples
https://api.docs.feast.dev/grpc/feast.core.pb.html
https://api.docs.feast.dev/grpc/feast.serving.pb.html

Please note, there could be more broken links on this page. Listed out that I could quickly see.

**Comment by thesuperzapper** [comment]
@rickysage do you want to have a crack at fixing it with a PR?

**Comment by rickysage** [comment]
Sure @thesuperzapper , please assign this to me! Will take it up :+1:

**Comment by rickysage** [comment]
@thesuperzapper the PR is raised, please let me know if anything else is required here. Just to share, I do not have the merge permissions.

**Comment by thesuperzapper** [comment]
@richardsliu I have asked @woop to do the approval [here](https://github.com/kubeflow/website/pull/2753#issuecomment-855587919), as he is in `OWNERS` for feast docs on kubeflow.org

**Comment by woop** [comment]
Thanks for pointing this out @rickysage!

**Comment by rickysage** [comment]
@thesuperzapper and @woop thanks for merging the PR. Just checked on live website, the urls seems to be working now. Can I close this issue now? :-)

**Comment by thesuperzapper** [comment]
Resolved by #2753
/close
