### ISSUE TITLE
Monitoring docs page missing

### ISSUE THREAD

**Issue by anthonydillon** [kubeflow/website#2720]
We link to this [logging and monitoring docs](https://www.kubeflow.org/docs/distributions/gke/monitoring/) page from this page https://ubuntu.com/ai/what-is-kubeflow. This page is now 404ing without a redirect. Has this page been removed for good?

**Comment by RFMVasconcelos** [comment]
Thank you for bringing this up @anthonydillon! 

It appears that this documentation was deprecated and was GKE specific. I suggest removing the link from  https://ubuntu.com/ai/what-is-kubeflow until there is further documentation on this regard.
