### ISSUE TITLE
Several issues in the "build pipelines" notebook

### ISSUE THREAD

**Issue by busycalibrating** [kubeflow/website#2732]
I've been playing around with the [build pipelines notebook](https://colab.research.google.com/github/kubeflow/website/blob/master/content/en/docs/components/pipelines/sdk/v2/build-pipeline.ipynb#scrollTo=-pxRW-6f_uNq) (also [here](https://www.kubeflow.org/docs/components/pipelines/sdk/v2/build-pipeline/)) and I've run into a few issues and inconsistent usages of various components. 

My environment is osx in a python venv running python 3.8.9, and `kfp==1.6.0rc0` (I've also tried the latest version, 1.6.2 and run into the same issues).

So far, I've run into the following issues:

**1: the imports are broken by default:**

```python
import kfp
import kfp.components as comp
# import kfp.vs.dsl as dsl  # ->  fails to import; presumably kfp.v2.dsl
import kfp.v2.dsl as dsl   # I've continued with this, and also tried without v2 
from kfp.v2 import compiler
from kfp.v2.dsl import component
from kfp.v2.dsl import (
    Input,
    Output,
    Artifact,
    Dataset,
)
```

**2: the default dsl pipeline decorator arguments do not include a name and cause it to fail downstream when we try to compile the pipeline:**

```python
# Define a pipeline and create a task from a component:
@dsl.pipeline(
    # name='my-pipeline',   # not included by default, required otherwise fails 
    pipeline_root='gs://my-pipeline-root/example-pipeline',
)
def my_pipeline(url: str):
    web_downloader_task = web_downloader_op(url=url)
    merge_csv_task = merge_csv(tar_data=web_downloader_task.outputs['data'])
    # The outputs of the merge_csv_task can be referenced using the
    # merge_csv_task.outputs dictionary: merge_csv_task.outputs['output_csv']
```
The error we get if we attempt to compile this pipeline without uncommenting the name line:
```
ValueError: Invalid pipeline name: My pipeline.
Please specify a pipeline name that matches the regular expression "^[a-z0-9][a-z0-9-]{0,127}$" using `dsl.pipeline(name=...)` decorator.
```

**3: after adding a name agreeing with the regex and try to recompile, `mode` is not a valid keyword argument:**

```python
compiler.Compiler().compile(
    pipeline_func=my_pipeline,
    package_path='pipeline.yaml',
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE   # unexpected kwarg; must comment out
```

The error you get otherwise:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-e64dcf5a766d> in <module>
----> 1 compiler.Compiler().compile(
      2     pipeline_func=my_pipeline,
      3     package_path='pipeline.yaml',
      4     mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE
      5 )

TypeError: compile() got an unexpected keyword argument 'mode'
```

**4. After commenting this out, finally we get that the `package_path` is expected to be a json file rather than a yaml file.**

```
ValueError                                Traceback (most recent call last)
<ipython-input-26-f98e52be61b3> in <module>
----> 1 compiler.Compiler().compile(
      2     pipeline_func=my_pipeline,
      3     package_path='pipeline.yaml',
      4 #     mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE
      5 )

~/Projects/kubeflow/kubeflow/lib/python3.8/site-packages/kfp/v2/compiler/compiler.py in compile(self, pipeline_func, package_path, pipeline_name, pipeline_parameters, type_check)
   1065           pipeline_name=pipeline_name,
   1066           pipeline_parameters_override=pipeline_parameters)
-> 1067       self._write_pipeline(pipeline_job, package_path)
   1068     finally:
   1069       kfp.TYPE_CHECK = type_check_old_value

~/Projects/kubeflow/kubeflow/lib/python3.8/site-packages/kfp/v2/compiler/compiler.py in _write_pipeline(self, pipeline_job, output_path)
   1087         json_file.write(json_text)
   1088     else:
-> 1089       raise ValueError(
   1090           'The output path {} should ends with ".json".'.format(output_path))

ValueError: The output path pipeline.yaml should ends with ".json".
```

This is solved by simply changing the output to `pipeline.json`, however this is not accepted by the `client.create_run_from_pipeline_package()` call, resulting in the error:

```
ValueError: The package_file pipeline.json should end with one of the following formats: [.tar.gz, .tgz, .zip, .yaml, .yml]
```

Is it possible that I have simply misconfigured my environment in some way? It feels like this might be more of a user-error issue, but I'm not totally sure. 

Thanks for the help!

**Comment by RFMVasconcelos** [comment]
Thank you for this issue @busycalibrating ! 

@zijianjoy @Bobgy could you PTAL?

**Comment by busycalibrating** [comment]
I'll add that this is only an issue with the SDK v2 tutorials; I ran through some of the original SDK tutorials and they worked fine.

**Comment by Bobgy** [comment]
@busycalibrating thank you for flagging these issues, sorry for not fully working initial documentation.

I think I've fixed most of these in PR https://github.com/kubeflow/website/pull/2729. Can you confirm?

**Comment by busycalibrating** [comment]
No problem, thanks for getting on it so fast!

**Comment by chensun** [comment]
> finally we get that the package_path is expected to be a json file rather than a yaml file.

JSON is for v2 only. You can submit it to Vertex AI, or later to KFP OSS once v2 engine is ready. 
For KFP v2 compatible mode, which is essentially "running v2 style pipeline on KFP OSS v1", the expected compilation result is still YAML.
