### ISSUE TITLE
Where to locate `multi-tenancy` docs?

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2736]
Broken down from #2671

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I think there are two options:

1. Move `Multi Tenancy` into `Components / Central Dashboard`:
    * Pros:
       * Central Dashboard is closely related to the istio configs which actually do the security for multi-tenancy (that is, mapping web sessions to namespaces/profiles)
    * Cons:
       * Multi Tenancy is really a "feature" of every component, and putting it under a single component might hide it from users
2.  As I proposed in https://github.com/kubeflow/website/issues/2671#issuecomment-829723462, create a new `Concepts` section of the website:
    * Pros:
       * "Concepts" is a very common section for docs (like in Kubernetes, Argo, Airflow etc), and usually outlines core principals which are central to the tool
       * Draws attention to "Multi Tenancy" as a core "feature"/"concept" of Kubeflow
    * Cons:
       * Creates a new website section (which will initially only have one page)

Personally I am in favour of option 2.

**Comment by thesuperzapper** [comment]
I am closing this in favour of discussion on the specific proposal of creating a `Concepts` section under `Getting Started`:
https://github.com/kubeflow/website/issues/2803

/close
