### ISSUE TITLE
Broken Link in Samples -> Kafka

### ISSUE THREAD

**Issue by difince** [kubeflow/website#2740]
https://github.com/kubeflow/kfserving/blob/master/docs/samples/kafka/README.md
contains broken link:
**5. Install [Kafka Event Source](https://github.com/knative/eventing-contrib/tree/main/kafka/source)**

https://github.com/knative/eventing-contrib/tree/main/kafka/source return 404

**Comment by himanshu9345** [comment]
@RFMVasconcelos can I work on this?

**Comment by RFMVasconcelos** [comment]
That would be great @himanshu9345! Thank you

**Comment by himanshu9345** [comment]
I am closing this issue as this issue should belong in Kubeflow/kfserving repo/project
/assign
/close

**Comment by himanshu9345** [comment]
@RFMVasconcelos can you please close this issue, reason mentioned above.
