### ISSUE TITLE
Remove the `Tutorials, Samples, and Shared Resources` section

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2759]
I believe most of the content of `Tutorials, Samples, and Shared Resources` can be split into other sections (or outright removed), allowing us to remove this top-level section and further declutter the website.

I will list out each page and propose a new home, (or explain why it should be removed):
* `Kubeflow Samples`:
   *  __MOVE__ to `Getting Started / Examples` 
   * links to examples on https://github.com/kubeflow/examples
* `Codelabs, Workshops, and Tutorials`:
   * __REMOVE__
   * this content is very out of date (but we could move it under the `Components / Pipelines`, if wanted)
* `Blog Posts`:
  * __REMOVE__
  * links to very old blog posts about Kubeflow, there is little reason to keep it around
* `Videos`:
  * __REMOVE__
  * links to very old videos about Kubeflow, there is little reason to keep it around
* `Shared Resources and Components`:
  * __REMOVE__
  * discusses AI Hub (which is very separate from Kubeflow these days)
  * discusses some stuff about pipelines, which is no longer needed

**Comment by thesuperzapper** [comment]
@RFMVasconcelos what do you think of this proposal?

**Comment by RFMVasconcelos** [comment]
Nice job picking up on this @thesuperzapper !

I fully agree, this was part of my initial [proposal](https://github.com/kubeflow/community/pull/440/files), but ended up not having the time to action it yet. 

I agree with all points. Would you be able to start a PR? :)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos Sorry, haven't had time to work on this lately, I will eventually get to it, but if someone else wants to pick it up and make a PR, I am happy to review.

**Comment by Arhell** [comment]
@thesuperzapper  done

**Comment by thesuperzapper** [comment]
@Arhell I am pretty sure you are referring to the other issue (https://github.com/kubeflow/website/issues/2760), as I don't see any PRs related to this issue?

**Comment by Arhell** [comment]
Here
https://github.com/kubeflow/website/pull/2825

**Comment by Arhell** [comment]
@thesuperzapper Wrong, sorry

**Comment by thesuperzapper** [comment]
Closing, as this has been done, we can discuss updating the `Examples` page in:
- https://github.com/kubeflow/website/issues/2856
