### ISSUE TITLE
Remove the `Further Setup and Troubleshooting` section

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2760]
I believe most of the content of `Further Setup and Troubleshooting` can be split into other sections (or outright removed), allowing us to remove this top-level section and further declutter the website.

__I will list out each page and propose a new home, (or explain why it should be removed):__

* `Deploying Kubeflow behind a proxy server`:
   * __REMOVE__
   * discusses `kfctl`, which is no longer used as of `1.3` (if distributions want to support kfctl docs, they can do it in their distribution docs)
* `Kubeflow On-prem in a Multi-node Kubernetes Cluster`:
   * __REMOVE__
   *  discusses how to setup "dyanmic volume provisioning" (this is effectively a doc for Kuberenetes itself, there is no reason to have it on the Kubeflow website)
* ~`Troubleshooting`:~
   *  __REMOVE__
   * discusses (very outdated) information about installing Kubeflow
* `Frequently Asked Questions`:
  * __REMOVE__
  * only has 1 question (which is really not very useful)
* `Support`:
  * __MOVE__ to `Getting Started / Support`
  * most of the information is out of date, but I think we only need to keep "Support from the Kubeflow community" section
* `Integrations`:
  * __REMOVE__
  * only contains one section, which references Rok (a proprietary tool, specific to Arrikto's distributions of Kubeflow)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos what do you think of this proposal?

**Comment by RFMVasconcelos** [comment]
I am in favour of this proposal

**Comment by RFMVasconcelos** [comment]
We need to re-write the Support page before moving it to Getting Started

**Comment by thesuperzapper** [comment]
Sorry, haven't had time to work on this lately, I will eventually get to it, but if someone else wants to pick it up and make a PR, I am happy to review.

**Comment by thesuperzapper** [comment]
@Arhell do want to take a crack at the rest of the removals since you did https://github.com/kubeflow/website/pull/2768?

**Comment by Arhell** [comment]
@thesuperzapper  done

**Comment by thesuperzapper** [comment]
@Arhell there are still two outstanding things:
1. The `/docs/other-guides` (Further Setup and Troubleshooting) section should be deleted (it's just an empty section now)
2. We should clean up the `Support` page (which was moved under `Getting Started`)
     - _NOTE: I am not sure what we should do with the content, but its clearly way to verbose, and not really helpful for directing users towards the right support channels_

**Comment by Arhell** [comment]
Got it, I'll fix it, but I won't touch the content on the `Support` page. Not sure what to remove or add.

**Comment by Arhell** [comment]
@thesuperzapper ready, it remains to fix the `Support` section

**Comment by thesuperzapper** [comment]
I am closing this issue, we can discuss updating the `Support` page in:
- https://github.com/kubeflow/website/issues/2855
