### ISSUE TITLE
Getting Started with Katib: pv.yaml no longer exists

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/website#2764]
In the Katib setup section, subsection [setting up persistent volumes](https://www.kubeflow.org/docs/components/katib/hyperparameter/#setting-up-persistent-volumes), it is mentioned a PV is needed to complete the step, but the link to pv.yaml file is broken (404 not found). It was actually removed by [#1527](https://github.com/kubeflow/katib/pull/1527), the documentation should reflect the change introduced by that PR.

Documentation where this is happening: [Getting started with katib](https://www.kubeflow.org/docs/components/katib/hyperparameter/)

**Comment by andreyvelich** [comment]
Thank you for noticing this @DnPlas!

We have an issue to track this: https://github.com/kubeflow/katib/issues/1528.
We will try to fix this soon.

**Comment by andreyvelich** [comment]
cc @kubeflow/wg-automl-leads

**Comment by DnPlas** [comment]
Ah! @andreyvelich didn't noticed it was already tracked, then shall I close this bug?

**Comment by johnugeorge** [comment]
Yes. it can be tracked in #1528. 

> Ah! @andreyvelich didn't noticed it was already tracked, shall I close this bug?

**Comment by DnPlas** [comment]
Closing this issue as it is already tracked in [#1528](https://github.com/kubeflow/katib/issues/1528)
