### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Arhell** [kubeflow/website#2766]
https://www.kubeflow.org/docs/other-guides/troubleshooting/#avx2
/assign

**Comment by thesuperzapper** [comment]
@Arhell there is a proposal to remove the "Troubleshooting" page: https://github.com/kubeflow/website/issues/2760

**Comment by Arhell** [comment]
@thesuperzapper Ok, I will

**Comment by thesuperzapper** [comment]
closed by https://github.com/kubeflow/website/pull/2768
/close
