### ISSUE TITLE
Azure OIDC docs point to kfctl 1.3.0 which does not exist

### ISSUE THREAD

**Issue by stewartadam** [kubeflow/website#2771]
On [Authentication using OIDC in Azure](https://www.kubeflow.org/docs/distributions/azure/authentication-oidc/), users are prompted to download kfctl 1.3.0 which does not exist. 1.2.0 appears to be the latest version.

**Comment by himanshu9345** [comment]
@RFMVasconcelos I guess we need to change kfctl version in the doc, as the latest available version is 1.2.0. Do you know the team/people to which I can talk to confirm/rectify the issue?

**Comment by RFMVasconcelos** [comment]
I believe @brettkoonce or @aronchick might be good people to ask about Azure :)
