### ISSUE TITLE
Add docs for the Models web app 

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/website#2778]
Follow up issue from https://github.com/kubeflow/kfserving/issues/1664

I want to add docs to the KFServing component for the new Models web app that is available in the KFServing 0.6 release. I'll also make it explicit that this will not be part of 1.3, since 1.3 contains KFServing 0.5, but I'll also add some steps on how someone could launch it with Kubeflow as well.

I was thinking of following this structure:
```
Components
    KFServing
        KFServing
        Models UI
```

cc @yuzisun @animeshsingh @pvaneck @RFMVasconcelos @shannonbradshaw

**Comment by shannonbradshaw** [comment]
@kimwnasptd I like this idea. I also think we should consider changing the title of the nested page so that we're doubling up with "KFServing". Maybe:
