### ISSUE TITLE
Install the Kubeflow Pipelines SDK

### ISSUE THREAD

**Issue by dmerz75** [kubeflow/website#2780]
https://www.kubeflow.org/docs/components/pipelines/sdk/install-sdk/

The "build a component and a pipeline" link is broken.

**Comment by himanshu9345** [comment]
@RFMVasconcelos Can I work on this?

**Comment by RFMVasconcelos** [comment]
That would be great @himanshu9345 !

**Comment by himanshu9345** [comment]
@RFMVasconcelos Can you please assign it to me?
