### ISSUE TITLE
Broken link in Getting Started Page

### ISSUE THREAD

**Issue by happyhuman** [kubeflow/website#279]
Hi
There seems to be a broken link in this page:
https://github.com/kubeflow/website/blob/master/content/docs/started/getting-started.md

The broken link is:
https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh

**Comment by sarahmaddox** [comment]
I think this issue is now resolved. If I substitute "v0.3.1" for KUBEFLOW_TAG, I get the following link, which works:
https://raw.githubusercontent.com/kubeflow/kubeflow/v0.3.1/scripts/download.sh

**Comment by sarahmaddox** [comment]
I'm closing this issue, but please do re-open it if the problem still occurs.

/close
