### ISSUE TITLE
close the "kubeflow docs restructure" kanban

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2806]
There is still a l[egacy project from the 1.3 release](https://github.com/kubeflow/website/projects/2
) on this repo.

We should close this in preference of [the new one](https://github.com/orgs/kubeflow/projects/45) (on the kubeflow organisation, rather than this repo).

I have also create an issue https://github.com/kubeflow/website/issues/2805 (which should be pinned) to help users find the new Kanban.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos are you OK if we close the old Kanban?

**Comment by RFMVasconcelos** [comment]
@thesuperzapper thank you for organizing the new kanban! 🚀 

I have just confirmed that there are no lost items, and hence closed the previous kanban.
