### ISSUE TITLE
Restructure the `About` section

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2807]
The `about` section of the website hasn't been touched/updated in a very long time, it is now very outdated, I propose we keep it but make the following changes.

__I propose we make the following changes to the `about` section:__
- `Introduction to Kubeflow`
    - __MOVE__ to `Getting Started / Introduction to Kubeflow`
    - this page will be more visible under `Getting Started`
- `Use Cases`
    - __REMOVE__
    - this page reads like marketing material, (and is very out of date)
- `Contributing to Kubeflow`
    - __LEAVE__ 
    - can be updated in future, but is fine for now
- `Community`
    - __SPLIT UP__
    - this page fails to highlight the most important links to the user, so we should break it up into:
        - `Kubeflow Blog`: a page which describes (and links to) the [offical Kubeflow blog](https://blog.kubeflow.org/)
        - `Kubeflow Slack Workspace`: a page that describes (and provides an invite to) the official Kubeflow Slack
        - `Kubeflow Mailing List`: a page which describes (and links to) the [kubeflow-dicsuss](https://groups.google.com/g/kubeflow-discuss) mailing list
        - `Kubeflow Community Call`: a page that describes the weekly community meeting, and how to join it
        - `Kubeflow Working Groups`: a page that lists and describes the Kubeflow Working Groups
            - links to the [kubeflow/community](https://github.com/kubeflow/community/tree/master/wg-automl) pages 
            - links to somewhere which aggregates all meeting calendars
- `Google Summer of Code`
    - __REMOVE__
    - this event has finished, and it's confusing to keep this page
-  `Docs`
    - __REMOVE__
    - this page does not provide useful information
- `Style Guide for the Kubeflow Docs`
    - __RENAME__  to `Documentation Style Guide`
    - this is still a very useful page (but possibly we should highlight it somewhere)
- `Events Calendar`
    - __REMOVE__
    - this page has not been updated in over a year

---

__This would leave the following structure:__
```
About:
- Contributing to Kubeflow
- Kubeflow Blog
- Kubeflow Slack Workspace
- Kubeflow Mailing List
- Kubeflow Community Call
- Kubeflow Working Groups
- Documentation Style Guide
```

```
Getting Started:
- Introduction to Kubeflow
- Kubeflow Overview
- Installing Kubeflow
- Examples
- Support
```

**Comment by thesuperzapper** [comment]
@RFMVasconcelos what are your thoughts?

**Comment by RFMVasconcelos** [comment]
Thank you for this @thesuperzapper! All the changes sound reasonable to me. If you are able to create a PR, I am more than happy to review :)
