### ISSUE TITLE
Amazon EKS and Kubeflow 1.3 Compatibility

### ISSUE THREAD

**Issue by akdigitalself** [kubeflow/website#2832]
The https://www.kubeflow.org/docs/distributions/aws/deploy/eks-compatibility/ page shows the compatibility of KF 1.2. Can you please add the compatibility matrix for KF 1.3 as well? Thanks!

**Comment by surajkota** [comment]
AWS Distribution of Kubeflow-1.3.1 is live

Please refer to what’s new: https://github.com/awslabs/kubeflow-manifests/releases/tag/v1.3.1-aws-b1.0.0
 
For documentation, please refer to the Kubeflow.org website: https://www.kubeflow.org/docs/distributions/aws/
 
If you have any issues, please refer to the help and feedback section: https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch#help--feedback

/close
