### ISSUE TITLE
update content of cards on "kubeflow.org" landing page

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2845]
Currently, the content inside the cards on the main "kubeflow.org" landing page is extremely out of date.

We should update them to reflect the new features of Kubeflow, and to highlight what people actually use Kubeflow for these days.

----

__For reference, here are the current cards:__
![Kubeflow](https://user-images.githubusercontent.com/5735406/142980816-4fb40c0c-9096-41af-ba7d-9594e30caae5.png)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos what are your thoughts?

**Comment by RFMVasconcelos** [comment]
Thanks for starting this Mathew. I do believe there is room to improve here! 

+1 to both suggestions: reduce height and update cards
