### ISSUE TITLE
update `Getting Started / Support`

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2855]
After issue https://github.com/kubeflow/website/issues/2760, we moved `Support` from `Further Setup and Troubleshooting`. We need to refactor/rewrite the `Support` page (as it is now highly visible).

This issue is a __PLACEHOLDER__ to discuss proposals for that page.

**Comment by kramachandran** [comment]
It seems like a lot of this material is duplicative of the material in the About section. 

- The 'Levels of support' seems to be a re-iteration of the Versioning policy. 
- And the remained of the doc seems to be pointers to issue trackers, slack channels, and the mailing lists. 

I'm wondering if this page is still necessary after refactoring of the About section you proposed in PR #3007

**Comment by thesuperzapper** [comment]
@kramachandran I agree that the page should be cleaned up (and probably renamed to "Get Support"), but I think it's useful to have a nexus page to help people ask questions in an appropriate place (and to the right people).

I don't think it currently duplicates much of the "about" pages, but when we rewrite it, we should try to link to the new "about" pages rather than duplicating their information.

**Comment by kramachandran** [comment]
That makes sense.
