### ISSUE TITLE
Update Training docs for KF 1.4

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/website#2915]
We will need to update the pages to use latest training operator.  

cc @kubeflow/wg-training-leads

**Comment by Jeffwan** [comment]
@shinytang6 Do you get a chance to take a look at if gang-scheduling part is up to date? https://www.kubeflow.org/docs/components/training/job-scheduling/

**Comment by Jeffwan** [comment]
Seems xgboost page is missing. If anyone has time, please help add a new page.

/good-first-issue
/help

**Comment by Talador12** [comment]
@Jeffwan it looks like the XGboost doc was created by @johnugeorge and merged. 

Looks like this is just pending response from @shinytang6

Is there anything else that needs to be included before this is considered lgtm?

**Comment by Talador12** [comment]
This ticket can now be closed

**Comment by Shabrinath** [comment]
I would like to work on this. Im new to opensource. can someone point me what I need to work on ?
