### ISSUE TITLE
python code to access Kubeflow Pipelines API from outside the cluster (when using dex)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2916]
Currently, we don't explain how to connect to the Pipelines API from outside the cluster (when using dex for multi-user, as is the default in [kubeflow/manifests](https://github.com/kubeflow/manifests)).

I think we can add this information to one of these pages:
- [components/pipelines/multi-user.md](https://github.com/kubeflow/website/blob/master/content/en/docs/components/pipelines/multi-user.md)
- [components/pipelines/sdk/connect-api.md](https://github.com/kubeflow/website/blob/master/content/en/docs/components/pipelines/sdk/connect-api.md)

---

__NOTE: this has been edited since I first posted this issue__

I have written a basic python script that uses the `requests` library to authenticate against a `staticPasswords` user:
```python
import re
from urllib.parse import urlsplit

import kfp
import requests

KUBEFLOW_ENDPOINT = "http://localhost:8080"
KUBEFLOW_USERNAME = "user@example.com"
KUBEFLOW_PASSWORD = "12341234"


def get_istio_auth_session(url: str, username: str, password: str) -> dict:
    """
    Determine if the specified URL is secured by Dex and try to obtain a session cookie.
    WARNING: only Dex `staticPasswords` and `LDAP` authentication are currently supported
             (we default default to using `staticPasswords` if both are enabled)

    :param url: Kubeflow server URL, including protocol
    :param username: Dex `staticPasswords` or `LDAP` username
    :param password: Dex `staticPasswords` or `LDAP` password
    :return: auth session information
    """
    # define the default return object
    auth_session = {
        "endpoint_url": url,    # KF endpoint URL
        "redirect_url": None,   # KF redirect URL, if applicable
        "dex_login_url": None,  # Dex login URL (for POST of credentials)
        "is_secured": None,     # True if KF endpoint is secured
        "session_cookie": None  # Resulting session cookies in the form "key1=value1; key2=value2"
    }

    # use a persistent session (for cookies)
    with requests.Session() as s:

        ################
        # Determine if Endpoint is Secured
        ################
        resp = s.get(url, allow_redirects=True)
        if resp.status_code != 200:
            raise RuntimeError(
                f"HTTP status code '{resp.status_code}' for GET against: {url}"
            )

        auth_session["redirect_url"] = resp.url

        # if we were NOT redirected, then the endpoint is UNSECURED
        if len(resp.history) == 0:
            auth_session["is_secured"] = False
            return auth_session
        else:
            auth_session["is_secured"] = True

        ################
        # Get Dex Login URL
        ################
        redirect_url_obj = urlsplit(auth_session["redirect_url"])

        # if we are at `/auth?=xxxx` path, we need to select an auth type
        if re.search(r"/auth$", redirect_url_obj.path):
            # default to "staticPasswords" auth type
            redirect_url_obj = redirect_url_obj._replace(
                path=re.sub(r"/auth$", "/auth/local", redirect_url_obj.path)
            )

        # if we are at `/auth/xxxx/login` path, then no further action is needed (we can use it for login POST)
        if re.search(r"/auth/.*/login$", redirect_url_obj.path):
            auth_session["dex_login_url"] = redirect_url_obj.geturl()

        # else, we need to be redirected to the actual login page
        else:
            # this GET should redirect us to the `/auth/xxxx/login` path
            resp = s.get(redirect_url_obj.geturl(), allow_redirects=True)
            if resp.status_code != 200:
                raise RuntimeError(
                    f"HTTP status code '{resp.status_code}' for GET against: {redirect_url_obj.geturl()}"
                )

            # set the login url
            auth_session["dex_login_url"] = resp.url

        ################
        # Attempt Dex Login
        ################
        resp = s.post(
            auth_session["dex_login_url"],
            data={"login": username, "password": password},
            allow_redirects=True
        )
        if len(resp.history) == 0:
            raise RuntimeError(
                f"Login credentials were probably invalid - "
                f"No redirect after POST to: {auth_session['dex_login_url']}"
            )

        # store the session cookies in a "key1=value1; key2=value2" string
        auth_session["session_cookie"] = "; ".join([f"{c.name}={c.value}" for c in s.cookies])

    return auth_session


def main():
    auth_session = get_istio_auth_session(
        url=KUBEFLOW_ENDPOINT,
        username=KUBEFLOW_USERNAME,
        password=KUBEFLOW_PASSWORD
    )

    print(auth_session)

    client = kfp.Client(
        host=f"{KUBEFLOW_ENDPOINT}/pipeline",
        cookies=auth_session["session_cookie"]
    )

    # test that we have a valid session
    print(client.list_pipelines())


if __name__ == "__main__":
    main()

```

**Comment by thesuperzapper** [comment]
What are your thoughts @Bobgy or @kubeflow/wg-pipeline-leads? 

I think explaining this to users will massively reduce the pain of using the Pipelines SDK outside the cluster (when using Dex).

_NOTE: the default configs from [kubeflow/manifests](https://github.com/kubeflow/manifests) uses dex with  `staticPasswords`_
_(user: `user@example.com`, pass: `12341234`)_

**Comment by Bobgy** [comment]
@thesuperzapper I think it's good to add this documentation. Ideally it should be in distribution documentation, why do you want it in KFP documentation?
For example, the corresponding connect to KFP on GCP documentation belong to KF on GCP documentation.

**Comment by thesuperzapper** [comment]
@Bobgy I agree that this is somewhat distribution-specific, but we still might want to include it under the "pipelines" docs, as pretty much every distribution uses dex (except GCP), so these docs would have to be duplicated under each one otherwise.

Possibly we could add it to the [`components/pipelines/sdk/connect-api.md`](https://github.com/kubeflow/website/blob/master/content/en/docs/components/pipelines/sdk/connect-api.md) page?

**Comment by Bobgy** [comment]
Yep, that seems like a good reason to add to pipelines doc.  Send a PR?

**Comment by ramdootp** [comment]
Is there any other approach for external SDK use cases other than using authservice session tokens - https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex#run-a-prediction
The current approach is a security risk for us 
/cc @andreyvelich

**Comment by andreyvelich** [comment]
@Bobgy @zijianjoy @yanniszark @thesuperzapper @elikatsis do we have any solution that @ramdootp mentioned above ?

**Comment by thesuperzapper** [comment]
@ramdootp can you explain what security risk you are talking about?

__NOTE:__ the above code __only works__ with logins defined as dex `staticPasswords`. 
(I like to think of dex `staticPasswords` as "service accounts", and dex SAML/OAUTH/LDAP as "user accounts")

Also, the above code will work for any API of Kubeflow sitting behind the `istio-ingressgateway` (as it authorizes with Istio, not kubeflow), just ensure you set the cookies which are returned by `get_dex_session_cookies()` in your HTTP request.

**Comment by bartgras** [comment]
@thesuperzapper I don't remember where I found this code snippet but it works for me with Dex + `staticPasswords` and seems to be much simpler:

```
import requests
import kfp

HOST = 'http://example.com'
USERNAME = "user@example.com"
PASSWORD = "12341234"
NAMESPACE = "<USER_NAMESPACE>"

session = requests.Session()
response = session.get(HOST)

headers = {
    "Content-Type": "application/x-www-form-urlencoded",
}

data = {"login": USERNAME, "password": PASSWORD}
session.post(response.url, headers=headers, data=data)
session_cookie = session.cookies.get_dict()["authservice_session"]

client = kfp.Client(
    host=f"{HOST}/pipeline",
    cookies=f"authservice_session={session_cookie}",
    namespace=NAMESPACE,
)
```

@ramdootp Maybe you will find that helpful as well: 
Similarly to @thesuperzapper example, because it returns `session_cookie`, then it can be used for e.g. KFServing endpoint as well.

**Comment by ramdootp** [comment]
@thesuperzapper is there any example client code which authenticates through tokens (for example - ID_TOKEN) rather than session cookie.

**Comment by thesuperzapper** [comment]
@bartgras the code you posted will only work for the default dex settings found in `kubeflow/manifests`:
- it won't handle the case when `staticPasswords` AND `OAUTH` / `SAML` / `LDAP` is enabled (it wont know how to direct itself to the `/auth/local` subpath)
- it wont handle if the auth cookie is named something other than `authservice_session`

**Comment by thesuperzapper** [comment]
@ramdootp currently, when using Kubeflow pipelines in multi-user mode, auth is handled by istio (not pipelines itself), so I'm not sure where you are seeing `ID_TOKEN`. 

Can you clarify where you are seeing `ID_TOKEN`? ​

_PS: while its not quite a token dex `staticPasswords` could be viewed as a "service account"_

**Comment by bartgras** [comment]
@thesuperzapper Thanks for explaining that. I wasn't aware. Then it definitely should be explained in documentation.

**Comment by thesuperzapper** [comment]
For those watching, I have updated the script to be more clear and robust:
- It now correctly handles multiple cookies being created
- It now returns information in an `auth_sesison` dictionary
- It now handles cases when your Kubeflow endpoint is unsecured (by checking if it doesn't get redirected)

**Comment by thesuperzapper** [comment]
Another quick update, the script was previously assuming `HTTP 200` (success) after POST of credentials meant the login succeeded, but this is WRONG. Dex actually gives you `HTTP 200` if you have INCORRECT credentials (it prompts you to enter them again), in reality `HTTP 302` (redirect) indicates success.

I have updated the script in the original comment to fix this issue.

**Comment by thesuperzapper** [comment]
Final update (hopefully): my fix from https://github.com/kubeflow/website/issues/2916#issuecomment-922640173 broke the script, causing no cookies to be returned in `auth_session["session_cookie"]`, this is because I disabled `allow_redirects` in the `s.post()`, but to get the auth cookies you must follow the redirects.

I have now made the script follow the redirects again, and I now check for redirects by checking the length of `resp.history` is non-zero.

In my local testing the script now works properly.

**Comment by thesuperzapper** [comment]
Another update to the script, I have added support for cases when the Dex `LDAP` connector is used.

___NOTE:__ if both `LDAP` and `staticPasswords` are enabled, the script defaults to using `staticPasswords`._

**Comment by thesuperzapper** [comment]
I have updated it one more time, this time fixing a bug introduced by https://github.com/kubeflow/website/issues/2916#issuecomment-938255344.

The issue was that I assumed if `/auth/local/login` was not present in the URL that `/auth/local` wasn't either, (but in older dex versions this is not true), so the old code would rewrite to `/auth/local/local` (which is invalid). 

This should be fixed now (and still support LDAP).

**Comment by thesuperzapper** [comment]
I have raised a PR which will add the dex example to the Kubeflow.org website: https://github.com/kubeflow/website/pull/3021

**Comment by thesuperzapper** [comment]
Because this issue seems to come up on Google for Kubeflow Pipelines SDK auth issues, I want to point people toward the docs with the final version of this code.

Specifically, you can find the information and code examples on the ["Connect the Pipelines SDK to Kubeflow Pipelines"](https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/) page under the `"Full Kubeflow (from outside cluster)"` heading.

My only other tip is that you should catch errors when calling methods like `kfp.Client.list_experiments()` to handle the case that your session lasts long enough for your cookie to expire (and re-auth in that case).

**Comment by gioargyr** [comment]
Is there any solution when we are using Keycloak instead of Dex?

**Comment by thesuperzapper** [comment]
Another update, for those using deployKF, please see the [Access Kubeflow Pipelines API](https://www.deploykf.org/user-guides/access-kubeflow-pipelines-api/#browser-login-flow) guide for your options.

Some of these will work on any Kubeflow, but others like the [Browser Login Flow](https://www.deploykf.org/user-guides/access-kubeflow-pipelines-api/#browser-login-flow) depend on some special authentication flows in deployKF.
