### ISSUE TITLE
Cut 1.3 branch for website

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/website#2937]
We need to cut a new branch for the website, in order to be able to merge PRs for the 1.4 release https://github.com/kubeflow/website/issues/2879. You can see the process we follow here https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#version-the-website.

@RFMVasconcelos @knkski what is the state of this? Is there something I can help with?

cc @kubeflow/release-team

**Comment by RFMVasconcelos** [comment]
As I mentioned I haven't been able to do this - @kimwnasptd would you be able to cut the branch? 

@Bobgy could you please tackle or find another Googler to tackle the release steps of docs pointing to the new `v1.3-branch` once it is there?

**Comment by kimwnasptd** [comment]
> @kimwnasptd would you be able to cut the branch?

Definitely! Since I'm in the release team I have permissions to create branches in the `website` repo.

Before cutting the branch I want to ensure that the `v1.3-branch` will not have commits that correspond to future versions of Kubeflow. Specifically:
* @Bobgy @zijianjoy I see commits in the current `master` that are for Pipelines 1.7.0. I guess these should not be included in the 1.3 version of the docs right?
* @andreyvelich I see some commits that update the Katib docs https://github.com/kubeflow/website/pull/2880 https://github.com/kubeflow/website/pull/2851. Are the commits intended for 1.4 and should not be present in 1.3?

**Comment by andreyvelich** [comment]
Yes, that commits should be part of Kubeflow 1.4

**Comment by zijianjoy** [comment]
@kimwnasptd I am tempting to say that users can upgrade KFP independently in Kubeflow 1.3, therefore KFP 1.7.0 is possible to be included as part of `kubeflow doc` 1.3 branch, and we have called out the version requirement for KFP in those KFP 1.7.0 related documents. But defer to @Bobgy to make the decision.

Reference: [KFP website doc history](https://github.com/kubeflow/website/commits/master?before=8ce6d0cf93840b28a072cbfd749a530089fe0053+35&branch=master&path%5B%5D=content&path%5B%5D=en&path%5B%5D=docs&path%5B%5D=components&path%5B%5D=pipelines)

**Comment by Bobgy** [comment]
Agree with @zijianjoy.
For configuring the website, I work with @zijianjoy to do it. Let us know once you cut 1.3 branch.

**Comment by kimwnasptd** [comment]
@zijianjoy @Bobgy ACK! This will actually make the process of cutting the 1.3 branch easier.

Could you only update [`Full Kubeflow deployment`](https://www.kubeflow.org/docs/components/pipelines/installation/overview/#full-kubeflow-deployment) section of the Pipelines docs to note the version used in the 1.3 Kubeflow installation? This way it will be clear to users what KFP version comes with the current version of docs they are looking at.

Then we can push a commit to add an entry for 1.4. WDYT?

**Comment by zijianjoy** [comment]
Hello,

I have cut the `v1.3-branch` and redirect kubeflow.org to point to this git branch. Would you like to follow up with the step in https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#updating-version-numbers-etc-for-the-upcoming-release-major-minor-or-patch? Thank you! @kimwnasptd @RFMVasconcelos

**Comment by kimwnasptd** [comment]
Thank you very much for all your help @zijianjoy!

> Would you like to follow up with the step in https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#updating-version-numbers-etc-for-the-upcoming-release-major-minor-or-patch? 

Sure, we can take it from here. @shannonbradshaw @bobuel could you take care of this one? The changes will happen as expected in the master branch.

**Comment by kimwnasptd** [comment]
Also, @kubeflow/wg-training-leads @kubeflow/wg-automl-leads since we've cut the 1.3 branch from the current master there is some of your work, intended for 1.4, that ended up in the 1.3 branch. 

Could you create a small PR to bring the docs for your components in the state that you want them for 1.3? You can copy paste the contents from a specific commit and PR them, it doesn't have to be a surgical removal of all the commits. The PRs should be done on top of the 1.3 branch.

Apologies for this inconvenience. We will make sure this won't be the case in future releases, by cutting the docs branch in time right after the official release is announced.

**Comment by Jeffwan** [comment]
@kimwnasptd That means we need to revert 1.4 changes in v1.3-branch, is that correct?

**Comment by kimwnasptd** [comment]
@Jeffwan correct!
