### ISSUE TITLE
create `Guides` section (and move non-distributions out of `Distributions`)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2967]
There has been significant discussion in community meetings and https://github.com/kubeflow/website/issues/2873, about confusion on some of the distributions in the "distributions" section. 

It has been suggested that some of the "Distributions" are actually just "Guides" for using the `kubeflow/manifests` repo with a specific cloud platform. That is, they simply describe deploying the generic manifests without providing significant customizations meeting the criteria of a "packaged" distribution.

__Proposals:__
1. __Establish a new "Guides" section on the sidebar:__
    - _(NOTE: this can also be used in the future for non-installation guides)_
    - _(NOTE: we should indicate the author/maintainers of any guides)_
2. __Move & Rename the following "Distributions" to "Guides":__
    - `Kubeflow on AWS` -> `Deploying Manifests on AWS`
    - `Kubeflow on Azure` -> `Deploying Manifests on Azure`
    - `Kubeflow on IBM Cloud` -> `Deploying Manifests on IBM Cloud`
    - `Kubeflow on Nutanix Karbon` -> `Deploying Manifests on Nutanix Karbon`
    - `Kubeflow on OpenShift` -> `Deploying Manifests on OpenShift`
    - `Kubeflow Operator` -> `Deploying Manifests with Kubeflow Operator`
3. __Update "Getting Started / Installing Kubeflow" page:__
    - Create a table under `Install the Kubeflow Manifests manually`  with links to the above "Guides"
    - Remove the guides from the existing table under `Install a packaged Kubeflow distribution`

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @Bobgy what are your thoughts?

**Comment by Bobgy** [comment]
The high level ideas make perfect sense to me.

Kubeflow Operator -- is this also a guide? It sounds like the operator is different enough.

/cc @zijianjoy @james-jwu

**Comment by thesuperzapper** [comment]
@Bobgy regarding the `Kubeflow Operator` there are a couple of issues that make me hesitant to leave it as a "distribution":
1. While there is some "custom code" in the form of a controller for `KFDef`, there is no YAML customization beyond what is found in the `kubeflow/manifests` repo.
   - _(NOTE: If we leave it as a "distribution" it will be the only one that installs straight YAML from `kubeflow/manifests`)_
2. The current docs describe installing `Kubefow 1.1` (so are very out of date)

But @animeshsingh please comment your thoughts.

**Comment by thesuperzapper** [comment]
@Bobgy I have raised PR https://github.com/kubeflow/website/pull/3004 which addresses this issue.

**Comment by thesuperzapper** [comment]
Given https://github.com/kubeflow/website/pull/3004 has proven too controversial to merge and is now just wasting time, I have closed it.

In reality, we were always planning to remove distribution docs from `kubeflow.org`, so it's easier to just move forwards with that to address the issue of non-distributions. 

# I have created issue https://github.com/kubeflow/website/issues/3074 to discuss this.
