### ISSUE TITLE
remove `Reference` section

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#2970]
The top-level `Reference` section is largely redundant as its content is really out-of-date, and better placed under the component-specific docs.

__Therefore I propose REMOVING the `Reference` section, and doing the following to each page:__
- `Reference Overview`
   - __REMOVE__
   - page is very out of date
   - this information should be under `Component` docs
- `Kubeflow Versioning Policies`
   - __REMOVE__
   - page is very out of date
   - the "Kubeflow application matrix" won't be needed after we add a ["Releases" section](https://github.com/kubeflow/website/issues/2969)
- `Dockerfile Locations`
   - __REMOVE__
   - page is very out of date 
   - the cost of keeping this page up-to-date in future is not worth it
- `Katib Reference`
   - __MOVE__ to `Components / Katib / API Reference`
- `MPIJob Reference`
   - __MOVE__ to `Components / Training Operators` (add to existing "MPIJob" page)
- `Notebook CRD Reference`
   - __MOVE__ to `Components / Notebook Servers`
- `PyTorchJob Reference`
   - __MOVE__ to `Components / Training Operators` (add to existing "PyTorchJob" page)
- `TFJob Reference`
   - __MOVE__ to `Components / Training Operators` (add to existing "TFJob" page)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos what are your thoughts?

**Comment by kramachandran** [comment]
+1 on this
