### ISSUE TITLE
Configure Kubeflow with Amazon RDS

### ISSUE THREAD

**Issue by zoltan-fedor** [kubeflow/website#2972]
https://www.kubeflow.org/docs/distributions/aws/customizing-aws/rds/

The referenced changes in the ${CONFIG_FILE} are no longer valid, as the ${CONFIG_FILE} has changed.

**Comment by surajkota** [comment]
AWS Distribution of Kubeflow-1.3.1 is live

To learn more about the new features and getting started with new capabilities, please refer to the documentation on [Kubeflow.org](http://kubeflow.org/) website: https://www.kubeflow.org/docs/distributions/aws/ and checkout the what’s new under releases: https://github.com/awslabs/kubeflow-manifests/releases/tag/v1.3.1-aws-b1.0.0

For any issues, please refer to the help and feedback section: https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch#help--feedback

Please find the updated RDS deployment guide here - https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/#deployment-options

/close
