### ISSUE TITLE
Update the installation page to update the distributions table for Kubeflow 1.4

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#2991]
https://www.kubeflow.org/docs/started/installing-kubeflow/

Update the distributions table on the installation page to reflect those distributions that have been upgraded for Kubeflow 1.4.

**Comment by jbottum** [comment]
priority /p1

**Comment by shannonbradshaw** [comment]
PRs submitted so far:
https://github.com/kubeflow/website/pull/3009 (Nutanix)
https://github.com/kubeflow/website/pull/3011 (Arrikto EKF)
