### ISSUE TITLE
Get rid of the old TFServing docs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#307]
We currently have two different pages for TFServing
https://www.kubeflow.org/docs/guides/components/tfserving/  (old docs)
https://www.kubeflow.org/docs/guides/components/tfserving_new/  (new docs)

By 0.4.0 we should get rid of the old docs and just have the new docs.

@lluunn What is blocking deleting the old docs and just using the new doc? Do the new docs only apply to 0.4? i.e. do we need to create a 0.3 branch of the docs and only update the docs on master?

**Comment by lluunn** [comment]
So old docs are for old prototypes, and new docs are for new ones. 
There are still some part of the new prototype/doc not updated (e.g. Grafana).
It should be ready by 0.4, and we can remove old ones.
