### ISSUE TITLE
TRACKING - remove distribution owned docs from website

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#3074]
_This issue was spawned from the discussions raised in [PR #3004](https://github.com/kubeflow/website/pull/3004)._

---

Some time ago, the community agreed that distributions would ["be owned and maintained outside of Kubeflow"](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-distributions.md#ownership--development).

We have already [removed distribution-owned YAML](https://github.com/kubeflow/manifests/issues/1904) from `kubeflow/manifests`, we should now also remove the [distribution-owned docs](https://www.kubeflow.org/docs/distributions/) from `kubeflow.org`.

_NOTE: It is important that we get started on this soon to minimize disruption of the [“Certified Kubeflow”](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-conformance-program-proposal.md#certified-kubeflow-for-kubeflow-distribution) program. 
As once this program is implemented, distributions will need to be certified if they wish to be linked on `kubeflow.org`._

## Proposed Plan:

1. Update the ["Installing Kubeflow"](https://www.kubeflow.org/docs/started/installing-kubeflow/) table with links to each distribution's nominated "external website":
    - (Most active distributions already have their own "external website" or GitHub repo that can serve this purpose)
2. Remove the [distribution-owned docs](https://www.kubeflow.org/docs/distributions/) from kubeflow.org:
    - (Target __February 1st, 2022 (70 days)__ for removing any remaining distribution docs)
    - (We can prevent 404 errors by redirecting existing docs pages to their "external websites")
    - (As ["Kubeflow on AWS"](https://www.kubeflow.org/docs/distributions/aws/) and ["Kubeflow on Azure"](https://www.kubeflow.org/docs/distributions/azure/) are abandoned, and thus unlikely to set up an "external website", we can move the still-relevant information into the [./docs/ folder](https://github.com/kubeflow/manifests/tree/master/docs) of the `kubeflow/manifests` repo, and update the `kubeflow/manifests` [installation guide](https://github.com/kubeflow/manifests#installation) with links to this)

## Tracking Table:

| Name | Docs Path | OWNERS | PR to Remove | Status |
| --- | --- | --- | --- | --- |
| Kubeflow on AWS | [docs/distributions/aws](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/aws) | @Jeffwan @PatrickXYS |  #3233   |  ✅  |
| Kubeflow on Azure | [docs/distributions/azure](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/azure) | @aronchick @berndverst @eedorenko @sudivate |   #3547  |  ✅ |
| Kubeflow Charmed Operators | [docs/distributions/charmed](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/charmed) | @RFMVasconcelos @knkski @DomFleischmann |  #3148   | ✅ |
| Arrikto Enterprise Kubeflow | [docs/distributions/ekf](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/ekf) | @kubeflow/arrikto |   #2641  |  ✅ |
| Kubeflow on Google Cloud | [docs/distributions/gke](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/gke) | @gkcalat  @zijianjoy |  #3419 (redirect) #3548 (remove)   | ✅  |
| Kubeflow on IBM Cloud | [docs/distributions/ibm](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/ibm) | @animeshsingh @Tomcli @shawnzhu @yhwang |  #3546   | ✅ |
| MicroK8s Kubeflow add-on | [docs/distributions/microk8s](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/microk8s) | @RFMVasconcelos @knkski @evilnick @DomFleischmann |  #3148  |  ✅ |
| Arrikto MiniKF | [docs/distributions/minikf](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/minikf) | @kubeflow/arrikto |  #3247  |  ✅ |
| Kubeflow on Nutanix Karbon | [docs/distributions/nutanix](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/nutanix) | @johnugeorge @deepak-muley |     #3473 | ✅ |
| Kubeflow on OpenShift | [docs/distributions/openshift](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/openshift)[](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/openshift) | @vpavlin @crobby @nakfour @pdmack @animeshsingh |  #3518   | ✅ |
| Kubeflow Operator | [docs/distributions/operator](https://github.com/kubeflow/website/tree/master/content/en/docs/distributions/operator) | @animeshsingh @adrian555 @animeshsingh @shawnzhu |  #3545  | ✅   |
| Argoflow | N/A | N/A | N/A |  ✅  |

**Comment by goswamig** [comment]
@thesuperzapper  you should also highlight here how a user will reach to these distro specific documentation. 

I believe most of the KubeFlow users uses one of these distro (or cloud provider).  We need to take care of those user well.

**Comment by thesuperzapper** [comment]
@goswamig you are correct, but the decision of what "external link" will be listed in the `Getting Started / Installing Kubeflow` table, will be up to the maintainers of that distribution.

For example, they might choose to link directly to their GitHub repo, or to their documentation website.

**Comment by Tomcli** [comment]
@thesuperzapper Are there any restrictions on the pictures and wordings we can use in our documentation website? Since the distribution websites are going to be outside of Kubeflow.

**Comment by thesuperzapper** [comment]
> @thesuperzapper Are there any restrictions on the pictures and wordings we can use in our documentation website? Since the distribution websites are going to be outside of Kubeflow.

DISCLAIMER: This is not legal advice.

@Tomcli I would argue that most of these distributions already meet the definition of "outside Kubeflow", it's just that we are hosting their docs on `kubeflow.org` for some reason.

You may want to review Google's [brand guidelines for Kubeflow](https://github.com/kubeflow/community/blob/master/KUBEFLOW_BRAND_GUIDELINES.pdf), but any questions about those should be directed at Google.

**Comment by surajkota** [comment]
@thesuperzapper can you change the following wording related to Kubeflow on AWS
> As "Kubeflow on AWS" are abandoned

It might mislead AWS users, Kubeflow on AWS is not abandoned. Documentation is not updated to the latest version 1.4 and we are working on it. Here are the tracking issues:

https://github.com/awslabs/kubeflow-manifests/issues/27
https://github.com/awslabs/kubeflow-manifests/issues/26

**Comment by thesuperzapper** [comment]
@zijianjoy @james-jwu mentioned today that google will need more time to move their docs, so this is just a ping to ask them to comment here on the timeline they need.

**Comment by surajkota** [comment]
Checking in from AWS side. We have started working on this and will complete this in phases. As part of Phase 1 and Kubeflow 1.3.1 update (see #3166), we are moving most of the [deployment](https://www.kubeflow.org/docs/distributions/aws/deploy/) and [customizing Kubeflow on AWS](https://www.kubeflow.org/docs/distributions/aws/customizing-aws/) related documentation to the [new Github repository](https://github.com/awslabs/kubeflow-manifests) as we figure out the legal and marketing side of things to acquire a new website.

**Comment by surajkota** [comment]
AWS distribution documentation is now hosted on external website: https://awslabs.github.io/kubeflow-manifests/

**Comment by LaVLaS** [comment]
OpenShift distribution documentation will be relocated to https://github.com/opendatahub-io/manifests

**Comment by thesuperzapper** [comment]
A quick update for everyone is that we are almost finished with this issue!

The remaining PRs are:

- remove legacy "kubeflow operator" docs: https://github.com/kubeflow/website/pull/3545
- redirect ibm distribution docs to new website: https://github.com/kubeflow/website/pull/3546
- redirect azure distribution docs to new website: https://github.com/kubeflow/website/pull/3547
- remove shadowed gke distribution docs: https://github.com/kubeflow/website/pull/3548

**Comment by thesuperzapper** [comment]
We are now only one PR away from getting this closed out!

Once https://github.com/kubeflow/website/pull/3572 is merged, the distribution section will be removed from the sidebar, and old links will be redirected to the external websites!
