### ISSUE TITLE
Create a troubleshooting guide for Notebooks

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#3093]
Some relevant issues:
- https://github.com/kubeflow/website/issues/2910
- https://github.com/kubeflow/website/issues/3051
- https://github.com/kubeflow/kubeflow/issues/6200

@kimwnasptd can you link relevant issues here?

**Comment by kimwnasptd** [comment]
Thanks for creating this @shannonbradshaw! 

This is one of the first things I'd like to include https://github.com/kubeflow/kubeflow/issues/6200. I'll have this in mind and keep linking issues that I find.

**Comment by shannonbradshaw** [comment]
Thanks, @kimwnasptd
