### ISSUE TITLE
Install Kubeflow on OpenShift

### ISSUE THREAD

**Issue by kilmarnock** [kubeflow/website#3097]
The Link 
(https://raw.githubusercontent.com/opendatahub-io/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml).
on page
https://www.kubeflow.org/docs/distributions/openshift/install-kubeflow/
is dead. 404. Seemls like the closing bracket got included in the link somehow.

**Comment by jbottum** [comment]
@nakfour have you seen this issue on the OpenShift Docs ?

/platform Openshift
/priority p2
/kind bug

**Comment by shannonbradshaw** [comment]
@kilmarnock thanks for filing this. We'll get it fixed.

@nakfour I'll fix the broken link, but I wanted to check in to see whether we should go ahead and update this page for Kubeflow 1.4.
