### ISSUE TITLE
Building Components: no example on how to use Artifacts with standard components

### ISSUE THREAD

**Issue by thms-ngn** [kubeflow/website#3099]
Hi,

According to the [v2 component doc](https://www.kubeflow.org/docs/components/pipelines/sdk-v2/component-development/):

> In addition to the artifact’s data, you can also read and write the artifact’s metadata. For output artifacts, you can record metadata as key-value pairs, such as the accuracy of a trained model. For input artifacts, you can read the artifact’s metadata — for example, you could use metadata to decide if a model is accurate enough to deploy for predictions.

But there is no example at all on how to properly manipulate Artifacts with standard components (in opposition to the Python Lightweight ones).

It is said on the same page:

> If you have large amounts of string data to pass to your component, such as a JSON file, annotate that input or output as a type of Artifact, such as Dataset, to let Kubeflow Pipelines know to pass this to your component as a file.

But what should be placeholder type in the component YAML file in that case?
And how to reconstruct or output an Artifact with all its metadata if only a path is given to the command line to invoke the component?

Thanks for your help.

**Comment by jbottum** [comment]
/kind question
/priority p2
/area pipelines
@kubeflow/pipelines
