### ISSUE TITLE
Update EKS and Kubeflow compatibility matrix

### ISSUE THREAD

**Issue by imamika** [kubeflow/website#3100]
---
name: area/docs
about: The EKS & Kubeflow compatibility matrix is outdated.

---

/area/docs

**What steps did you take and what happened:**
Documentation on EKS and Kubeflow compatibility is outdated.

**What did you expect to happen:**
Expected to see updated matrix for Kubeflow 1.3/1.4

**Environment:**
here is the link to the doc
https://www.kubeflow.org/docs/distributions/aws/deploy/eks-compatibility/

**Comment by surajkota** [comment]
AWS Distribution of Kubeflow-1.3.1 is live

To learn more about the new features and getting started with new capabilities, please refer to the documentation on [Kubeflow.org](http://kubeflow.org/) website: https://www.kubeflow.org/docs/distributions/aws/ and checkout the what’s new under releases: https://github.com/awslabs/kubeflow-manifests/releases/tag/v1.3.1-aws-b1.0.0

For any issues, please refer to the help and feedback section: https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch#help--feedback

Please find the updated compatiblity matrix here - https://www.kubeflow.org/docs/distributions/aws/deploy/eks-compatibility/

/close
