### ISSUE TITLE
Updated the installation page distributions table for 1.5

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#3131]
Update the distributions table on the installation page to reflect those distributions that have been upgraded for Kubeflow 1.5.
https://www.kubeflow.org/docs/started/installing-kubeflow/

**Comment by shannonbradshaw** [comment]
@jbottum we'll want to ping on all the distribution teams on this ticket. Would you please tag everyone involved?

**Comment by shannonbradshaw** [comment]
We need to know which distros will be updated for the 1.5 release.

**Comment by jbottum** [comment]
@shannonbradshaw Hey Shannon - I believe that we are tracking on this issue, https://github.com/kubeflow/manifests/issues/2146.      @DomFleischmann do you have any suggestions on this requirement for the kubeflow.org docs ?  will this material be similar to the chart that you are creating for the 1.5 slide on distributions ?

**Comment by DomFleischmann** [comment]
@jbottum I think their readiness for 1.5 should be tracked in the issue that you mentioned. Regarding updating the distribution table in the docs, it seems to me like that should usually be part of the PR where they update their documentation for the next version and should be handled by each distribution on their own. I might be wrong with this but that seems the most reasonable as they know best if they are ready or not.

**Comment by surajkota** [comment]
Created a PR to update AWS distro status #3191

**Comment by shannonbradshaw** [comment]
OK. Let's the distributions update this page as they become ready.

**Comment by thesuperzapper** [comment]
No longer applicable. 

/close
