### ISSUE TITLE
Add release page for 1.5 to docs

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#3132]
Add a 1.5 page similar to this one:
https://www.kubeflow.org/docs/releases/kubeflow-1.4/

**Comment by shannonbradshaw** [comment]
@kimwnasptd from where can I pull a list of component versions for the 1.5 release page?

cc: @jbottum

**Comment by jbottum** [comment]
@shannonbradshaw this WG versions are tracked in in this issue, https://github.com/kubeflow/manifests/issues/2112

**Comment by jbottum** [comment]
Hey Shannon - I am trying to track the versions on page 9 of this slide deck, https://docs.google.com/presentation/d/1Kd_z8Fzb7xuzIcAhIbGs7sndT1gghGALVi7T_3C_9Gc/edit?userstoinvite=jamxl@google.com&actionButton=1#slide=id.g10fdd574828_0_83 

Here are the WG versions that I have collected, which I think is current,.
Working Group | WG Version
Notebooks | v1.5
Training Operators | v1.4
Katib | v0.13
KF Pipelines | v1.8.1
KServe | v0.7

</b>

**Comment by kimwnasptd** [comment]
@shannonbradshaw this part should suffice, but if we haven't included something we can add it

https://github.com/kubeflow/manifests/tree/v1.5-branch#kubeflow-components-versions

**Comment by jbottum** [comment]
@kimwnasptd will Knative be upgraded to 0.22.3 ?   should the Notebooks,etc be on 1.5 RC2 (or will that be updated) ?
