### ISSUE TITLE
Cut a website branch for the Kubeflow 1.5 release

### ISSUE THREAD

**Issue by shannonbradshaw** [kubeflow/website#3134]

**Comment by shannonbradshaw** [comment]
@zijianjoy we cut the 1.5 docs branch. If I remember correctly, you need to do something on the backend to make it live?

cc: @kimwnasptd

**Comment by zijianjoy** [comment]
That is right, I have performed this step https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#deploy-new-branch-to-netlify. We need to give it a day or so for SSL certificate update.

**Comment by shannonbradshaw** [comment]
Thanks, @zijianjoy !
