### ISSUE TITLE
Build pipeline1 0.0 failed

### ISSUE THREAD

**Issue by wanvincent** [kubeflow/website#3150]
on my linux, i do this, and got error!
# docker build -t api-server:test20220215-1.0 -f backend/Dockerfile .

Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //backend/src/apiserver:apiserver (1 packages loaded, 0 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (5 packages loaded, 16 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (25 packages loaded, 6126 targets configured)
INFO: SHA256 (https://codeload.github.com/golang/tools/zip/bf090417da8b6150dcfe96795325f5aa78fff718) = 11629171a39a1cb4d426760005be6f7cb9b4182e4cb2756b7f1c5c2b6ae869fe
INFO: SHA256 (https://github.com/grpc-ecosystem/grpc-gateway/archive/v1.9.0.tar.gz) = bea3b9c3b8f979c448c935f6c5c2c06b4c0bac14300ceb0802cf3419bb92cba7
DEBUG: Rule 'com_github_grpc_ecosystem_grpc_gateway' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "bea3b9c3b8f979c448c935f6c5c2c06b4c0bac14300ceb0802cf3419bb92cba7"
DEBUG: Rule 'org_golang_x_tools' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "11629171a39a1cb4d426760005be6f7cb9b4182e4cb2756b7f1c5c2b6ae869fe"
Analyzing: target //backend/src/apiserver:apiserver (32 packages loaded, 6150 targets configured)
Analyzing: target //backend/src/apiserver:apiserver (32 packages loaded, 6150 targets configured)
ERROR: /go/src/github.com/kubeflow/pipelines/backend/src/apiserver/BUILD.bazel:3:1: no such package '@com_github_minio_minio_go//': failed to fetch com_github_minio_minio_go: # cd .; git clone https://github.com/minio/minio-go /root/.cache/bazel/_bazel_root/ff9dc353908781674f376ac4c88da873/external/com_github_minio_minio_go
Cloning into '/root/.cache/bazel/_bazel_root/ff9dc353908781674f376ac4c88da873/external/com_github_minio_minio_go'...
fatal: unable to access 'https://github.com/minio/minio-go/': Empty reply from server
2022/02/15 00:59:13 exit status 128
 and referenced by '//backend/src/apiserver:go_default_library'
ERROR: Analysis of target '//backend/src/apiserver:apiserver' failed; build aborted: no such package '@com_github_minio_minio_go//': failed to fetch com_github_minio_minio_go: # cd .; git clone https://github.com/minio/minio-go /root/.cache/bazel/_bazel_root/ff9dc353908781674f376ac4c88da873/external/com_github_minio_minio_go
Cloning into '/root/.cache/bazel/_bazel_root/ff9dc353908781674f376ac4c88da873/external/com_github_minio_minio_go'...
fatal: unable to access 'https://github.com/minio/minio-go/': Empty reply from server
2022/02/15 00:59:13 exit status 128
INFO: Elapsed time: 92.059s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (32 packages loaded, 6150 targets configured)
FAILED: Build did NOT complete successfully (32 packages loaded, 6150 targets configured)

How to slove it ？

**Comment by thesuperzapper** [comment]
This is not the right place to ask for help, please reach out to the maintainers of the distribution you are using.

/close
