### ISSUE TITLE
 '@org_golang_x_sys//unix:go_default_library%linux_amd64_msan%cgo_cxx_lib' does not have mandatory providers: 'cc'. 

### ISSUE THREAD

**Issue by wanvincent** [kubeflow/website#3159]
ERROR: /root/.cache/bazel/_bazel_root/47ca83421d4eade77cfa488519355325/external/org_golang_x_sys/unix/BUILD.bazel:3:1: in libs attribute of _cgo_collect_info rule @org_golang_x_sys//unix:go_default_library%linux_amd64_msan%cgo_info: '@org_golang_x_sys//unix:go_default_library%linux_amd64_msan%cgo_cxx_lib' does not have mandatory providers: 'cc'. Since this rule was created by the macro 'go_library_macro', the error might have been caused by the macro implementation in /root/.cache/bazel/_bazel_root/47ca83421d4eade77cfa488519355325/external/io_bazel_rules_go/go/private/rules/cgo.bzl:694:16

![image](https://user-images.githubusercontent.com/16995757/154874279-b0feba0c-cb22-418b-a092-3aa2cd533e1c.png)

**Comment by thesuperzapper** [comment]
This is not the right place to ask for help, please reach out to the maintainers of the distribution you are using.

/close
