### ISSUE TITLE
Simple examples components are good. Documentation is complicated un-related to real tasks.

### ISSUE THREAD

**Issue by deepakdhiman7** [kubeflow/website#3160]
Simple examples components are good. Documentation is complicated un-related to real tasks. For example:

if this is the task:

#Importing data

data = pd.read_csv('/home/bb00745059/working_directory/Projects_try/Customer_Complaint/Data/FINAL_COMPLAINTS_DATASET(120k Rows).csv', usecols=['complaintid', 'product', 'consumer_complaint_narrative', 'company'])
data.head()

Then how to write it in kubeflow component? Which variables to use - simple or artifacts? And then show it by example component code on it and then using it within pipeline. No where I could find that. It is so confusing.

This will be really helpful.

**Comment by thesuperzapper** [comment]
This is not the right place to ask for help, please reach out to the maintainers of the distribution you are using.

/close
