### ISSUE TITLE
Change "AI Platform Pipelines" to "Vertex AI Pipelines"

### ISSUE THREAD

**Issue by connor-mccarthy** [kubeflow/website#3163]
Users should prefer to run pipelines on Vertex AI Pipelines (Vertex Pipelines for short), rather than AI Platform Pipelines. The website still suggests AI Platform Pipelines.

See comment here: https://github.com/kubeflow/website/pull/3154#discussion_r808565794

**Comment by connor-mccarthy** [comment]
@zijianjoy, can you please add me as an assignee for this issue? I do not have permission.

**Comment by zijianjoy** [comment]
Hello Connor, I just assigned this bug to you.
