### ISSUE TITLE
Install Kubeflow on EKS tutorial.

### ISSUE THREAD

**Issue by DanielLund** [kubeflow/website#3165]
This just does not work, I've had to modify my OIDC provider because the wrong one is attached to the trust relationship for the kf-admin role. The subnets weren't tagged with the shared tags, and once I finally got the load balancer up and running I cannot access the dashboard because it just returns a 504 error and there are no solutions to it

**Comment by jbottum** [comment]
/priority p2
/kind question
/area installation
/platform AWS

@DanielLund can you please provide the link that you are referring to.   Are you working with your AWS team for support?   Also, have you look at this material ?  https://github.com/kubeflow/manifests

**Comment by DanielLund** [comment]
This is the documentation I followed https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/

I have contacted AWS support and they kindly assisted with the OIDC problem, the trust relationship policy for the kf admin role had a different OIDC string and once I changed it it then gave me the error that the subnets were not tagged with the kubernetes.io/cluster/cluster-name tag and hence couldn't be found when trying to build the load balancer. I tagged all my subnets and the load balancer appeared and the command

`kubectl get ingress -n istio-system`

finally returned a dns address for the dashboard. However when I try to visit it I got a 504 error and the target group health checks were reported as failing. 

I followed a guide on how to get the health checks to check for the right port etc but again a 504 error was returned.

I just can't for the life of me figure out why it won't work when I followed the documentation to the letter

**Comment by surajkota** [comment]
Hi @DanielLund, thanks for reporting the issue. Is there a requirement for you to use Kubeflow 1.2 or are you open to try out 1.3? Let me know and we can guide you to the appropriate docs accordingly

The current docs on website are using Kubeflow 1.2 and work is in progress to update it to 1.3(~25% work remaining for this). We appreciate your patience in the meantime.

**Comment by DanielLund** [comment]
@surajkota Hi Suraj, thanks for the response. No requirement for me to stick to 1.2 so would be happy to try with 1.3. I also randomly got the self link empty can't make reference error too which as far as I know got patched quite a while ago? I also added the security groups for the target group/nodes and the load balancer to the ingress.yaml but that also didn't work and again it continued to return a 504 error

**Comment by surajkota** [comment]
HI @DanielLund, apologies for the delay in response. Here is the link to updated deployment instructions for v1.3.1: https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples#deployment-options

**Comment by surajkota** [comment]
AWS Distribution of Kubeflow-1.3.1 is live

To learn more about the new features and getting started with new capabilities, please refer to the documentation on [Kubeflow.org](http://kubeflow.org/) website: https://www.kubeflow.org/docs/distributions/aws/ and checkout the what’s new under releases: https://github.com/awslabs/kubeflow-manifests/releases/tag/v1.3.1-aws-b1.0.0

For any issues, please refer to the help and feedback section: https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch#help--feedback

/close
