### ISSUE TITLE
Add Docker for Mac installation process

### ISSUE THREAD

**Issue by rogaha** [kubeflow/website#318]
-- https://docs.docker.com/docker-for-mac/install/
-- https://download.docker.com/mac/stable/Docker.dmg
<img width="922" alt="screenshot of google chrome 11-29-18 1-12-29 pm" src="https://user-images.githubusercontent.com/4483394/49252277-710d9080-f3d8-11e8-8f7c-42354396cb02.png">

<img width="296" alt="screenshot of google chrome 11-29-18 1-10-21 pm" src="https://user-images.githubusercontent.com/4483394/49252198-37d52080-f3d8-11e8-8fa0-a02ddb05911a.png">

<img width="500" alt="screenshot of docker 11-29-18 1-10-36 pm" src="https://user-images.githubusercontent.com/4483394/49252201-3a377a80-f3d8-11e8-90c1-e1cc72c18b66.png">

### Steps
```
export KUBEFLOW_SRC=/path/to/directory
mkdir ${KUBEFLOW_SRC}
cd ${KUBEFLOW_SRC}
export KUBEFLOW_TAG=v0.3.4-rc.1
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
${KUBEFLOW_SRC}/scripts/kfctl.sh init ks_app_d4m --platform docker-for-desktop
cd ks_app_d4m
../scripts/kfctl.sh generate k8s
../scripts/kfctl.sh apply k8s
```

**Comment by rogaha** [comment]
related to https://github.com/kubeflow/kubeflow/pull/1954 and https://github.com/kubeflow/kubeflow/issues/218#issuecomment-439767431

**Comment by shaunc** [comment]
Indeed -- its odd that the MacOS page doesn't say anything about how to install if you already have Kubernetes installed. It seems to promise to at the top of the page but then it peters out after MiniKube install instructions. What about Kubeflow itself!? :)
