### ISSUE TITLE
Getting started guide for Microsoft Azure

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#32]
Related to kubeflow/kubeflow#240

We currently have getting started instructions for GKE & and minikube
https://github.com/kubeflow/website/blob/master/content/docs/getting-started-gke.md
https://github.com/kubeflow/website/blob/master/content/docs/getting-started-minikube.md

Do we want to add a getting started guide for Azure?

/cc @wbuchwalter @lachie83

**Comment by jlewi** [comment]
There is a lot of documentation on this page for Azure.
https://github.com/Azure/kubeflow-labs

it would be great to port all or some of that over to kubeflow.org

@ritazh per our conversation at Kubecon we'd love to get docs for Azure up on www.kubeflow.org

If you or someone else is willing to take this on that would be great.

/cc @aronchick

**Comment by jlewi** [comment]
@aronchick @wbuchwalter @ritazh @sozercan anyone interested in picking this up?

Related to this it would be great to get our mnist example updated to work with Azure. I think this is just a matter of updating the templates in the example to support adding the appropriate environment variables and PVCs necessary to work with data on Azure.

**Comment by ritazh** [comment]
Hi @jlewi, sorry for the delay on this. I plan to look at this once I'm done with few other priorities first.

**Comment by carmine** [comment]
@ritazh - can we assign this to you for now? 👍

**Comment by ritazh** [comment]
@carmine sure!

**Comment by ritazh** [comment]
@carmine signed. sorry for the delay.

**Comment by carmine** [comment]
@ritazh - Thx

**Comment by jlewi** [comment]
@ritazh You need to join the kubeflow org before we can assign issues to you.
More info here:
https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

**Comment by sarahmaddox** [comment]
I've added this issue as a potential one to tackle during the upcoming Kubeflow Doc Sprint. Stay tuned for info about the doc sprint!

**Comment by rem20806** [comment]
Hi! There is an intern team here at Microsoft (consisting of myself, Maanav Dalal, and Mohona Ahmed) that is working to get these docs started if you would like to assign us this issue.

**Comment by rem20806** [comment]
We also plan to attend the doc sprint in a few weeks to continue work on this issue.

**Comment by sarahmaddox** [comment]
/assign

Thanks @rem20806! I've assigned this issue to myself, so people know someone is working on it. Thanks to all three of you for taking it on. And it will be great to see you at the doc sprint too!

**Comment by sarahmaddox** [comment]
This is done.

/close
