### ISSUE TITLE
kfp diagnose_me falsely claims kubectl is not installed and fails to run

### ISSUE THREAD

**Issue by dfisk** [kubeflow/website#3200]
$ kfp diagnose_me
kubectl is not installed, gcloud, gsutil and kubectl are required for this app to run. Please follow instructions at https://cloud.google.com/sdk/install to install the SDK.

However, kubectl is installed and in the PATH:
$  dpkg --list | grep kubectl
ii  kubectl                                                      1.23.4-00                                       amd64        Kubernetes Command Line Tool

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by thesuperzapper** [comment]
This repo is not the correct place to ask for help, please raise an issue with the maintainers of the distribution you are using.

/close
