### ISSUE TITLE
Kubeflow slack invite link has expired

### ISSUE THREAD

**Issue by duttab49** [kubeflow/website#3204]
Hello,

The following slack invite link has expired.
https://www.kubeflow.org/docs/about/community/#:~:text=the%20Kubeflow%20community-,Slack,Join%20the%20official%20Kubeflow%20Slack%20with%20this%20invite%20link.,-Tip

Please share new invite link to join the Kubeflow slack channels.

Thanks
Balaram

**Comment by zijianjoy** [comment]
Thank you for reporting this, new link is created in https://join.slack.com/t/kubeflow/shared_invite/zt-15p4qkx7a-gy2kDrQS52Y44HoSssxpcw. We are going to update documentation soon.

**Comment by duttab49** [comment]
Thanks @zijianjoy
