### ISSUE TITLE
Kubeflow Slack invite

### ISSUE THREAD

**Issue by atrakriv** [kubeflow/website#3209]
The official Kubeflow Slack invite has expired. Could someone please provide a new link? Thank you!

**Comment by zijianjoy** [comment]
Done: https://github.com/kubeflow/website/pull/3210

**Comment by GerardoGR** [comment]
Not sure if we should create a new issue or just comment on this one so I will do both. Consider closing #3226 once the invite link is updated.

**Comment by zijianjoy** [comment]
Thank you for reporting! New link is https://join.slack.com/t/kubeflow/shared_invite/zt-17rs5ttas-bhCYiDwi1e25yGok_HZN2A, I will update website with new link later.
