### ISSUE TITLE
Update slack invite link

### ISSUE THREAD

**Issue by GerardoGR** [kubeflow/website#3226]
Same as #3209: The slack invite link is currently broken

**Comment by zijianjoy** [comment]
Thank you for reporting! New link is https://join.slack.com/t/kubeflow/shared_invite/zt-17rs5ttas-bhCYiDwi1e25yGok_HZN2A, I will update website with new link later.

**Comment by GerardoGR** [comment]
Thanks @zijianjoy !.

Greatly appreciated!
