### ISSUE TITLE
Update Ksonnet minimum version requirement

### ISSUE THREAD

**Issue by IronPan** [kubeflow/website#324]
Based on this https://github.com/kubeflow/pipelines/issues/414#issuecomment-443607626
the deployment won't work with <ks_v0.13

Should we update the ks version in the doc?
https://www.kubeflow.org/docs/started/getting-started/

**Comment by sarahmaddox** [comment]
The getting-started guide (and all other places where we refer to ksonnet version) says min version is 0.11.

@jlewi Is there any reason why we shouldn't specify a min version of v0.13? I see your comment in [issue 414](https://github.com/kubeflow/pipelines/issues/414#issuecomment-443607626) and am not sure of its significance with respect to this bug.

**Comment by sarahmaddox** [comment]
The min ksonnet version is now set to 0.13.1.

/close
