### ISSUE TITLE
Install Kubeflow Documentation

### ISSUE THREAD

**Issue by Niko32** [kubeflow/website#3246]
Hi,
I've been following the documentation on how to install kubeflow (https://www.kubeflow.org/docs/distributions/azure/deploy/install-kubeflow/) step by step but the kfctl apply command in step 4 throws an error for me:
kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 400 with message: couldn't create namespace kubeflow Error: Post "http://localhost:8080/api/v1/namespaces": dial tcp 127.0.0.1:8080: connect: connection refused

I'm using WSL with the kfctl_v1.2.0..._linux.tar.gz version from the kfctl release page

**Comment by chboudry** [comment]
Kubeflow 1.2 is limited to AKS 1.21 which is not deployable anymore.
You need to deploy using manifest instead of the packaged distribution, that way you will have Kubeflow 1.6.
I did a tutorial here : https://github.com/chboudry/Kubeflow-on-AKS
