### ISSUE TITLE
Slack invite has expired

### ISSUE THREAD

**Issue by isaranto** [kubeflow/website#3252]
Hey, raising an issue here as requested, cause the slack invite on the Community page has expired

**Comment by thesuperzapper** [comment]
@isaranto it seems like slack has reduced the number of people who can join per invite link to 100...

We will need to think up a more scalable solution than updating the link every time it expires, but until then, you can use:
- https://join.slack.com/t/kubeflow/shared_invite/zt-19dc5j59g-zYTxDdZgEJYzmrp6O1hyGw

**Comment by thesuperzapper** [comment]
I have raised a PR with a more permanent solution to inviting, https://github.com/kubeflow/website/pull/3269 it uses the https://invite.playplay.io/ invite bot.

Hopefully, this means that we won't have this problem again.
