### ISSUE TITLE
Slack invite link expired. 

### ISSUE THREAD

**Issue by rtkshahwar** [kubeflow/website#3261]
Slack invite link here: https://www.kubeflow.org/docs/about/community/
 has expired.

**Comment by bioshazard** [comment]
@rtkshahwar https://github.com/kubeflow/website/issues/3252#issuecomment-1132410100

**Comment by thesuperzapper** [comment]
@rtkshahwar  Let's keep the discussion in one issue, find a temporary invite link here: https://github.com/kubeflow/website/issues/3252#issuecomment-1132410100

/close
