### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by riosv** [kubeflow/website#3263]
Hi there, 

The invite link to join the official Kubeflow Slack, displayed [here](https://www.kubeflow.org/docs/about/community/), is expired. Could you provide a new link?

Thank you

**Comment by riosv** [comment]
Closing as this is a duplicate of https://github.com/kubeflow/website/issues/3261

**Comment by thesuperzapper** [comment]
@riosv find a temporary invite link here: https://github.com/kubeflow/website/issues/3252#issuecomment-1132410100
