### ISSUE TITLE
Kubeflow Slack link expired.

### ISSUE THREAD

**Issue by casperyap** [kubeflow/website#3264]
Hi, I will like to join the kubeflow community but it seems that the link provided has expired.

**Comment by arshsidana98** [comment]
Hi, I would like to add a plus one to the above request. Can we get an updated invite link to the slack channel.

**Comment by thesuperzapper** [comment]
@casperyap @arshsidana98  Let's keep the discussion in one issue, find a temporary invite link here: https://github.com/kubeflow/website/issues/3252#issuecomment-1132410100

/close
