### ISSUE TITLE
Add Containerized Dev Environment

### ISSUE THREAD

**Issue by IMBurbank** [kubeflow/website#327]
Current [dev instructions](https://github.com/kubeflow/website/blob/master/README.md) for this repo require locally installing following dependencies:
* git
* hugo
* npm
* gulp-cli
* gulp

I suggest creating an optional, simpler dev workflow using a Docker image for portable dependency management. This can simplify development instructions, allow dev environments to be quickly spun up and avoid dependency conflicts between this and other projects.

I created a Dockerfile and a few convenience scripts to make changes for my last PR. 

A PR will follow with the dev tooling I've used to make changes to this project.

**Comment by sarahmaddox** [comment]
We've had a couple of PRs suggesting the containerized workflow for doc updates, but we've decided the current workflow is simpler.

/close
