### ISSUE TITLE
Expired Kubeflow slack invite

### ISSUE THREAD

**Issue by Rishit-dagli** [kubeflow/website#3270]
The Slack invite on [this page](https://github.com/kubeflow/website/blob/master/content/en/docs/about/community.md) is outdated.

Using the slack invite:

> This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by thesuperzapper** [comment]
@Rishit-dagli this was resolved by https://github.com/kubeflow/website/pull/3269

/close
