### ISSUE TITLE
Tutorial hyperlink takes you to a "404 Page not found" page

### ISSUE THREAD

**Issue by achoreim** [kubeflow/website#3290]
At the bottom of the [KubeFlow Overview](https://www.kubeflow.org/docs/distributions/gke/deploy/overview/) page, under "Next Steps," there is a hyperlink titled: "[end-to-end MNIST tutorial](https://www.kubeflow.org/docs/distributions/gke/gcp-e2e/)"
This link takes you to a "404 Page Not Found" page which may be very frustrating to some users.

**Comment by wilkensoncode** [comment]
this issue is resolved
[end-to-end MNIST tutorial](https://github.com/kubeflow/pipelines/blob/e42d9d2609369b96973c821dca11fe5b2565e705/samples/contrib/kubeflow-e2e-mnist/kubeflow-e2e-mnist.ipynb).
