### ISSUE TITLE
Kubeflow is incompatible with openshfit 4.10

### ISSUE THREAD

**Issue by lukeyan2023** [kubeflow/website#3299]
ERRO[0618] Permanently failed applying application istio-stack:  (kubeflow.error): Code 500 with message: Apply.Run : [unable to recognize "/tmp/kout111198435": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout111198435": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "/tmp/kout111198435": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "/tmp/kout111198435": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"]  filename="kustomize/kustomize.go:288"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run : [unable to recognize "/tmp/kout111198435": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout111198435": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "/tmp/kout111198435": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "/tmp/kout111198435": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"

**Comment by thesuperzapper** [comment]
This is not the right place to ask for help, please reach out to the maintainers of the distribution you are using.

/close
