### ISSUE TITLE
Getting started guide for OpenShift

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#33]
Do we want/need a special getting started guide for open shift?

Related to kubeflow/kubeflow#240

/cc @willb  @pdmack

**Comment by pdmack** [comment]
Websites are infinite. I'm sure we could find room to add some info.

**Comment by sarahmaddox** [comment]
I've added this issue as a potential one to tackle during the upcoming Kubeflow Doc Sprint. Stay tuned for info about the doc sprint!

**Comment by sarahmaddox** [comment]
Hallo @pdmack How are you doing with this guide? (Have you earned a doc sprint T-shirt? ;) )

**Comment by pdmack** [comment]
I am doing poorly due to other commitments. Still would like the XXL t-shirt though.

**Comment by sarahmaddox** [comment]
You got it! I've just sent you your code by email. Claim the T-shirt by August 9th.

**Comment by marcredhat** [comment]
If  it helps, I'm doing some testing with OpenShift 4.2/CodeReady Containers:
https://github.com/marcredhat/crcdemos/blob/master/kubeflow/README.adoc
video at http://bit.ly/33nwbi0

**Comment by vpavlin** [comment]
Hi, we have started working on creating `KFDef` file to deploy Kubeflow on OpenShift so that users do not have to run gazillion of commands and can easily follow the KF docs.

I am happy to join and contribute it as part of the Doc Sprint:)

**Comment by sarahmaddox** [comment]
Thanks @vpavlin that's excellent news! I'm looking forward to working with you at the doc sprint in February.

/assign @vpavlin

**Comment by vpavlin** [comment]
FYI we are mostly done with https://github.com/opendatahub-io/manifests/pull/4 - there are still a few bits to be enabled and polished, but KFDef and manifests from that PR seem to mostly work for us

**Comment by sarahmaddox** [comment]
Adding some info from a [kubeflow-discuss thread](https://groups.google.com/d/msgid/kubeflow-discuss/7298be12-cce6-412b-aa7c-d0c98b88ecee%40googlegroups.com):

Work is currently in progress in a fork, which will be contributed to the Kubeflow repositories soon.

To use Kubeflow on OpenShift, you should be able to use https://github.com/opendatahub-io/manifests/ with Kubeflow v0.7 and this kfdef file: https://github.com/opendatahub-io/manifests/blob/v0.7-branch-openshift/kfdef/kfctl_openshift.yaml 

It's been tested on OpenShift 4.2, and is expected to work on any OpenShift 4 version. It's not tested on OpenShift 3.x.

Looking forward to seeing the docs emerge from the February doc sprint! :)

**Comment by sarahmaddox** [comment]
More info from [another kubeflow-discuss thread](https://groups.google.com/d/msgid/kubeflow-discuss/7cde5365-071f-4bd9-9163-73ca3e255b26%40googlegroups.com?utm_medium=email&utm_source=footer):

If you want to deploy to OpenShift, make sure you have kfctl version 0.7, then clone the manifests (https://github.com/opendatahub-io/manifests) and run

```
kfctl build --file=kfdef/kfctl_openshift.yaml
kfctl apply --file=./kfdef/kfctl_openshift.yaml
```

Assuming you are logged into an OpenShift cluster, you should see kubeflow namespace created with all the components deployed.

**Comment by vpavlin** [comment]
@sarahmaddox With the above comment, I'd say we kind of finished our initial work for KF 0.7 on OpenShift. We will go over our changes and propose them also to KF master, but I wanted to ask - what would you think about adding a "how to install" section to kubeflow website pointing to our fork until the changes get back to the KF repositories?

I am not sure what the policies for content of website are.

**Comment by sarahmaddox** [comment]
@vpavlin Yes, it will be great if you add an installation section on kubeflow.org. It's fine for the installation page(s) to point to your fork until the changes are merged into the Kubeflow repositories. For Kubeflow users, it's good to have the installation guides in one place.

Looking forward to seeing you at the doc sprint!

**Comment by sarahmaddox** [comment]
@vpavlin I've moved this issue to **In progress** in the [doc sprint Kanban board](https://github.com/orgs/kubeflow/projects/21), because the issue is assigned to you. Happy sprinting!
