### ISSUE TITLE
Short content doesn't look good on Kubeflow site

### ISSUE THREAD

**Issue by IronPan** [kubeflow/website#330]
![image](https://user-images.githubusercontent.com/2348602/49550133-9a7a6080-f89f-11e8-980e-61570550c378.png)

**Comment by sarahmaddox** [comment]
Thanks @IronPan ! I'm closing this as a duplicate of issue [#322](https://github.com/kubeflow/website/issues/322)

Note also that the Docsy theme fixes this problem. See issue #291
