### ISSUE TITLE
gcloud deployment documentation of Kubeflow is too high level

### ISSUE THREAD

**Issue by arraytuple** [kubeflow/website#3309]
gcloud deployment page  of Kubeflow  documentation is too high level.  It would be great if the steps to be followed to set up Kubeflow are elaborated.  

Thanks

**Comment by thesuperzapper** [comment]
The GKE docs are no longer on this website, please raise an issue on their new one if you are still having problems.

https://googlecloudplatform.github.io/kubeflow-gke-docs/

/close
