### ISSUE TITLE
when in run there are somany errors on the workflow when i try to configure kubeflow on azure KMS service...

### ISSUE THREAD

**Issue by prasannavj** [kubeflow/website#3345]
when in run there are somany errors on the workflow when i try to configure kubeflow on azure KMS service...WARN[0076] Encountered error applying application application:  (kubeflow.error): Code 500 with message: Apply.Run : [unable to recognize "/tmp/kout425701374": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout425701374": no matches for kind "Application" in version "app.k8s.io/v1beta1"]  filename="kustomize/kustomize.go:284"
WARN[0076] Will retry in 13 seconds.

**Comment by thesuperzapper** [comment]
The Azure docs are being removed from the website in https://github.com/kubeflow/website/pull/3547, please raise an issue on their new repo if you are still having problems.

/close
