### ISSUE TITLE
Azure OIDC installation page is broken

### ISSUE THREAD

**Issue by 64J0** [kubeflow/website#3374]
## Description:

There is a value being used in the template that is breaking the visualization for the Azure OIDC installation page ([Authentication using OIDC in Azure](https://www.kubeflow.org/docs/distributions/azure/authentication-oidc/)).

Take a look at the following screenshot to better understand it:

![image](https://user-images.githubusercontent.com/50725287/195166690-973dbb58-8885-46a9-9f14-eaf81f858ded.png)

As you can see, there is a white space or an empty line being added to the `export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_azure_aad.v1.2.0.yaml` which breaks the visualization.

The file related to this page is this:

* https://github.com/kubeflow/website/blob/master/content/en/docs/distributions/azure/authentication-oidc.md

Apparently this value is automatically written to the final build, and I don't know where to find it.

If you point where to change, I can make this contribution.

**Comment by 64J0** [comment]
It's this expression: `export CONFIG_URI="{{% azure/config-uri-azure-oidc %}}"`

**Comment by thesuperzapper** [comment]
The Azure docs are being removed from the website in https://github.com/kubeflow/website/pull/3547, please raise an issue on their new repo if you are still having problems.

/close
