### ISSUE TITLE
Create a Pipelines tutorial

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#340]
We need a pipelines tutorial, which should consist of a doc on the website plus corresponding code in the kubeflow/examples repo. We have a few samples and demos floating around - find the best one, adapt it for a tutorial that shows the happy path thru pipelines, put the resulting code in the kubeflow/examples repo, and write the doc.

**Comment by sarahmaddox** [comment]
Progress update: We're thinking it'll be good to use the same sample as for the GKE end-to-end guide. 
@DanSanche is planning to upgrade the sample to Kubeflow 0.3.4 and include an option to use Pipelines. When that's done, we can write the tutorial. Time estimate for the sample is January.

**Comment by sarahmaddox** [comment]
Started work on this.

**Comment by jinchihe** [comment]
@sarahmaddox @jlewi That's good to create a Pipeline for GKE end-to-end, but I believe some of users would like a example for on-prem cluster.  What do you think? I have implemented one mnist pipeline basic on [mnist example](https://github.com/kubeflow/examples/tree/master/mnist),  I can create a PR to commit that after kubeflow/examples#492 merged.

**Comment by sarahmaddox** [comment]
@jinchihe That sounds great! When you're ready, I'll be happy to review your PR. :)

**Comment by DanSanche** [comment]
@jinchihe  Please ping me before you merge the PR. It sounds like we may have made very similar examples, we may need to figure out how to integrate them

**Comment by jinchihe** [comment]
> @jinchihe Please ping me before you merge the PR. It sounds like we may have made very similar examples, we may need to figure out how to integrate them

@DanSanche OK, got that. Thanks.

**Comment by jinchihe** [comment]
> @jinchihe Please ping me before you merge the PR. It sounds like we may have made very similar examples, we may need to figure out how to integrate them

The PR is just created. Thanks. https://github.com/kubeflow/examples/pull/519
