### ISSUE TITLE
migrate to Google Analtics v4 before July 1, 2023 (+ share data with community)

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/website#3402]
Google will be [killing "Universal Analytics" on `July 1, 2023`](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4) which we [currently use](https://github.com/kubeflow/website/blob/39f5336ca445bf67141c0471b55cf0ad332f595d/config.toml#L68-L69) (but don't have access to as a community).

A long time ago, I tried to set up a community-owned Google Analytics v4 (PR https://github.com/kubeflow/website/pull/2875), but this was denied by Google.
Hopefully, with the CNCF donation, we can take ownership of this important and useful data.

___PS:__ if someone at Google has access to the existing data, can you please share it with the community (especially the `"Was this page helpful?"` data)?_

**Comment by chalin** [comment]
> Hopefully, with the CNCF donation, we can take ownership of this important and useful data.

Hi. FYI, use of a new (CNCF org) GA4 site tag is being setup via:

- #3620
- #3627

/cc @nate-double-u

**Comment by thesuperzapper** [comment]
Closing as completed in https://github.com/kubeflow/website/pull/3627

/close
