### ISSUE TITLE
Help people who want to use Kubeflow Pipelines alongside other GCP services

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#341]
Create a section about using Pipelines in conjunction with GCP services e.g. CMLE, Dataflow, etc. A good starting point is the GKE guide:
https://cloud.google.com/solutions/using-gcp-services-from-gke

**Comment by iyera** [comment]
For now, as a placeholder, we can point them to the relevant examples.

Soon, we will have reusable components that will simplify this, and we can update the docs accordingly when we have the reusable components.

**Comment by sarahmaddox** [comment]
Thanks @iyera - do you have any specific examples in mind?
