### ISSUE TITLE
multiple matches

### ISSUE THREAD

**Issue by lixianfa** [kubeflow/website#3417]
Error: multiple matches for rbac.authorization.k8s.io_v1_Role|~X|leader-election-role:
  [rbac.authorization.k8s.io_v1_Role|kubeflow|notebook-controller-leader-election-role
 rbac.authorization.k8s.io_v1_Role|kubeflow|profiles-leader-election-role
]
error: no objects passed to apply
Retrying to apply resources

**Comment by lixianfa** [comment]
Install Kubeflow on OpenShift
when Execute the deployment command

**Comment by thesuperzapper** [comment]
This is not the correct place to ask for support, please raise an issue with the appropriate repo (for example, whatever distro you are using).

/close
