### ISSUE TITLE
Document how to switch between TFJob's v1alpha1 and v1alpha2

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#35]
We should document how to switch the version of the TFJob CRD deployed in a cluster.

The basic commands would be something like the following

```
ks param set kubeflow-core tfJobVersion v1alpha2
kubectl -n kubeflow delete deploy tf-job-operator
kubectl delete crd tfjobs.kubeflow.org
ks apply ${ENV} -c kubeflow-core
```

We need to delete the existing CRD because we can't deploy two versions simultaneously.

**Comment by pdmack** [comment]
`kubectl -n kubeflow delete deploy tf-job-operator`

Is that actually required?

**Comment by jlewi** [comment]
@pdmack The v1alpha2 and v1alpha1 deployments have different names so if you don't delete it sticks around.

I believe they can coexist ok but probably better to delete it anyway.

**Comment by jlewi** [comment]
Instructions were added here:
https://www.kubeflow.org/docs/about/user_guide/#upgrading-kubeflow-deployments
