### ISSUE TITLE
Arrikto Kubeflow as a Service

### ISSUE THREAD

**Issue by andrewspiers-csiro** [kubeflow/website#3519]
This page:
https://www.kubeflow.org/docs/distributions/kfaas/
contains a link to:
https://kubeflow.arrikto.com/
Which doesn't resolve for me:

# curl https://kubeflow.arrikto.com/
curl: (6) Could not resolve host: kubeflow.arrikto.com

**Comment by thesuperzapper** [comment]
@andrewspiers-csiro thanks for raising this, I have made a PR to remove it from the website https://github.com/kubeflow/website/pull/3549

**Comment by thesuperzapper** [comment]
Resolved by https://github.com/kubeflow/website/pull/3549

/close
