### ISSUE TITLE
Error at the end of "e2e kubeflow on GCP" guide

### ISSUE THREAD

**Issue by giogit** [kubeflow/website#353]
At the end of the guide, the command to activate port forwarding contains some errors:
1) the command refers to the variable $ {NAMESPACE} that is not defined
2) the command to select the pod does not work
3) when creating the ksonnet component for the UI, port 5000 is indicated while in port forwarding, port 80 is indicated

Below is a version that works:
```
kubectl port-forward -n ${DEPLOYMENT_NAME}  `kubectl get pods --all-namespaces \
  --selector=app=web-ui -o=jsonpath='{.items[0].metadata.name}'` 8080:5000
```

**Comment by sarahmaddox** [comment]
/assign

Thanks!
