### ISSUE TITLE
How to install Kubeflow cli?

### ISSUE THREAD

**Issue by Mayuraggarwal1992** [kubeflow/website#3576]
I am playing with kubeflow containerized python components. As per the below doc, we can push a component to the container registry by using "target_image" flag in definition and run the following command "kfp component build .................".

https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/#3-build-the-component

I am having a hard time to figure out how to install kubeflow cli. I would really appreciate if someone can point me to the documentation or alternative way to build the component.

The below link refers to how to use kubeflow cli but there is no mention of how to install it. 
https://kubeflow-pipelines.readthedocs.io/en/2.0.0b16/source/cli.html#kfp

KFP version: Running on Vertex

KFP SDK version: 2.0.1

**Comment by connor-mccarthy** [comment]
Clarified by https://github.com/kubeflow/website/pull/3575
