### ISSUE TITLE
Docs for build / train / deploy from notebook

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#361]
A core CUJ for 0.5. is build train deploy from a notebook.

We will need docs explaining how users can do this.

**Comment by jlewi** [comment]
The instructions should include how people can push code to git.
This most likely mean generating an ssh key and adding it to their repo (e.g. GitHub) so they can authenticate to their repo.

**Comment by sarahmaddox** [comment]
Also focus on how data scientists can find this content and get started quickly. This can be part of the information architecture updates - see issue [#383](https://github.com/kubeflow/website/issues/383).
