### ISSUE TITLE
Broken link in Readme file for samples 

### ISSUE THREAD

**Issue by vikas-saxena02** [kubeflow/website#3610]
The kubfeflow documentation at https://www.kubeflow.org/docs/components/pipelines/v1/tutorials/build-pipeline/  asks users to clone or download the samples at https://github.com/kubeflow/pipelines/tree/sdk/release-1.8/samples

However, the second link in the Readme.md that states Build and deploy your pipeline [using the provided samples](https://www.kubeflow.org/docs/guides/pipelines/pipelines-samples/), seems to be broken and returns a 404. 
<img width="1047" alt="Screenshot 2023-10-28 at 7 27 24 am" src="https://github.com/kubeflow/website/assets/90456542/caac3520-7c92-464c-83a0-a3465d806222">

**Comment by Siddharth133** [comment]
It's Working

**Comment by vikas-saxena02** [comment]
Thanks Sid, it was fixed at end of july
