### ISSUE TITLE
Check our copyright statement

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#363]
We currently reserve all copyright rights. Should we instead use a cc-by license?

**This is what we currently state in the Kubeflow footer:**
Copyright © 2018 Kubeflow.org. All Rights Reserved. 

**For comparison, this is what the Kubernetes site states:**
© 2018 The Kubernetes Authors | Documentation Distributed under CC BY 4.0
Copyright © 2018 The Linux Foundation ®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page

**Comment by sarahmaddox** [comment]
@ewilderj @abhi-g Do you have the history behind the copyright statement on the Kubeflow site, and do you think we should move to cc-by?

**Comment by abhi-g** [comment]
I really didn't put any deep thought into the copyright statement of the
website.

Please feel free to update as necessary and appropriate.

Regards
Abhishek

**Comment by sarahmaddox** [comment]
I've checked with the Open Source Programs Office. We should have the following copyright notice on the Kubeflow docs:

Copyright 2018 The Kubeflow Authors | Documentation Distributed under CC BY 4.0
