### ISSUE TITLE
Cleaning script of "e2e kubeflow on GCP" guide doesn't work

### ISSUE THREAD

**Issue by giogit** [kubeflow/website#371]
The cleaning command at the end of the guide does not work.

I tried to use the command suggested in [issue 1092](https://github.com/kubeflow/kubeflow/issues/1092) but, in this way, IAM roles were not deleted.

**Comment by sarahmaddox** [comment]
Just a note that we're planning to update the e2e tutorial to a later version of Kubeflow. See issue [#261](https://github.com/kubeflow/website/issues/261). This will fix the problem. In the meantime, using the "abandon" policy is the workaround, with manual cleanup of the IAM roles.

**Comment by jlewi** [comment]
Should we mark this a duplicate of #261 (Upgrade GKE end to guide to use a later version of Kubeflow) and close this issue?

**Comment by sarahmaddox** [comment]
Sounds good!
