### ISSUE TITLE
Improvements for Kubeflow Pipelines documentation

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3712]
- [x] https://github.com/kubeflow/website/issues/3716
- [x] https://github.com/kubeflow/website/issues/3760
- [x] https://github.com/kubeflow/website/issues/3714
- [ ] https://github.com/kubeflow/website/issues/3729
- [x] https://github.com/kubeflow/website/issues/3715
- [x] https://github.com/kubeflow/website/issues/3766

### Issues found during https://github.com/kubeflow/website/pull/3737

- [x] https://github.com/kubeflow/website/issues/3761
- [x] https://github.com/kubeflow/website/issues/3756
- [x] https://github.com/kubeflow/website/issues/3751
- [x] https://github.com/kubeflow/website/issues/3749
- [x] https://github.com/kubeflow/website/issues/3773
- [x] https://github.com/kubeflow/website/issues/3764
- [ ] https://github.com/kubeflow/website/issues/3750
- [ ] https://github.com/kubeflow/website/issues/3752
- [ ] https://github.com/kubeflow/website/issues/3757
- [ ] https://github.com/kubeflow/website/issues/3742
- [ ] https://github.com/kubeflow/website/issues/3741

**Comment by StefanoFioravanzo** [comment]
@hbelmiro  can you please elaborate on the third bullet? Do you have something specific in mind?

**Comment by StefanoFioravanzo** [comment]
@hbelmiro @diegolovison Hey, I'd like to draw your attention to these two comments:

- https://github.com/kubeflow/training-operator/issues/1998#issuecomment-2063642934
- https://github.com/kubeflow/katib/issues/2314#issue-2256543450

and then the Katib PR that addresses those comments:

- https://github.com/kubeflow/website/pull/3723

As you can see, I am proposing a restructuring based on principles that we can apply for KFP as well. Would either one of you take the lead and propose a similar restructuring for the KFP docs? It would be great to start with a proposal similar to what I did for Katib, outlining what needs to change, what needs to move, what new sections we need. As you go through this exercise, you can also take note of what user guides or topics are missing, and share a separate list of TODOs.

We can track this here https://github.com/kubeflow/website/issues/3716 if you want. Whatever suits you better. Let me know your thoughts!

PS: My thought process follows this doc framework https://diataxis.fr/ - I encourage you to take ~1h and go through it. It's very well written and easy to follow. It won't take long!

**Comment by hbelmiro** [comment]
@StefanoFioravanzo I really like the idea. It will enhance the documentation's quality and keep consistency between the components. We could also mention that structure in https://www.kubeflow.org/docs/about/style-guide/.

> Would either one of you take the lead and propose a similar restructuring for the KFP docs?

Yes, I can do it.

> We can track this here https://github.com/kubeflow/website/issues/3716 if you want. Whatever suits you better. Let me know your thoughts!

Yeah, sounds good.

**Comment by StefanoFioravanzo** [comment]
@hbelmiro Can you link this in the first comment? https://github.com/kubeflow/website/issues/3729

**Comment by hbelmiro** [comment]
@StefanoFioravanzo I added as a new bullet since it can be done in a follow-up PR.

**Comment by thesuperzapper** [comment]
We should also update the link in the `Legacy (v1) / References / Pipelines SDK Reference` to actually point to the V1 version of the SDK, it currently points to:

- https://kubeflow-pipelines.readthedocs.io/en/stable/

It should be updated to point to the last V1 version:

- https://kubeflow-pipelines.readthedocs.io/en/1.8.22/

**Comment by thesuperzapper** [comment]
We should place a warning at the top of all pages in the `Legacy (v1)` section that says something like:

```md
This page is for Kubeflow Pipelines V1.
While the V2 backend is [backwards compatible](xxx_page_about_this_xxxx) with V1 pipelines, 
we recommend you [upgrade to the V2 SDK](xxxx_v2_migration_guide_xxxx), please see the [V2 docs](xxxx_v2_docs_xxxx) for more information.
```

**Comment by varodrig** [comment]
@hbelmiro 
@StefanoFioravanzo 
@rimolive 
should we close this issue since it's related to Release 1.9 or is this still a working progress?
