### ISSUE TITLE
Add content to the Kubeflow Pipelines V2 installation page

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3714]
Right now, the installation page shows only: This page will be available soon. We need to add the steps to install Kubeflow Pipelines V2 in a vanilla Kubernetes cluster.
We can use https://www.kubeflow.org/docs/components/pipelines/v1/installation/standalone-deployment/ as a reference.

**Comment by thesuperzapper** [comment]
@hbelmiro The PR https://github.com/kubeflow/website/pull/3782 did nothing to actually update the installing KFP docs for V2.

I am going to reopen this issue, please raise a proper PR.

/reopen
