### ISSUE TITLE
Document that is possible to upload a .zip or .tar.gz file as a pipeline

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3715]
When uploading a pipeline, users can also send .zip or .tar.gz files. This can be added to the documentation.

![Screenshot from 2024-04-12 11-06-22](https://github.com/kubeflow/website/assets/11776454/2bcc9ecf-f195-4494-9243-b3fe7465c5a7)

**Comment by milosjava** [comment]
@hbelmiro Hi Helbert, I hope you heard my discussion with Ricardo during today's release call regarding this issue. I am willing to help with this one if you are interested.

**Comment by hbelmiro** [comment]
Sure @milosjava.
Do you need anything from my side?

**Comment by milosjava** [comment]
@hbelmiro  https://github.com/kubeflow/website/pull/3778
