### ISSUE TITLE
Review the structure of the docs to reflect Kubeflow 1.9

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3716]
Based on https://github.com/kubeflow/website/issues/3712#issuecomment-2090564646, we need to review the structure of the docs.

The new structured is defined in the [comment bellow](https://github.com/kubeflow/website/issues/3716#issuecomment-2107564488).

**Comment by hbelmiro** [comment]
@StefanoFioravanzo what do you think about the following structure?

- Overview (Section)
  - [Introduction](https://www.kubeflow.org/docs/components/pipelines/v2/introduction/)
  - [Installation](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/)
  - [Getting Started](https://www.kubeflow.org/docs/components/pipelines/v2/hello-world/)
- How tos/User guides (Section)
  - Run a pipeline (there are two sections that seems duplicated)
    - [Run a Pipeline](https://www.kubeflow.org/docs/components/pipelines/v2/run-a-pipeline/)
    - [Run a basic pipeline using KFP Dashboard and SDK](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/)
  - [Compile a Pipeline](https://www.kubeflow.org/docs/components/pipelines/v2/compile-a-pipeline/)
  - [Execute KFP pipelines locally](https://www.kubeflow.org/docs/components/pipelines/v2/local-execution/)
  - [Interact with KFP via the CLI](https://www.kubeflow.org/docs/components/pipelines/v2/cli/)
  - Create components (Section)
    - [Lightweight Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/lightweight-python-components/)
    - [Compose components into pipelines - Pipeline Basics](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/pipeline-basics/)
    - [Containerized Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/)
    - [Container Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/)
    - [Special Case: Importer Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/importer-component/)
    - [Additional Functionality](https://www.kubeflow.org/docs/components/pipelines/v2/components/additional-functionality/)
  - [Load and Share Components](https://www.kubeflow.org/docs/components/pipelines/v2/load-and-share-components/)
  - [Create pipelines with control flow](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/control-flow/)
  - [Pass small amounts of data between components (Parameters)](https://www.kubeflow.org/docs/components/pipelines/v2/data-types/parameters/)
  - [Create, use, pass, and track ML artifacts (Artifacts)](https://www.kubeflow.org/docs/components/pipelines/v2/data-types/artifacts/)
  - Build a more advanced ML pipeline (from https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/)
  - [Use caching](https://www.kubeflow.org/docs/components/pipelines/v2/caching/)
  - [Server Configuration](https://www.kubeflow.org/docs/components/pipelines/v2/administration/server-config/)
  - [Migrate from KFP SDK v1](https://www.kubeflow.org/docs/components/pipelines/v2/migration/)
  - [Author tasks with platform-specific functionality](https://www.kubeflow.org/docs/components/pipelines/v2/platform-specific-features/)
- Reference (Section)
  - [Community and Support](https://www.kubeflow.org/docs/components/pipelines/v2/community-and-support/)
  - [Version Compatibility](https://www.kubeflow.org/docs/components/pipelines/v2/version-compatibility/)
  - [Pipelines API Reference](https://www.kubeflow.org/docs/components/pipelines/v2/reference/api/kubeflow-pipeline-api-spec/)
  - [Pipelines SDK Reference](https://www.kubeflow.org/docs/components/pipelines/v2/reference/sdk/)

**Comment by StefanoFioravanzo** [comment]
@hbelmiro this looks pretty good! Are you planning on submitting a PR with this refactoring? Few questions:

- Did you take every single guide from the current structure, or is there anything that was left out?
- Current we have `v1` and `v2` as the two top-level sections. Are you planning to remove them? If yes, where does the `v1` content go?
- It could make sense to promote `Migrate from KFP SDK v1` to a top-level page. WDYT?

**Comment by hbelmiro** [comment]
@StefanoFioravanzo 

> Are you planning on submitting a PR with this refactoring?

Yes, once we get aligned with the structure.
I plan to move the existing pages to the new structure in a first PR and then make other changes, if needed, in follow-up PRs. It will make reviews easier and unlock other changes.

> Current we have v1 and v2 as the two top-level sections. Are you planning to remove them? If yes, where does the v1 content go?

Actually, not. I didn't analyze v1. The suggested structure is only for v2.
What do you think of setting v1 as a stretch goal? We can prioritize v2 and when v2 is good we enhance v1.

> It could make sense to promote Migrate from KFP SDK v1 to a top-level page. WDYT?

It could, but I don't see the need. Also, it concerns me that we can be opening a precedent and having everything mixed again in the future.

**Comment by hbelmiro** [comment]
> I would rather suggest an approach that moves the docs away from this structure
> 
> ```
> /pipelines/
>   /v1
>   /v2
> ```
> 
> to something like this
> 
> ```
> /pipelines/
>   /<unfolded v2 content>
>   /legacy-v1/
> ```
> 
> But we can work on this in a separate PR. I don't think it makes sense to spend precious hours in refactoring the v1 structure. We can keep it as-is and move it under that legacy section. If needed we can promote some guides from v1 to v2.

Perfect. I think the same way.

It would be nice to have @milosjava's inputs too.

### Updated structure

- Overview (Section)
  - [Introduction](https://www.kubeflow.org/docs/components/pipelines/v2/introduction/)
  - [Installation](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/)
  - [Getting Started](https://www.kubeflow.org/docs/components/pipelines/v2/hello-world/)
- How tos/User guides (Section)
  - Run a pipeline (there are two sections that seems duplicated)
    - [Run a Pipeline](https://www.kubeflow.org/docs/components/pipelines/v2/run-a-pipeline/)
    - [Run a basic pipeline using KFP Dashboard and SDK](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/)
  - [Compile a Pipeline](https://www.kubeflow.org/docs/components/pipelines/v2/compile-a-pipeline/)
  - [Execute KFP pipelines locally](https://www.kubeflow.org/docs/components/pipelines/v2/local-execution/)
  - [Interact with KFP via the CLI](https://www.kubeflow.org/docs/components/pipelines/v2/cli/)
  - Create components (Section)
    - [Lightweight Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/lightweight-python-components/)
    - [Compose components into pipelines - Pipeline Basics](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/pipeline-basics/)
    - [Containerized Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/)
    - [Container Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/)
    - [Special Case: Importer Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/importer-component/)
    - [Additional Functionality](https://www.kubeflow.org/docs/components/pipelines/v2/components/additional-functionality/)
  - [Load and Share Components](https://www.kubeflow.org/docs/components/pipelines/v2/load-and-share-components/)
  - [Create pipelines with control flow](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/control-flow/)
  - [Pass small amounts of data between components (Parameters)](https://www.kubeflow.org/docs/components/pipelines/v2/data-types/parameters/)
  - [Create, use, pass, and track ML artifacts (Artifacts)](https://www.kubeflow.org/docs/components/pipelines/v2/data-types/artifacts/)
  - Build a more advanced ML pipeline (from https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/)
  - [Use caching](https://www.kubeflow.org/docs/components/pipelines/v2/caching/)
  - [Server Configuration](https://www.kubeflow.org/docs/components/pipelines/v2/administration/server-config/)
  - [Migrate from KFP SDK v1](https://www.kubeflow.org/docs/components/pipelines/v2/migration/)
  - [Author tasks with platform-specific functionality](https://www.kubeflow.org/docs/components/pipelines/v2/platform-specific-features/)
- Reference (Section)
  - [Community and Support](https://www.kubeflow.org/docs/components/pipelines/v2/community-and-support/)
  - [Version Compatibility](https://www.kubeflow.org/docs/components/pipelines/v2/version-compatibility/)
  - [Pipelines API Reference](https://www.kubeflow.org/docs/components/pipelines/v2/reference/api/kubeflow-pipeline-api-spec/)
  - [Pipelines SDK Reference](https://www.kubeflow.org/docs/components/pipelines/v2/reference/sdk/)
- Legacy-v1
  - [The entire existing v1 tree]

**Comment by milosjava** [comment]
@hbelmiro documentation is quite good. One thing maybe to improve would be to give more info in section [control-flow ](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/control-flow/) , regarding the part when it says: " not yet supported by the KFP orchestration backend, but may be supported by other orchestration backends".  Do we have some docs regarding "orchestration backends"?

**Comment by HumairAK** [comment]
cc @chensun / @zijianjoy
