### ISSUE TITLE
Accessing Ambassador docs should port-forward using service not pod

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#373]
Context kubeflow/kubeflow#2155
kubectl can now port-forward to a service.

This simplifies the port-forward command since we don't have to get the ambassador pod first.

We should update the port-forward command in the docs
https://www.kubeflow.org/docs/guides/accessing-uis/

to port-forward based on the service.

**Comment by andreyvelich** [comment]
Will take it. 
/assign
