### ISSUE TITLE
Update the outdated content of pages about the Feature Store Feast.

### ISSUE THREAD

**Issue by shuchu** [kubeflow/website#3730]
The current version of Feast is v0.37. And we need to update the outdated content.

**Comment by sagnik3788** [comment]
@shuchu  I want to work on this issue. Please assign it to me

**Comment by rimolive** [comment]
cc @franciscojavierarceo

**Comment by shuchu** [comment]
> @shuchu I want to work on this issue. Please assign it to me

Hi, It seems I can not modify the Assigned option for this code repo. but feel free to submit a PR for this issue. :)

**Comment by shuchu** [comment]
it is solved by this PR: https://github.com/kubeflow/website/pull/3734
