### ISSUE TITLE
contributions table not showing 

### ISSUE THREAD

**Issue by sagnik3788** [kubeflow/website#3732]
![Screenshot 2024-05-05 201826](https://github.com/kubeflow/website/assets/116512372/53937f44-932c-48e7-928d-ff477e291d16)

![Screenshot 2024-05-05 201811](https://github.com/kubeflow/website/assets/116512372/8e6b3620-0db1-4428-b828-5126d2504314)

**Comment by hbelmiro** [comment]
Https://github.com/kubeflow/website/pull/3657 will fix this.
