### ISSUE TITLE
Not able to go Next 

### ISSUE THREAD

**Issue by dhirajpatra** [kubeflow/website#3747]
- It will help a lot when user gets a Next button after reading the current page. This Next button link must be dynamically created based on the previous page visited by the current user.
- Another update though optional be if you provide code and steps to test in local environment as well instead of cloud.

Thank you -
Dhiraj

**Comment by hbelmiro** [comment]
> * It will help a lot when user gets a Next button after reading the current page. This Next button link must be dynamically created based on the previous page visited by the current user.

I'm not sure I'm following. We already have [Next Steps](https://www.kubeflow.org/docs/components/pipelines/v2/introduction/#next-steps) sections, not on all pages though.

> Another update though optional be if you provide code and steps to test in local environment as well instead of cloud.

Indeed. We already have running initiatives to be more cloud-agnostic. But there's still a long way to go.
Feel free to send PRs. Any help is welcome.

**Comment by dhirajpatra** [comment]
Ok sure.
Thank you.

Warm Regards,
*Dhiraj Patra*

*Software Architect & AI Engineer*
*Phone: +917893273022*
*skype: dhirajpatra  Profile <https://github.com/dhirajpatra>*
*P* *Please consider the environment before printing this e-mail*
