### ISSUE TITLE
Add "Out of date" warnings to all Pipelines v1 docs

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3751]
```
{{% alert title="Old Version" color="warning" %}}
This page is about __Kubeflow Pipelines V1__, for information about __Kubeflow Pipelines V2__, please see the [new docs](__root_link_to_v2_docs__).

Please note that Kubeflow Pipelines V2 supports running V1 pipelines in a [backwards compatible mode](__page_which_explains_this__).
{{% /alert %}}
```

**Comment by thesuperzapper** [comment]
Cross-posting from https://github.com/kubeflow/website/pull/3737#discussion_r1626590777

All of the pages under the pipeline's section which contain `{{% alert title="Out of date" color="warning" %}}` need to have it removed, there are currently 5 in master:

- Component Specification
     - You removed this one already.
- Best Practices for Designing Components
- DSL Recursion
- Using environment variables in pipelines
- Manipulate Kubernetes Resources as Part of a Pipeline
    - Looking at this one,  we also need to create a V2 version of this, because its changed a lot.
    - See https://github.com/kubeflow/website/issues/3750#issuecomment-2148396967
