### ISSUE TITLE
OAuth client instructions are ambiguous

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#376]
_From @vfontama on December 21, 2018 21:21_

The instructions to create credentials is a bit ambiguous.  Specifically, in step 2 where we set the "Authorized redirect URIs" the instructions have this sample: "https://<name>.endpoints.<project>.cloud.goog/_gcp_gatekeeper/authenticate".

The <project> is straightforward.  However, the <name> is confusing. It is not clear which name to use:  In the screenshot the "Name" field has a different name from the name used in the "Authorized redirect URIs" field.  So it's not clear if we should use the same name or not.

<img width="960" alt="screen shot 2018-12-21 at 12 21 45 pm" src="https://user-images.githubusercontent.com/37591676/50364078-53d56900-0523-11e9-9eff-320b36f27a61.png">

_Copied from original issue: kubeflow/pipelines#586_

**Comment by jlewi** [comment]
Thanks @sarahmaddox is this fixed by #377?

**Comment by sarahmaddox** [comment]
Yes it is. I don't know why the "fixed" annotation on the PR didn't work.
/close
