### ISSUE TITLE
Incorrect links in V2 / data types / artifacts documentation page

### ISSUE THREAD

**Issue by ichbinjakes** [kubeflow/website#3766]
The links in these two paragraphs for "Python Components" and "Container Components" are for the wrong pages. Additionally, it is unclear from the text if python components refers to lightweight AND containerised python components.

https://github.com/kubeflow/website/blob/6be88bd593f4069183731bd5732aab5069986c1b/content/en/docs/components/pipelines/v2/data-types/artifacts.md?plain=1#L78-L84

**Comment by hbelmiro** [comment]
> it is unclear from the text if python components refers to lightweight AND containerised python components.

@ichbinjakes I don't understand what is the problematic text. Can you please highlight the statement that leaves the above unclear.

**Comment by rimolive** [comment]
This is where the KFP docs describes the concept of a component.

https://www.kubeflow.org/docs/components/pipelines/concepts/component/
