### ISSUE TITLE
Docs for multi-user Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#379]
See: 
CUJ: http://bit.ly/kubeflow_cuj_multi_user
Design Doc:http://bit.ly/kf_jupyter_design_doc

In 0.5 we want to support multi-user Kubeflow deployments in which each user is isolated in their own namespace.

This is the tracking issue for adding docs to describe these scenario.

I think we should have a new section in our docs page corresponding to critical user journeys. We can then have a page or section for each user journey. multi-user would be one of them.

**Comment by sarahmaddox** [comment]
+1 to ensuring all critical user journeys are included in the docs, but I'm not sure we should actually use the term "critical user journey" in the docs or group docs as CUJs. The term CUJ is quite specific, probably used only by particular groups of UX researchers. I hadn't heard it until recently, and the word "critical" is overloaded in meaning. Also, it'd be hard to define which guides should fit into a CUJ section. For example, I'd argue that "getting started" is a CUJ. :)

Instead, we should make sure there's a guide that describes each user journey, or use case, or task, or whatever we want to call it. So, we'd just have a guide named something like **Multi-user deployments** or **Managing multi-user deployments**.

One thing I do want to do is to organize our **guides** section to make the important guides easier to find. I'm also considering that we may need a **tutorials** section, so people can more easily find the end-to-end guides/tutorials. See issue [#383](https://github.com/kubeflow/website/issues/383).

**Comment by sarahmaddox** [comment]
Updating the current thinking for docs for multi-user Kubeflow:

* Hold off on documenting this for now.
* When we're ready, we'll start with a script for the release demo, followed by a blog post. Then can base the docs on those.
* For docs, we'll need to decide whether to create a tutorial or focus on reference docs.

**Comment by jlewi** [comment]
Here's the demo/release script for multi-user Jupyter
https://bit.ly/2UOzzxB

That's probably a good place to start for updating the docs.

**Comment by jlewi** [comment]
@abhi-g How is #903 coming?

**Comment by abhi-g** [comment]
in review with kunming.
