### ISSUE TITLE
Fix broken links in Katib

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3811]
[Now that we have Checklinks enabled in Netlify](https://github.com/kubeflow/website/pull/3763), we can fix the existing broken links we have on our TODO list.

1. Remove Katib links from [Checklinks TODO list](https://github.com/kubeflow/website/blob/e1eb76b4facca9562445a63c14bbe30b7003b5c3/netlify.toml#L12).
2. Fix links [reported in Netlify deployment log](https://github.com/kubeflow/website/assets/11776454/01cf5cf0-3d8a-49dd-b32e-89506c4a71d9).

https://github.com/kubeflow/website/pull/3807 can be used as a reference.

cc @andreyvelich @gaocegege @johnugeorge @sperlingxx

**Comment by varodrig** [comment]
@hbelmiro  please assign this issue to me. thank you

**Comment by hbelmiro** [comment]
> @hbelmiro I'm working on this. there's a link broken in the page Page: docs/components/katib/user-guides/trial-template/ Link broken: docs/components/training/user-guides/mxnet The page doesn't exists however, it does exist on this branch. https://v1-9-branch.kubeflow.org/docs/components/training/user-guides/mxnet/ please recommend steps to resolve this if needed to create the page or remove the link. thanks

You probably can remove that bullet.
@andreyvelich can you confirm?

**Comment by hbelmiro** [comment]
@varodrig since you're leaving for vacation, please send the PR with the bullet removed.
Hopefully, it will be merged when you get back, otherwise you can fix it later.
