### ISSUE TITLE
Fix broken links in Training Operator

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/website#3812]
[Now that we have Checklinks enabled in Netlify](https://github.com/kubeflow/website/pull/3763), we can fix the existing broken links we have on our TODO list.

1. Remove Training Operator links from [Checklinks TODO list](https://github.com/kubeflow/website/blob/e1eb76b4facca9562445a63c14bbe30b7003b5c3/netlify.toml#L12).
2. Fix links [reported in Netlify deployment log](https://github.com/kubeflow/website/assets/11776454/01cf5cf0-3d8a-49dd-b32e-89506c4a71d9).

https://github.com/kubeflow/website/pull/3807 can be used as a reference.

cc @andreyvelich @ChanYiLin @gaocegege @Jeffwan @johnugeorge @terrytangyuan

**Comment by varodrig** [comment]
I'm working on it. @hbelmiro  to assign to @varodrig

**Comment by varodrig** [comment]
@hbelmiro  we should closed this issue.

**Comment by hbelmiro** [comment]
/close
Resolved by https://github.com/kubeflow/website/pull/3899
