### ISSUE TITLE
Documentation for kubeflow 1.9 is missing

### ISSUE THREAD

**Issue by tzabbi** [kubeflow/website#3824]
Kubeflow Documentation for v1.9 is not found on Webpage. I can select 1.9 but then i get the page not found:
![image](https://github.com/user-attachments/assets/bd2f069f-e6db-4726-8098-5e5e2ce7c118)

![image](https://github.com/user-attachments/assets/6c7c7759-2163-41fc-a335-0e3be8837284)

**Comment by rimolive** [comment]
cc @zijianjoy

**Comment by rimolive** [comment]
@tzabbi The page should be available, but we still need to work on the certificate update which might take 1 one day. Let me know if you can get access.

**Comment by tzabbi** [comment]
@rimolive the page is now available but still with ssl issues.

**Comment by rimolive** [comment]
@tzabbi The certificate issue is now solved. Please take a look and if it looks good, close the issue.

**Comment by tzabbi** [comment]
thanks works now!
