### ISSUE TITLE
[Feedback] docs/components/spark-operator/getting-started.md

### ISSUE THREAD

**Issue by JTBS** [kubeflow/website#3893]
Please change documentation:
helm install my-release spark-operator/spark-operator \
   --namespace spark-operator  \
   --create-namespace \
   --set "sparkJobNamespaces={spark}" \
   --set webhook.enable=true \
   --set webhook.port=443

TO:
helm install my-release spark-operator/spark-operator \
   --namespace spark-operator  \
   --create-namespace \
   --set "spark.jobNamespaces={spark}" \
   --set webhook.enable=true \
   --set webhook.port=443

Change: It needs to be "**spark.jobNamespaces**" NOT sparkJobNamespaces - I spent lot of time to finally figure this out :) So it might save time for others

**Comment by varodrig** [comment]
/close
cc @hbelmiro
