### ISSUE TITLE
[Feedback] docs/components/pipelines/operator-guides/installation/_index.md

### ISSUE THREAD

**Issue by padhr2810** [kubeflow/website#3895]
This worked fine a few days ago, but has stopped working on my Ubuntu 22.04.3 laptop. 

`export PIPELINE_VERSION=2.3.0`
`kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"`

Received the following error message:

> Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
> error: error validating "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=2.3.0": error validating data: failed to download openapi: Get "https://192.168.49.2:8443/openapi/v2?timeout=32s": dial tcp 192.168.49.2:8443: connect: no route to host; if you choose to ignore these errors, turn validation off with --validate=false

I tried turning off validation and updating kustomization as instructed but this didn't help.

**Comment by hbelmiro** [comment]
What is the output of `kustomize version`?

**Comment by hbelmiro** [comment]
The error `connect: no route to host` indicates that your `kubectl` command cannot reach the Kubernetes API server at `192.168.49.2:8443`.
Make sure you're connected to a Kubernetes cluster.

**Comment by padhr2810** [comment]
Thanks @hbelmiro .
Tried a couple of things. [Simple suggestion at this link](https://www.reddit.com/r/kubernetes/comments/1ewwube/minikube_is_not_able_to_start/) worked: 
`minikube delete`
`minikube start`

Before that I tried the suggestion at this link but didn't work for me.
`minikube stop`
`minikube start`

Thanks again.

**Comment by hbelmiro** [comment]
I'm not sure about the compatibility and steps needed for minikube. I recommend using kind instead. 
Please see: https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/localcluster-deployment/#kind
