### ISSUE TITLE
Japan's ruling party loses its majority in blow to new PM

### ISSUE THREAD

**Issue by aarsffsersees** [kubeflow/website#3919]
The coalition led by Japan’s ruling Liberal Democratic Party (LDP) has lost its majority in parliament, its worst result in over a decade.

The LDP and its coalition partner, the much smaller Komeito, have taken 215 seats together, falling short of the 233-seat majority needed to govern[.](https://myboohd.wufoo.com/forms/zuyz2500rjzj3g/)[.](https://myboothai.wufoo.com/forms/z132ag2n132a98i/)[.](https://phadamkham.wufoo.com/forms/z1jwiv6p0m3tffp/)[.](https://waiipeng2thai.wufoo.com/forms/z1lj8u2w0xlxhwu/)[.](https://waiipeng2.wufoo.com/forms/z1of2v481je4uq7/)[.](https://teeyod2thai.wufoo.com/forms/z1guv0pr1p3hme9/)[.](https://teeyod2.wufoo.com/forms/zp466k11cyn17v/)[.](https://bobby52rodriguez732.outgrow.us/hd)[.](https://bobby52rodriguez732.outgrow.us/bobby52rodriguez732-4)[.](https://teeyod2hd.outgrow.us/thai)

The election was called by the LDP’s new leader Shigeru Ishiba just days before he was sworn in as prime minister - but the loss of his party's parliamentary majority has now put his political future into question.

In a speech on Monday, he said the LDP had received "severe judgement", adding they would "humbly" accept this.

"Voters have handed us a harsh verdict and we have to humbly accept this result," Ishiba told national broadcaster NHK.

"The Japanese people expressed their strong desire for the LDP to do some reflection and become a party that acts in line with the people's will," he said.

Ahead of the election, Japanese media had reported that if the LDP loses its parliamentary majority, Ishiba could quit to take responsibility, which would make him Japan's shortest-serving prime minister in the post-war period.

This is the first time the LDP has lost its parliamentary majority since 2009. Since its founding in 1955, the party has ruled the country almost continuously.

The result comes after a tumultuous few years for the LDP which saw a “cascade” of scandals, widespread voter apathy and record-low approval ratings.

The party had seen approval ratings of below 20% earlier in the year, in the wake of a political fundraising corruption scandal.

Meanwhile, largest opposition party, the Constitutional Democratic Party (CDP), won 148 seats at around 02:00 JST (17:00 GMT), according to NHK.

Yet opposition parties have failed to unite, or convince voters they are a viable option to govern.

The CDP, which is the main opposition party, had an approval rating of just 6.6% before parliament was dissolved.

CDP leader Yoshihiko Noda on Monday said he plans to work with other parties to oust the incumbents.

“It is so hard to make decisions to choose parties, I think people are losing interest,” Miyuki Fujisaki, a long-time LDP supporter who works in the care-home sector, told the BBC ahead of polls opening.

The LDP, she said, has its problems with alleged corruption, “but the opposition also does not stand out at all”.

“They sure complain a lot, but it’s not at all clear on what they want to do,” the 66-year-old said.

In the wake of the results, the benchmark Nikkei 225 stock index was up by around 1.5%, while the yen fell against the US dollar.

For all the apathy, politics in Japan has been moving at a fast pace in recent months.

Ishiba took over as prime minister after being voted in by the LDP following his predecessor Fumio Kishida - who had been in the role since 2021 – making a surprise decision to step down in August.

The move to call the election came at a time when the LDP is desperate to restore its tarnished image among the public. Ishiba - a long-time politician who previously served as defence minister - has described it as the “people’s verdict”.

A series of scandals has tarnished the party’s reputation. Chief among them is the party’s relationship with the controversial Unification Church - described by critics as a “cult” - and the level of influence it had on lawmakers.

Then came the revelations of the political funding corruption scandal. Japan’s prosecutors have been investigating dozens of LDP lawmakers accused of pocketing proceeds from political fundraising events. Those allegations - running into the millions of dollars - led to the dissolution of powerful factions, the backbone of its internal party politics.

“What a wretched state the ruling party is in,” said Michiko Hamada, who had travelled to Urawa station, on the outskirts of Tokyo, for an opposition campaign rally.

“That is what I feel most. It is tax evasion and it’s unforgivable.”

It strikes her as particularly egregious at a time when people in Japan are struggling with high prices. Wages have not changed for three decades – dubbed “the lost 30 years” – but prices have risen at the fastest rate in nearly half a century in the last two years.

This month saw more price hikes on thousands of food products, as well as other day-to-day provisions like mail, pharmaceuticals, electricity and gas.

“I pay 10,000 yen or 20,000 yen ($65 - $130; £50 - £100) more for the food per month (than I used to),” Ms Hamada said.

“And I’m not buying the things I used to buy. I am trying to save up but it still costs more. Things like fruit are very expensive.”

She is not the only one concerned with high prices.

Pensioner Chie Shimizu says she now must work part-time to make ends meet.

“Our hourly wage has gone up a bit but it does not match the prices,” she told the BBC as she picked up some food from a stand at Urawa station.

“I come to places like this to find something cheaper and good because everything in regular shops is expensive.”

**Comment by thesuperzapper** [comment]
/close

Reported to GitHub

**Comment by thesuperzapper** [comment]
/close

Reported to GitHub
