### ISSUE TITLE
kubeflow installation issues on minikube using v0.7 docs guide

### ISSUE THREAD

**Issue by bohemia420** [kubeflow/website#3923]
getting the following error:
```
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout653223145": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout653223145": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout653223145": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"]  filename="kustomize/kustomize.go:183"
WARN[0169] Will retry in 35 seconds.                     filename="kustomize/kustomize.go:184"
```

upon doing: `kfctl apply -V -f ${CONFIG_FILE}`

while trying to install `kubeflow` on **minikube**. I have precisely been following this [deployment-with-kfctl-k8s-istio](https://v0-7.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)guide. 

minikube version
minikube version: v1.32.0

OS: 23.2.0 Darwin Kernel Version 23.2.0

**Comment by thesuperzapper** [comment]
@bohemia420 I hope you are joking?

Because Kubeflow 0.7 is no longer supported, it was released on 2019-10-17, over 5 years ago.

How did you even come across the 0.7 docs?

**Comment by bohemia420** [comment]
@thesuperzapper search for "minikube for kubeflow". the first search that shows up is of either 0.2 or 0.7. Nevermind, I have been using kind so far for standalone kf setups, but needed minikube now! let me grok more.

**Comment by thesuperzapper** [comment]
@bohemia420 ok, well I am going to close this issue.

If you want to run Kubeflow on Minikube, I recommend looking at the [kubeflow distributions](https://www.kubeflow.org/docs/started/installing-kubeflow/#packaged-distributions) which support all Kubernetes clusters.

I personally maintain [deployKF](https://www.deploykf.org/), so am a bit biased toward that one!

/close

**Comment by thesuperzapper** [comment]
Also, we are aware of the older sites showing up and have actually just got that fixed today, but it will take Google a few months to de-index them as it tries to re-scrape them.
