### ISSUE TITLE
Update KubeFlow Website banner with the new event

### ISSUE THREAD

**Issue by varodrig** [kubeflow/website#3926]
Right now the site is showing the past kubecon event. We should update it to KubeCon Europe https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/

![image](https://github.com/user-attachments/assets/aa33df7a-0ab9-47d6-b972-ab85d43760ed)

**Comment by varodrig** [comment]
Please assign to me and confirm event. thanks,

**Comment by varodrig** [comment]
@hbelmiro

**Comment by hbelmiro** [comment]
@varodrig now that you're a member you can assign yourself with `/assign`.

/assign @varodrig
