### ISSUE TITLE
Styling: Adjusting timing of colour change in top nav bar on front page

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#393]
https://www.kubeflow.org/

When you scroll down the front page of the website, past the dark hero area, the colour of the top navigation bar changes from dark blue to light blue. The lighter blue matches the header in the rest of the docs, and the change of colour helps to highlight the nav bar.

However, the change of colour seems to happen at the wrong time. It should actually happen either as soon as the scrolling starts, or when the top section (the dark blue) scrolls away.

**Comment by sarahmaddox** [comment]
Just a note that we have some volunteers working on this fix. I'm assigning the issue to myself, so people know it's being worked on.
/assign

**Comment by mk-nickyang** [comment]
@sarahmaddox This issue should be fixed if we upgrade the docsy version

**Comment by sarahmaddox** [comment]
Thanks @mk-nickyang!
