### ISSUE TITLE
icon exceeds and is not wrapped

### ISSUE THREAD

**Issue by nihalchollampat** [kubeflow/website#3933]
<img width="752" alt="Screenshot 2024-11-29 at 6 30 25 PM" src="https://github.com/user-attachments/assets/5fcc9dd7-fa15-4c0c-9387-d0020a3ca113">

**Comment by nihalchollampat** [comment]
top left icon is exceeding to the body

**Comment by thesuperzapper** [comment]
This is a stylistic decision that allows the full logo while not having a very tall top bar.

/close
