### ISSUE TITLE
[Feedback] docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md  (ml-pipeline-ui container is restarting)

### ISSUE THREAD

**Issue by shaik-byte** [kubeflow/website#3937]
Hi Team,

I have been using the kubeflow pipeline version 2.3.0.

I am getting the issue with the ml-pipeline-ui container, while i am doing the installatio on Docker desktop and Kuberenetes cluster.

Can you please look into it. The container is restaing with the crashloopbackoff and other issues.

**Comment by hbelmiro** [comment]
@shaik-byte you need to create this issue in https://github.com/kubeflow/pipelines.

/close
