### ISSUE TITLE
What permissions are required for a user to setup Kubeflow on GKE?

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#399]
Recently, I worked through the process of setting up Kubeflow on GKE from the following page:
[https://www.kubeflow.org/docs/started/getting-started-gke/](https://www.kubeflow.org/docs/started/getting-started-gke/)

What permissions are required for a user to set up Kubeflow on GKE through the UI or the command line? In my case, I had to grant myself **Owner** permissions for the installation process to work using the UI. Does the user need project **Owner** permissions to set up Kubeflow or can the user install this with a narrower set of permissions?

**Comment by joeliedtke** [comment]
@jlewi, Would you please clarify which permissions are required for a user to set up Kubeflow on GKE? Does the user need project **Owner** permissions to install Kubeflow through the UI or command line, or could Kubeflow be installed with a narrower set of permissions in GCP?

**Comment by jlewi** [comment]
I think you pretty much need to be an OWNER.

If you install on GCP we create IAM service accounts, ingress resources, cloud endpoints and enable required services on the project.

**Comment by sarahmaddox** [comment]
Thanks @joeliedtke and @jlewi 

It'd be good to add this requirement to the [prerequisites](https://www.kubeflow.org/docs/started/getting-started-gke/#prerequisites) section of the GKE getting-started guide.

Also, in the section on [using the UI](https://www.kubeflow.org/docs/started/getting-started-gke/#deploy-kubeflow-on-gke-using-the-ui) we talk about "administrator privileges" - it'd be good to be more precise.

/good-first-issue

**Comment by sarahmaddox** [comment]
/assign

I'll tackle this as part of PR https://github.com/kubeflow/website/pull/712
