### ISSUE TITLE
Docsy theme contrast for inlined code is too low

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#402]
With the new docsy theme inlined code i.e text in back quotes renders as white text on a grey background.

The contrast ends up being very low and its hard to read.

**Comment by sarahmaddox** [comment]
Just a note that we have some volunteers working on this fix. I'm assigning the issue to myself, so people know it's being worked on.
/assign

**Comment by mk-nickyang** [comment]
@sarahmaddox This issue should be fixed if we upgrade the docsy version

**Comment by sarahmaddox** [comment]
Thanks @mk-nickyang!
