### ISSUE TITLE
ksonnet rationale

### ISSUE THREAD

**Issue by pdmack** [kubeflow/website#415]
@jlewi provided some very useful elaboration of the utility of ksonnet for the project here:
https://groups.google.com/d/msg/kubeflow-discuss/aEqGFLnjZCU/j1QSI82FGQAJ

The debates can continue but might be worth augmenting https://www.kubeflow.org/docs/guides/components/ksonnet/#why-kubeflow-uses-ksonnet with those details.

**Comment by sarahmaddox** [comment]
I'm going to close this issue as obsolete, given the pending [archiving of ksonnet](https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/) by
HeptIO/VMWare.
