### ISSUE TITLE
Getting started for onprem

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/website#418]
Add docs for getting started onprem. 
Documentation should address Setup Kubernetes and Kubeflow quick start.

**Comment by sarahmaddox** [comment]
@swiftdiaries How are you getting on with this issue?

**Comment by swiftdiaries** [comment]
I'm currently working on a PR related to this: https://github.com/kubeflow/kubeflow/pull/3026

So, once I have the platform specific customization in and the PR is merged, I can contribute the related changes to the docs as well

**Comment by elviraux** [comment]
Issue for reference:
#3972

**Comment by sarahmaddox** [comment]
I think this requirement is now covered by the following set of docs:
https://www.kubeflow.org/docs/started/k8s/overview/

I'll close this issue, but please do re-open it if more work is needed.

/close
