### ISSUE TITLE
kfctl.sh: explain how to reuse deploy name

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/website#420]
In current version of kfctl.sh, we don't provide way to delete deployment. Most user will just delete from deployment manager and redeploy.
That unfortunately didn't work because IAM bindings from old deployment still holding the position.

We need to add instruction:

If kfctl.sh user want to reuse deploy name, they should clear IAM bindings related to old deployment manually.

**Comment by sarahmaddox** [comment]
Include info on **how** to clear the IAM bindings.

Add the info to this doc:
https://www.kubeflow.org/docs/guides/gke/troubleshooting-gke/#troubleshooting-cloud-iap

**Comment by sarahmaddox** [comment]
I'm closing this issue as obsolete. We don't use kfctl.sh any more.

/close
