### ISSUE TITLE
Explain how to how to disable IAP in the command-line setup

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#421]
You don't need IAP when testing in your own cluster.

Add info on how to disable IAP in the command-line setup:
https://www.kubeflow.org/docs/guides/gke/customizing-gke/

For v0.4.1, one way is before `apply`, do:
`ks param set jupyter jupyterHubAuthenticator null`

To remove jupyter auth dependency on IAM

**Comment by amygdala** [comment]
This would also be useful for workshop contexts (or any time-constrained contexts), where we want to skip IAP but also can't use the launcher UI due to some customization.

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/432

**Comment by sarahmaddox** [comment]
The CLI deployment doc now explains how to set up basic auth:
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

/close
