### ISSUE TITLE
Using Cloud Filestore - Instruction assumes ${KFAPP} is complete path 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/website#422]
The instruction seems to assume ${KFAPP} is fully qualified path, however following the instructions on kubeflow setup this ENV variable must be set to app name. 

if user is copying the instructions and running them in order as is they will not work.

**Comment by sarahmaddox** [comment]
This is the page:
https://github.com/kubeflow/website/blob/master/content/docs/gke/cloud-filestore.md
