### ISSUE TITLE
Docs need to be updated to point at 0.4.1 by default

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#430]
0.4.1 is now available.

We should update the docs to make 0.4.1 the default.

**Comment by sarahmaddox** [comment]
/assign @abhi-g 

Before we can re-point the docs, we need the 0.4 archive of the docs, as described in our procedures here:
https://github.com/kubeflow/website/blob/master/README.md#versioning-of-the-docs

**Comment by sarahmaddox** [comment]
/close

Thanks @CraigSterrett!
