### ISSUE TITLE
for GKE launcher, add more detail on non-IAP process

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#432]
in this section of the docs: https://www.kubeflow.org/docs/started/getting-started-gke/#deploy-kubeflow-on-gke-using-the-ui
consider describing how to connect via either setup path (either use IAP, or don't use IAP)

For the non-IAP path, the instructions could look something like what's in step 3 of this codelab:
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-pipelines-gis/#2
(clicking on the cloud shell button in the launcher UI, doing the port forwarding, etc.)

**Comment by sarahmaddox** [comment]
Fixed by https://github.com/kubeflow/website/pull/712
