### ISSUE TITLE
TensorFlow Training (TFJob) - exitCode behaviour

### ISSUE THREAD

**Issue by mateusz-ciesielski** [kubeflow/website#443]
Description of ExitCode restartPolicy should be updated to reflect changes made in the following PR: github.com/kubeflow/tf-operator/pull/518

Current description is misleading: only specific exit codes are identified as retryable, not the whole 128-255 range.

**Comment by sarahmaddox** [comment]
This is the page that needs updating:
https://github.com/kubeflow/website/blob/master/content/docs/components/tftraining.md

/good-first-issue
