### ISSUE TITLE
FAQ: Does Kubeflow Support Helm

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#450]
We should start an FAQ for Kubeflow.

One of the questions we get most often is do we support helm.

The answer to this should be something along the lines of:

You don't need to use ksonnet to use TFServing, TFJob, etc... You can define those resources using whatever K8s tooling you want; raw YAML, helm, kustomize, ksonnet.

We provide ksonnet mostly as convenient syntax sugar. The arena CLI might have helm charts if that's the route you prefer.

**Comment by jlewi** [comment]
@sarahmaddox Any idea where we should put an FAQ?

**Comment by sarahmaddox** [comment]
I think we should put it under "Other Guides":
https://www.kubeflow.org/docs/other-guides/

and change the description and title of the index file so they don't restrict the section to guides/instructions only:
https://github.com/kubeflow/website/blob/master/content/docs/other-guides/_index.md

**Comment by sarahmaddox** [comment]
@jlewi Is it still true to say that people can define their resources using whatever K8s tooling they want? We seem to be pretty heavily invested in kustomize. Do we still get the question about helm support?

**Comment by jlewi** [comment]
@sarahmaddox People can use whatever resourcing they want to create Kubeflow resources (e.g. TFJob, Seldon Deployments, Notebooks, they want).

Kubeflow's deployment infrastructure is closely tied to kustomize.

**Comment by Swikar** [comment]
Hello @sarahmaddox Would you please assign this issue to me? I will take care this.

**Comment by sarahmaddox** [comment]
Thanks @Swikar!
/assign @Swikar

**Comment by sarahmaddox** [comment]
Fixed by PR https://github.com/kubeflow/website/pull/1681

/close
