### ISSUE TITLE
Link from the contributor guide to the inclusivity doc 

### ISSUE THREAD

**Issue by ewilderj** [kubeflow/website#454]
Doc here https://github.com/kubeflow/community/blob/master/INCLUSIVITY.md

cc @texasmichelle

**Comment by sarahmaddox** [comment]
We should add a link from this section of the website, where we mention the code of conduct:
https://www.kubeflow.org/docs/about/contributing/#follow-the-code-of-conduct

**Comment by janeman98** [comment]
I will tackle this for the doc sprint.

**Comment by sarahmaddox** [comment]
Thanks @janeman98 

/assign @janeman98

**Comment by sarahmaddox** [comment]
@janeman98 I've moved this issue to **In progress** in the [doc sprint Kanban board](https://github.com/orgs/kubeflow/projects/21), because the issue is assigned to you. Happy sprinting!
