### ISSUE TITLE
Kubeflow Day LA - March 7, 2019 in Pasadena

### ISSUE THREAD

**Issue by jbottum** [kubeflow/website#455]
The Kubeflow Community is sponsoring a Kubeflow Day LA on March 7, 2019 in Pasadena with sessions planned by Google, Microsoft, Cisco, Redhat, Canonical, MavenCodes, Arrikto, and local ML specialists.    This url provides the current info on the event.    could we please add it to the list of Kubeflow events.   Thanks.   Josh 

https://www.socallinuxexpo.org/scale/17x/kubeflow-day-la

**Comment by jbottum** [comment]
how is this coming along? will it be posted on the events page ?

**Comment by irabinovitch** [comment]
@theadactyl Anything we can help with to get this online ahead of the event?

**Comment by sarahmaddox** [comment]
@irabinovitch Would you like to send a PR? Here's the guide to updating the docs:
https://github.com/kubeflow/website/blob/master/README.md

/cc @theadactyl

**Comment by scottilee** [comment]
Seeing as how this event date has passed, the issue should be closed.

/close
