### ISSUE TITLE
tf-job yaml spec appears to be incorrect

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#462]
I believe that this example:
https://github.com/kubeflow/website/blob/master/content/docs/components/tftraining.md#what-is-tfjob
is incorrect in 2 respects: 
 - it needs a 'Master' or 'Chief' spec added
 - the status stuff at the end should be removed, as this is meant to be an example of the yaml file that is submitted to create the job.

**Comment by amygdala** [comment]
More detail: As is (but removing the 'status' stuff), I get this error:
```
INFO:tensorflow:TF_CONFIG environment variable: {u'environment': u'cloud', u'cluster': {u'ps': [u'trainer-hbvxc-ps-0.kubeflow.svc:2222', u'trainer-hbvxc-ps-1.kubeflow.svc:2222'], u'worker': [u'trainer-hbvxc-worker-0.kubeflow.svc:2222']}, u'task': {u'index': 1, u'type': u'ps'}}
Traceback (most recent call last):
train files list: ['gs://aju-dev-demos-pipelines/newtfjob2/workflow-1-h659q/tft-train/train_transformed-00000-of-00001.gz']
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
eval files list: ['gs://aju-dev-demos-pipelines/newtfjob2/workflow-1-h659q/tft-eval/eval_transformed-00000-of-00001.gz']
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/trainer/task.py", line 201, in <module>
    run_experiment(train_files, eval_files, hparams)
  File "/ml/trainer/task.py", line 105, in run_experiment
    estimator = train_and_maybe_evaluate(train_files, eval_files, hparams)
  File "/ml/trainer/task.py", line 79, in train_and_maybe_evaluate
    save_checkpoints_steps=999, keep_checkpoint_max=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/run_config.py", line 528, in __init__
    self._init_distributed_setting_from_environment_var(tf_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/run_config.py", line 589, in _init_distributed_setting_from_environment_var
    self._cluster_spec, task_env, TaskType.CHIEF)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/run_config.py", line 163, in _validate_task_type_and_task_id
    chief_task_type)
ValueError: If "cluster" is set in TF_CONFIG, it must have one "chief" node.
```
I fixed it by adding a 'Master' spec, like so:
https://github.com/amygdala/code-snippets/blob/master/ml/kubeflow-pipelines/components/kubeflow/launcher/train.template.yaml
(**Note**: we don't want to swap in this example as is, since it also includes mounting the user-gcp-sa secret, which is GKE specific. But it gives the gist.). 

I'm confused as to how the existing example in the docs worked for the person who provided it, so I'm wondering if there's something I'm missing.

**Comment by sarahmaddox** [comment]
Friendly ping @amygdala How are you doing with this update?

**Comment by amygdala** [comment]
I'm sorry, I'm having trouble digging out of N*xt work.  I will try to come back to this on the weekend. One issue: as mentioned above, I'm confused as to how the existing example in the docs worked for the person who provided it, so I'm wondering if there's something I'm missing. It would be good to find the original author -- do you have any idea who that might be?

**Comment by sarahmaddox** [comment]
I don't know who the original author is. Perhaps @jlewi knows?

**Comment by amygdala** [comment]
okay, I'm finally returning to this.  amazing, I know :).  Hope to tackle it tomorrow.
