### ISSUE TITLE
URL still links to pantheon

### ISSUE THREAD

**Issue by syvlabs** [kubeflow/website#479]
### Problem

In the [Kubernetes Engine for Kubeflow](https://www.kubeflow.org/docs/started/getting-started-gke/#deleting-your-kubeflow-deployment) page, the cloud console link still links to this internal [pantheon url](https://pantheon.corp.google.com/dm/deployments).

### Solution

I think it was meant to link to [this GCP url](https://console.cloud.google.com/dm/deployments) instead.

**Comment by sarahmaddox** [comment]
/assign

Thank you for reporting this issue!
