### ISSUE TITLE
Make all external links on the Docs website open in a new tab

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/website#482]
## Existing Behavior
Most external links already have `target="_blank"` on the anchor tags. For the iframe approach being used to render the docs portal within the landing page, it would be ideal to have all external links present this behavior

## Concern
Some pages, when opened, like Github or Medium, block rendering inside a frame. This causes a broken behavior on the page like:

![image](https://user-images.githubusercontent.com/5303018/52746748-1a573200-2f97-11e9-9eed-9d570a621363.png)

Thanks!

/assign @sarahmaddox

**Comment by sarahmaddox** [comment]
On iframing the docs into the Kubeflow UI, please see issue https://github.com/kubeflow/kubeflow/issues/2546

**Comment by sarahmaddox** [comment]
Investigation shows that all links within the doc pages do already open in a new tab. This is configured by the following setting in our `config.toml` file:

```
[blackfriday]
hrefTargetBlank = true
```

After spending some time investigating this issue report, the only links that I can find that do not follow this rule are the following links in the top nav and footer:

* Footer: Privacy Policy
* Top nav: Blog, GitHub
