### ISSUE TITLE
Microk8s for Kubeflow

### ISSUE THREAD

**Issue by sachin-ac** [kubeflow/website#487]
When following the quick start, I am having issues with the following step
**kubeflow-tools/install-kubeflow.sh**

Seeing below error:

INFO Applying customresourcedefinitions applications.app.k8s.io
INFO Creating non-existent customresourcedefinitions applications.app.k8s.io
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/tmp/ksonnet-mergepatch883366293": no matches for kind "Application" in version "app.k8s.io/v1beta1"

**Comment by sarahmaddox** [comment]
This issue was moved to kubeflow/kubeflow#2545
