### ISSUE TITLE
Running tfcnn example does not work

### ISSUE THREAD

**Issue by qiujian16** [kubeflow/website#501]
The link is here https://github.com/kubeflow/website/blob/master/content/docs/components/tftraining.md#running-the-tfcnn-example.

It mentions to run
```
ks generate tf-job-simple ${CNN_JOB_NAME} --name=${CNN_JOB_NAME}
```

however it does not work since the API of tfjob has switched from v1alpha2 to v1beta1. So it should be updated to
```
ks generate tf-job-simple-v1beta1 ${CNN_JOB_NAME} --name=${CNN_JOB_NAME}
```

Also should ask user to run
```
ks init {some tf job}
```
at the beginning of the example, otherwise it will fail to run other `ks` commands.

Would like to help to submit a PR to fix it if it makes sense..

**Comment by sarahmaddox** [comment]
Thanks @qiujian16 Yes, please do submit a PR and assign it to me for review.
