### ISSUE TITLE
Doc on TF serving - document Istio and other features like prometheus

### ISSUE THREAD

**Issue by lluunn** [kubeflow/website#51]
migrating [this](https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/istio-integration.md) to website

**Comment by jlewi** [comment]
See also #97 we should have a new guide page for just TFServing and put all the information about TFServing there.

**Comment by amsaha** [comment]
/assign

Will get this done once #97 is closed (currently pr #102 in review).

**Comment by amsaha** [comment]
Waiting on #105.
