### ISSUE TITLE
building lightweight components: doc how to use py3 vs py2?

### ISSUE THREAD

**Issue by amygdala** [kubeflow/website#515]
Are the functions that the user builds for this process: 
https://www.kubeflow.org/docs/pipelines/lightweight-python-components/
required to be py3 (including imports)?  I believe that is so, in which case we should probably indicate that.
E.g. that precludes import of many of the TFX libs IIRC.

**Comment by amygdala** [comment]
Update: It looks like support for py2 was added last week (https://github.com/kubeflow/pipelines/pull/730).  
Looks like it does require building with a separate image (as shown in this notebook: https://github.com/kubeflow/pipelines/blob/master/samples/notebooks/KubeFlow%20Pipeline%20Using%20TFX%20OSS%20Components.ipynb) ... is that something it makes sense to mention on this page?)

**Comment by sarahmaddox** [comment]
@amygdala Please assign the issue to someone for an answer, or send someone a PR for review, otherwise the issue will just sit here. People can't write docs an issue that's just a question. :)

I'll assign the issue now to @vicaire as he knows about Pipelines.

/assign @vicaire

**Comment by amygdala** [comment]
The question was more on whether we wanted to go into that level of detail in the docs vs just pointing them to the notebook.  I can add the info as well if we think it's a good idea -- let me see if I have assign permissions for this repo:
/assign @amygdala 

(btw, I've had people tell me it's inappropriate to assign bugs myself -- they prefer to ID who should tackle it -- so I was holding off. Sorry).

**Comment by sarahmaddox** [comment]
Oh no, docs are different. Please do grab any issue you like. :D
