### ISSUE TITLE
Pipeline DSL and SDK documentations

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/website#518]
We need to build or generate SDK documentation from current python code. The documentation should cover:
* The public surface of DSL SDK [code](https://github.com/kubeflow/pipelines/tree/master/sdk/python/kfp)
* The public surface of pipeline client SDK [code](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py)
* The public surface of component sdk which user can use inside their container. [code](https://github.com/kubeflow/pipelines/tree/master/component_sdk/python/kfp_component)

The best thing we can do is to generate the python docs from docstring, but we need to figure out how to integrate with the kubeflow/website structure.

**Comment by sarahmaddox** [comment]
Thanks @hongye-sun! I've transferred your comment to the existing issue:
https://github.com/kubeflow/website/issues/345

I'll close this issue as a duplicate.

/close
