### ISSUE TITLE
Update getting started guide to use new kfctl binary

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#529]
We will need to update the getting started guides to use the new kfctl go binary.

**Comment by sarahmaddox** [comment]
@jlewi Please would you assign an engineer to create a PR for this task (preferable), or supply more detail so that someone else can take it on (less efficient).

**Comment by sarahmaddox** [comment]
See all docs that refer to kfctl:
https://github.com/kubeflow/website/search?q=kfctl&unscoped_q=kfctl
