### ISSUE TITLE
Getting started on GCP error: DM failed because not enough quota

### ISSUE THREAD

**Issue by lluunn** [kubeflow/website#533]
Someone at the summit reported that it's really hard to get started using Kubeflow on GCP.
- they got a quota error on DM. New project probably doesn't have enough cpu quota? 
- didn't know how to spend the 300 gcp credit
- so many [steps](https://www.kubeflow.org/docs/started/getting-started-gke/) to get started. Do we have doc for basic auth @kunmingg ?

**Comment by sarahmaddox** [comment]
This isn't a doc issue:

* If there's a quota problem, the engineering team should make sure new projects have more quota.
* GCP credits are outside of Kubeflow.
* Basic auth is AFAIK not yet released. Once it is released, we should add a separate issue to update the docs with basic auth instructions.

I'm going to close this issue, as it's not reproducible and therefore not addressable. If necessary, please raise separate issues for each point, explaining how the docs should be updated to address the point.

/close

**Comment by lluunn** [comment]
> This isn't a doc issue:

I think if a user following our guide and can't get it work, the doc needs some update.

> * If there's a quota problem, the engineering team should make sure new projects have more quota.

We should explain how to check quota or raise quota.

> * GCP credits are outside of Kubeflow.

We should link to gcp guide on how to use credit.

> * Basic auth is AFAIK not yet released. Once it is released, we should add a separate issue to update the docs with basic auth instructions.

I think basic auth is working. filed #549
