### ISSUE TITLE
NVIDIA TensorRT Inference Server: libcaffe2.so Error

### ISSUE THREAD

**Issue by ultrons** [kubeflow/website#538]
I see the following error when NVIDIA container is started following the instruction in the article:

"E  trtserver: error while loading shared libraries: libcaffe2.so: cannot open shared object file: No such file or directory"
  
I am using nvcr.io/nvidia/inferenceserver:18.08.1-py3

**Comment by jlewi** [comment]
@ultrons Can you explain what you are doing? E.g. if you are deploying some server can you provide the YAML spec for your resource?

This seems like it would be an issue with your docker image since its missing a linked file.

**Comment by jlewi** [comment]
My suggestion for debugging would be to use kubectl to start an interactive shell

```
kubectl -it run ...
```

Then use a tool like `ldd` to look at linking of whatever binary you are running.

**Comment by sarahmaddox** [comment]
Thanks jlewi

I'm going to close this issue as answered. If there's a need for a doc update, please raise an issue specifying the doc update required.

/close
