### ISSUE TITLE
Amend the "Getting Started with Kubeflow" page

### ISSUE THREAD

**Issue by cspavlou** [kubeflow/website#548]
The current "[Getting Started with Kubeflow](https://www.kubeflow.org/docs/started/getting-started/)" page includes instructions for installing Kubeflow with Kubernetes as a prerequisite. Moreover, there is a section for installing Kubernetes. However, the "Set up Kubernetes" section is not actually a guide for installing K8s, but for installing Kubeflow on top of Minikube or Microk8s, which looks like a conflict with the "Kubeflow quick start" in a following section of the guide. We propose to split the guide in two sections:
a) Installation without pre-existing Kubernetes
b) Installation on existing Kubernetes

Furthermore, we add MiniKF in the instructions as a third option for installing Kubeflow locally.

We propose the following structure for the updated page:

- Who should consider using Kubeflow?
- Installation without pre-existing K8s
  - Local
    - MiniKF
    - Minikube Guide
    - MicroK8s Guide
  - Cloud
    - GKE Guide
- Installation on existing K8s
  - Install Kubeflow
  - Remove Kubeflow
- Troubleshooting
- Resources

**Comment by sarahmaddox** [comment]
This structure LGTM.

@abhi-g do you have any feedback?

**Comment by abhi-g** [comment]
It looks great! On the section about installing on existing K8s, it would be great if it also clarified that it's the path to take for on-prem.

**Comment by cspavlou** [comment]
@abhi-g thanks for the comment. I will add a sentence to clarify this
