### ISSUE TITLE
Code-formatted text is too light when in list

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#553]
The styling of text in code format (that is, surrounded by tick marks like `this`) when included in a list makes the text hard to read.

See for example the text in the bulleted list in the section "Creating a custom Jupyter image" on this page:
https://www.kubeflow.org/docs/components/jupyter/#creating-a-custom-jupyter-image

I've seen the same issue with code-formatted text in a definition list.

**Comment by sarahmaddox** [comment]
Related issue: https://github.com/kubeflow/website/issues/402

@mk-nickyang Is this something you could take a look at?

**Comment by mk-nickyang** [comment]
@sarahmaddox Fix PR(https://github.com/google/docsy/pull/59) is submitted in google/docsy

**Comment by sarahmaddox** [comment]
Thanks @mk-nickyang!
