### ISSUE TITLE
Document how to transition from bootstrapper to running the examples

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#56]
We need to document how users transition from deploying Kubeflow to running the samples

I think we could directly point users at
https://github.com/kubeflow/examples/tree/master/github_issue_summarization

Provided we made a couple updates to the latter 
- We should link to the official docs for setting up Kubeflow on kubeflow.org rather than repeating them in the example
- We should probably emphasize that users will need to have kubectl & ksonnet instead on their local machines

**Comment by sarahmaddox** [comment]
Our docs now showcase the pattern of including a "Next steps" section to help people go somewhere after deploying Kubeflow. For example:

*  [Resources and troubleshooting sections in "getting started"](https://www.kubeflow.org/docs/started/getting-started/)

* [Next steps section in GCP getting started docs](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#next-steps)

* [Next steps section in Pipelines getting started docs](https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/#next-steps)

While not all the docs include a "next steps" section yet, I think we've initiated the pattern well enough to close this issue.

Please do re-open the issue or create a new issue pointing to a particular doc that needs updating if necessary.

/close
