### ISSUE TITLE
Document the new Jupyter web app as a component of Kubeflow

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#561]
Kubeflow v0.5 introduces a new web UI for Jupyter notebooks (replacing the integration with JupyterHub used in 0.4 and earlier) to natively spawn Jupyter notebooks in a Kubeflow environment. 

Update this existing page:
https://www.kubeflow.org/docs/components/jupyter/

See Kubeflow doc issue:
https://github.com/kubeflow/kubeflow/issues/2232

And initial Kubeflow PR:
https://github.com/kubeflow/kubeflow/pull/2357

Design doc:
http://bit.ly/kf_jupyter_design_doc

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/617

**Comment by sarahmaddox** [comment]
Starting this now

**Comment by jlewi** [comment]
@sarahmaddox Thank you so much for picking this up!.

/cc @zabbasi @vkoukis @kimwnasptd

**Comment by sarahmaddox** [comment]
Given that notebooks are an important part of the Kubeflow story, in particular for data scientists, I'm planning to create a doc section specifically about notebooks. It'll include roughly the following pages:

* Get started with Kubeflow notebooks - a link to the Kubeflow installation guide, plus info on how to access a notebook in your Kubeflow installation. Includes a link to the **Fairing section** for the build/train/deploy CUJ.
* How to submit k8s resources from Jupyter Notebook.
* How to create a custom Jupyter image.
* How to include a notebook into your Kubeflow pipeline.
* How to build docker images from Jupyter Notebook on GCP.

I'll create a PR which will help crystalize the above thoughts. Also the work @zabbasi is doing on user-defined namespaces (issue https://github.com/kubeflow/website/issues/617) will fit in here.
