### ISSUE TITLE
Add documentation for fairing using KF notebooks

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/website#566]

**Comment by joeliedtke** [comment]
/reopen

If I understand correctly, this issue relates to using Fairing from within the notebook environment hosted in Kubeflow.

**Comment by sarahmaddox** [comment]
@joeliedtke We have a number of [Kubeflow issues related to Fairing](https://github.com/kubeflow/website/issues?utf8=%E2%9C%93&q=is%3Aissue+fairing). Please would you take a look at them and provide more explanation for each, to differentiate them from each other?

**Comment by joeliedtke** [comment]
Sure, I'll work with the Fairing team to add additional details.

**Comment by sarahmaddox** [comment]
Thanks Joe! Following up on my earlier comment about the various Fairing issues, I think it'd be good to create a design doc with proposed fairing docs structure, so people can see what the new section may look like and can give input if they like.

Here's [an example of such a design doc](https://docs.google.com/document/d/10Jn2Bt-U8YLdCkDKDZgILKNMqPpTw1-ZIPalKn1mwzI/edit#heading=h.76g367a6n4wf). It's in the [Kubeflow community team drive](https://drive.google.com/drive/folders/1g-WA9n68qFcI2OZhVyXnn-JYC9hC9tjN).

**Comment by joeliedtke** [comment]
Sounds good. I've started to discuss the doc plan with karthickv2k. After I get his feedback, I'll write up a design doc on the Kubeflow community team drive.
