### ISSUE TITLE
Refactor the "Components" section of the Kubeflow docs for better UX

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#572]
Restructure the “Components” section of the Kubeflow docs - categorize the components by phase in ML workflow: training, serving, parameter tuning, etc.

https://www.kubeflow.org/docs/components/

**Comment by sarahmaddox** [comment]
Some suggested sections, copied from duplicate issue https://github.com/kubeflow/website/issues/868

* Training (TFJob, PytorchJob, MPI, MXNet, Chainer)
* Serving (TF serving, Seldon, Batch Predict)
* Pipelines
* Hyperparameter Tuning
* Data

**Comment by sarahmaddox** [comment]
Related issue: https://github.com/kubeflow/website/issues/868

**Comment by sarahmaddox** [comment]
/assign @Tabrizian  

@Tabrizian  Thanks for volunteering to tackle this issue. Please add a comment to this issue, then I can assign it to you properly.

**Comment by Tabrizian** [comment]
I want to work on this issue.
