### ISSUE TITLE
Highlight the Kubeflow Pipelines UI for data and metrics visualization

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#575]
Give an overview of the Kubeflow Pipelines UI - see our existing “Kubeflow Pipelines quickstart” doc, and then explain additional capabilities of the UI. See also the existing doc about the Kubeflow UIs in general.

**Comment by sarahmaddox** [comment]
On re-examining the Pipelines docs, I think we cover the UI well enough. I'd prefer not to have exhaustive docs on the UI, as a UI should be self-explanatory.

We have the quickstart, which introduces most of the UI:
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/

We have the overview, which includes some of the UI as an explanation of the concepts of pipelines:
https://www.kubeflow.org/docs/pipelines/pipelines-overview/

We have a tutorial that walks through the full workflow including UI parts:
https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/

Note also that issue https://github.com/kubeflow/website/issues/574 requests an overview of the various Pipelines interfaces, including UI et al.

@paveldournov What other aspects of the Pipelines UI would you like the docs to cover?

**Comment by paveldournov** [comment]
My vote is to prioritize the UI programmability, i.e. the way users can generate visualizations for the data, integrate with tensorBoard, generate traceable metrics, and logs. It is an intersection between DSL and UI.

**Comment by sarahmaddox** [comment]
Related docs:

* https://www.kubeflow.org/docs/pipelines/metrics/output-viewer/
* https://www.kubeflow.org/docs/pipelines/metrics/pipelines-metrics/
