### ISSUE TITLE
Provide a walkthrough of the xgboost Housing Serve example using high level fairing APIs

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#593]
A walkthrough of the https://github.com/kubeflow/fairing/blob/master/examples/prediction/xgboost-high-level-apis.ipynb

**Comment by sarahmaddox** [comment]
@joeliedtke is working with the Fairing engineering team on this tutorial. It may end up that we put all the info in the notebook rather than create a separate website doc.

**Comment by abhi-g** [comment]
I think a notebook with Markup is definitely a better document. We might
still need a website doc just as a pointer and an introduction to the
notebook.
