### ISSUE TITLE
Launching jobs on Kubeflow from a local Jupyter notebook

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#594]
Document the steps needed to enable launching jobs on Kubeflow deployment from a local Jupyter notebook. 
 - How to provide access to secrets/credentials to the local notebook
 - what Fairing configuration is recommended

**Comment by joeliedtke** [comment]
This document will describe how to configure a kubeconfig file to enable Fairing to authenticate with Kubeflow. For Kubeflow on cloud providers, additional steps may be required. These steps will be covered in other documents.

**Comment by joeliedtke** [comment]
Per karthikv2k in Fairing issue 248
--------
Yes, you can use docker hub. You need to run "docker login" to get the right creds to push.

If you are using KF notebooks then you need to run "docker login" within the container or copy your docker config (~/.docker/config.json) from your laptop to the notebook instance.

You may need to install docker client in the container to run "docker login" in the notebook instance.
