### ISSUE TITLE
Launching jobs on GCP using Fairing

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#595]
Document the steps needed to enable launching training jobs or prediction deployments on GCP.
  - What secrets/credentials the user needs available in the notebook
  - if running Kubeflow on GKE, which ones of these will be automatically set
  - what configuration of Fariing is recommended

**Comment by sarahmaddox** [comment]
@joeliedtke is creating a doc which handles **part** of this issue - specifically, the GCP config.

**Comment by joeliedtke** [comment]
This document will describe the configuration steps required to enable Fairing to authenticate with Kubeflow on GKE, GKE, and AI Platform. A good example of these steps can be found in https://www.kubeflow.org/docs/fairing/gcp-local-notebook/.
