### ISSUE TITLE
Update Getting Started kfctl.sh references

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#597]
Update [Getting Started](https://www.kubeflow.org/docs/started/getting-started/) 
  - [Installing on Existing Kubernetes section](https://www.kubeflow.org/docs/started/getting-started/#installation-on-existing-kubernetes)
       - install & delete instructions

**Comment by sarahmaddox** [comment]
Do we have a `kfctl` binary that supports platforms other than GCP? We've updated the docs for GCP but held off on the other platforms until the binary supports other platforms.

**Comment by gabrielwen** [comment]
for 0.5 release we only shoot for GCP.

/cc @kunmingg

**Comment by sarahmaddox** [comment]
/priority p2

Downgrading the priority because we've already updated the docs for GCP and the new binary isn't yet available for the other platforms, so we can't update the other docs yet.

**Comment by sarahmaddox** [comment]
This doc now references the `kfctl` binary rather than the shell command.
https://www.kubeflow.org/docs/started/getting-started-k8s/
