### ISSUE TITLE
Create a document page for downloading kfctl binary

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#598]
A document page or reference pointing a user to the github page hosting kfctl binaries for different platforms.  

Will be good to also suggest contributions on kfctl binary builds for other platforms.

**Comment by sarahmaddox** [comment]
The GCP deployment page points to the kfctl binary:
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

If we add a separate doc page pointing to the download page, the doc page should be in the [Reference](https://www.kubeflow.org/docs/reference/) section of the website.

Please would you provide the link to the GitHub page hosting kfctl binaries for various platforms - do you mean the [Releases page](https://github.com/kubeflow/kubeflow/releases/)?

**Comment by abhi-g** [comment]
Yes, the releases page has the links to downloadable binaries.

Abhishek
