### ISSUE TITLE
Link to new definitions of pipeline/component from various docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#609]
A number of the Pipelines docs include either a wordy definition of a pipeline/component, or a link to some page or other in an attempt to get around defining a pipeline/component yet again.

We now have handy definitions of [pipeline](https://www.kubeflow.org/docs/pipelines/concepts/pipeline/) and [component](https://www.kubeflow.org/docs/pipelines/concepts/component/) in our new concepts docs.

We need to go through the docs, move/merge the long definitions into the new concept docs, and leave all the other docs with a very short definition of each concept plus a link to the relevant concept doc.

This may apply to other concepts too.

**Comment by alecglassford** [comment]
You've also added a [component specification reference page](https://www.kubeflow.org/docs/pipelines/reference/component-spec/) in #604, and in many of the places where it's relevant to link to the concept docs, it may be useful to link to the specification as well (or instead). In addition, perhaps the component concept page and the component specification page should link to one another.

(Feel free to separate this into a new issue; I was going to file one, but it seemed related.)
