### ISSUE TITLE
Add an event page on Kubeflow website

### ISSUE THREAD

**Issue by amsaha** [kubeflow/website#61]
This is based on email by @ewilderj on kubeflow-discuss@

FYI here are the events we know about at Google where we'll be representing Kubeflow. Please feel free to chime in with others where you know you'll be speaking on KF.

    Container Day (June 26)
    OSCON TensorFlow Day  - July 17th
        Barbara Fusinska will be giving a Kubeflow talk
    Google Next (July)
    SciPy (July)
    JupyterCon - Mid August 21-25  (Chris Cho, Fei Xue)
    O’Reilly Strata NYC - September 11-13
        Workshop
        40-min talk
    O’Reilly AI conference London - October 8-11
        TF Workshop 
    Kafka Summit (October 16-17)
    Kubecon Shanghai (November 14-15)
    Kubecon Seattle (December 11-13)

I guess an events pager would make a great addition to the Kubeflow web site—good opportunity for somebody to submit their first PR to https://github.com/kubeflow/website if they want, then we can keep it up to date.

**Comment by ddysher** [comment]
We (Caicloud) will present at Open Source Summit North America at Vancouver (August 29-31).

/cc @gaocegege @xinzhangcmu

**Comment by amsaha** [comment]
Closed via pull #74
