### ISSUE TITLE
Couple of additional Kubeflow events to add

### ISSUE THREAD

**Issue by JavaDerek** [kubeflow/website#616]
Could these be added to the events list, please?  Both will be primarily dedicated to Kubeflow...

"Accelerating Machine Learning DevOps with Kubeflow" -- https://gotochgo.com/2019/sessions/837

"Architecting and Deploying Machine Learning in the Private Cloud" -- https://conferences.oreilly.com/software-architecture/sa-ca/public/schedule/speaker/337165

**Comment by sarahmaddox** [comment]
Thanks @JavaDerek - please would you send a PR?

**Comment by sarahmaddox** [comment]
The [docs README](https://github.com/kubeflow/website/blob/master/README.md) has useful info about updating the docs. :)

**Comment by JavaDerek** [comment]
Just awaiting legal approval on the Google agreement in order to commit.
