### ISSUE TITLE
Add documentation on how to create Jupyter notebooks in user-defined namespaces.

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/website#617]
As described [here](https://github.com/kubeflow/kubeflow/issues/2980) currently in order for a user to spawn a notebook in a given namespace, the namespace should have some service accounts. We should document how this works.

**Comment by sarahmaddox** [comment]
@zabbasi Would you like to tackle this issue during the Kubeflow Doc Sprint (July 10-12)?

**Comment by sarahmaddox** [comment]
@zabbasi Can we close this issue, as I think the docs currently cover creating notebooks in specific namespaces?
https://www.kubeflow.org/docs/notebooks/setup/#create-a-jupyter-notebook-server-and-add-a-notebook

/assign

**Comment by sarahmaddox** [comment]
@zabbasi I'm going to close the issue. Please do re-open it if more work is needed.

/close
