### ISSUE TITLE
What is ${KF_ENV}

### ISSUE THREAD

**Issue by David-Bess** [kubeflow/website#619]
${KF_ENV} is mentioned several time in the kubeflow documetnation, but I can not find any description of what it is.  In GCP cloudshell  I am getting this error: 

ERROR environment is not set; use `env list` to see available environments

I even did a search of all kubeflow docs, and I can not find any reference to how this gets set.  Not good to use a env var which was never set.  I deployed using cli on gcp.

**Comment by sarahmaddox** [comment]
+1
[Here's a search](https://github.com/kubeflow/website/search?q=KF_ENV&unscoped_q=KF_ENV) showing the usage of this environment variable.

The env variable is used to hold an *environment* as defined by ksonnet. We give some explanation of the environment concept on [our ksonnet page](https://www.kubeflow.org/docs/components/ksonnet/#more-about-ksonnet). The docs should set the variable to `default` when we don't need a specific environment, and should explain in brief what the variable means.
