### ISSUE TITLE
PyTorch Training 404 link

### ISSUE THREAD

**Issue by marrrcin** [kubeflow/website#635]
https://www.kubeflow.org/docs/components/pytorch/

The link in the paragraph with:
> See distributed MNIST example config file.

(https://github.com/kubeflow/pytorch-operator/blob/master/examples/tcp-dist/mnist/v1beta1/pytorch_job_mnist.yaml)

leads to 404.

**Comment by chupman** [comment]
Found the [commit](https://github.com/kubeflow/pytorch-operator/commit/bcb6a34087319c2393c54ea6a6da4c7fa7df0ae1#diff-bfebe34154a0dfd9fc7b447fc9ed74e9) that broke the link. I'll submit a PR to fix.
