### ISSUE TITLE
Outdated docs: iOS doesn't show client secret

### ISSUE THREAD

**Issue by grehce** [kubeflow/website#636]
Unsure how to proceed with creating a Kubeflow deployment; entered IAP OAuth client ID but for iOS applications, GCP does not provide a "client secret" but rather an "iOS URL scheme."

**Comment by jlewi** [comment]
@grehce When you create the OAuth credential you should set the type to "Web Application" 
https://www.kubeflow.org/docs/gke/deploy/oauth-setup/

The type of operating system you are using is irrelevant.

**Comment by grehce** [comment]
@jlewi thanks, created the new OAuth 2.0 client IDs and get the following error when I create Kubeflow deployment:

`Deployment Error
Error trying to get the project number: Error: Error trying to get the project number: {"result":{"error":{"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT"}},"body":"{\n \"error\": {\n \"code\": 400,\n \"message\": \"Request contains an invalid argument.\",\n \"status\": \"INVALID_ARGUMENT\"\n }\n}\n","headers":{"date":"Fri, 19 Apr 2019 06:19:08 GMT","content-encoding":"gzip","server":"ESF","content-type":"application/json; charset=UTF-8","vary":"Origin, X-Origin, Referer","cache-control":"private","content-length":"129"},"status":400,"statusText":null}`
