### ISSUE TITLE
Seldon Deployment Graphs readme link broken

### ISSUE THREAD

**Issue by munro** [kubeflow/website#638]
On this page:

https://www.kubeflow.org/docs/components/seldon/

> ### Seldon Deployment Graphs
> Seldon allows complex runtime graphs for model inference to be deployed. Some example prototypes have been provided to help you get started. Follow the [Seldon docs](https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/readme.md) to wrap your model code into an image that can be managed by Seldon. In the examples below we will use a model image seldonio/mock_classifier ; replace this with your actual model image. You will also need to choose between the v1alpha2 and v1alpha1 prototype examples depending on which version of Seldon you generated above. The following prototypes are available:

this link https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/readme.md is broken

**Comment by animeshsingh** [comment]
Fixed 
https://github.com/kubeflow/website/pull/664
