### ISSUE TITLE
Pipelines: Create a tutorial that uses pre-built component(s) for a common ML workflow

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#639]
For data scientists getting started with Kubeflow Pipelines, our docs should focus first on re-using standard pipeline architectures with pre-built containers, where the code within the containers is configurable (like CMLE training). 

We already provide an [index of reusable components](https://www.kubeflow.org/docs/pipelines/reusable-components/) - we can build on that by creating specific tutorials.

We need at least one fairly simple tutorial that demonstrates how to use a prebuilt component in a real use case. We'll probably need to develop a reusable component as well as the tutorial, to fill any gaps in our current supply of reusable components.

We may need to develop a reusable component as well as the tutorial, to fill any gaps in our current supply of reusable components.

**Comment by sarahmaddox** [comment]
Further analysis required: split this issue into separate tutorials.

**Comment by sarahmaddox** [comment]
This issue provides a good set of tasks for our upcoming [Kubeflow Doc Sprint](https://github.com/kubeflow/website/wiki/Kubeflow-Doc-Sprint). I've added it to the [tutorial wish list](https://docs.google.com/spreadsheets/d/1dIUt1PTyDLfU9zya98nxm7UZtlel6dNVq5jy2_1OeZo/edit#gid=0).

**Comment by JohanWork** [comment]
HI @sarahmaddox 
Checked the tutorial wish list, have experience from build a pipeline extracting data from a sql database, transforming it saving it to a bucket, reading from a bucket and training a model. If i would create a tutorial of this would it be of interest and would it be fine if it has the form of a notebook with python light weight components? Or is it preferred in another shape?

**Comment by andersonvc** [comment]
I can add a hello world example that incorporates some of the reusable pipeline components.

**Comment by sarahmaddox** [comment]
Thanks @andersonvc 

/assign @andersonvc
