### ISSUE TITLE
Clarify that pipelines work outside GCP except for specific functionality

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#655]
In various places in the docs (e.g. the [pipelines overview](https://www.kubeflow.org/docs/pipelines/pipelines-overview/) we state the following:

"*Due to kubeflow/pipelines#345 and kubeflow/pipelines#337, Kubeflow Pipelines depends on Google Cloud Platform (GCP) services and some of the functionality is currently not supported by non-GKE clusters.*"

The documentation as it is worded today makes it seem like KFP can only work on GCP. However, due to the bugs listed above, only a couple non-essential pieces of functionality are unavailable outside GCP.

Update the docs to be more specific:

"*Due to kubeflow/pipelines#345 and kubeflow/pipelines#337, a couple of non-critical pieces of functionality are currently available only on GKE clusters.*

The code for the paragraph is in this shortcode (re-used in multiple places in the docs):
https://github.com/kubeflow/website/blob/master/layouts/shortcodes/pipelines-compatibility.html

**Comment by animeshsingh** [comment]
Did a quick PR on this https://github.com/kubeflow/website/pull/662
