### ISSUE TITLE
Initial cluster setup for existing cluster

### ISSUE THREAD

**Issue by mmuppidi** [kubeflow/website#677]
When running the following command

```${KUBEFLOW_SRC}/scripts/kfctl.sh generate platform```

It raises the following error
```
+ echo 'Nodegroup Roles must be provided for existing cluster with --awsNodegroupRoleNames <AWS_NODEGROUP_ROLE_NAMES>'
Nodegroup Roles must be provided for existing cluster with --awsNodegroupRoleNames <AWS_NODEGROUP_ROLE_NAMES>
```

I think in the documentation  "AWS_NODE_GROUP_ROLE_NAMES" should be changed to "AWS_NODEGROUP_ROLE_NAMES"

Ref: https://www.kubeflow.org/docs/aws/deploy/existing-cluster/
Ref: https://github.com/kubeflow/kubeflow/blob/master/scripts/aws/util.sh#L39

**Comment by Jeffwan** [comment]
@mmuppidi Thanks a lot for reporting this issue. I was carelessly bring in error.  I filed a PR to address it.
