### ISSUE TITLE
GCP troubleshooting guide for credentials

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#679]
A common failure mode for deploying on GCP is people not having sufficient privileges. 
Another failure mode is people not understanding what credentials they are using (i.e running on a GCE VM and using the service account).

We should provide instructions on how people can test/troubleshoot this process

e.g.

1. Running gcloud config list to see what account they are using
1. Checking they have sufficient privileges by looking at the IAM policy

    ```
    gcloud projects get-iam-policy cloud-ml-dev
    ```

**Comment by DanSanche** [comment]
I'll take a look at this next

**Comment by DanSanche** [comment]
@jlewi I wrote a draft of some content I want to cover. Before I go much further, does this look like what you had in mind?

**Comment by sarahmaddox** [comment]
@DanSanche Do you have a link :)

**Comment by DanSanche** [comment]
@sarahmaddox haha thanks, completely missed that! https://docs.google.com/document/d/15bQmPPkmUW7BehQjpdderifv7ONatISeHtj-vR9TdyA

**Comment by DanSanche** [comment]
I opened a PR related to this here: https://github.com/kubeflow/website/pull/916
