### ISSUE TITLE
Styling of reference docs - PyTorchJob api reference: text colors, size

### ISSUE THREAD

**Issue by kbhawkey** [kubeflow/website#680]
- Field names, descriptions are hard to read (choose a darker gray?)
- The table has gray on gray (gray text and gray row color)
- In general, pale blue color is hard to read
- PyTorchReplicaType (string alias), string is light gray in the method signature -- difficult to read
- Why is PyTorchReplicaType listed at the bottom of the page? Link up?
- Could you add a link to the api reference generation tool, `gen-crd-api-reference-docs`
- Could vary the size of the text in the table for the descriptions

**Comment by sarahmaddox** [comment]
Issue https://github.com/kubeflow/website/issues/730 addresses the styling of code within a table.

For the overall table styling, I recommend we use Bootstrap table styling. This will get rid of the alternating grey and white rows, add a border, and add a background to the header row. Example:

```
<div class="table-responsive">
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th>My col header 1</th>
        <th>My col header 1</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>My table cell 1</td>
        <td>My table cell 1</td>
      </tr>
    </tbody>
  </table>
</div>
```

**Comment by kbhawkey** [comment]
👍

**Comment by kbhawkey** [comment]
Closing. Re-open as needed.

**Comment by sarahmaddox** [comment]
The tables in the ref docs could still do with some style improvements:
https://www.kubeflow.org/docs/reference/tfjob/v1/common/

In particular, it'd help to add borders, highlight the header row, and remove the alternating gre/white rows. See earlier comment for styling suggestion.

**Comment by sarahmaddox** [comment]
Thank you @kbhawkey for the fix. The generated ref docs look sooo much better! See [improved styling](https://www.kubeflow.org/docs/reference/tfjob/v1beta2/common/) versus [original styling](https://v0-5.kubeflow.org/docs/reference/tfjob/v1beta2/common/).
