### ISSUE TITLE
Create the docs archive for Kubeflow v0.5

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#694]
I think it's time to create the v0.5 branch of the docs and hook it up to the version dropdown on the website.

This is the only outstanding issue that claims to be relevant to v0.5:
https://github.com/kubeflow/website/issues/650

Pretty soon we'll start adding v0.6 features.

**Comment by sarahmaddox** [comment]
/assign @abhi-g 

/cc @jlewi 
/cc @paveldournov 

What do you folks think?

**Comment by jlewi** [comment]
lgtm

**Comment by sarahmaddox** [comment]
This task is in progress. We've created the v0.5 archive and hooked it up to the version dropdown on the website. The remaining task is to get an SSL certificate.

**Comment by sarahmaddox** [comment]
SSL up and running. Thanks all!

/close
