### ISSUE TITLE
[discussion] Setup Prow

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/website#7]
Maybe we could refer to https://github.com/kubernetes/website for details. I think they do not setup presubmit or postsubmit since it is a website repo.

Should we remove them from test-infra?

/cc @jlewi @ewilderj

**Comment by jlewi** [comment]
/priority p1
/assign jlewi
/unassign @gaocegege 
@gaocegege tried but asked me to take over since he's hitting some test failures with empty prow_config.yaml.

**Comment by jlewi** [comment]
Fixed by #11 
/close
