### ISSUE TITLE
Contents nav section is cutoff and doesn't have a scroll bar

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#70]
On user guide
https://www.kubeflow.org/docs/about/user_guide/

The contents nav section doesn't have a scroll bar and some of the items are cutoff. The scroll bar on the right side scrolls the page but not the nav bar.

![navsection](https://user-images.githubusercontent.com/777219/42028318-c91d1b00-7a80-11e8-8bec-466342f94f70.png)

**Comment by ankushagarwal** [comment]
Talked to the designer. He'll update this.
