### ISSUE TITLE
Grant sarah and abhishek access to netlify

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#703]
It looks like netlify allows access to be shared with individuals
You should be able to login with SSO (e.g. github) if it matches your email

Currently @jlewi and @richardsliu are members

I'm adding @sarahmaddox and @abhi-g 

I needed to upgrade to paid plan to add more members

**Comment by jlewi** [comment]
With the current plan we can have up to 5 members

**Comment by sarahmaddox** [comment]
Thanks @jlewi !

/close
