### ISSUE TITLE
Remove 2 sentences that imply Pipelines is available only on GCP

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#704]
On page:
https://www.kubeflow.org/docs/pipelines/pipelines-overview/

Remove these 2 sentences:

"You can try it currently with a Kubeflow deployment on GKE in Google Cloud Platform (GCP). See the guide to deploying Kubeflow on GCP."

**Comment by animeshsingh** [comment]
Can be closed with #721

**Comment by sarahmaddox** [comment]
/close

Thanks!
