### ISSUE TITLE
Guide for installing Kubeflow on EKS does not work

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/website#714]
This guide (https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/) currently does not work. The step ` ${KUBEFLOW_SRC}/scripts/kfctl.sh generate platform` creates a template using `ksctl.io/v1alpha4` which is not compatible with the newest version of `eksctl `.

The generated template needs to be manually changed to `ksctl.io/v1alpha5`.

Yesterday, after making that change the rest the worked, except that `kubectl get ingress -n istio-system` produces an blank in the ADDRESS column. That prevents you from performing the next steps unless you do manual port forwarding.

Today I tried this again, and now the `${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s` command doesn't even run through, failing with:

```
ERROR find objects: RUNTIME ERROR: Unexpected type null, expected array
        vendor/kubeflow/aws/istio-ingress.libsonnet:(199:12)-(202:6)    object <anonymous>
        <extvar:__ksonnet/components>:41:17-29  thunk from <object <anonymous>>
        vendor/kubeflow/aws/istio-ingress.libsonnet:204:45-48   thunk from <function <anonymous>>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:96:24-29    thunk from <function <anonymous>>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:97:36-41    thunk from <function <anonymous>>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:97:27-42    function <anonymous>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:96:13-30    function <anonymous>
        vendor/kubeflow/aws/istio-ingress.libsonnet:204:26-50   function <anonymous>
        <extvar:__ksonnet/components>:41:3-30   object <anonymous>
        vendor/kubeflow/application/application.libsonnet:104:21-31     thunk from <object <anonymous>>
        vendor/kubeflow/application/application.libsonnet:104:12-32     object <anonymous>
        vendor/kubeflow/application/application.libsonnet:(99:32)-(110:13)      function <anonymous>
        <std>:235:50-62 function <anonymous>

        <std>:762:38-46 thunk from <thunk from <function <aux>>>
        <std>:815:34-35 function <anonymous>
        <std>:762:24-47 thunk from <function <aux>>
        <std>:762:9-57  function <aux>
        <std>:763:5-28  function <anonymous>
        <std>:815:5-46  function <anonymous>
        ...
        vendor/kubeflow/application/application.libsonnet:207:30-77     object <anonymous>
        vendor/kubeflow/application/application.libsonnet:374:9-25      thunk from <thunk from <object <anonymous>>>
        <std>:762:38-46 thunk from <thunk from <function <aux>>>
        <std>:815:34-35 function <anonymous>
        <std>:762:24-47 thunk from <function <aux>>
        <std>:762:9-57  function <aux>
        <std>:763:5-28  function <anonymous>
        <std>:815:5-46  function <anonymous>
        vendor/kubeflow/application/application.libsonnet:(372:11)-(385:6)      object <anonymous>
        <extvar:__ksonnet/components>:15:19-31  thunk from <object <anonymous>>
        vendor/kubeflow/application/application.libsonnet:387:36-39     thunk from <function <anonymous>>
        vendor/kubeflow/common/util.libsonnet:206:34-37 thunk from <function <anonymous>>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:96:24-29    thunk from <function <anonymous>>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:97:36-41    thunk from <function <anonymous>>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:97:27-42    function <anonymous>
        lib/ksonnet-lib/v1.12.6/k.libsonnet:96:13-30    function <anonymous>
        vendor/kubeflow/common/util.libsonnet:206:15-39 function <anonymous>
        vendor/kubeflow/application/application.libsonnet:387:26-40     function <anonymous>
        <extvar:__ksonnet/components>:15:5-32   object <anonymous>
        During manifestation
```

I would recommend that someone goes through this guide again from start to finish and ensures that all steps are working.

**Comment by Jeffwan** [comment]
@karlschriek Thanks for reporting this issue. 
We recently have one PR merged into upstream and brings a bug here. 

Please check https://github.com/kubeflow/kubeflow/pull/3302.  You can manually change value in `${KUBEFLOW_SRC}/${KFAPP}/ks_app/vendor/kubeflow/aws/istio-ingress.libsonnet` this file before it merged. 

For eksctl version problem, we talked with eksctl team and add backward compatibility in next release. I have a PR (https://github.com/kubeflow/kubeflow/pull/3280) pending for this change as well. At the same time, I will submit a PR to add some notes in documentation.

**Comment by Jeffwan** [comment]
@karlschriek  Please have another try. I tested it and it's working well now.

**Comment by karlschriek** [comment]
Yes, this works thanks. There is however no guarantee that it won't break because of some other upstream change. Wouldn't it make sense to change this guide to work with specificly defined versions of `ekctl`, `kfctl` etc. rather than using master?

**Comment by Jeffwan** [comment]
@karlschriek The original plan was use 0.5 branch as stable branch and new coming changes are against master. At the same time, I am working on golang version and it will be release soon and we will change to that version and get ride of libs management. Let me double check schedule, if that's going to be available soon, we will do a doc upgrade. If it comes later, I will change documentation to   against 0.5.

**Comment by sarahmaddox** [comment]
Thanks @Jeffwan and @karlschriek It looks as if this issue is solved for now. I'll close it, but please do re-open it if there's still work to be done at this time.

/close
