### ISSUE TITLE
.gitattributes path "resource/" is not correctly parsed

### ISSUE THREAD

**Issue by michelle192837** [kubeflow/website#716]
Hi! Getting a error in Prow: "error parsing pattern: directory patterns are not matched recursively, use path/** instead: <resources/>"

Parsing code: https://github.com/kubernetes/test-infra/blob/1b4923af3b1b6de999f7f5d8e946ddd398233f40/prow/gitattributes/gitattributes.go#L90

Think someone should just need to use 'resources/**' instead of 'resources/' in the .gitattributes file.

**Comment by sarahmaddox** [comment]
Hallo @michelle192837 Just checking, as I don't know much about this area: Is Prow complaining about a parsing error that originates in the kubeflow/website repo?

**Comment by michelle192837** [comment]
I believe that's the case! The error is reported by hook, specifically for https://github.com/kubeflow/website/pull/715
