### ISSUE TITLE
Add sample code and screenshot for Pipelines Markdown output viewer

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#723]
This page will soon show code snippets and images for all the Pipelines output viewer types except the `markdown` type:
https://www.kubeflow.org/docs/pipelines/metrics/output-viewer/

We should add a code snippet and screenshot showing the `markdown` option for an output viewer.

**Comment by rileyjbauer** [comment]
I can take this

**Comment by sarahmaddox** [comment]
/assign @rileyjbauer 

Thanks @rileyjbauer!
