### ISSUE TITLE
TensorFlow Serving `ks generate tf-serving-service mnist-service` prototype name not found

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/website#724]
I am working through the following guide: https://www.kubeflow.org/docs/components/tfserving_new/

The very first step here fails (`ks generate tf-serving-service mnist-service`).

Firstly, if used exactly as above this will result in the following error: 

`ERROR finding app root from starting path: : unable to find ksonnet project `

So it is necessary to first create a ks project and cd to the project folder:
```
ks init myproject
cd myproject
ks generate tf-serving-service mnist-service
```

This will then result in the following error:
```
ERROR no prototype names matched 'tf-serving-service' 
```

### EDIT 

I was able to overcome this issue with the following fixes:

Add the kubeflow registry in order to gain access to the necessary prototypes:

```
ks registry add kubeflow github.com/google/kubeflow/tree/master/kubeflow
export GITHUB_TOKEN=<my generated token> # to avoid "rate limit execeed" error. See https://github.com/ksonnet/ksonnet/blob/master/docs/troubleshooting.md
ks pkg install kubeflow/tf-serving@master # NOTE, this is tf-serving, not tf-serving-service
```

And then followed by `ks generate tf-serving mnist-service`

**Comment by sarahmaddox** [comment]
This issue is now resolved, as the guide no longer uses ksonnet.
https://www.kubeflow.org/docs/components/serving/tfserving_new/

/close
