### ISSUE TITLE
mysql Backup&Restore procedure

### ISSUE THREAD

**Issue by xaoo** [kubeflow/website#726]
Hey,

we are trying to restore kubeflow mysql db. Is a mysql dump enogh to backup?

we are dealing with the current error after restore:
Error: failed to generate Pipeline graph.
An error occurred
Cannot read property 'spec' of undefine

**Comment by xaoo** [comment]
I found that if I add a pipeline, backup the mysql DB, delete the pipeline then restore, that pipeline will return the erro above.

all the other pipelines, which were not deleted, just backed and restored, are ok.

**Comment by xaoo** [comment]
Hey guys, any suggestions?
I need to know what that delete button does when a pipeline is deleted.
Because it's sure deletes more than something in mysql.

In this way I can prepare some consistent backups.

TY
//George

**Comment by xaoo** [comment]
Hey Sarah, thank you, that would be really helpful to find out the missing dependency when we delete a pipeline

**Comment by IronPan** [comment]
just to double check did you follow up this instruction or some other ways
https://www.kubeflow.org/docs/pipelines/upgrade/

**Comment by xaoo** [comment]
aha, so I can get a backup of all pipeline with _Reinstalling Kubeflow Pipelines_ ?
I just did a mysql dump, deleted a pipeline, and restore the dump, and I saw the delete pipeline is not consistent after restore.
