### ISSUE TITLE
Create a minimal usage example for the Kubeflow Pipelines API

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#734]
For documenting the Kubeflow Pipelines API, we need a minimal example using the API. Suggestion: A bash script that uses curl to call the API with some parameters, highlighting the primary use case for the API.

We'll use the example in a doc that introduces the API and links to the generated API reference.

**Comment by sarahmaddox** [comment]
Suggestion from https://github.com/kubeflow/website/issues/708:
"Even if it's just how to generate swagger and create a client from that"

**Comment by sarahmaddox** [comment]
FYI @OfficePop

**Comment by fediazgon** [comment]
Taking this one! /assign @fediazgon

**Comment by sarahmaddox** [comment]
Thanks @fediazgon 

/assign @fediazgon
