### ISSUE TITLE
istio-ingress is not a component or module

### ISSUE THREAD

**Issue by brussell757** [kubeflow/website#745]
After installing Kubeflow via [kfctl_v0.5.0_linux.tar.gz](https://github.com/kubeflow/kubeflow/releases/tag/v0.5.0) and following the guide at [https://www.kubeflow.org/docs/aws/authentication/](https://www.kubeflow.org/docs/aws/authentication/) when running the following commands: <br>
`ks param set istio-ingress CognitoUserPoolArn arn:aws:cognito-idp:us-west-2:xxx:userpool/xxx
ks param set istio-ingress CognitoAppClientId xxxxxx
ks param set istio-ingress CognitoUserPoolDomain xxxx
ks param set istio-ingress enableCognito true
ks param set istio-ingress certArn arn:aws:acm:us-west-2:xxx:certificate/xxxe4031c`
<br>

My console returns the following error:<br>
`ERROR could not find component: extracting module and component names from istio-ingress: "istio-ingress" is not a component or a module `

**Comment by sarahmaddox** [comment]
I'm closing this issue, as it's been a while since there was any activity, and the AWS installation docs have changed considerably since Kubeflow v0.5. Please do re-open the issue if there's still doc work to do.

/close
