### ISSUE TITLE
Run trigger doc is vague

### ISSUE THREAD

**Issue by haresh-chudgar** [kubeflow/website#746]
The Run trigger documentation references a flag but there's no documentation on how that flag should be set in the pipeline and no examples are linked.

**Comment by sarahmaddox** [comment]
I think this is the page that the issue refers to:
https://www.kubeflow.org/docs/pipelines/concepts/run-trigger/

**Comment by discordianfish** [comment]
Yes, it's unclear to me as well how this is suppose to work and I can't find an example in https://github.com/kubeflow/examples either.

**Comment by discordianfish** [comment]
Related: ScheduledWorkflow isn't documented in general. I assume the run-trigger is part of that: https://github.com/kubeflow/pipelines/blob/578e8231d01074b9dbe40ace1db8cc444a6a1bd8/backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go

**Comment by discordianfish** [comment]
This relevant
