### ISSUE TITLE
Kubeflow on Kubernetes: subPath dynamic volume provisioning broken

### ISSUE THREAD

**Issue by masonlr** [kubeflow/website#749]
The Kubeflow on Kubernetes getting started docs indicate [kind](https://github.com/kubernetes-sigs/kind#installation-and-usage) as a recommended tool for local development and testing (introduced in https://github.com/kubeflow/website/commit/1a95986c4c1c2b8adbe5655ed7de94050492de23).

@gyliu513, I'm new to kubeflow and having difficulty deploying using kind due to, I think, a kind issue with the `subPath` property (https://github.com/kubernetes-sigs/kind/issues/403) and that kind dynamic volume provisioning support is still a work in progress (https://github.com/kubernetes-sigs/kind/issues/118).

## To reproduce

1. Create a local kind cluster and generate the kubeflow config files:

```shell
kind create cluster
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"

export KFAPP=kubeflow-test
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate all -V
```

2. Open the  file `ks_app/vendor/pipeline/minio.libsonnet`, which contains:

```
volumeMounts: [
  {
    name: "data",
    mountPath: "/data",
    subPath: "minio",
  }
]
```

3. Deploy kubeflow to the local kind cluster:

```
$ kfctl apply all -V
$ kubectl -n kubeflow get pods
NAME                                                        READY   STATUS                       RESTARTS   AGE

...

minio-5f6b9b5b7-w42mg                                       0/1     CreateContainerConfigError   0          39m
ml-pipeline-79474f7b99-bwkwj                                0/1     CrashLoopBackOff             7          39m

...

```

```
$ kubectl -n kubeflow describe pods minio-5f6b9b5b7-w42mg

...

Events:
  Type     Reason            Age                   From                         Message
  ----     ------            ----                  ----                         -------
  Warning  FailedScheduling  35m (x3 over 35m)     default-scheduler            persistentvolumeclaim "minio-pvc" not found
  Normal   Scheduled         35m                   default-scheduler            Successfully assigned kubeflow/minio-5f6b9b5b7-w42mg to kind-control-plane
  Normal   Pulling           35m                   kubelet, kind-control-plane  Pulling image "minio/minio:RELEASE.2018-02-09T22-40-05Z"
  Normal   Pulled            11m                   kubelet, kind-control-plane  Successfully pulled image "minio/minio:RELEASE.2018-02-09T22-40-05Z"
  Warning  Failed            9m46s (x12 over 11m)  kubelet, kind-control-plane  Error: stat /tmp/hostpath_pv/4d2d668f-824c-11e9-8c85-0242ac110002: no such file or directory
  Normal   Pulled            104s (x48 over 11m)   kubelet, kind-control-plane  Container image "minio/minio:RELEASE.2018-02-09T22-40-05Z" already present on machine
```

The following message corresponds to https://github.com/kubernetes-sigs/kind/issues/403:

```
Error: stat /tmp/hostpath_pv/4d2d668f-824c-11e9-8c85-0242ac110002: no such file or directory
```

## Suggestion

Either:

1. Test whether kubeflow pipelines function as intended when manually removing the `subPath` property from `ks_app/vendor/pipeline/minio.libsonnet`. If so, mention this modification as an additional step in the Kubeflow on Kubernetes documentation.

2. Investigate whether `subPath` could be removed from the ml-pipeline .libsonnet configuration files. (/cc @jlewi)

3. Wait for https://github.com/kubernetes-sigs/kind/issues/403 to be resolved and add a warning note in the Kubeflow on Kubernetes documentation.

**Comment by sarahmaddox** [comment]
It looks like PR https://github.com/sighupio/fury-images/pull/27 fixed the problem. Also, the Kubeflow installation docs have been substantially rewritten and no longer recommend kind. I'm closing this issue, but please do re-open it if more doc work is required.

/close
