### ISSUE TITLE
Diagram suggestion

### ISSUE THREAD

**Issue by pdmack** [kubeflow/website#75]
This line `(laptop <-> ML rig <-> training cluster <-> production cluster)` in "The Kubeflow Mission" probably should be converted into a diagram with some pop to show the path through deployment envs.

/cc @ewilderj 
/cc @abhi-g

**Comment by amsaha** [comment]
Would this diagram be decent (or a slightly modified version of it, at least the arrow on the top row should wrap around to bottom row)?

<img width="809" alt="screen shot 2018-07-24 at 10 39 51 am" src="https://user-images.githubusercontent.com/2220322/43118108-ed8a26e2-8f2d-11e8-8071-41a6741982be.png">

This was taken from https://schd.ws/hosted_files/kccnceu18/d4/Kubeflow_Deep_Dive.pdf (slide no. 11) which are the slides from the [Kubeflow Deep Dive presentation](https://kccnceu18.sched.com/event/Drnd/kubeflow-deep-dive-david-aronchick-jeremy-lewi-google-intermediate-skill-level) at KubeCon + CloudNativeCon Europe 2018.

**Comment by sarahmaddox** [comment]
This is the file where the "mission" text occurs:
https://github.com/kubeflow/website/blob/master/content/docs/about/kubeflow.md

**Comment by sarahmaddox** [comment]
This is the page: https://www.kubeflow.org/docs/about/kubeflow/

**Comment by sarahmaddox** [comment]
I'll take this one as part of the work I'm doing to create a diagrammatic overview of Kubeflow.
