### ISSUE TITLE
Pipelines: Create a tutorial using the Python SDK

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#751]
Create a Python SDK tutorial for Kubeflow Pipelines: 

* creating experiments 
* uploading pipelines, and
* running runs.

**Comment by zanedurante** [comment]
@sarahmaddox the [simple notebook tutorial](https://github.com/kubeflow/examples/blob/master/pipelines/simple-notebook-pipeline/Simple%20Notebook%20Pipeline.ipynb) I created at the doc sprint does all of these.
It creates a pipeline, uploads it, creates an experiment, and then creates a run (all using the SDK).  It seems like a perfect match WDYT?

**Comment by krishnadurai** [comment]
@zanedurante @sarahmaddox Looks like the example referred to here covers this use-case. I'll go ahead and close this issue.

/close
