### ISSUE TITLE
A guide to batch prediction through Kubeflow

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#756]
Thanks @DanSanche for suggesting this doc!

**Comment by NikeNano** [comment]
Something for you maybe @JohanWork?

**Comment by sarahmaddox** [comment]
Note that the TensorFlow batch predict option isn't supported beyond [Kubeflow v0.6](https://v0-6.kubeflow.org/docs/components/serving/tfbatchpredict/). 

@jlewi should we close this issue, or is there some other way that we want to recommend for doing batch prediction?

**Comment by JohanWork** [comment]
@NikeNano my knowledge on tensorFlow is a bit limited at the moment and working on other contributions to kubeflow.

**Comment by jlewi** [comment]
Closing as stale.
