### ISSUE TITLE
Kubeflow Pipelines Volume examples

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#757]
The Kubeflow Pipelines DSL was recently extended to include `PipelineVolume` and `PipelineVolumeSnapshot`. These are an abstraction for the user to manipulate PVCs and VolumeSnapshots for data management purposes, also exposing dependencies according to their usage.

See PR https://github.com/kubeflow/pipelines/pull/926 for further details.

We need and example and doc covering the above feature.

Thanks @DanSanche for suggesting this doc!

**Comment by elikatsis** [comment]
Hi there!
The initial design has changed after the review process.
For example, `PipelineVolumeSnapshot`s don't exist. Also, the manipulation of any Kubernetes Resource is available via `ResourceOp` class.

The final implementation is closer to [this design](https://github.com/kubeflow/pipelines/issues/801#issuecomment-477395555). The merged PR has just a few minor enhancements (it doesn't diverge from the logic described).

There are some examples under https://github.com/kubeflow/pipelines/tree/master/samples/resourceops.
However, I will be refactoring the directories of the samples to group the ones that aim to show PVC manipulation and those which refer to the `VolumeSnapshot`s to make the navigation easier for the users.

I'll be happy to help with the documentation!

**Comment by sarahmaddox** [comment]
Thanks @elikatsis! Would you like to take part in the doc sprint, to help create the docs? July 10-12. You can take part on site (Kirkland) or online.

Here's the [Kanban board for the Kubeflow Doc Sprint](https://github.com/orgs/kubeflow/projects/21?fullscreen=true).

Full details are on the [doc sprint wiki](https://github.com/kubeflow/website/wiki/Kubeflow-Doc-Sprint).

Here's the [signup form](https://forms.gle/grPdJJb8PGa5EMhb7).

**Comment by elikatsis** [comment]
@sarahmaddox, Hello Sarah !

Unfortunately, I couldn't make it for this doc sprint and I am really sorry I didn't mention it earlier.
I've already begun working on some basic documentation with the PR kubeflow/pipelines#1433 (I'll ping the PR thread to see what's need to be done to get it merged).

I believe I will be able to contribute to the documentation within the next few weeks!

**Comment by sarahmaddox** [comment]
/assign @elikatsis 

Thanks @elikatsis it's great to know that you'll be able to tackle the docs. No worries that it won't be within the timeframe of the doc sprint.

**Comment by elikatsis** [comment]
Hello!

Right now we've got kubeflow/website#837 merged ([link](https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/) to the official website) and there are also several examples in kubeflow/pipelines repo:
* [samples/core/resource_ops](https://github.com/kubeflow/pipelines/tree/master/samples/core/resource_ops)
* [samples/core/volume_ops](https://github.com/kubeflow/pipelines/tree/master/samples/core/volume_ops)
* [samples/core/volume_snapshot_ops](https://github.com/kubeflow/pipelines/tree/master/samples/core/volume_snapshot_ops)
* [samples/contrib/volume_ops](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/volume_ops)
* [samples/contrib/volume_snapshot_ops](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/volume_snapshot_ops)

There are some READMEs, too ([1](https://github.com/kubeflow/pipelines/blob/master/samples/core/volume_ops/README.md), [2](https://github.com/kubeflow/pipelines/blob/master/samples/core/volume_snapshot_ops/README.md)).

I think all of the above close this issue.

@sarahmaddox, Sarah, what's your opinion? Is there anything else you think we should do?

**Comment by sarahmaddox** [comment]
Thanks @elikatsis! The information is a little scattered at the moment. We have:

* The [SDK overview on the website](https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/) which links to the `VolumeOp` etc in the SDK reference docs.
* The [SDK reference docs](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.VolumeOp) which have very limited info.
* The READMEs and samples that you've linked above.

It'd be good to have an overview of the features on the website, in a page under this section: https://www.kubeflow.org/docs/pipelines/sdk/
The overview should explain what the features allow users to do, and link to the samples for indepth usage info.

Preferably the info in the READMEs should move to the website, as they contain user-focused info rather than developer-focused info.
