### ISSUE TITLE
Guide to launching persistent Kubernetes resources through Kubeflow Pipelines

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#758]
Using a pipeline step to launch long-lived Kubernetes resources seems to be the standard way of doing certain tasks, like launching web servers. If this is recommended, it should be explained in the docs. If there's a better way, it should be mentioned (https://github.com/kubeflow/examples/blob/21f76812ec2e0f1e98827b9dede5350080b7e5d3/pipelines/mnist-pipelines/mnist_pipeline.py#L62)

Thanks @DanSanche for suggesting this doc!

**Comment by elikatsis** [comment]
@sarahmaddox,

There is some other way as well!
Creating (or, in general, manipulating) K8s resources can be performed using `ResourceOp` entity of the DSL.

In my opinion, both techniques are good in their own way.
The one you mention, via some `ContainerOp`, is good and easy when there is such image for the desired resource creation and the arguments cover the case.
The other, using `ResourceOp`, is good for any action on K8s resources (`create`, `delete`, `get`, ...) and gives the opportunity to define a full specification, exactly as desired.

Following [my comment](https://github.com/kubeflow/website/issues/757#issuecomment-510805427) in #757, I can contribute to the documentation of this approach along with the one regarding PVCs and `VolumeSnapshot`s.

**Comment by sarahmaddox** [comment]
Thanks @elikatsis! I'll assign this issue to you for tackling along with # 787 as you mentioned.

/assign @elikatsis
