### ISSUE TITLE
Guide to setting environment variables in Kubeflow Pipelines

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#759]
Setting environment variables is very common in container-based workflows. It is supported in Kubeflow Pipelines, but you have to dig through the code to find out how: https://github.com/kubeflow/pipelines/blob/8110de0419b943a0666fe8dc759fe70f7e0517cc/sdk/python/kfp/dsl/_container_op.py#L338

We should create a guide explaining how to do it.

Thanks to @DanSanche for suggesting this doc.

**Comment by JohanWork** [comment]
Hi thinking about taking this one. But would like som guidance, do you have any similare tutorials that I can see the structure, and where in the repository would be a good place to put the turotial? 
Cheers 
Johan

**Comment by sarahmaddox** [comment]
Hallo @JohanWork sure! Are you registered to take part in the doc sprint, or would you like to tackle this outside of the doc sprint?

You can find a guide to working in the doc sprint here: 
https://github.com/kubeflow/website/wiki/Sprinter's-Guide
Make sure you're registered by filling out the registration form (link is on the above guide), so that we can send you all the details.

If you'd like to contribute outside the doc sprint, that's great too. Here's the guide to updating the docs:
https://github.com/kubeflow/website/blob/master/README.md

The code for this particular page should go in this section of the docs:
https://master.kubeflow.org/docs/pipelines/

I'll hand over to @joeliedtke to give further guidance, as he's the lead tech writer for Kubeflow Pipelines.

**Comment by joeliedtke** [comment]
Hello,
I would recommend creating a guide like one of the following:

- [Build components and pipelines](https://master.kubeflow.org/docs/pipelines/sdk/build-component/)
- [Building lightweight components](https://master.kubeflow.org/docs/pipelines/sdk/lightweight-python-components/)

I would recommend adding this doc to `/docs/pipelines/sdk`.

In general, guides like this describe:

1. What the feature does and why someone would want to use it
1. What steps are required before you start this guide. Where possible, refer back to existing docs, such as [Getting Started](https://master.kubeflow.org/docs/started/getting-started/)
1. What steps are required to do this, and if possible providing example code
1. If appropriate, the example code can be provided as a notebook or Python script as well as included in the doc, and saved in an examples repo. Please let me know if that would be useful in this case and I will recommend a location for the example code. 

Please let me know if you have any questions. Thank you for thinking about taking this issue on!

**Comment by JohanWork** [comment]
Thansk! I am not registred for the doc-sprint my plane was to finish this during the sprint but the work came in between. So If some one wants to take this task feel free otherwise I will takle it ouside and create a tutorial!

**Comment by JohanWork** [comment]
@sarahmaddox I have started to work on it, to clarify. When I have been using env variables in Kubeflow piplines it has mostly been true kubernetes secrets is that the same thought as here, the process then normally is.
1. You create a secret (for example usernamen and password for a database)
2. You pass it in to the container in the pipline  through the  .add_env_variable

**Comment by sarahmaddox** [comment]
@JohanWork I'm not sure if the username/password is a typical use case. @Ark-kun can you add some clarity here?

In case they're useful, here are some examples from the SDK code:
* https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L128 (hello world)
* https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L1138

/cc @joeliedtke

**Comment by sarahmaddox** [comment]
Thanks for taking this one @JohanWork!
/assign @JohanWork 

If you'd like to register for the doc sprint (link in previous comment) then we can still count this work as part of the doc sprint.

**Comment by JohanWork** [comment]
Realised now that something like the hello world would be a much easier example. Will do something like that @sarahmaddox.

**Comment by sarahmaddox** [comment]
Thanks @JohanWork! I also just realised that @rmgogogo may have good input on use cases too.
