### ISSUE TITLE
 Typo in Documentation/Kubeflow on GCP/Deploying Kubeflow/Deploy using CLI 

### ISSUE THREAD

**Issue by tarrade** [kubeflow/website#785]
Hi there,

I guess in the doc, there is a typo  in Documentation/Kubeflow on GCP/Deploying Kubeflow/Deploy using CLI (on GCP)
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

${PROJECT} - the _name_ of the GCP project where you want Kubeflow deployed.

it should be

${PROJECT} - the **PROJECT_ID** of the GCP project where you want Kubeflow deployed.

It is no the name of the project on GCP that need to be used but the project ID.

Thanks
Cheers
Fabien

**Comment by adepuravikrishna** [comment]
Hi, I created a PR for this issue.  Could you please review? 
https://github.com/kubeflow/website/pull/813
