### ISSUE TITLE
Upgrade site to latest version of Hugo

### ISSUE THREAD

**Issue by kbhawkey** [kubeflow/website#793]
Update the hugo version in netlify.toml to v0.53 or later.
Seems as if Netlify now supports Hugo 0.53 extended on Ubuntu xenial 16.04.
https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify

**Comment by scottilee** [comment]
@sarahmaddox how often should Hugo be updated? As of today, the most recent version is `0.56.3`. Is it as simple as updating the two `HUGO_VERSION` lines in https://github.com/kubeflow/website/blob/master/netlify.toml?

If it should be updated frequently maybe we can get some automation, in the form of a bot, that continuously checks for Hugo releases and sends a pull request?

**Comment by kbhawkey** [comment]
hi! I raised this issue to upgrade the production site to >= hugo v0.53 *extended*. I have not evaluated the latest version of hugo ext. with netlify. Would this version upgrade simplify the CSS generation (no git check in of generated files to source)?

**Comment by sarahmaddox** [comment]
Hallo both! I think we need to update our site to the latest Netlify, to pick up support for Hugo extended.

These updates (Netlify, Hugo, and also Docsy) are on my radar, but we have some content updates that take higher priority at the moment. Any update of the site infrastructure needs careful testing of the whole site.

**Comment by sarahmaddox** [comment]
I've added https://github.com/kubeflow/website/issues/1139 for the Netlify upgrade.
