### ISSUE TITLE
Outdated pipelines SDK guide

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#795]
The guide to creating a pipeline component instructs people to create a class that inherits from `dsl.ContainerOp` - `class TrainerOp(dsl.ContainerOp)`
https://www.kubeflow.org/docs/pipelines/sdk/build-component/#create-a-python-class-for-your-component

But the related sample has since been updated to use a function that returns a ContainerOp:
https://github.com/kubeflow/pipelines/blob/master/samples/xgboost-spark/xgboost-training-cm.py#L124

We should update the doc to match the sample.

**Comment by OfficePop** [comment]
I'd like to contribute on this article next, @sarahmaddox  if you could assign when you have a chance. Thanks!

**Comment by sarahmaddox** [comment]
Thanks @OfficePop 

/assign @OfficePop

**Comment by OfficePop** [comment]
[PR 971](https://github.com/kubeflow/website/pull/971) created for this issue.

**Comment by sarahmaddox** [comment]
Congrats and thanks @OfficePop!

/close
