### ISSUE TITLE
kubeflow codelab ui Troubleshooting

### ISSUE THREAD

**Issue by galebm1004** [kubeflow/website#797]
❗ Exception making request: <_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "Name resolution failure" debug_error_string = "{"created":"@1560374449.373584765","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2706,"referenced_errors":[{"created":"@1560374449.373579829","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3035,"grpc_status":14}]}" >

**Comment by sarahmaddox** [comment]
Hallo @galebm1004 Is this a bug in the documentation? 

* If yes, please add a link to the relevant page, or explain any addition required to the docs.
* If no, please raise this issue in the relevant repository, which may be https://github.com/kubeflow/kubeflow/issues or https://github.com/kubeflow/examples/issues

**Comment by sarahmaddox** [comment]
/assign @texasmichelle 

@texasmichelle Please would you take a look at this codelab issue?

**Comment by sarahmaddox** [comment]
/unassign @texasmichelle 

@galebm1004  I'm closing this issue, as it's not reproducible unless we know which page/codelab gave the problem. Please do re-open the issue if you can provide more detail.

/close
