### ISSUE TITLE
Fairing: Add tutorials for single node and distributed training with LightGBM

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#802]
Currently, we have example notebooks for single node and distributed training with LightGBM but we do not have any documentation. Add a tutorial that describes how to use Fairing to train and predict with LightGBM, based on the example notebooks.

Single node training:
https://github.com/kubeflow/fairing/blob/master/examples/lightgbm/simple-training.ipynb

Distributed training:
https://github.com/kubeflow/fairing/blob/master/examples/lightgbm/distributed-training.ipynb

**Comment by joeliedtke** [comment]
The example notebooks were written for using Fairing and LightGBM to train on Kubeflow on GKE. Assuming that the code is not revised with instructions for using LightGBM in general, this tutorial should go in the following folder:

/docs/fairing/gcp/tutorials/

**Comment by sarahmaddox** [comment]
@joeliedtke Should we close this issue as obsolete?
