### ISSUE TITLE
No success, no error message either

### ISSUE THREAD

**Issue by jariolehtonen** [kubeflow/website#804]
Tried to follow the instructions. The graph was not shown as in the instruction, only one node instead. I tried with some wrong project etc. names and those did not cause any error messages to appear.

**Comment by sarahmaddox** [comment]
Hallo @jariolehtonen thanks for raising this issue! Please would you add a link to the doc page that you were following when you encountered this problem?

Many thanks
Sarah

**Comment by sarahmaddox** [comment]
@jariolehtonen I'm closing this issue, as it's not reproducible unless we know which page gave the problem. Please do re-open the issue if you can provide more detail.

/close
