### ISSUE TITLE
Suggested update to Kubeflow on Kubernetes doc

### ISSUE THREAD

**Issue by blaisethom** [kubeflow/website#808]
I think it would be good to note that Kubeflow requires Kubernetes v1.11+ (https://github.com/kubeflow/kubeflow/issues/2487). In particular, the current Docker for Mac stable release is on v1.10 so these users will encounter an issue unless they upgrade their Kubernetes.

(In this doc https://www.kubeflow.org/docs/started/getting-started-k8s/)

**Comment by scottilee** [comment]
This page (https://www.kubeflow.org/docs/started/getting-started/) states that Kubernetes 1.8 is the minimum required version.

@sarahmaddox who can help us figure out the minimum Kubernetes version required to run Kubeflow?

**Comment by sarahmaddox** [comment]
@IronPan Please would you confirm: Based on https://github.com/kubeflow/kubeflow/issues/2487#issuecomment-469817860, it seems that the minimum version of Kubernetes is **v1.11** for Kubeflow v0.6+ (unless people want to disable the Pipelines component, which isn't something we should recommend in the docs).

Related issue: https://github.com/kubeflow/website/issues/858

Note that we use a shortcode in the docs for the min version:  `{{% kubernetes-min-version %}}`. Please update the value here:
https://github.com/kubeflow/website/blob/master/layouts/shortcodes/kubernetes-min-version.html
