### ISSUE TITLE
[bug or feature] https://ajax.googleapis.com is banned in China

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/website#81]
Hi, I am trying to visit our website in China while I find I can not scroll down the Section Nav in the left side. When I opened the console I found that we use https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js while it cannot be visited in China. Thus the console has an error `ReferenceError: jQuery is not defined[Learn More]`

**Comment by pdmack** [comment]
Maybe BootCDN? I wonder what we would need to support that in the site.

https://www.bootcdn.cn/

**Comment by sarahmaddox** [comment]
@gaocegege Does this error still occur?

**Comment by gaocegege** [comment]
Nope, thanks for the fix. It seems that we are using https://code.jquery.com/jquery-3.3.1.min.js

/close
