### ISSUE TITLE
Add Getting started use case for Kubeflow in on-prem kubernetes multi-node cluster

### ISSUE THREAD

**Issue by mastrogiovanni** [kubeflow/website#814]
In on-prem multi-node kubernetes cluster Volume provisioning can be a problem since KubeFlow deploy some PersistentVolumeClaims that need to be binded to some Persistent Volume.

Since HostPath Volumes cannot be used in multi-node scenario a basic use case (Getting Started) example could be written using Dynamic Volume Provisioning with a simple NFS Volume.

**Comment by sarahmaddox** [comment]
This sounds to me like a very useful addition to the docs. @Michele Mastrogiovanni would you like to create the doc as part of the upcoming [Kubeflow Doc Sprint](https://github.com/kubeflow/website/wiki/Kubeflow-Doc-Sprint)? You can take part online or on site in Kirkland, WA.

**Comment by mastrogiovanni** [comment]
Of course! I already registered on the event for online partecipation. Please add this issue to the Kanban.

**Comment by sarahmaddox** [comment]
Great! I've added this issue to the Kanban board for the doc sprint:
https://github.com/orgs/kubeflow/projects/21

/assign @mastrogiovanni

**Comment by Tabrizian** [comment]
May I work on this as a part of doc sprint if @mastrogiovanni is not working on it?

**Comment by sarahmaddox** [comment]
Hallo @Tabrizian and welcome to the Kubeflow Doc Sprint! @mastrogiovanni is working on this issue, but would you like to work on another instead?

Here's a fairly meaty issue that involves restructuring a section of the docs:
* https://github.com/kubeflow/website/issues/572


Here's another  - keep an eye on it to see if Dan responds to the comment I added, and if he's not tackling it then add a comment and I'll assign it to you:
* https://github.com/kubeflow/website/issues/904

I'll be happy to help you find the right reviewers when you submit a PR.

**Comment by Tabrizian** [comment]
Sure, I can work on #572.

**Comment by Tabrizian** [comment]
I guess this issue can be closed now as #897 is merged.

**Comment by sarahmaddox** [comment]
Thanks @Tabrizian you're right. Closing this issue.

/close
