### ISSUE TITLE
Pipelines: Update SDK references to point to the generated docs on Read The Docs

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#819]
We now have auto-generated SDK ref docs on *Read The Docs*:
https://kubeflow-pipelines.readthedocs.io/en/latest/

We should search for all references in the pages on kubeflow.org that point to the GitHub repo for the SDK, and point to the relevant Read The Docs link instead.

**Comment by sarahmaddox** [comment]
I've marked this one for tackling during the doc sprint. It's a good one for a tech writer to tackle.

**Comment by scottilee** [comment]
@sarahmaddox it looks this has been taken care of in some pull requests like https://github.com/kubeflow/website/pull/770/files. I did a search of the docs repo and couldn't find any other references of the SDK that pointed to Github. Let me know if I'm mistaken.

**Comment by sarahmaddox** [comment]
There are still some left. I haven't done an exhaustive search, but [this search](https://github.com/kubeflow/website/search?q=%22%2Fkubeflow%2Fpipelines%2Ftree%2Fmaster%2Fsdk%22&unscoped_q=%22%2Fkubeflow%2Fpipelines%2Ftree%2Fmaster%2Fsdk%22) and [this search](https://github.com/kubeflow/website/search?q=%22github.com%2Fkubeflow%2Fpipelines%2F%22&unscoped_q=%22github.com%2Fkubeflow%2Fpipelines%2F%22) pick up some occurrences (tho the later search contains non-relevant hits too). There may be more.

**Comment by scottilee** [comment]
@sarahmaddox I was trying to help with this but I wasn't quite clear on the mapping. For instance, the first result from https://github.com/kubeflow/website/search?q=%22github.com%2Fkubeflow%2Fpipelines%2F%22&unscoped_q=%22github.com%2Fkubeflow%2Fpipelines%2F%22, is [content/docs/pipelines/sdk/reusable-components.md](https://github.com/kubeflow/website/blob/3c584ba13e260db1c6b2ed0a298146eb0e04f190/content/docs/pipelines/sdk/reusable-components.md). Would I just replace the link for `reusable components` with https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html ? And what would I replace `Cloud ML Engine model training` with -- I couldn't find an equivalent link on https://kubeflow-pipelines.readthedocs.io.
