### ISSUE TITLE
Install Pipelines SDK - SDK Install depends on jq

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#823]
The following code sample depends on `jq` which is not installed in the default notebook images. JQ is an open source project, and may not be available in most cases.

`
latest_version=$(curl --silent https://api.github.com/repos/kubeflow/pipelines/releases/latest | jq -r .tag_name)
pip install https://storage.googleapis.com/ml-pipeline/release/${latest_version}/kfp.tar.gz --upgrade
`

Resolution options:

- Add instructions for installing jq
- Update code sample to work without jq

https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/

**Comment by sarahmaddox** [comment]
I'm thinking it's perhaps not a good idea to fetch the latest version of pipelines, as that version may not be stable.

We could consider going back to the code that we had prior to PR https://github.com/kubeflow/website/pull/688/files

The prior code relied on a variable which we need to manually update (shortcode `pipelines-sdk-version`) and which is intended for use across the docs. Here's the code:

```
pip install https://storage.googleapis.com/ml-pipeline/release/{{% pipelines-sdk-version %}}/kfp.tar.gz --upgrade
```

**Comment by sarahmaddox** [comment]
This is done.

/close
