### ISSUE TITLE
History Section

### ISSUE THREAD

**Issue by hamelsmu** [kubeflow/website#824]
https://www.kubeflow.org/docs/about/kubeflow/

For newcomers this section triggers many questions:

```
History
Kubeflow started as an open sourcing of the way Google ran TensorFlow internally, based on a pipeline called TensorFlow Extended. It began as just a simpler way to run TensorFlow jobs on Kubernetes, but has since expanded to be a multi-architecture, multi-cloud framework for running entire machine learning pipelines.
```

The natural question for a newcomer is why is that a separate project now and how do they relate?  This is a question people often ask me when they land on this website.  It might be worth fleshing this one out more.  I would make a PR but I don't know the deep history on how these two projects and I think probably should be worded carefully based on that context?

**Comment by sarahmaddox** [comment]
Thank you for this question @hamelsmu. Asking people who were in at the start of Kubeflow: @jlewi and @aronchick Do you have an context that we can add to the doc? Please plus in anyone else who may have input.
