### ISSUE TITLE
Change doc "Customizing Kubeflow on GKE" to use kustomize not ks

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/website#825]
https://www.kubeflow.org/docs/gke/customizing-gke/

Has out dated reference to ks 

Example: 
cd ${KF_APP}/ks_app
ks param set jupyter disks "kubeflow-gcfs"

**Comment by sarahmaddox** [comment]
We've updated the end-to-end GCP tutorial to use kustomize, but we haven't yet updated the other docs. We should find all docs that need updating, test all the updates, and apply the updates where the test results are good.

**Comment by sarahmaddox** [comment]
See details of the `customizing-gke` page in https://github.com/kubeflow/website/issues/843

We also need to check the rest of the docs, so I'm leaving both issues open.

**Comment by sarahmaddox** [comment]
The doc "Customizing Kubeflow on GKE" now uses kustomize not ksonnet.

We'll track other docs with individual issues.

/close
