### ISSUE TITLE
Add examples for serving a model with Kubeflow

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#826]
Request from the KFServing team: Add more examples and docs for serving models with Kubeflow. 

Comment from sarahmaddox: We do have a couple of tutorials in the docs that include serving, and some serving examples on GitHub. At a minimum, we can create a page that links all the serving-related info from one place.

**Comment by isaacmg** [comment]
I can work on adding a couple of serving examples with Seldon.

**Comment by sarahmaddox** [comment]
/assign @isaacmg 

Thanks @isaacmg that's great!

**Comment by sarahmaddox** [comment]
We now have many serving examples described in or linked from these pages:
* https://www.kubeflow.org/docs/components/serving/seldon/
* https://www.kubeflow.org/docs/components/serving/kfserving/
* https://www.kubeflow.org/docs/components/serving/tfserving_new/

/close
