### ISSUE TITLE
Clarify the section titles in the left-hand nav

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#83]
I'm finding the left-hand navigation panel a little confusing:

* The top-level section title is “Section Nav”. That title didn't help me understand what the section contains, which is a list of the docs available. 
How about this as a title for the top section: **Docs**

* The second section title is “Contents”. I thought it meant the contents of the doc set, but the section actually lists the headings on the page. 
How about this as a title for the top section: **On this page**
An alternative suggestion: **Page contents**

**Comment by sarahmaddox** [comment]
I'd be concerned about "Site Contents", in that we may add other content to the site that's not part of the docs, whereas the left-hand nav includes only the docs.

**Comment by amsaha** [comment]
Good point.

**Comment by sarahmaddox** [comment]
I think we can close this issue now, since the navigation has been changed to fix issue #70. Now the page contents is on the right of the page, and is labelled "Contents". It's therefore clearer what "Section Nav" means on the left.
