### ISSUE TITLE
Could use a walk-through on building Kubeflow from source

### ISSUE THREAD

**Issue by JavaDerek** [kubeflow/website#832]
Maybe for the doc sprint?  

If someone wants to contribute to the Open Source effort, there's not a clear overall starting point in the documentation for them.  It would be really useful to have a document that says "clone these repos, build this first, now build this, now here's how you deploy what you just built, here's the overall build process, etc."

**Comment by sarahmaddox** [comment]
Hallo @JavaDerek This is a great task to tackle during the doc sprint!

Some thoughts: I think such a guide for Kubeflow contributors belongs in the [Kubeflow GitHub repo](https://github.com/kubeflow/kubeflow) in one or more README files, rather than on kubeflow.org. Up to now, at least, we're viewing kubeflow.org as docs for Kubeflow users, whereas the docs for Kubeflow developers go with the code in the repo.

**Comment by JavaDerek** [comment]
Cool -- we'll run with this! :-)

**Comment by sarahmaddox** [comment]
Adding some info from an email conversation:

Creating individual developer guides (for each Kubeflow application) that people can follow would be very valuable. ideally they would be guides like this [README](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard#development) that live side by side with the application and provide focused instructions for how to run it.

If you think of Kubeflow as a set of applications (e.g. central dashboard is one application). Then each application should be buildable/deployable on its own and have an appropriate development guide.  

Suggested process for tackling this documentation task:

1. Identify the bug/feature you want to fix in Kubeflow.
2. Identify the application (e.g. TFJob, Jupyter Web App, Pipelines) in which the bug/feature resides.
3. Locate the source for the application.
4. Look for a README and/or developer guide co-located with the source that describes how to build/deploy/test just that application.
5. Create a specific issue in https://github.com/kubeflow/website/issues/ and add the **doc-sprint** label (or add a comment that you're fixing this in the doc sprint).
6. Assign the issue to yourself.
7. Create or edit the relevant README and/or developer guide.

**Comment by carmine** [comment]
I'm interested in this topic as well. It'd be great to have a Developer Setup. I'll create a separate issue for that and link to his.

**Comment by sarahmaddox** [comment]
Hallo @javaderek I'm thinking the developer-focused getting-started guide belongs in the kubeflow/kubeflow repo on GitHub rather than on the website, so it'd make sense to move this issue to that repo. WDYT?

**Comment by sarahmaddox** [comment]
I'm going to close this issue, as it's not relevant for the website docs. Please do re-create the issue in kubeflow/kubeflow to track work if need be.

/close
