### ISSUE TITLE
AWS IAM prerequisites are not explained

### ISSUE THREAD

**Issue by jonin** [kubeflow/website#836]
Cannot install Kubeflow according to these instructions:
https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/

The exact set of required IAM permissions is missing from the page.

**Comment by Jeffwan** [comment]
@jonin 

Thanks. I will add minimum permissions to make sure you can go through tutorials.

**Comment by scottilee** [comment]
@Jeffwan any update on this?

**Comment by Jeffwan** [comment]
@PatrickXYS Can you help on this issue?

**Comment by PatrickXYS** [comment]
Sure,  I'll take it after v1.0.2 released.

/assign

**Comment by PatrickXYS** [comment]
For now, we have IRSA enabled for the permission model, we don't need to have explicitly IAM permission

/close
