### ISSUE TITLE
"Kubeflow on Kubernetes" refers to file not yet in master

### ISSUE THREAD

**Issue by edmeister** [kubeflow/website#840]
https://www.kubeflow.org/docs/started/getting-started-k8s/

The page refers to a file that is not yet in master, but in [a PR that is still in heavy debate](https://github.com/kubeflow/kubeflow/pull/3538). 

```
export CONFIG="https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config/kfctl_platform_existing.yaml"
```

**Comment by sarahmaddox** [comment]
@yanniszark can you update this to a config file that's in production, or should we revert PR https://github.com/kubeflow/website/pull/833?

/assign @yanniszark

**Comment by yanniszark** [comment]
Hi @sarahmaddox thanks for the heads-up!
I forgot to add /hold to the PR.

Given that PR https://github.com/kubeflow/kubeflow/pull/3538 will be in 0.6 and 0.6 will be released very soon, we can either revert it or keep it for a little bit longer until the PR is merged.

**Comment by sarahmaddox** [comment]
Hallo @yanniszark I think we should revert PR https://github.com/kubeflow/website/pull/833 until the change is ready for use in 0.6. The "master" version of the docs does describe v0.6 (we've already archived a branch for v0.5) but even so the docs should describe the available functionality, not future functionality. 

Will you revert the PR, or let me know if you'd like me to revert it? Then you can submit it again for review and merge when the software update is ready.

**Comment by sarahmaddox** [comment]
/assign

Fixed by PR https://github.com/kubeflow/website/pull/848 (reverts previous PR). @yanniszark Please do resubmit the original PR when the software is available for use.

/close
