### ISSUE TITLE
Conflicting pipelines upgrade instructions

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/website#841]
The instructions here https://www.kubeflow.org/docs/pipelines/upgrade/
do not match the instructions here https://github.com/kubeflow/pipelines/tree/master/manifests

**Comment by sarahmaddox** [comment]
There are no longer any upgrade instructions at https://github.com/kubeflow/pipelines/tree/master/manifests or https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize

The upgrade guide on the website is up to date: https://www.kubeflow.org/docs/pipelines/upgrade/

I'm closing this issue, but please do re-open it if there's still work to do.
/close
