### ISSUE TITLE
Kubeflow Filestore documentation is out dated

### ISSUE THREAD

**Issue by jessiezcc** [kubeflow/website#842]
see https://github.com/kubeflow/pipelines/issues/1564 for original issue. 

Documentation instructions refer to using KS.. this can be simply done with Kubectl and directly deploying yamls for pv / and pvc.

Documentation link: https://www.kubeflow.org/docs/gke/cloud-filestore/

Example for out dated documentation :
cd //${KFAPP}/ks_app
ks generate google-cloud-filestore-pv google-cloud-filestore-pv --name="kubeflow-gcfs" 
--storageCapacity="${GCFS_STORAGE}" 
--serverIP="${GCFS_INSTANCE_IP_ADDRESS}"

**Comment by jlewi** [comment]
We can just link to these docs.
https://cloud.google.com/filestore/docs/accessing-fileshares
