### ISSUE TITLE
Merge requirements into getting-started page

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#845]
Merge the "requirements" page (https://www.kubeflow.org/docs/started/requirements/) into the getting-started guide (https://www.kubeflow.org/docs/started/getting-started/) and add the appropriate redirect.

**Comment by sarahmaddox** [comment]
I've marked this one for tackling during the Kubeflow Doc Sprint. This is a good task for a tech writer to tackle during the sprint.

**Comment by OfficePop** [comment]
This one seems like a good place to get started, please assign it to me when you have a chance!

**Comment by OfficePop** [comment]
Changes have been added to [kubeflow/website PR 890](https://github.com/kubeflow/website/pull/890).

**Comment by OfficePop** [comment]
Did someone else resolve this issue? Had to remove the related updates from my original PR because it was causing merge conflicts. If it's still outstanding, let me know and i'll submit a separate PR for it once the original is handled.

**Comment by sarahmaddox** [comment]
This issue is not yet resolved. The page is still in the docs:
https://www.kubeflow.org/docs/started/requirements/

As far as I know there's no PR in flight to move the content to the getting-started page.

There was a change to the requirements page, that swapped ksonnet to kustomize. That change probably caused the merge conflict.

Please do go ahead with this change, if you have the bandwidth.

**Comment by OfficePop** [comment]
Excellent, I've edited the previous comment with current PR.

**Comment by joeliedtke** [comment]
Glad to be wrong on this, thanks for adding that change in OfficePop
