### ISSUE TITLE
Kubeflow on Kubernetes bootstrap URL broken

### ISSUE THREAD

**Issue by charlesccychen** [kubeflow/website#847]
https://www.kubeflow.org/docs/started/getting-started-k8s/

Looks like the bootstrap config url is broken: https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config/kfctl_platform_existing.yaml

**Comment by sarahmaddox** [comment]
Thanks for reporting this issue! I'm closing it as a duplicate of https://github.com/kubeflow/website/issues/840

/close
