### ISSUE TITLE
kfctl instructions need KUBEFLOW_TAG

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/website#849]
Instructions on the [kfctl page](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) are missing the requirement to set the environment variable KUBEFLOW_TAG=0.5.1. Add this before CLIENT_ID and use it in place of the text "`<release tag>`".

When this env var is not set, strange error messages occur on `kfctl apply`, which do not reference this environment variable, making it impossible to troubleshoot.

**Comment by jlewi** [comment]
@texasmichelle Can you describe what you did and what errors you saw?

I'm pretty sure the kfctl go binary no longer uses that tag.
https://github.com/kubeflow/kubeflow/search?q=KUBEFLOW_TAG&unscoped_q=KUBEFLOW_TAG

I believe its only the kfctl.sh shell scripts that use that environment variable.

The instructions you linked to are using the go binary.

**Comment by texasmichelle** [comment]
When I tried to reproduce, turns out KUBEFLOW_TAG is not the problem. Closing this issue to open one in kubeflow/kubeflow.
