### ISSUE TITLE
How to shutdown and restart the kubeflow instances..

### ISSUE THREAD

**Issue by maniappan** [kubeflow/website#850]
The steps are very detailed and excellent. Was able to create the instances and get into the kubeflow dashboard and create the notebook server and build models. However there is no instruction on how to shutdown the cluster, AWS/Azure/GCP instances and bring it back up. Please add it to the end of the section after the troubleshooting link.

**Comment by Jeffwan** [comment]
For aws, https://www.kubeflow.org/docs/aws/deploy/ We have a step to uninstall kubeflow. Does it meet your need? 

I do think Azure and GCP have it as well.

**Comment by maniappan** [comment]
I am looking for instructions to shutdown and restart and not uninstall. I want to save some $$ when the infra is not in use.

--Mani.

________________________________

**Comment by Jeffwan** [comment]
@maniappan Do you install kubeflow with new eks cluster or existing cluster? 
If you install with new cluster, uninstallation will shutdown EKS cluster. If you install with existing cluster, it's user's responsibility to shutdown the cluster since kubeflow scripts can not make the decision for user.

**Comment by maniappan** [comment]
Created a new one, first time installation in a new AWS account.

--Mani.

________________________________

**Comment by Jeffwan** [comment]
> Created a new one, first time installation in a new AWS account.
> […](#)

Thanks for the feedbacks. Do you still have uninstallation logs? I can help debug the issue.

**Comment by Jeffwan** [comment]
Revisit this issue. Actually, I think what users want is scale down cluster to 0 instance and scale up when needed. This is probably a question should not be addressed here. Technically, you can scale down node groups to 0 and all pods won't be scheduled. Whenever user want to come back working on it, scale up node group. Pod will be scheduled on new coming nodes and service will behave correctly. 


Close this issue and feel free to reopen if it doesn't work for you.

/close
