### ISSUE TITLE
AWS: Document manual steps for ASG/EC2 deletion

### ISSUE THREAD

**Issue by maniappan** [kubeflow/website#851]
Kubeflow on AWS: After deleting EKS cluster and removing the EKS cluster in the AWS, the instances are still getting created, how do we stop the same?

**Comment by Jeffwan** [comment]
@maniappan Could you provide more details? Do you mean the existing instances? Or worker nodes? Have you deleted worker node group before you remove EKS cluster?

**Comment by Jeffwan** [comment]
Sorry for late response. I just come back from vacation.

**Comment by maniappan** [comment]
I followed the uninstall instructions. There was some exception in the process, so wen ahead and removed the worker nodes and eks clusters. However the worker nodes were constantly spun up even after terminating.. whole sequence of shutdown process may have to be verified.

--Mani.

________________________________

**Comment by Jeffwan** [comment]
> removed the worker nodes
How do you remove the nodes? from EC2? for Cloud Formation?

> were constantly spun up
Sounds like the instances are still controlled by ASG? Have you deleted ASG?

**Comment by maniappan** [comment]
Deleted ec2, eks clusters and asg. Asg deletion was not happening due some circular dependendency.

--Mani.

________________________________

**Comment by Jeffwan** [comment]
> Deleted ec2, eks clusters and asg. Asg deletion was not happening due some circular dependendency

Eksctl will delete worker node group cloud formation template first and then eks cluster cloud formation.  EC2 instances will be delete along with ASG deletion.

If you delete ec2 separately, new instance will be created because ASG has to maintain at desired count.

**Comment by maniappan** [comment]
Thanks, will it be possible to have the manual steps documented?.

--Mani.

________________________________

**Comment by Jeffwan** [comment]
> Thanks, will it be possible to have the manual steps documented?.

I will wrote more docs in 0.6 release. AWS still have some changes in pending for 0.6
