### ISSUE TITLE
End-to-end example of Named Entity Recognition model with Keras and AI Platform

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#853]
The example covers the following topics:

* Demonstrate how to use Keras only models
* Demonstrate how to train a Named Entity Recognition model
* Demonstrate how to train the model with Kubeflow
* Demonstrate how to use a custom prediction routine
* Demonstrate how to use serve the model with AI Platform
* Demonstrate how to use Kubeflow metrics
* Demonstrate how to use Kubeflow visualizations

**Comment by sarahmaddox** [comment]
Sascha Heyer will develop this tutorial during the Kubeflow Doc Sprint.

**Comment by SaschaHeyer** [comment]
Hi @sarahmaddox 
great thank you for adding the issue.

**Comment by SaschaHeyer** [comment]
@sarahmaddox 
Pull request created

**Comment by sarahmaddox** [comment]
That looks great, thanks @SaschaHeyer! I've asked @texasmichelle to review the PR.

**Comment by GarethLewin** [comment]
Any update on this PR?

**Comment by SaschaHeyer** [comment]
@GarethLewin 
The pull requests is merged

**Comment by sarahmaddox** [comment]
Thanks @SaschaHeyer!
/close

**Comment by SaschaHeyer** [comment]
You're welcome 🙂
