### ISSUE TITLE
Why use Jupyter notebooks in Kubeflow

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#855]
Useful information in this discussion thread:
https://groups.google.com/forum/#!msg/kubeflow-discuss/v1jwuGIjetk/4tdYZqw9BgAJ

**Comment by sarahmaddox** [comment]
Location for the doc: A new page in this section: https://www.kubeflow.org/docs/notebooks/

**Comment by sarahmaddox** [comment]
Recommended reviewer for the PR: @abhi-g

**Comment by swapnilogale** [comment]
@sarahmaddox Happy to look at this at some point today. Thanks for the link to the resources.

**Comment by sarahmaddox** [comment]
/assign @swapnilogale 

Great, thanks Swapnil! Looking forward to the PR. :)

**Comment by sarahmaddox** [comment]
Fixed by PR https://github.com/kubeflow/website/pull/914

/close
