### ISSUE TITLE
kubectl version requirements

### ISSUE THREAD

**Issue by kbhawkey** [kubeflow/website#858]
Document the suggested or minimum version of kubectl required to run the examples.
Also, if I understand correctly, what version is preinstalled in the `jupyter-notebook` k8s Service?

**Comment by sarahmaddox** [comment]
More info:

The Kubeflow [requirements](https://www.kubeflow.org/docs/started/requirements/) page states the minimum Kubernetes version. (Note that the page uses a shortcode `{{% kubernetes-min-version %}}` for the min version.)

The [kubectl docs](https://kubernetes.io/docs/tasks/tools/install-kubectl/) state the following:

> You must use a kubectl version that is within one minor version difference of your cluster. For example, a v1.2 client should work with v1.1, v1.2, and v1.3 master. Using the latest version of kubectl helps avoid unforeseen issues.

Kubeflow issue https://github.com/kubeflow/website/issues/845 requests that we merge the requirements page with the getting-started page. This will make the version info easier to find.
