### ISSUE TITLE
Kubeflow Pipelines - create guide for moving an existing training script to KFP

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#859]
Data-scientists don't necessarily have a lot of experience with Docker, so it can be daunting to take a monolithic training script and build a pipeline. 

This guide should help users with the following:

1.  Containerize their training script and build an MVP pipeline, this pipeline will use a single component in a single container. Then validate that the script works as expected.
1.  Refactor their script into components. This will use multiple entry points into the initial container. Build an updated pipeline with several components and verify that the script still works.
1.  Refactor the script to replace common functions with reusable pipelines, streamline bespoke functionality into custom containers. Build an updated pipeline and verify that the script still works.

This process demonstrates how to create a container, and the conceptual process for splitting a monolithic script into components. Then it demonstrates how you can reduce your workload by reusing existing components so you only need to focus on what is unique to your pipeline.

**Comment by sarahmaddox** [comment]
@joeliedtke Do you plan to pick up work on this project for the February 2020 doc sprint?

**Comment by joeliedtke** [comment]
Yes, I plan to work on this during the doc sprint.
