### ISSUE TITLE
Update the KFP end-to-end tutorial

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/website#860]
Recently I have received some feedback on challenges that users are running into when getting started with KFP. The [end-to-end tutorial][e2e] is a terrific resource, and it would be great to update it to reduce the friction that has been identified: 

1.  Update the docs to recommend installing the latest version of KF on deploy.kubeflow.cloud.
1.  Revise the instructions to use Cloud Shell instead of local gcloud
1.  The following instructions are not required when using Cloud Shell and can be removed:

     *   Install kubectl
     *   Setting up some handy environment variables

1.  Add instructions for granting users access to Kubeflow. Users will need the following roles: Owner, IAP-secured Web App User
1.  Remove the following command: apt-get install -y wget bzip2
1.  Add notes throughout the tutorial pointing out decisions that have been made. (Using GCS for storage instead of mounting a PV.) Link to the docs for those items so users can research them if they want, after completing the guide
1.  Ensure that users understand how to find the trained model at the end of the tutorial.

End-to-end tutorial URL:
https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/

[e2e]: https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/

**Comment by OfficePop** [comment]
I'll work on this one.

**Comment by sarahmaddox** [comment]
/assign @OfficePop 

Thanks @OfficePop !

**Comment by OfficePop** [comment]
I have submitted [kubeflow/website PR 890](https://github.com/kubeflow/website/pull/890) in response to this issue, thanks!
