### ISSUE TITLE
Create and tag issues related to updating the docs for 0.6

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#862]
The purpose of this issue is to make sure we have a list of P0s and P1 issues that need to be fixed to update the docs for 0.6.

Here's a [list](https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubeflow+project%3Akubeflow%2F5+is%3Aopen+label%3Aarea%2Fdocs+) of issues related to updating the docs for 0.6.

Currently there are only 2 issues. I'm guessing there are more. 
We can close this issue once we have a backlog of issues that are tagged into the project 0.6 with labels area/docs and priority p0 or p1

**Comment by richardsliu** [comment]
Opened a few more issues:
https://github.com/kubeflow/website/issues?q=is%3Aopen+is%3Aissue+project%3Akubeflow%2F5

**Comment by jlewi** [comment]
Thanks @richardsliu; is there more to do here or can we close this?

**Comment by richardsliu** [comment]
Still waiting to see if we need to update docs for fairing and pipelines. I've pinged the relevant owners on Kubeflow chat.

**Comment by jlewi** [comment]
@richardsliu Any update can we go ahead and close this?

**Comment by richardsliu** [comment]
This can be closed.
/close
