### ISSUE TITLE
Update Kubeflow  Katacoda example 

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#863]
The Katacoda example for Kubeflow is outdated, and still refers to deprecated components like kubeflow-core: https://www.katacoda.com/kubeflow/scenarios/deploying-kubeflow-with-ksonnet

This should be updated to the v0.6 instructions.

**Comment by sarahmaddox** [comment]
@richardsliu @abhi-g Do you know who in the Kubeflow community is responsible for the Katacoda docs?

Until they're updated, I recommend that we remove the reference to them from this page:
https://www.kubeflow.org/docs/started/getting-started/

**Comment by sarahmaddox** [comment]
I've pinged the #community channel on Slack to see who can take on the Katacoda updates.

(Note issue https://github.com/kubeflow/website/issues/983 which proposes that we move all the tutorial links (not just Katacoda) from the getting-started page to the section devoted to tutorials/codelabs/etc. The Katacode tutorials are already linked in that section.)

I'm going to close this issue, as we can't take any more action on it from the Kubeflow docs side of things.

/assign
/close
