### ISSUE TITLE
Remove ksonnet page from "Components of Kubeflow"

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#867]
This page is no longer necessary: https://www.kubeflow.org/docs/components/ksonnet/

We should consider adding a page about Kustomize.

**Comment by scottilee** [comment]
@sarahmaddox I can work on removing the ksonnet page and adding a kustomize page that at the least explains what it is and how to install it.

**Comment by richardsliu** [comment]
@scottilee Please feel free to reference this page: https://github.com/kubeflow/manifests/blob/master/README.md

**Comment by scottilee** [comment]
@richardsliu Will do, will have a pull request later today.

**Comment by sarahmaddox** [comment]
/assign @scottilee 
Great! Thanks @scottilee and @richardsliu

**Comment by scottilee** [comment]
I made a pull request here: https://github.com/kubeflow/website/pull/913

@sarahmaddox or @richardsliu could you please review and give me some feedback?

**Comment by richardsliu** [comment]
This is done.
