### ISSUE TITLE
"Components of Kubeflow" can be better organized

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#868]
Consider refactoring the page, by organizing them along functional lines:
- Training (TFJob, PytorchJob, MPI, MXNet, Chainer)
- Serving (TF serving, Seldon, Batch Predict)
- Pipelines
- Hyperparameter Tuning
- Data

**Comment by sarahmaddox** [comment]
Thanks for raising this issue! I'm closing it as a duplicate of https://github.com/kubeflow/website/issues/572
