### ISSUE TITLE
Update the guides in section "Other Guides"

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#869]
https://www.kubeflow.org/docs/other-guides/upgrade/

Documentation is out of date (still refers to v1alpha1 TFJobs). Also the page makes references to ksonnet which is deprecated.

We should just remove the section completely until upgrade is supported.

Similarly, these pages also contain references to ksonnet:
https://www.kubeflow.org/docs/other-guides/troubleshooting/
https://www.kubeflow.org/docs/other-guides/usage-reporting/
https://www.kubeflow.org/docs/other-guides/advanced/

**Comment by sarahmaddox** [comment]
I think we should update the guides, rather than removing the section. The guides are needed, but are out of date.
