### ISSUE TITLE
Update Github Issue summarization codelab

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#871]
This is still referencing ksonnet:
https://codelabs.developers.google.com/codelabs/cloud-kubeflow-e2e-gis/index.html#5

**Comment by richardsliu** [comment]
@amygdala Do you know who owns this codelab?

**Comment by amygdala** [comment]
Unfortunately, it no longer has an owner amongst people who work on KF.  (I'm the owner of the one in the 'pipelines' subdir, but not this one). @velascoluis was just testing it and said it didn't work properly. Luis, could you add the details of how it broke, to this bug? 

We may need to just deprecate it for now, and possibly move the pipelines subdir one to under the 'pipelines' dir at the top level.

**Comment by amygdala** [comment]
Apparently Drew is working on a related qwiklabs replacement -- they pulled the qwiklabs version of this. (for googlers: https://buganizer.corp.google.com/issues/146655130)
Drew, is there a GH issue for your new work? @dhodun

**Comment by dhodun** [comment]
We replaced the qwiklab with the current end-to-end with digit classification and did not update the github summarization code.

**Comment by richardsliu** [comment]
Should we just deprecate this codelab then?

**Comment by dhodun** [comment]
Potentially? It's pretty old at this ponit and seemed to serve the same purpose as https://www.kubeflow.org/docs/gke/gcp-e2e/

At cursory glance, only major differences were use-case and seldon core for serving vs tf serving.

**Comment by amygdala** [comment]
Thanks, Drew (Unfortunately, https://www.kubeflow.org/docs/gke/gcp-e2e/ is currently broken too.)

**Comment by velascoluis** [comment]
Hi, following step by step the issues I found are related to ksonnet.
The code itself works good  inside the notebook.
For googlers here is ks error ouput and the log from the execution inside the notebook: https://docs.google.com/spreadsheets/d/12eo6sc1S_tKAyBpi1iMPeoixOt4UfmMrNnImXaxWxQM/edit#gid=0

**Comment by amygdala** [comment]
For now we're in the process of 'hiding' this codelab from the codelab index, and have also marked the text 'deprecated' for those who had the link bookmarked.  
We should similarly mark the readme in kf/examples -- I'll put in a PR for that shortly.

**Comment by amygdala** [comment]
The codelab has been 'deprecated' for now (& hidden in the index), but let's leave this open as a reminder to decide whether to update it or phase it out if we get more bandwidth.
