### ISSUE TITLE
Kubeflow on Kubernetes

### ISSUE THREAD

**Issue by boniek83** [kubeflow/website#875]
https://www.kubeflow.org/docs/started/getting-started-k8s/
kfctl version 0.5.1 init has no --config flag - cannot proceed with installation.
```
$ kfctl init ${KFAPP} --config=${CONFIG} -V
Error: unknown flag: --config
Usage:
  kfctl init <[path/]name> [flags]

Flags:
      --disable_usage_report    disable_usage_report disable anonymous usage reporting.
  -h, --help                    help for init
  -n, --namespace string        namespace where kubeflow will be deployed (default "kubeflow")
  -p, --platform string         one of 'gcp|minikube'
      --project string          name of the gcp project if --platform gcp
  -r, --repo string             local github kubeflow repo
      --skip-init-gcp-project   Set if you want to skip project initialization. Only meaningful if --platform gcp. Default to false
      --use_basic_auth          use_basic_auth use basic auth service instead of IAP.
      --use_istio               use_istio use istio for auth and traffic routing.
  -V, --verbose                 verbose output default is false
  -v, --version string          desired version of Kubeflow or master if not specified. Version can be master (eg --version master) or a git tag (eg --version=v0.5.0), or a PR (eg --version pull/<id>). (default "master")

unknown flag: --config
```

**Comment by sarahmaddox** [comment]
Hallo @boniek83, the master version of this page is for use with Kubeflow v0.6. Please try the following page for Kubeflow v0.5:
https://v0-5.kubeflow.org/docs/started/getting-started-k8s/

**Comment by sarahmaddox** [comment]
/assign @yanniszark 

@yanniszark Please would you take a look at this issue.

**Comment by boniek83** [comment]
> 
> 
> Hallo @boniek83, the master version of this page is for use with Kubeflow v0.6. Please try the following page for Kubeflow v0.5:
> https://v0-5.kubeflow.org/docs/started/getting-started-k8s/

It works now, although this is very unexpected and confusing. Probably the best way would be like documentation for [kafka](https://kafka.apache.org/documentation/) - each version has it's own page

**Comment by sarahmaddox** [comment]
Thanks @boniek83 and I'm sorry the experience was confusing. I'll close this issue, as we've solved the problem, but I'll think about site design to make the individual versions more accessible.
