### ISSUE TITLE
Pipelines: Create a tutorial for Pix2Pix with TF2.0

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#876]
Create a Kubeflow Pipelines tutorial that uses the TensorFlow 2.0 [Pix2Pix model](https://www.tensorflow.org/alpha/tutorials/generative/pix2pix)

**Comment by sarahmaddox** [comment]
/assign  @fdasilva59 

@fdasilva59 will work on this during the Kubeflow Doc Sprint

**Comment by fdasilva59** [comment]
From [#737](https://github.com/kubeflow/website/issues/737#issuecomment-510100233) : I can confirm that CUDA 10 is working fine on GKE : I am able to run my code on a GPU with a TF 1.13.1 image. 

Let's see how to uses the [TensorFlow 2.0 Pix2Pix model](https://www.tensorflow.org/alpha/tutorials/generative/pix2pix) in the pipeline !

**Comment by fdasilva59** [comment]
Let's define some specifications !

1. location:  this tutorial 
   - will have to be listed [here](https://www.kubeflow.org/docs/examples/resources/)
   - and will be hosted in this [kubeflow/examples repo](https://github.com/kubeflow/examples)

2. Proposed Specifications (inspired by [my previous work](https://github.com/fdasilva59/Pix2Pix-Kubeflow-Demo/) but reusing [TF 2.0 Pix2Pix example](https://www.tensorflow.org/beta/tutorials/generative/pix2pix)  ) - @texasmichelle , I am being told that you might have feedback on the outline specifications for this tutorial ?
   
   - Define 4 components (in 4 python files)
       - **download_dataset**: download the Facades dataset, uncompress on a NFS volume (with NFS server added in Kubeflow namespace during environment setup)
       - **prepare_tfrecords** : import pictures into 2 TFRecord files (training and test).  Use NFS too
       - **train**
          - Use training TFRecord (from NFS) and perform data augmentation with tf.data API
          - Build Conditional GAN + Train the model
          - Collect tensorboard logs (graph + metrics + generated images during training for every epoch
       - **test**
           - use the test dataset and trained model to generate images (on NFS ?)
   
   - Create and execute the pipeline from inside a notebook (running in Kubeflow) 
       - Use the python Kubeflow Pipelines SDK 
       
   - Setup instructions :
       - Deploy cluster on GKE using Cloud Deploy 
           - Add instructions regarding billing requirements and GPU quotas
       - Customize cluster 
           - Use Cloud Shell kubectl commands to add NFS storage (NFS server added in the K8S Kubeflow namespace)
           - Use Cloud Shell kubectl commands to add a GPU node pool (1 server with one P100)
       - Need instruction to setup teh Jupyter Server so that the NFS volume is mounted (in order to dispaly the generated images from the test dataset)
       
       
       
3. Questions/To be investigated

   - Does this tutorial have to run on GKE on does it have to run anywhere ?
       - Does using Tensorboard with Kubeflow still requires to store the logs on Google Storage ?
       - Do we need a dedicated and detailled setup instructions document, like [this one](https://github.com/fdasilva59/Pix2Pix-Kubeflow-Demo/blob/master/SETUP.md) ? Or is this too complicated ? can we do better ? Also it can get quickly outdated ?  
       
   - Do we want to provide built docker containers for the components ?
       - if yes where/how to store so that they are available to anyone ? 
           - Defining these components as prebuilt components (hub) might not be a good idea (too specialized on this task ? NFS requirements,  ??? )
           
       - if no, then define the components in a high level function to be converted in a KF operation (as in my own Pix2Pix Maps implementation)
           - or if time (+ support?) : investigate on using Kubeflow Fairing ?
      
   - verify that model checkpoints can be written on GS ? (It should be ok)
   
   - Cluster customization setup : Maybe : add a shell script in the github project's repo that could be easily downloaded from github in the cloudshell environment, and be executed to setup the NFS server and add the GPU


Feel free, to give feedback (agree, disagree, suggestions, ...)  !

**Comment by sarahmaddox** [comment]
Thanks @fdasilva59 

@texasmichelle Do you have any feedback on the proposal?

From me: +1 to the suggestion for the location of the tutorial:

> 1. location:  this tutorial
>    
>    * will have to be listed [here](https://www.kubeflow.org/docs/examples/resources/)
>    * and will be hosted in this [kubeflow/examples repo](https://github.com/kubeflow/examples)
