### ISSUE TITLE
Create a Getting Started for Developers 

### ISSUE THREAD

**Issue by carmine** [kubeflow/website#878]
This page should guide developers to getting started. It is related to #832 and may surround that. This issue will tackle a holistic view, starting from windows / mac / linux, through to compiling from source, and then to deploying locally.

**Comment by sarahmaddox** [comment]
Hallo @carmine how are you going with this doc? I'm thinking the developer-focused getting-started guide belongs in the kubeflow/kubeflow repo on GitHub, so it'd make sense to move this issue to that repo. Or, if the update is already done, we can close this issue now. :)

**Comment by carmine** [comment]
@sarahmaddox I'll submit the update today. I think there is value in putting this on the website proper for those evaluating the project. I'll add the PR later today and we can use that determine best place. Will that work?

**Comment by sarahmaddox** [comment]
Sounds good.

**Comment by sarahmaddox** [comment]
I'm going to close this issue as obsolete, and because the request is related to the contributor-focused docs (housed in repo README-type docs) rather than to Kubeflow users (housed on the website). Please do open an issue in the kubeflow/kubeflow repo if you'd like to work on this task.

/close
