### ISSUE TITLE
move kfctl downloads page from reference section

### ISSUE THREAD

**Issue by kbhawkey** [kubeflow/website#881]
- Is the [reference section](https://www.kubeflow.org/docs/reference/) the right place for information about downloading `kfctl`
- Is there a reference guide for `kfctl`
- Could the kfctl download page be moved to the Getting Started/requirements section; update information about `how to get a kubeflow release` with `how to get kfctl`

**Comment by sarahmaddox** [comment]
+1 to the suggestion of moving the kfctl download info into the getting-started section.

@kbhawkey is this something you'd like to tackle during the doc sprint?

**Comment by kbhawkey** [comment]
Sure!

**Comment by sarahmaddox** [comment]
This is done.

/close
