### ISSUE TITLE
Pipelines: Create a tutorial that uses components for Dataflow, AI Platform training and prediction

### ISSUE THREAD

**Issue by thedriftofwords** [kubeflow/website#886]
[This issue is in response to #639, for which there are multiple possibilities.]

Translate [this Cloud Dataflow tutorial](https://cloud.google.com/dataflow/docs/samples/molecules-walkthrough) to use KFP.

1. Test the existing tutorial and see if it works with TF 1.14.
2. Leverage [existing components](https://www.kubeflow.org/docs/pipelines/sdk/reusable-components/).

**Comment by sarahmaddox** [comment]
/assign @thedriftofwords 

@thedriftofwords I've assigned this to you, since the assignment to @sirtorry didn't work.

**Comment by thedriftofwords** [comment]
Where to add this in the kubeflow repo:

- Code in kubeflow/examples
- Links to docs: [Examples and tutorials](https://www.kubeflow.org/docs/examples/resources/),[Pipelines tutorials](https://www.kubeflow.org/docs/pipelines/tutorials/), and the "What's next" section of the Dataflow tutorial on cloud.google.com.

**Comment by sarahmaddox** [comment]
@thedriftofwords I'm going to close this issue, as there hasn't been any activity on it for a while. Please do re-open it if there's existing work that we can pick up.

/close
