### ISSUE TITLE
Add Simple Notebook Pipeline

### ISSUE THREAD

**Issue by zanedurante** [kubeflow/website#891]
Add a simple notebook pipeline for new users in `kubeflow/examples/pipelines`.  Also, add a link to the simple notebook pipeline in the docs.

**Comment by zanedurante** [comment]
@sarahmaddox add doc sprint label

**Comment by sarahmaddox** [comment]
@zanedurante Awesome work in getting your kubeflow/examples PR merged! Once you've added the doc link, this issue will be ready to close.

**Comment by zanedurante** [comment]
@sarahmaddox Just sent out the PR for the doc link
