### ISSUE TITLE
Break up the examples page into 4 pages

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#904]
We should break up the examples page into 4 separate pages (one for each section on the page).
https://www.kubeflow.org/docs/examples/resources/

Also add an _index page, following the pattern of the other doc directories.

This will solve 2 problems:

* The examples page is getting a little long.
* The link to the examples page in the left-hand nav looks odd, because all other links are to sections and are therefore bold.

**Comment by sarahmaddox** [comment]
/cc @mameshini 
/cc @DanSanche 

This is a great issue for a tech writer to handle during the Kubeflow Doc Sprint. I'll publicize it as such in Slack.

**Comment by sarahmaddox** [comment]
I think @DanSanche is working on this issue. @DanSanche please would you confirm? If not, I may have a tech writer to work on it.

**Comment by DanSanche** [comment]
I believe @mameshini was looking at this? I'm happy to review, but not looking at this currently
