### ISSUE TITLE
Organize "Components" section

### ISSUE THREAD

**Issue by DanSanche** [kubeflow/website#905]
Right now, the components section is hard to navigate, with all components thrown in together in alphabetical order. I think it would be helpful to add folders to the components list. Maybe "Training", "Serving", "Preprocessing", etc. This would make it easier for users to evaluate the different training options, and it would emphasize all the different use cases Kubeflow can help with.

Thoughts?

**Comment by sarahmaddox** [comment]
Thanks for raising this issue! I'm closing it as a duplicate of https://github.com/kubeflow/website/issues/572
