### ISSUE TITLE
Out-dated GCP service account names

### ISSUE THREAD

**Issue by DanSanche** [kubeflow/website#910]
The [docs say](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#gcp-service-accounts)) that the service account should be called ${KFAPP}-user. I thought the name should be `user-gcp-sa`, independent of the KFAPP name, and [YAML files](https://github.com/kubeflow/examples/blob/master/mnist/training/GCS/Chief_patch.yaml) I've found shows the same. Is the doc out of date, or is it my knowledge?

**Comment by sarahmaddox** [comment]
My Kubeflow v0.5.1 deployment has the three service accounts described in the docs, including `${KFAPP}-user`. I wonder if `user-gcp-sa` is a different type of account? Alternatively, this could be a Kubeflow v0.6 change that I haven't heard about.

**Comment by sarahmaddox** [comment]
/assign
/close

@DanSanche and I have discussed this issue. The YAML file hasn't been updated since May, which means it isn't a v0.6 change. The docs are correct.
