### ISSUE TITLE
Remove ksonnet from training/serving guides

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/website#930]
See latest comments for the list of docs that need updating.

**Comment by scottilee** [comment]
@richardsliu These docs are pretty integrated with ksonnet as they use it to either create configurations or for deployment. I can take this up but I would need a resource that explains alternative steps or tools. Is something like that available?

**Comment by richardsliu** [comment]
@scottilee Which docs are you thinking of taking up? Some of these (e.g. chainer, MPI) don't even have kustomize manifests yet.

**Comment by sarahmaddox** [comment]
See specific issue https://github.com/kubeflow/website/issues/958 for TFServing.

**Comment by sarahmaddox** [comment]
See engineering issue tracking the needed manifests:
https://github.com/kubeflow/manifests/issues/176

**Comment by sarahmaddox** [comment]
I've removed the v0.6 label from this issue. The components still need updating to kustomize, but we've added a note in the docs on each component, letting folks know that the component is not yet updated for the switch from ks to kustomize. This issue therefore no longer blocks us from creating the v0.6 archive of the docs.

**Comment by jlewi** [comment]
We should get this fixed for 1.0; so bumping the priority and adding to the 1.0 kanban board.

Does anyone want to do a pass over the docs and provide an updated status about what remaining pages need to be updated?

**Comment by sarahmaddox** [comment]
The following docs still need updating from ksonnet to kustomize:
* https://www.kubeflow.org/docs/components/training/chainer/
* https://www.kubeflow.org/docs/components/training/mxnet/
* https://www.kubeflow.org/docs/components/serving/istio/
* https://www.kubeflow.org/docs/components/serving/trtinferenceserver/
* https://www.kubeflow.org/docs/components/serving/pytorchserving/
* https://www.kubeflow.org/docs/components/serving/tfbatchpredict/
* https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/
* https://www.kubeflow.org/docs/other-guides/gitops-for-kubeflow/

**Comment by jlewi** [comment]
Thanks @sarahmaddox ; all of the pages you mentioned above now have their own issue. So I'm going to close this issue and we can use the individual issues to track.

**Comment by sarahmaddox** [comment]
Thanks @jlewi!
