### ISSUE TITLE
Troubleshooting guide; why didn't jupyter notebook start

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#935]
We need a trouble shooting guide to explain how people should troubleshoot why their notebooks didn't start.

The basic steps would be something like

```
kubectl get notebooks -o yaml ${NOTEBOOK}
kubectl describe notebooks ${NOTEBOOK}
```

  * Look for errors why it didn't start

If the notebook looks good then look at the statefulset

```
kubectl get statefulsets -o yaml ${NOTEBOOK}
kubectl describe statefulsets ${NOTEBOOK}
```

  * Look for errors such as problems binding PV/PVCs

If that looks good then look at the pod

```
kubectl get pod -o yaml ${NOTEBOOK}-0
kubectl describe pod ${NOTEBOOK}-0
```

   * Is the container running?

Look at the container logs

```
kubectl logs ${NOTEBOOK}-0
```

**Comment by Tabrizian** [comment]
I can work on this issue.

**Comment by sarahmaddox** [comment]
/assign @Tabrizian 
Thanks @Tabrizian!

**Comment by rajesh-chawla** [comment]
I attempted to create a notebook called 'test1'. Following the suggestions above, I executed the command: 

`kubectl describe statefulsets test1`

shows the following error:

    Type     Reason        Age                     From                    Message
    ----     ------        ----                    ----                    -------
    Warning  FailedCreate  2m19s (x26 over 7m39s)  statefulset-controller  create Pod test1-0 in StatefulSet test1 failed error: pods "test1-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found

Note -- on slack, the user Nihir had suggested changing default-editor in the code to juptyer-web-app-service-account in components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py and recompiling kfctl. Unfortunately, this did not work for me.

**Comment by rajesh-chawla** [comment]
I can create a notebook successfully after I create a service account named 'default-editor' clusteradmin rights.

**Comment by Tabrizian** [comment]
Thanks for pointing out @rajesh-chawla! I included this in the troubleshooting guide.

**Comment by jlewi** [comment]
Thanks @Tabrizian for the guide.

**Comment by Tabrizian** [comment]
You’re welcome!
