### ISSUE TITLE
Setting up OAuth for Cloud IAP: Need to get client ID after entering URI

### ISSUE THREAD

**Issue by hchiuzhuo** [kubeflow/website#940]
https://www.kubeflow.org/docs/gke/deploy/oauth-setup/
Question:
If i haven't create  OAuth client ID, how do i fill in <CLIENT_ID> in this stage?

![Screen Shot 2019-07-16 at 12 19 37 PM](https://user-images.githubusercontent.com/26019397/61265709-0329a400-a7c4-11e9-9478-dcdef617c9a8.png)

**Comment by sarahmaddox** [comment]
Hallo @hchiuzhuo The alternative to using OAuth is to authenticate with username and password ("basic authentication"). Here are some docs to help:
https://www.kubeflow.org/docs/gke/deploy/deploy-ui/#authenticating-with-username-and-password

**Comment by sarahmaddox** [comment]
We should add a link to the basic auth info from this page.

**Comment by hchiuzhuo** [comment]
Hi, my question is when I fill Authorized redirect URIs, I have not generate client ID and client secret yet; then, how do I fill the <CLIENT_ID> in this stage? (My workaround is to fill up a whatever uri, after I got client ID and client secret, I came back and fill in again)

**Comment by sarahmaddox** [comment]
Ah thanks @hchiuzhuo I misunderstood. PR https://github.com/kubeflow/website/pull/942 has updated the page - your workaround is the right one.
