### ISSUE TITLE
[GCP] Describe creating service accounts and using pod defaults

### ISSUE THREAD

**Issue by jlewi** [kubeflow/website#946]
0.6 is designed to allow users to consume Kubeflow in their own namespace.

* When they create a new namespace; they will need to install GCP credentials into that namespace. This means running a bunch of gcloud and kubectl commands to create a service account, download the key and install it in the cluster.
* They will also want to create a PodDefault object in order to automatically attach the credentials to certain pods.

The relevant commands are documented [here](https://docs.google.com/document/d/1zT1yhDgmS59_uMWJ76hr7FCyXTDQ1Ju1MVADnlCfNEQ/edit#heading=h.dchzjmu0p6dp)

Related to #679 troubleshooting guide for credentials

**Comment by jlewi** [comment]
@DanSanche any chance you could pick this up?

**Comment by jlewi** [comment]
We can add the info to the existing authentication guide: #916

**Comment by jlewi** [comment]
One thing we should document is how people can copy a secret from one namespace to another using 
the CLI

```
SOURCE=kubeflow
DEST=<namespace user is using kubeflow in>
SECRET=$(kubectl -n ${SOURCE} get secrets user-gcp-sa -o jsonpath="{.data.${NAME}\.json}" | base64 -d)
kubectl create -n ${DEST} secret generic ${NAME} --from-literal="${NAME}.json=${SECRET}"
```

**Comment by jlewi** [comment]
The other path we should document is as follows

1. Create a service account with desired roles

```
export PROJECT_ID=<your-project-id>
export NAMESPACE=<your-desired-namespace>
export SA_NAME=<name for SA>
export GCPROLES=roles/editor
gcloud --project=${PROJECT_ID} iam service-accounts create $SA_NAME
gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$SA_NAME@$PROJECT_ID.iam.gserviceaccount.com \
    --role $GCPROLES

```

1. Download a json service account key
 
```
export KEYPATH=some/path/${SA_NAME}.gcp..json
gcloud --project=${PROJECT_ID} iam service-accounts keys create ${KEYPATH} \
   --iam-account $SA_NAME@$PROJECT_ID.iam.gserviceaccount.com
```

1. Upload as a secret to the cluster.

```
kubectl create secret generic user-gcp-sa -n $NAMESPACE \ --from-file=user-gcp-sa.json=${KEYPATH}
```

**Comment by DanSanche** [comment]
@jlewi did you have a timeline in mind for this? I should be able to help, but I likely won't have the bandwidth for a couple weeks

**Comment by scottilee** [comment]
@jlewi I made a pull request here https://github.com/kubeflow/website/pull/957, let me know what you think.

**Comment by jlewi** [comment]
@DanSanche I was hoping to get it done this week.

@scottilee Thanks! I'll take a look.

**Comment by jlewi** [comment]
/assign @jlewi 
/assign @abhi-g 
/assign @scottilee 

@jlewi and @abhi-g  to review the PR
