### ISSUE TITLE
"kfctl init ${KFAPP} --config=${CONFIG} -V" does not work

### ISSUE THREAD

**Issue by doschkinow** [kubeflow/website#949]
Hi,

the init command "kfctl init ${KFAPP} --config=${CONFIG} -V" does not work. It says:

$ kfctl init ${KFAPP} --config=${CONFIG} -V
Error: unknown flag: --config
Usage:
  kfctl init <[path/]name> [flags]
....
The kfctl vrsion I am using is:
$ kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e

Please advise how to proceed.
Thanks!

**Comment by sarahmaddox** [comment]
Related: https://github.com/kubeflow/website/issues/875

**Comment by sarahmaddox** [comment]
/assign @yanniszark 

@yanniszark Please would you take a look at this issue.

**Comment by sarahmaddox** [comment]
/assign
/unassign @yanniszark 

Hallo @doschkinow The master version of the docs are for Kubeflow v0.6. You can get the latest version of kfctl here:
https://github.com/kubeflow/kubeflow/releases

Alternatively, if you want to continue using an older version of Kubeflow, such as v0.5, you can choose the corresponding version of the docs from the version dropdown near the top right of the page.

**Comment by doschkinow** [comment]
Many thanks for the hint! I'll try this and come back.

**Comment by doschkinow** [comment]
I noticed, that the v0.5 relies on ksonnet which is deprecated, so I decided to go with the latest version (v0.6, just released a couple of hours ago). However I hit a Makefile problem when trying to build kfctl, as described in the "Getting Started":

(base) [opc@bastion ~]$ cd  kubeflow-0.6.0/bootstrap/
(base) [opc@bastion bootstrap]$ make build-kfctl-container
**Makefile:85: *** missing target pattern.  Stop.**

Any hints or suggestions?
Thanks!

**Comment by doschkinow** [comment]
It turned out that in my env I had a GOPATH variable which had a ":" inside. So the syntax for the target in line 85 was incorrect. Unsetting GOPATH before  calling "make build-kfctl-container" solved my problem.

This could be considered as a bug in the Makefile.
