### ISSUE TITLE
Getting Started with Kubeflow

### ISSUE THREAD

**Issue by BonavincciAI2020** [kubeflow/website#962]
https://www.kubeflow.org/docs/started/getting-started/

**Comment by sarahmaddox** [comment]
Hallo @BonavincciAI2020 Please would you describe the problem that you found on the linked page? If there's no problem, please close this issue.

**Comment by sarahmaddox** [comment]
I'm going to close this issue since there's not enough information to act upon. Please do re-open it if there's work to do on the issue.

/close
