### ISSUE TITLE
Kubeflow on Kubernetes

### ISSUE THREAD

**Issue by pdmack** [kubeflow/website#966]
https://www.kubeflow.org/docs/started/getting-started-k8s/

Should it say `make build-kfctl`?

**Comment by yanniszark** [comment]
Hi @pdmack.
`make build-kfctl` builds in the host machine while `make build-kfctl-container` builds inside a container.
The difference is that `build-kfctl-container` only requires Docker as a dependency and is a very easily reproducible way of building.
`make build-kfctl` make break depending on the host's go configuration, if they have set up the v2 folder, etc.

**Comment by sarahmaddox** [comment]
/assign @yanniszark 

Thanks @yanniszark. 

I'll close this issue as I think it's answered, but please do re-open it if any work is required.
