### ISSUE TITLE
Kubeflow version issue in Pipelines End-to-end on GCP

### ISSUE THREAD

**Issue by numerology** [kubeflow/website#968]
https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/

In the 'Deploy Kubeflow' section it said to use Kubeflow version > 0.6. However it's currently not available in the UI-based deployment yet. (Currently supporting v0.5)

**Comment by sarahmaddox** [comment]
Thanks for reporting this issue @numerology 

For general discussion: It seems to be a confusing experience for the user if we release a Kubeflow version without supporting that version in the UI-based deployment. @jlewi and @abhi-g is there any way we can hold off on the Kubeflow release until the deployment UI supports the same version?

**Comment by sarahmaddox** [comment]
I'm closing this issue as fixed, but the discussion item in comment https://github.com/kubeflow/website/issues/968#issuecomment-515659423 remains valid.

/close

**Comment by jlewi** [comment]
The Click To Deploy is GCP only. We don't want to hold up releases for vendor/platform specific solutions.

We are working on fixing click to deploy so we can sim ship with the OSS stack.
