### ISSUE TITLE
kubeflow.org SEO needs some love

### ISSUE THREAD

**Issue by pdmack** [kubeflow/website#98]
Part of the confusion with new users is that outdated material is showing up first in searches. We need to pump up the SEO to make sure the current getting started/user guide is what they see first.

/assign @abhi-g 
/assign @ewilderj 

<img width="925" alt="screen shot 2018-07-20 at 1 32 11 pm" src="https://user-images.githubusercontent.com/2380545/43016673-92560f8e-8c21-11e8-94df-47aa03a913bd.png">

**Comment by pdmack** [comment]
https://keithpblog.org/post/hugo-website-seo/

**Comment by sarahmaddox** [comment]
https://support.google.com/webmasters/answer/9128669?hl=en

**Comment by sarahmaddox** [comment]
https://developers.google.com/search/docs/guides/

**Comment by sarahmaddox** [comment]
Most fitting Schema.org category seems to be: WebSite
https://schema.org/WebSite

**Comment by sarahmaddox** [comment]
https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by sarahmaddox** [comment]
I'm going to try building our site with the env variable set to production, to index the site. Evidently we've never done that. Could help our SEO as well as fix the search box.

**Comment by sarahmaddox** [comment]
We should target specific words on the relevant docs. Examples:

tutorial
install/installation/deploy/deployment

**Comment by sarahmaddox** [comment]
Our SEO is already better, 2 days after setting the Hugo environment to "production". Here are some "before" and "after" screenshots, all taken from an incognito window.

Search for "kubeflow" **before** - the website does not appear:
![screenshot-search-kubeflow-2019-02-12 04-59-36](https://user-images.githubusercontent.com/6138251/52742753-508fb400-2f8d-11e9-9dc3-ff6c5e66494d.png)

Search for "kubeflow" **after** - the website is the 3rd result, after GitHub and Twitter:
![screenshot-search-kubeflow-2019-02-13 12-42-54](https://user-images.githubusercontent.com/6138251/52742796-67cea180-2f8d-11e9-9397-084a3ec34121.png)

Search for "kubeflow install ksonnet" **before**:
![screenshot-search-kubeflow-install-ksonnet-2019-02-12 05-00-59](https://user-images.githubusercontent.com/6138251/52742828-7e74f880-2f8d-11e9-8683-00784a2cfc14.png)

Search for "kubeflow install ksonnet" **after**:
![screenshot-search-kubeflow-install-ksonnet-2019-02-13 12-41-38](https://user-images.githubusercontent.com/6138251/52742854-90ef3200-2f8d-11e9-9942-efb198e6aa9f.png)

Search for "kubeflow ml pipelines" **before**:
![screenshot-search-kubeflow-ml-pipelines-2019-02-12 05-02-57](https://user-images.githubusercontent.com/6138251/52742887-a82e1f80-2f8d-11e9-9200-42afef198355.png)

Search for "kubeflow ml pipelines" **after**:
![screenshot-search-kubeflow-ml-pipelines-2019-02-13 12-37-49](https://user-images.githubusercontent.com/6138251/52742905-b67c3b80-2f8d-11e9-8e6c-f862b5b6483a.png)

**Comment by abhi-g** [comment]
Awesome job. Thank you Sarah!

Abhishek

**Comment by pdmack** [comment]
Great work Sarah!

**Comment by sarahmaddox** [comment]
Thanks folks :)
