### ISSUE TITLE
Pipelines: Document how to include a notebook into your Kubeflow pipeline

### ISSUE THREAD

**Issue by sarahmaddox** [kubeflow/website#997]
Document how to include a notebook into your Kubeflow pipeline.

Update and repurpose content from here:
https://towardsdatascience.com/how-to-deploy-jupyter-notebooks-as-components-of-a-kubeflow-ml-pipeline-part-2-b1df77f4e5b3

**Comment by Tabrizian** [comment]
I can work on this issue but I need limited access to GCP to create a Kubeflow. I am running out of my free tier account on GCP.

**Comment by sarahmaddox** [comment]
Actually, for this particular doc it'd be great to offer a solution that doesn't rely on GCP. So, perhaps using Kubeflow on prem or local. Our docs are becoming a little heavy on the GCP side. If you create a guide that uses Kubeflow on a generic Kubernetes cluster, readers can move it to GCP or another cloud if they wish.

(About the access to GCP in a more general sense: I'll enquire about the situation with GCP credits for people updating the docs, and get back to you on that.)

Shall I assign this issue to you, @Tabrizian? It'll be great if you can work on it.

**Comment by Tabrizian** [comment]
Thanks @sarahmaddox!

Sure, I can start working on it but I don't promise. I try my best to add it.

**Comment by sarahmaddox** [comment]
Great!

/assign @Tabrizian
